### ISSUE TITLE
Googleカレンダーとの連携

### ISSUE THREAD

**Issue by patipati3** [exceedone/exment#1000]
### Describe the feature you'd like / 希望する機能の説明を行ってください
A clear and concise description of what you want to happen. / あなたが何をしたいのかについての、明確で簡潔な説明を行ってください。
お世話になっております。

他のチームのメンバーからご要望があったのですが、Exmentで使用しているカレンダーと、個人で使用しているGoogleカレンダーのデータを連携させたいという要望があったのですが、もしすでに実装されているようであれば、設定方法などご教示いただけますと幸いです。

また、もし現状ない場合は、今後そのような機能の導入を検討いただけますと幸いです。

**Comment by Yuusuke9228** [comment]
開発者ではなくて申し訳ないのですが、私はGoogleカレンダーとの連携が行たくてプラグインで実装しました。
手順としては、

- Exment側で「ユーザーID」「カレンダーID（Google）」「GoogleAPIの設定JSONファイル」を保持するテーブルを作成
- Google APIコンソールで、APIの設定を行い、JSONファイルを取得
- Googleカレンダーへ先ほど設定したClientEmailを設定（JSONの中に記載があります。）
- 一番最初に作ったExmentのテーブルへ、ユーザー単位で設定データを作成
- 後は、プラグインでカレンダー表示の際に、ログインユーザーの設定データを取得し、Googleカレンダーからイベントを取得したり、イベント保存時にGoogleカレンダーへ書き込みに行くだけです。

基本的に、ユーザーのAPI情報などを管理ユーザーが全て管理する事になりますし、APIの設定部分も一般ユーザーに説明する必要があります。

Exmentのカレンダーはユーザー単位での色分けなどが出来ないので、スケジュール管理部分はプラグインで自前で実装して、Googleカレンダーなどと連携させるのがよろしいかと思います。

参考ページ：[https://blog.capilano-fw.com/?p=5365](LaravelでGoogleカレンダーのスケジュールを取得・追加・変更・削除する)
