### ISSUE TITLE
データ更新時のメール通知のパラメータ変数にて更新前の値が通知メールに反映される

### ISSUE THREAD

**Issue by shuheie** [exceedone/exment#1003]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
データ更新をトリガーとしたメール通知を実装し、「${value:(列名)}」パラメタ変数を使用してカスタム列の値を通知本文に含む実装を行いました。
この時、データ更新時に通知される本文に、更新後のカスタム列の値ではなく更新前のカスタム列の値が反映されます。

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
通知メール本文に含みたいカスタム列の列名を「Status」とします。
通知テンプレートを、「${value:Status}」のパラメタ変数を含んで作成し、カスタムテーブルの通知設定にて、データ更新時にメール通知がされるよう実装します。メール通知先は、カスタム列に含む通知先メールアドレスとしています。
その後、カスタム列「Status」の値を「A」→「B」に変更します。
通知メールが送信されますが、「${value:Status}」のパラメタ変数には「B」が入ってほしいところに「A」が入って送信されます。
また、「${created_user}」のパラメタ変数でも、同様に更新前の値 (=前回の更新者のユーザ名) が通知テンプレートに代入されてメール通知されることを確認しています。

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
v4.1.4
本日上記バージョンへの更新後の動作確認をしている際に気づきましたが、過去バージョン (v3.x.x) でも発生していたようです。

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。
上記操作を行ったタイミングで "storage/logs/laravel.log" のログ出力はありませんでした。

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。
こういったバグレポートへの投稿が初めてなので、不備不足ありましたらご指摘ください。

**Comment by hirossyi73** [comment]
現象を確認しました。次回リリースで反映します。

**Comment by hirossyi73** [comment]
v4.1.5で対応しました。
