### ISSUE TITLE
【ワークフロー】通知メールの宛先に次の作業ユーザを指定するとエラーが発生する

### ISSUE THREAD

**Issue by naeky** [exceedone/exment#1009]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
ワークフローの通知設定で通知対象に次の作業ユーザを指定して対象がグループの場合、エラーが発生する

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
1. ワークフローを定義する
2. アクション設定の実行可能ユーザに組織でグループを指定する
3. 通知設定の通知アクション設定にメールを指定して通知対象を次の作業ユーザにする
4. ワークフローを実行する
5. 画面上にエラーが発生する

エラーが発生しました
メール送信に失敗しました。メール設定と、システムログファイルをご確認ください。

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
v4.1.3

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

[2021-06-08 20:07:44] local.ERROR: Swift_TransportException: Expected response code 354 but got code "503", with message "503 5.0.0 Need RCPT (recipient)
" in /var/www/exment/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:459

**Comment by hirossyi73** [comment]
メール設定を見直してください。
https://exment.net/docs/#/ja/mailsend_setting

**Comment by hirossyi73** [comment]
メール設定を見直してほしいです。
https://exment.net/docs/#/ja/mailsend_setting

テストメールは正常に送信されていますでしょうか？
まずはテストメールが正常に送信されているかをご確認いただきたいです。

**Comment by naeky** [comment]
コメントありがとうございます。メール設定に問題がないことは確認していました。
元環境の手配が難しいため、別環境で再現を試みておりました。
しかしながら、事象が発生していないことから環境固有の問題が高そうです。
お騒がせして申し訳ありませんが、クローズでお願いします。
