### ISSUE TITLE
データの更新履歴が設定件数以上の場合に上書きで保持されない

### ISSUE THREAD

**Issue by mtkoki** [exceedone/exment#1015]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

テーブルでの変更履歴バージョン数の設定以上のデータの変更履歴が保存されない。

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

テーブルにて変更履歴バージョン数を設定する。（例として5を設定したと仮定）
データに変更を加えると変更履歴が保持されるが、6回目以降の変更履歴が保存されない。

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
4.1.4（デモ環境にて確認）

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。
説明を見ると、1回目の変更履歴が削除、6回目の変更履歴が保存されるのが正しいと思われますが、
正常な動作なのでしょうか。

**Comment by hirossyi73** [comment]
不具合を確認したので、近日アップデートリリースします。

**Comment by hirossyi73** [comment]
v4.2.0にてリリースしました。
