### ISSUE TITLE
アップデート後カスタムテーブルでデータ一覧表示されない

### ISSUE THREAD

**Issue by Nemzo** [exceedone/exment#1019]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
4.2.0にアップデート後カスタムテーブルでデータ一覧表示されない

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
4.2.0

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

エラーメッセージ
syntax error, unexpected ')'

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

[20210702.txt](https://github.com/exceedone/exment/files/6751371/20210702.txt)

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by hirossyi73** [comment]
別の方からご指摘を受け、4.2.1のリリースを実施いたしました。
お手数ですが、4.2.1へアップデートをお願いします。

**Comment by hirossyi73** [comment]
#1021 にて記載しました。
