### ISSUE TITLE
親子入力できるフォームの子テーブルで、サーチモーダルから値を設定すると複数行ある場合、全て値が置き換わる。

### ISSUE THREAD

**Issue by Yuusuke9228** [exceedone/exment#1022]
### Describe the bug / バグの説明

タイトルの通りなのですが、１対多のテーブルのフォームで子側のフォームでサーチモーダルから値を設定するとそのデータ内の全ての行が書き変わってしまいます。

### To Reproduce / 再現手順

1. １対多のテーブルを作り、フォームで「子テーブルを使用」「フォームをテーブル形式」にチェックを入れたフォームを定義します。
  ※子テーブルの項目に「他のテーブルから選択」を含んでください。
  ※「複数選択」を許可しない設定です。
  ※このフィールドは１００行以上のデータがあるテーブルを選択しています。

2. 新規画面か編集画面のいずれかで、子側のデータを数行入力します。

3. どの行のデータでも良いので、「他のテーブルから選択」のフィールドで「サーチ」を押し、モーダルからデータを設定します。

4. 全ての行のデータが置き換わってしまいます。

  ※サーチボタンからでなく、入力した場合には再現しなかったので、モーダルから設定した場合のみ発生している様です。
  ※サーチボタンでモーダルを表示した際に、前の行に設定した値が残っていて、「追加」ボタンを押すと書き変わっているので、恐らくそれが原因ではないかと思います。

### Version / 発生バージョン

4.1.5

**Comment by Yuusuke9228** [comment]
現在の最新バージョン4.2.1でも同様の症状が発生しています。

**Comment by tkpontas** [comment]
私の環境下では、フォーム設定の見出し設定（既定のやつ）を「横並び」以外にすると、上記修正を行っても、親子入力できるフォームの子テーブルで、サーチモーダルから値を設定すると複数行ある場合、全て値が置き換わるか、モーダルから選択しても入力されない現象が発生。フォーム設定の見出し設定を横並び（初期規定値）にして、各カスタム列ごとにフォーム設定すれば、サーチモーダルは正常に作動する。　もし同じような現象で悩まれている方がいたら、試してみてください。

**Comment by tkpontas** [comment]
【追記】
サーチモーダルを利用するカスタム列をフォーム設定で「横並び」以外にセットすると、サーチモーダルから選択肢を追加し、送信しても、選択されたことになっていない。（子テーブル・表形式の場合は複数行がすべて値が置換される）

なお、選択肢を直接選択時は問題ない。

**Comment by hirossyi73** [comment]
v4.4.0までの更新で対応しました。
