### ISSUE TITLE
カスタムテーブルーカスタム列ーカレンダー入力　履歴表示の非表示方法

### ISSUE THREAD

**Issue by fleming35800** [exceedone/exment#1024]
カスタムテーブルーカスタム列ーカレンダー入力に値を入力しているときに、使用しているうちに過去の入力履歴を記憶し、
入力フィールドにカーソルがあった時点で入力候補が出てきてしまう。
特に不具合などではありませんが、候補が増えてくるとカレンダーにかぶってしまって操作しずらくなってしまいます。
オートコンプリートの機能などをオフにしてみたりいろいろ試してみたのですが、表示を消すことが出来ません。
有志の方でも構いません、何か対策方法あれば教えて頂ければ幸いです。

![image](https://user-images.githubusercontent.com/75713203/125019754-84198e80-e0b2-11eb-9b0f-1f3262f26ad4.png)

**Comment by tkpontas** [comment]
オートコンプリートの機能などをオフにした後、ブラウザの設定から、検索や入力フォームの履歴は削除しましたか？
特にFirefoxとGoogleChromeはきちんと削除しないと残っていることがあります。

**Comment by tkpontas** [comment]
![スクリーンショット 2021-07-12 125202](https://user-images.githubusercontent.com/60683813/125228574-fc30c000-e30f-11eb-85bd-85e916821075.jpg)
おそらくExment側の問題では無く、Webブラウザ側の問題と思われます。

**Comment by jyodai** [comment]
2つほど対応案を記載させていただきます。
※動作確認は全てChromeで行いました。

**手動での対応**

カレンダーをクリックし、AutoComplete部分とカレンダーが重なった状態で表示されます。
その状態で、Escキーを押すことでAutoComplete部分を非表示にすることが可能です。

**コードでの対応**

カレンダーの入力部分のコードに「autocomplete="off"」を差し込むとAutoCompleate部分を非表示にすることができます。

```
<input 
    autocomplete="off"
    data-column_type="date"
    style="width: 110px"
    type="text"
    id="calendar"
    name="value[calendar]"
    value=""
    class="form-control class_btnxmwhwmpcwuzwbjdyb value_calendar"
    placeholder=""
>
```

Tampermonkey等を使用して、ページ読み込み時に「autocomplete="off"」を差し込んであげれば、非表示にすることができそうです。
