### ISSUE TITLE
アップデート時のエラー

### ISSUE THREAD

**Issue by crux023** [exceedone/exment#1025]
### Describe the bug / バグの説明
下記のエラーメッセージが出るようになった。どのように対応したらよいか・・・。

### To Reproduce / 再現手順
アップデート時

### Version / 発生バージョン
4.2.1

Migrating: 2019_08_19_000000_create_failed_jobs_table

   Illuminate\Database\QueryException  : SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'failed_jobs' already exists 
(SQL: create table `failed_jobs` (`id` bigint unsigned not null auto_increment primary key, `connection` text not null, `queue` text 
not null, `payload` longtext not null, `exception` longtext not null, `failed_at` timestamp default CURRENT_TIMESTAMP not null) defau
lt character set utf8mb4 collate 'utf8mb4_unicode_ci')

  at /home/*******/*******/laravel/exment/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673| 

  Exception trace:

  1   Doctrine\DBAL\Driver\PDO\Exception::("SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'failed_jobs' already exis
ts")
      /home/********/********/laravel/exment/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18

  2   Doctrine\DBAL\Driver\PDO\Exception::new(Object(PDOException))
      /home/********/*******/laravel/exment/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:114

  Please use the argument -v to see more details.
Finish Update!

**Comment by dainetjp** [comment]
同現象が起こりましたが下記の手順で治りました。
参考になれば幸いです。

https://github.com/exceedone/exment/issues/983#issuecomment-823898590
