### ISSUE TITLE
選択肢複数選択時のフィルタが機能しない

### ISSUE THREAD

**Issue by crux023** [exceedone/exment#1028]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
別サーバーからデータをリストア後新サーバーでの運用
両サーバーとも最新版にしてから移行
追記1
ちなみに以前のサーバーで入力していたデータは、フィルタにかかるが
新サーバで入力したデータは、複数設定だと引っかからない

追記2
再度xサーバーにインストールしなおして実験
結果　選択肢　複数を許可　でフィルタがかからなかったことから　リストアは関係なし
単一選択のみ検索がヒットして
複数選択だと検索がかからない

選択肢の複数選択を許可
・入力したはずの値がフィルタした際にヒットしない
・複数選択から一つ選択に戻してデータを見るとその選択肢のカラムだけ消えている

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
4.21

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by skmt8585** [comment]
同じ現象で困っております。

**To Reproduce / 再現手順**
1.任意のテーブルを作成
2.カスタム列を下記の設定で追加
　列種類：選択肢
　検索インデックス：YES
　選択肢：
　　　あああ
　　　1111
　　　いいい
　　　2222
　複数選択を許可する：YES
　ラジオボタン・チェックボックス形式で表示：YES
3.レコードをいくつかのパターンで追加
4.フィルタで選択肢を指定する
　半角英数字の選択肢：フィルタは正常に動作する
　日本語を含む選択肢：フィルタは正常に動作しない

**Version / 発生バージョン**
4.2.3

**Screenshots / スクリーンショット**
![image](https://user-images.githubusercontent.com/57421787/140465258-e7f9c945-3b33-484a-a6bd-21136f578156.png)

![image](https://user-images.githubusercontent.com/57421787/140465373-1715d246-2786-47cc-a306-0df112a31184.png)

![image](https://user-images.githubusercontent.com/57421787/140465455-157fd4a3-dc57-456a-83a9-49284f46a046.png)

**Comment by crux023** [comment]
たしかに！日本語だとフィルタが機能しませんね・・・。

**Comment by skmt8585** [comment]
v4.2.5 で修正された事を確認しました。（同じ問題の #1080 に対応のコメントがありますね）
https://github.com/exceedone/exment/issues/1080
