### ISSUE TITLE
管理者がデータ編集できない

### ISSUE THREAD

**Issue by sota1141** [exceedone/exment#1029]
### Describe the bug / バグの説明
不要なカスタム列を削除後、システム管理者権限で個人が作成したデータを編集しようとするとエラーが発生するようになった。
作成者は編集画面が表示され編集することができる。
このエラーのせいなのか、このテーブルだけテンプレート保存ができない。

### To Reproduce / 再現手順
①テーブル作成
②ワークフローを設定。（ワークフロー種類：テーブル専用）
③テーブルの不要なカスタム列削除。
④一覧画面で、既存データ列をクリックするもエラーが表示される
⑤設定しているワークフローを削除後、新規作成
⑥一覧画面で、既存データ列クリックで表示でき③のエラーは解消
⑦システム管理者で、編集マーククリックで以下のエラー表示

### Version / 発生バージョン
v4.2.1

### Error log / エラーログ
![larabel_log](https://user-images.githubusercontent.com/87462224/125733258-62f15a47-8d14-47e9-acfb-a814775fcb7b.png)

### Screenshots / スクリーンショット
![err](https://user-images.githubusercontent.com/87462224/125732890-c7071d21-adaa-4cc5-87b4-7c393b1952af.png)

**Comment by sota1141** [comment]
> このエラーのせいなのか、このテーブルだけテンプレート保存ができない。
は別にbug報告をします

**Comment by hirossyi73** [comment]
ご報告ありがとうございます。
バグの内容を見る限り、管理者というよりも、なんらかの理由で、htmlをエスケープする処理に、配列が入ってくることが原因のようです。

かなりテーブル or 列 or データ依存の不具合だと考えています。再現のためには、可能であればデータやテンプレートなどをいただくことがもっとも迅速なのですが、それも難しいようで、ちょっと考えます。

**Comment by sota1141** [comment]
お忙しい中ご確認ありがとうございます。
削除したカスタム列は、組織テーブルを選択肢に設定したカスタム列でした。複数選択不可にしてたと思います。
送りたいのですがこのテーブルのテンプレートが保存できず。。
なにか解決に繋がると大変ありがたいです。よろしくお願いいたします。
