### ISSUE TITLE
組織テーブルでデータ並べ替えを設定したビューでのExcelエクスポートができない

### ISSUE THREAD

**Issue by sota1141** [exceedone/exment#1030]
### Describe the bug / バグの説明
組織テーブルで、並べ替えを設定したビューを表示し「エクスポート(すべてのシステム列・カスタム列)
」でエクスポートするとExcelだけエラーになる。
他のエクスポートはできる

### Version / 発生バージョン
v4.2.1

### Error log / エラーログ
SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]A column has been specified more than once in the order by list. Columns in the order by list must be unique. (SQL: select top 100 [exm__66b54555b73411f74662].* from [exm__66b54555b73411f74662] where [exm__66b54555b73411f74662].[deleted_at] is null order by CAST([exm__66b54555b73411f74662].[column_07354aa6dc7a130a6d1f] AS int) asc, [exm__66b54555b73411f74662].[column_ee468a2a214ccb1e8b41] asc, CAST([exm__66b54555b73411f74662].[column_07354aa6dc7a130a6d1f] AS int) asc, [exm__66b54555b73411f74662].[column_ee468a2a214ccb1e8b41] asc)

**Comment by hirossyi73** [comment]
v4.2.2にて修正完了
