### ISSUE TITLE
APIアプリ設定でエラーが表示される

### ISSUE THREAD

**Issue by sota1141** [exceedone/exment#1032]
### Describe the bug / バグの説明
APIアプリ設定でエラーが表示される

### To Reproduce / 再現手順
システム設定→APIアプリ設定→エラー表示

### Version / 発生バージョン
v4.2.1

### Error log / エラーログ
Argument 1 passed to Exceedone\Exment\Grid\Filter\Between::__construct() must be an instance of Closure, string given, called in /var/www/exment/vendor/exceedone/laravel-admin/src/Grid/Filter.php on line 682

### Screenshots / スクリーンショット
![err](https://user-images.githubusercontent.com/87462224/125899571-d13f25bf-a47b-475b-ac8d-abe822c04eaa.png)

**Comment by hirossyi73** [comment]
お手数おかけします。
原因調査など行いますので、一時的に、以下のファイルの60行目前後の、
「$filter->betweendatetime('created_at', trans('admin.created_at'))->date();」
の記述をコメントアウトしてもらえると幸いです。
vendor\exceedone\exment\src\Controllers\ApiSettingController.php

![image](https://user-images.githubusercontent.com/8457265/125900069-e6b8b9d7-9d72-4272-90ae-3fed915d0e66.png)

**Comment by sota1141** [comment]
ありがとうございます。コメントアウトで解消しました。

**Comment by hirossyi73** [comment]
v4.2.2にて修正完了
