### ISSUE TITLE
列種類がユーザーの初期値を複数選択可能にしてほしい

### ISSUE THREAD

**Issue by sota1141** [exceedone/exment#1034]
### Describe the feature you'd like / 希望する機能の説明を行ってください
列種類をユーザーに設定したカスタム列の初期値を「指定のユーザー（現在、IDの種類が必要）」で複数選択可能にしてほしい。

### Additional context / その他
「複数選択を許可する」をYESにしています。
試しに、'330,350'のようにカンマ区切りで初期値を設定する事はできますが、
対象のテーブルを開くと以下のエラーが表示されます。

 ViewException In Connection.php line 669 :
  SQLSTATE[22018]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Conversion failed when converting the nvarchar value '330,350' to data type int. (SQL: select top 1 * from [exm__c70459ea2a09ce84fe80] where [exm__c70459ea2a09ce84fe80].[id] = 330,350 and [exm__c70459ea2a09ce84fe80].[deleted_at] is null) (View: /var/www/exment/vendor/exceedone/exment/resources/views/form/field/gridembeds.blade.php)

**Comment by hirossyi73** [comment]
v4.2.3にて対応済
