### ISSUE TITLE
`LoginService::getAccessToken()` でアクセストークンが取得できない

### ISSUE THREAD

**Issue by hmatsumaru-idcf** [exceedone/exment#1040]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
OAuthログインしたあと、プラグインからアクセストークンの取得をしようと試みたところできません(参考: https://exment.net/docs/#/ja/login_oauth?id=%e3%82%a2%e3%82%af%e3%82%bb%e3%82%b9%e3%83%88%e3%83%bc%e3%82%af%e3%83%b3%e5%8f%96%e5%be%97 )。

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
Exmentをサーバーに設定後、OAuthログインの設定をドキュメント(https://exment.net/docs/#/ja/login_oauth) に従って行いました。プロバイダにはMicrosoft Graphを設定しています。
また、アクセストークンを取得するプラグイン(ボタン)を作成しました。
```
class Plugin extends PluginButtonBase {
    public function execute() {
        \Log::debug(is_null(LoginService::getAccessToken()));
        return true;
    }
}
```

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
- Exment Ver 4.2.1

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。
エラーログはありません。ただし、上記のプラグインのように、
```
\Log::debug(is_null(LoginService::getAccessToken()))
```
とすると
```
[2021-08-19 14:49:56] local.DEBUG: 1
```
と表示されます。

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。
ありません

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。
`exment/src/Services/Login/LoginService.php` の 86行目
```
if (is_nullorempty($custom_login_user) || $custom_login_user != LoginType::OAUTH) {
```
にて、 `$custom_login_user != LoginType::OAUTH` が常にTrueとなってしまっており、下部のトークンの設定が正しく行われないことが問題かと思われます。
```
if (is_nullorempty($custom_login_user) || $custom_login_user->login_type != LoginType::OAUTH) {
```
と、 `->login_type` を追加することで正しくアクセストークンが取得できました。

**Comment by hirossyi73** [comment]
最新バージョンでリリースしたためクローズします。
