### ISSUE TITLE
アップデート後のエラー

### ISSUE THREAD

**Issue by crux023** [exceedone/exment#1041]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
テーブルを表示させようとすると、エラーが出て表示されない。

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
4.2.2

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'operation_column_type' in 'where clause' (SQL: select * from `custom_operation_columns` where `custom_operation_columns`.`custom_operation_id` = 3 and `custom_operation_columns`.`custom_operation_id` is not null and `operation_column_type` = 1) (View: /home/******/*******/laravel/exment/vendor/exceedone/laravel-admin/resources/views/grid/tools.blade.php)

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by hirossyi73** [comment]
こちら実行して、なにか変化はありますか？

php artisan exment:update

**Comment by crux023** [comment]
php artisan exment:update
実行しましたが、変化はないようです。

**Comment by Yuusuke9228** [comment]
私の環境でもアップデートをかけると下記のエラーが出てアップデートが失敗します。


Illuminate\Database\QueryException  : SQLSTATE[42S01]: Base table or view alr                                                           eady exists: 1050 Table 'failed_jobs' already exists (SQL: create table `failed_                                                           jobs` (`id` bigint unsigned not null auto_increment primary key, `connection` te                                                           xt not null, `queue` text not null, `payload` longtext not null, `exception` lon                                                           gtext not null, `failed_at` timestamp default CURRENT_TIMESTAMP not null) defaul                                                           t character set utf8mb4 collate 'utf8mb4_unicode_ci')

**Comment by masa1212** [comment]
以下のエラーはV4.15→4.23にアップデート時に同様のエラーが発生しました
手動で、failed_jobsテーブルを削除して実行したところ、うまく動作しました。
（当方では、MySQLをつかっていまして、手動でDROP　TABLEしました）

＞Illuminate\Database\QueryException : SQLSTATE[42S01]: Base table or view alr eady exists: 1050 Table 'failed_jobs' already exists (SQL: create table failed_ jobs (id bigint unsigned not null auto_increment primary key, connection te xt not null, queue text not null, payload longtext not null, exception lon gtext not null, failed_at timestamp default CURRENT_TIMESTAMP not null) defaul t character set utf8mb4 collate 'utf8mb4_unicode_ci')
