### ISSUE TITLE
初期設定で入力された値が、連動設定列の値と連動しない

### ISSUE THREAD

**Issue by minamiosaka-gisenko** [exceedone/exment#1048]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
・A列に列種類 ：ユーザーで値を初期設定していた際、B列で連動設定を使ってメールアドレスを表示させようとしても、一度A列のユーザーを選択し直さないと値が連動しない。

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
・A列を列種類：ユーザーで作成する。この時初期値をログインユーザーに設定する。
・B列を列種類：メールアドレスで作成する
・フォーム基本設定で、B列のデータ連動設定に、列を選択：A列・リンク列を選択：メールアドレスを入力する。
・データの新規登録を開くとA列にログインユーザーは入力されているが、B列は空白になっている。
　A列を別にユーザーに変更し、再度ログインユーザーを入力すると、B列にログインユーザーのメールアドレスが入力される。

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
・現在のバージョン：v4.2.1

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。
・特に無し

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。
・フォームの設定内容
![image](https://user-images.githubusercontent.com/48745888/133712487-ef10faa3-ab5c-4169-ad94-0bf052f5abb8.png)

・初期設定でユーザー名のみ入力されている
![image](https://user-images.githubusercontent.com/48745888/133711887-97046bf0-231b-4087-8ae7-8f70904ec280.png)

・ユーザーを変更して、再度初期入力のユーザーを入力すると自動でメールアドレスも入力される
![image](https://user-images.githubusercontent.com/48745888/133713163-b13513b4-89fa-4300-917c-8195565e816f.png)

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。
・特に無し

**Comment by izumi-nkc** [comment]
私も似たようなことをしようとしてつまづきました。
私はプラグインで乗り切りましたので、参考までに。

やったこと
- 6行目 : 特定のテーブルのみでスクリプトが動くように条件設定
- 7行目：列の種類＝ユーザのフィールドのチェンジイベントを無理やり発火

```javascript
$(function () {
    // データ新規作成・編集画面の読み込み完了時
    $(window).off('exment:form_loaded', setFormLayout).on('exment:form_loaded', setFormLayout);

    function setFormLayout(){
        if ($("[class*='custom_value_d_shinsei']").length = 0) return;
        $('select[name="value[assigned_user]"]').change();
    }
});
```
