### ISSUE TITLE
カレンダービューで翌月に表示を変えると表示が消える

### ISSUE THREAD

**Issue by sota1141** [exceedone/exment#1050]
### Describe the bug / バグの説明
カレンダービューで、日付のカスタム列が2つ以上あるとき、翌月を表示するとデータが一瞬表示されたあと消える。
数か月先のデータは表示されない。
カスタム列が1つの場合は発生しない

### To Reproduce / 再現手順
①日付のカスタム列を２つ作成
②１つに今月の日付（9/24）、もう１つに翌月の日付（10/1）を入力する
③②で登録した日付の内容がカレンダーに表示される
④翌月ボタンをクリックして10月を表示すると、一瞬表示されたあと消える

### Version / 発生バージョン
4.2.2

### Error log / エラーログ
なし

### Screenshots / スクリーンショット
![cale1](https://user-images.githubusercontent.com/87462224/134609955-19956c6f-581a-4a7c-aa30-8b65297fbc44.gif)

![cal2](https://user-images.githubusercontent.com/87462224/134609961-bad663e4-d803-4e20-9ee0-93c6668b5b85.gif)

![cal3](https://user-images.githubusercontent.com/87462224/134609966-0226e59f-6018-448b-9f92-5a7830bbfcec.gif)

### Additional context / その他  
お忙しいところ申し訳ありませんがよろしくお願いします

**Comment by hirossyi73** [comment]
最新バージョンにて対応済
