### ISSUE TITLE
特定の組織・ユーザーの構成の場合、権限をもたないユーザーの判定が正しくない

### ISSUE THREAD

**Issue by nkgwf** [exceedone/exment#1068]
### Describe the bug / バグの説明
特定の組織・ユーザーの構成の場合、下記の場合に選択できないユーザーが発生する。

・列種類が「 ユーザー」で「権限をもたないユーザー・組織も表示する」が「NO」
・共有時のユーザ

### To Reproduce / 再現手順
１．下記ファイルのユーザー・組織を登録

[ユーザー - コピー.xlsx](https://github.com/exceedone/exment/files/7509575/-.xlsx)
[組織 - コピー.xlsx](https://github.com/exceedone/exment/files/7509576/-.xlsx)

２．「組織Ａ」に役割グループの「一般グループ 」を割り当て

３．カスタムテーブル「テーブル１」を作成
　　列種類が「 ユーザー」の列を追加（「権限をもたないユーザー・組織も表示する」は「NO」）

４．「一般グループ 」に「テーブル１」の「担当データの編集」「担当データの閲覧」「データの共有 」権限を追加

５．「テーブル１」にデータを新規作成。「 ユーザー」の列に一部ユーザーが表示選択できない。

![サーチユーザ](https://user-images.githubusercontent.com/93745479/141044323-d3a1cb70-3c3a-4baa-a272-c10d2f8775ea.png)

上記で「ユーザー３」が選択肢にでてこないが、ユーザー３は下記のような組織構造になっているので選択可能なはず。
似た構成の「ユーザー４」は表示されている。

組織Ａ（一般グループ ）
　組織Ａ４
　　組織Ａ４－７
　　　ユーザー３

組織Ａ（一般グループ ）
　組織Ａ３
　　組織Ａ３－７
　　　ユーザー４

![ユーザ３](https://user-images.githubusercontent.com/93745479/141043630-f5315e98-b246-400d-a42f-eac383246337.png)
![ユーザ４](https://user-images.githubusercontent.com/93745479/141043633-fc13ae57-f64c-4d22-b170-5474802a30ed.png)

６．共有時のユーザ選択も同様

![共有](https://user-images.githubusercontent.com/93745479/141043780-cb6bf7df-9129-47c2-92bb-ad0dc41dc598.png)

### Version / 発生バージョン
 v4.2.3

**Comment by hirossyi73** [comment]
最新バージョンで反映しましたので、ご確認ください。
