### ISSUE TITLE
カスタムビューの表示条件が「現在の作業ユーザ」の場合、該当データが表示されない

### ISSUE THREAD

**Issue by nkgwf** [exceedone/exment#1069]
### Describe the bug / バグの説明
カスタムビューの表示条件に「現在の作業ユーザ」「ログインユーザーに合致する」を選択した場合、
該当データが表示されないケースがある。（下記手順のケース）

### To Reproduce / 再現手順
１．カスタムテーブルにユーザー列（複数選択を許可する：YES）を作成
２．ワークフローで実行可能ユーザーに上記１のユーザー列を指定する
３．カスタムビューの表示条件に「現在の作業ユーザ」「ログインユーザーに合致する」を設定する
４．データを作成し、上記２が作業ユーザになるまで進める
５．作業ユーザでログインしてもカスタムビューに該当データが表示されない

なお、ユーザー列（複数選択を許可する：NO）場合は正しく表示される

### Version / 発生バージョン
v4.2.3

### Screenshots / スクリーンショット
![一覧](https://user-images.githubusercontent.com/93745479/141233309-3ec8fdfe-fa57-4262-8962-7367014e490e.png)

ワークフローのアクション設定
![フローアクション設定](https://user-images.githubusercontent.com/93745479/141233314-a26b38e7-fdb7-4823-9b69-e3e52185af4e.png)

カスタムビューのデータ表示条件
![ビュー表示条件](https://user-images.githubusercontent.com/93745479/141233394-a53a9f65-4806-4d40-9887-4337c52a901a.png)

**Comment by hirossyi73** [comment]
最新バージョンで反映しましたので、ご確認ください。
