### ISSUE TITLE
カスタムビューのデータ表示条件の「現在のステータス」に「検索値を含む」のような複数選択が欲しい

### ISSUE THREAD

**Issue by nkgwf** [exceedone/exment#1070]
### Describe the feature you'd like / 希望する機能の説明を行ってください
作成ユーザー かつ 現在のステータスが「承認」「棄却」のいずれか のような条件を設定したい。

**Comment by hirossyi73** [comment]
バージョンは忘れてしまいましたが、すでに対応しておりますのでご確認ください。
