### ISSUE TITLE
データコピー設定のボタンのHTML classが反映されない

### ISSUE THREAD

**Issue by nkgwf** [exceedone/exment#1073]
### Describe the bug / バグの説明
データコピー設定のボタンのHTML classが反映されない。

### To Reproduce / 再現手順
データコピー設定のボタンのHTML classがに「btn-info」を入力
詳細画面でボタンのclassを見ると
btn btn-sm btn-default pull-right
となり、btn-infoが反映されていない

### Version / 発生バージョン
v4.2.3

**Comment by hirossyi73** [comment]
最新バージョンで対応しましたので、ご確認ください。
