### ISSUE TITLE
N:Nリレーション状態の親テーブルでレコード作成時にエラー

### ISSUE THREAD

**Issue by marumoto-ug** [exceedone/exment#1074]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
テーブルAを親、テーブルBを子として多対多のリレーションを設定した場合
テーブルAのレコードを作成できなくなる。

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
※1対多のリレーションでは発生しません
1. 親テーブルのリレーション設定画面にてリレーション種類を「1対多」→「多対多」に変更して保存
2. 親テーブルにて新規ボタンを押下後、添付のエラー画面に遷移

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
v4.2.3

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。
<img width="1435" alt="____________________________2021-11-22_11 23 53" src="https://user-images.githubusercontent.com/65703301/142811233-d357b236-0e92-432e-9822-533c0af8636b.png">

**Comment by hirossyi73** [comment]
リレーションの種類の変更を出来ないようにしました。種類を変えたい場合は、一度削除を行ってください。
