### ISSUE TITLE
一覧表示する時に任意のカスタム列を右詰めで表示したい

### ISSUE THREAD

**Issue by skmt8585** [exceedone/exment#1075]
### Describe the feature you'd like / 希望する機能の説明を行ってください
テーブルのデータを一覧表示する時に、任意のカスタム列を右詰めで表示したい。
カスタム列が「整数」や「小数」「通貨」の場合に見やすくなります。

案1.カスタム列設定画面または、カスタムビュー設定画面に「配置」の設定を追加する。
案2.カスタム列設定画面または、カスタムビュー設定画面に「(CSSの書式に従った)スタイル」の設定を追加する。例：text-align: right;

**Comment by a-nagai-dkg** [comment]
みなさんプラグインでCSSいじって対応なさってるんでしょうか😢

**Comment by hirossyi73** [comment]
最新版で、左寄せ・真ん中寄せ・右寄せを選択できるようにしました。カスタム列設定画面から設定してください。

**Comment by a-nagai-dkg** [comment]
すばらしい！ 迅速な対応まことにありがとうございます☺

**Comment by skmt8585** [comment]
動作を確認しました。ご対応ありがとうございます。
