### ISSUE TITLE
「リビジョンを復元」が正しく動作しないことがある

### ISSUE THREAD

**Issue by hmatsumaru-idcf** [exceedone/exment#1078]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

カスタムテーブルのレコードの履歴から、「リビジョンを復元」したとき、正しく動作しないことがある

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

- 必須でないカスタムカラムを含むカスタムテーブルを作成する
- 必須でないカラムが空のレコードを作成する
- 作成したレコードの空の部分を入力してレコードを更新する
- レコードの履歴から、必須でないカラムが空のときのリビジョンを選択し、復元する
- 復元ができていない

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。

v4.2.2

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

なし

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

空でないカラムを編集した場合は「リビジョンの復元」は正しく動作していました。

**Comment by hirossyi73** [comment]
最新バージョンで対応しましたので、ご確認ください。
