### ISSUE TITLE
Docurainプラグイン導入の不具合

### ISSUE THREAD

**Issue by nko-ss** [exceedone/exment#1079]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

Docurainのプラグインをアップロードし、ユーザーテーブルを対象テーブルに設定したあと、ユーザー詳細ページを閲覧すると、エラーが発生しました。

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

1. 公式の[Docurain](https://exment.net/docs/#/ja/plugin_quickstart_docurain)プラグインをアップロードします。

2. プラグイン編集画面にて下記通りに入力します。
対象テーブル：ユーザー
Docurainトークン：Docurainの試用トークン
テーブル名と帳票ファイル名一覧：user,user.xlsx

3. ユーザー詳細ページを閲覧すると、エラーが発生します。
http://exment.local/data/user/1

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
Version   v4.2.2

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。
ログファイルを添付します。
[exment error.log](https://github.com/exceedone/exment/files/7630900/exment.error.log)

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。
自分で追加したテーブルで試したところ、同じくエラーが発生しました。

**Comment by hirossyi73** [comment]
@nko-ss 
調査いたします。

**Comment by hirossyi73** [comment]
@nko-ss 
先行してご連絡すると、以下の対応でお試しください。

・src/Services/Plugin/PluginEventTrait.phpの46行目付近を以下のように編集する。以下の方法でお願いします。
https://exment.net/docs/#/ja/update_tmp

修正前：

        $this->isCreate = is_nullorempty($custom_value) || $custom_value->wasRecentlyCreated;
        $this->isDelete = !is_nullorempty($custom_value) && (isset($custom_value->deleted_user_id) || isset($custom_value->deleted_at));

修正後：

        $this->isCreate = is_nullorempty($this->custom_value) || $this->custom_value->wasRecentlyCreated;
        $this->isDelete = !is_nullorempty($this->custom_value) && 
            (isset($this->custom_value->deleted_user_id) || isset($this->custom_value->deleted_at));

**Comment by nko-ss** [comment]
迅速なご対応を頂き、ありがとうございました。
不具合を解決することができました。

もう一点お伝えしたいのですが。
公式の[Docurain](https://exment.net/docs/#/ja/plugin_quickstart_docurain)プラグインをそのまま使うと、PDF出力時、下記のエラーが発生しました。

> Too few arguments to function Exceedone\Exment\Model\File::storeAs(), 3 passed in C:\exment\storage\app\plugins\Docurain\Plugin.php on line 116 and at least 4 expected

storeAs関数のソースを見て、下記のように、DourainのPlugin.phpの行116を修正したら、無事に出力できました。

修正前：
`$file = ExmentFile::storeAs($pdfFile, $this->custom_table->table_name, $outFileName)`

修正後：
`$file = ExmentFile::storeAs('application/pdf', $pdfFile, $this->custom_table->table_name, $outFileName)`

ありがとうございました。

**Comment by hirossyi73** [comment]
@nko-ss 
ありがとうございます。外部拡張機能ということもあり、メンテナンスが漏れていました。助かります。
