### ISSUE TITLE
カスタム列設定で複数選択を許可してる場合に、 フィルターで該当する検索語を入れたときにヒットしない

### ISSUE THREAD

**Issue by toshihiro86** [exceedone/exment#1083]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
カスタム列設定で複数選択を許可してる場合に、
フィルターで該当する検索語を入れたときにヒットしない

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
検索画面で該当項目を選択した場合にレコードがあるにも関わらずヒットしない。ただし同じ項目の別の選択肢を選ぶとヒットするので、ヒットする項目となぜかヒットしない項目が存在してしまっている。

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
Version   v4.2.3

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。
特になし

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by crux023** [comment]
複数選択に変更後
新しくデータを入力したものは検索にヒットして
今まで入力されていたデータは再度更新するまで検索やフィルタにヒットしない現象が起きていますので
それと同じでしょうか？
