### ISSUE TITLE
通知テンプレートの表示が重複している

### ISSUE THREAD

**Issue by sota1141** [exceedone/exment#1087]
### Describe the bug / バグの説明
通知テンプレートのカスタム列が重複して表示されている。
DB: SQL Server

### Version / 発生バージョン
ｖ4.2.4、ｖ4.2.5

### Error log / エラーログ
lalavel.logには何も記載されていません

### Screenshots / スクリーンショット
【通知テンプレート表示直後】
![err](https://user-images.githubusercontent.com/87462224/147170222-ad4c1c71-a6d4-427c-9561-33afa15e7df2.gif)

【編集画面】
![err2](https://user-images.githubusercontent.com/87462224/147170483-0724dca0-76a6-4e6a-a7e5-8024bc6e13ad.gif)

【１つ空欄にして保存ボタン押下後】
![err3](https://user-images.githubusercontent.com/87462224/147170522-169e3627-77e5-45d3-b1ca-ce0b14aa1862.gif)

### Additional context / その他  
特に急ぎ来ませんのでよろしくお願いします。

**Comment by hirossyi73** [comment]
先日リリースしたのですが、申し訳ないのですがテンプレートの仕様で、v4.2.8より新規インストールした場合にのみ有効になります。
v4.2.7以下で新規インストールし、別の環境にテンプレートインストールする場合は、初期インストール時に既定で追加されているテーブルのテンプレートは含めないようにお願いいたします。
