### ISSUE TITLE
カスタムデータ一覧取得(ビュー使用)の動作不具合

### ISSUE THREAD

**Issue by thara26** [exceedone/exment#1092]
### Describe the bug / バグの説明
カスタムデータ一覧取得(ビュー使用)APIにおいて、全件ビュー以外のビューを使用したデータ一覧が取得できない。

### To Reproduce / 再現手順
以下の条件の場合、カスタムデータ一覧取得(ビュー使用)APIがエラーになる。
・カスタムテーブルを新規作成する
・ワークフローを定義する
・定義したワークフローに新規作成したカスタムテーブルの使用設定を行う
・新規作成したカスタムテーブルにカスタムビューを設定する
・カスタムデータ一覧取得(ビュー使用)APIに新規作成したカスタムテーブルと全件ビュー以外のカスタムビューを指定して実行する

つまり、ワークフローの使用設定を行ったカスタムテーブルの標準ビューをカスタムデータ一覧取得(ビュー使用)APIに指定するとエラーになる。全件ビューの指定はエラーにならず、API仕様通りの動作となる。

### Version / 発生バージョン
v4.2.2

### Error log / エラーログ
Illuminate\Database\QueryException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'workflow_status_to_id' in 'where clause' (SQL: select count(*) as aggregate from `exm__8729fc6b51bd05ee5d39` inner join ((select * from `exm__8729fc6b51bd05ee5d39` where (`workflow_status_to_id` = 17) and `exm__8729fc6b51bd05ee5d39`.`deleted_at` is null) union (select * from `exm__8729fc6b51bd05ee5d39` left join (select `exm__8729fc6b51bd05ee5d39`.`id` as `morph_id`, `morph_type`, `workflow_status_from_id`, `workflow_status_to_id` from `exm__8729fc6b51bd05ee5d39` left join `workflow_values` on `workflow_values`.`morph_id` = `exm__8729fc6b51bd05ee5d39`.`id` and `workflow_values`.`morph_type` = kyuuka and `workflow_values`.`latest_flg` = 1) as `workflow_values` on `exm__8729fc6b51bd05ee5d39`.`id` = `workflow_values`.`morph_id` where (`workflow_status_to_id` = 17) and `exm__8729fc6b51bd05ee5d39`.`deleted_at` is null)) as `sub` on `sub`.`id` = `exm__8729fc6b51bd05ee5d39`.`id` where `exm__8729fc6b51bd05ee5d39`.`deleted_at` is null) in file /var/www/exment/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 669

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

### Additional context / その他  
本現象は、GUIでは発生しない。

**Comment by hirossyi73** [comment]
以前のバージョンで対応しています。ご確認いただけると幸いです。
