### ISSUE TITLE
データインポート時の空白トリムの選択

### ISSUE THREAD

**Issue by a-nagai-dkg** [exceedone/exment#1098]
データインポート時に、データの左右に空白があるとトリムしてくれるようです。
ただ、トリムして欲しくない場合に困るので、トリムの要否を選択できると助かります。
都度選択するのかシステムの設定値とするのかはどちらでも問題ないです。

なお、CSVで両端に空白を含むデータはダブルクォーテーションで囲っています。

**Comment by hirossyi73** [comment]
Laravelの仕様上、対応不可となります。

**Comment by a-nagai-dkg** [comment]
ご検討ありがとうございました。
