### ISSUE TITLE
サイト名(略)が使われない

### ISSUE THREAD

**Issue by a-nagai-dkg** [exceedone/exment#1100]
### Describe the bug / バグの説明
システム設定に「サイト名」「サイト名(略)」がありますが、メニューを折りたたんだ際も「サイト名(略)」ではなく「サイト名」が使われる。

### To Reproduce / 再現手順
上記のとおり。
「サイト名(略)」の登録自体は正常にできている。
サイトスキンを変えても一緒。

### Version / 発生バージョン
v4.2.7

以前のバージョンで発生していたかは不明。

### Error log / エラーログ
[laravel.log](https://github.com/exceedone/exment/files/7893178/laravel.log)

### Screenshots / スクリーンショット
![2022-01-19_09h13_30](https://user-images.githubusercontent.com/77262858/150039663-06bea793-529d-4869-a4b5-7268fa0fd2c3.jpg)

**Comment by hirossyi73** [comment]
再現しません。
![image](https://user-images.githubusercontent.com/8457265/150705303-720fca3d-a333-444b-949f-3175e99d3a49.png)
![image](https://user-images.githubusercontent.com/8457265/150705309-e93549ed-c8cb-4027-9c9a-5d26b47362c7.png)
![image](https://user-images.githubusercontent.com/8457265/150705319-3135caab-db74-4046-8ad4-3ea7c0aaf810.png)

**Comment by a-nagai-dkg** [comment]
確認いただきありがとうございます。
私も「Exment」「Ex」で試したところ再現しましたんでした。
ところが「Exment 2」「Ex」で試すと添付画像のようになり、どうやら名称によっては実は下にある長い名前の一部が隠れきれず見えている、というのが症状のようでした。
![image](https://user-images.githubusercontent.com/77262858/150706588-429d8218-f56e-49b5-98bf-2e53cbe7e39b.png)
`

**Comment by scsaht** [comment]
上記の修正の適用で、意図したとおりに「サイト名」「サイト名(略)」が表示されるようになりました。
ご対応ありがとうございます。

**Comment by hirossyi73** [comment]
v4.4.0にて修正しました。
