### ISSUE TITLE
カレンダービューのセルが特定の操作により縦に伸びる

### ISSUE THREAD

**Issue by izumi-nkc** [exceedone/exment#1104]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
カレンダービューで以下[再現手順]の操作を行うと、カレンダー内のセルが縦に伸びる

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
PC : ブラウザの高さをリサイズ
スマホ : スクロールの上下を繰り返す

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
4.2.4

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。
ブラウザのコンソールにエラーログは出力されていませんでした。

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。
<img width="375" alt="before_scroll_calendar" src="https://user-images.githubusercontent.com/75245652/150297669-94985cd4-fa61-453d-a769-8fd133fa560e.png">
<img width="375" alt="after_scroll_calendar" src="https://user-images.githubusercontent.com/75245652/150297696-d1f67f1e-ffce-47d5-a376-5b2874955013.png">

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。
カレンダービューの元になっている　FullCalendar　のバージョンアップをお願いしたいです。
Exment同梱Ver : 4.1.0
最新Ver : 5.10.1

**Comment by hirossyi73** [comment]
FullCalendarのv5は、インタフェースが変更され、構成が変わっている都合、単純な置き換えは難しいです。
v4の最新版であるv4.4.3も試したところ、こちらエンジニアが確認した限りでは、特に不具合修正されていませんでした。
申し訳ありませんが、現状このままとさせてください。
