### ISSUE TITLE
API「カスタムデータ情報更新」で複数IDが指定できない

### ISSUE THREAD

**Issue by izumi-nkc** [exceedone/exment#1110]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
APIのドキュメントを見ると、「カスタムデータ情報更新」は、複数のidを指定できると書いてありますが、複数していしたところ、最初のidだけしか更新されませんでした。

なお、本件、ドキュメントの誤植ではないかと思っております。
idの説明が、「カスタムデータ情報削除」と同じでした。

『カスタムデータのID。**複数件を削除する場合、**カンマ区切りで指定』

![image](https://user-images.githubusercontent.com/75245652/151512927-183b5e66-8b4d-4ebf-80f5-6185baf43872.png)

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
http://localhost/admin/api/data/{tableKey}/1,2,3,4,5

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
4.2.4

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。
ログはなし

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。
対象ファイルがあっているかわかりませんが、[ApiDataController.php]を見てみると、dataDeleteは複数ID分繰り返し処理をしていますが、dataUpdateは繰り返し処理がありません。

![image](https://user-images.githubusercontent.com/75245652/151513425-178df59f-a979-45c1-b0b8-0e64d6ce7e46.png)

**Comment by hirossyi73** [comment]
@izumi-nkc 
ありがとうございます。ドキュメントの誤植ですね。直します。

**Comment by hirossyi73** [comment]
@izumi-nkc 
修正しました。

**Comment by izumi-nkc** [comment]
@hirossyi73 
早々の対応ありがとうございます

いつか、情報更新も複数IDに対応していただけると大変助かります！！
リリースお待ちしております！！
