### ISSUE TITLE
View Setting Problem

### ISSUE THREAD

**Issue by MoePwintPhyu1** [exceedone/exment#1112]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。
![view_problem](https://user-images.githubusercontent.com/46021506/152726545-a2223fd6-c9f5-4f7f-bc51-01a54e409c34.jpg)
![loading_error](https://user-images.githubusercontent.com/46021506/152726664-91264af4-0956-4a38-8eb5-1a809675f5d2.jpg)

**Comment by hirossyi73** [comment]
Sorry, I want to fix this bug for next update.
If you want to fix now, Please modify the file "vendor/exceedone/exment/resources/lang/en/exment.php", and change this.

``` diff
L.1780
        'alldata_view_name' => 'All Data View',
-        'custom_view_grid_filters' => 'View "filter" item setting',
+        'custom_view_grid_filters' => 'View filter item setting',
        'description_custom_view_columns' => 'Select display columns.',
        
```

**Comment by MoePwintPhyu1** [comment]
Thanks a lot [hirossyi73](https://github.com/hirossyi73) . It's work now. 👍
