### ISSUE TITLE
Exment v4.3.1に出力されたExcelファイルから画像が消える不具合

### ISSUE THREAD

**Issue by nko-ss** [exceedone/exment#1118]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
Exment v4.3.1に更新した後、プラグイン（ドキュメント出力）に作成されたExcelファイルから元のテンプレートにあった画像・図形が消えます。

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
1. 公式の[ユーザー情報出力](https://exment.net/downloads/sample/plugin/document_demo_user.zip)プラグインをアップロードします。

2. テンプレートファイルに画像・図形を装入します。

3. ユーザー詳細ページにて、Excelファイル出力を行います。
http://exment.local/data/user/1

4. 出力されたファイルに装入された画像・図形が消えていることが確認できます。

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
Exment v4.3.1

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。
エラーログに何も出力されません。

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。
元のテンプレートファイル
![元のテンプレートファイル](https://user-images.githubusercontent.com/77083297/154638621-5978c593-d8fc-42bf-9747-8faed5c7d509.PNG)
出力されたExcelファイル
![出力されたExcelファイル](https://user-images.githubusercontent.com/77083297/154638620-32069b34-97eb-4be3-ba93-23ce6c36e663.PNG)

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。
- 自分で調べた結果、「\local\exment\vendor\phpoffice」にあるphpspreadsheet（v1.19.0）をv1.18.0に下げることで、画像が正しく出力されました。図形については、出力されたり、されなかったりしました。
- Microsoft Excel 2019を使っています。なお、出力されたExcelファイルを7zipで開いてみたところ、画像・図形のファイルが入っていました。

**Comment by hirossyi73** [comment]
確かに、以前調べた時に、PHPSpreadSheetによるものだったと記憶しています。
Exmentのバージョンを、1.18.0でバージョン指定できないか検討します。
