### ISSUE TITLE
通知設定の複製がエラーになる

### ISSUE THREAD

**Issue by a-nagai-dkg** [exceedone/exment#1119]
### Describe the bug / バグの説明
通知設定で既存の通知の操作から「この通知の複製」をクリックすると、必ずエラーになります。

### Error log / エラーログ
エラーログは出力されないようです。

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

![image](https://user-images.githubusercontent.com/77262858/155052638-16cd1b52-7f52-4c39-8f4d-93a4de2f615a.png)

**Comment by hirossyi73** [comment]
開発者メモ：
コピー時のエンドポイントが誤っているようなので、修正をお願いします。

現在：
http://localhost/admin/notify/create?copy_id=16

正：
  http://localhost/admin/notify/(テーブル名)/create?copy_id=16


また、ワークフローの通知の複製も怪しいので、ご確認をお願いします。

**Comment by hirossyi73** [comment]
最新バージョンで対応しました。

**Comment by a-nagai-dkg** [comment]
修正されていることを確認しました。
迅速なご対応まことにありがとうございました！
