### ISSUE TITLE
一度出たプラグインのエラーが修正後もログアウトするまで消えない

### ISSUE THREAD

**Issue by a-nagai-dkg** [exceedone/exment#1120]
### Describe the bug / バグの説明
自作プラグインをインストールしようとすると「以下のコードの読み込みに失敗しました。記述を見直してください。」というエラーが出ました。単純ミスでしたので修正して再度アップロードしましたが、エラーが消えません。
まだ間違っているのかと再度確認しましたが、間違っていないようです。

エラーはプラグイン管理画面だけではなく、Exmentのすべての画面に同じものが出ます。
そこでいったんプラグインを削除しましたが、まだエラーは消えません。
ログを見てみると、一度エラーが出ただけで、修正後はエラーは発生していないようでした。

結局ログインしなおすとエラーは消えたのですが、なにかのついでにでも修正していただけると助かります。

### Version / 発生バージョン
4.2.7

### Screenshots / スクリーンショット
![image](https://user-images.githubusercontent.com/77262858/155084010-d54d10d3-0c7c-4988-8fcf-1df1556e8de9.png)

**Comment by hirossyi73** [comment]
最新バージョンで対応しました。

**Comment by a-nagai-dkg** [comment]
修正されていることを確認しました。
迅速なご対応まことにありがとうございました！
