### ISSUE TITLE
フォーム設定画面で関連絞り込みの選択肢に表示されるべき項目が表示されない。

### ISSUE THREAD

**Issue by yuttta** [exceedone/exment#1134]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
「選択肢（他のテーブルの値一覧から選択）」で親子関係を持たせている際に、
関連絞り込みの選択肢として複数表示されるはずが一つしか表示されない。
（恐らく、カスタム列の並び順が最も小さい数値になっている項目のみ関連絞り込み可能な項目として表示される？）

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
実験的に以下のようなテーブルを作成しました。
・「テスト項目」
　　カスタム列１：項目名
　　　⇒列種類は「1行テキスト」
　　　⇒「必須」「検索インデックス」「ユニーク」をON

・「テストレベル」
　カスタム列１：対象項目名
　　　⇒列種類は「選択肢（他のテーブルの値一覧から選択）」　→　「テスト項目」テーブルを参照
　　　⇒「検索インデックス」をON
　カスタム列２：レベル名
　　　⇒列種類は「1行テキスト」
　　　⇒「検索インデックス」をON

・「テストグレード」
　カスタム列１：グレード名
　　　⇒列種類は「1行テキスト」
　　　⇒「必須」「検索インデックス」「ユニーク」をON
　カスタム列２：A_01：項目
　　　⇒列種類は「選択肢（他のテーブルの値一覧から選択）」　→　「テスト項目」テーブルを参照
　　　⇒「検索インデックス」をＯＮ
　カスタム列３：A_01：標準レベル
　　　⇒列種類は「選択肢（他のテーブルの値一覧から選択）」　→　「テストレベル」テーブルを参照
　カスタム列４：A_02：項目
　　　⇒列種類は「選択肢（他のテーブルの値一覧から選択）」　→　「テスト項目」テーブルを参照
　　　⇒「検索インデックス」をＯＮ
　カスタム列５：A_02：標準レベル
　　　⇒列種類は「選択肢（他のテーブルの値一覧から選択）」　→　「テストレベル」テーブルを参照

※各テーブルのデータのイメージはスクリーンショットをご参照ください。
※スクリーンショットには他のカスタム列も表示されていますが、
　本内容に関係ないカスタム列については割愛しております。

上記のような設定を行った後、テストグレードテーブルのフォーム設定で、
　「カスタム列３：A_01：標準レベル」　⇒　関連絞り込み「カスタム列２：A_01：項目」
　「カスタム列５：A_02：標準レベル」　⇒　関連絞り込み「カスタム列４：A_02：項目」
と本来は設定したいのですが、
「カスタム列３：A_01：標準レベル」「カスタム列５：A_02：標準レベル」共に、
関連絞り込みには「カスタム列２：A_01：項目」しか選択できない状態になります。

その後、たまたま気付いたのですが、
「カスタム列２：A_01：項目」と「カスタム列３：A_01：標準レベル」を、
「カスタム列４：A_02：項目」と「カスタム列５：A_02：標準レベル」より後ろに来るように
カスタム列の並び順を変更（スクリーンショットの⑤参照）したところ、
「カスタム列３：A_01：標準レベル」「カスタム列５：A_02：標準レベル」共に、
関連絞り込みには「カスタム列４：A_02：項目」しか選択できない状態に変わりました。

カスタム列の並び順によって関連絞り込みの選択可能項目が変動する現象と、
そもそも従来設定したい、
　「カスタム列３：A_01：標準レベル」　⇒　関連絞り込み「カスタム列２：A_01：項目」
　「カスタム列５：A_02：標準レベル」　⇒　関連絞り込み「カスタム列４：A_02：項目」
の設定ができない現象について、
大変お忙しい中申し訳ございませんがご確認いただけませんでしょうか。
よろしくお願いいたします。

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
v4.3.3

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。
ログは記録されていません。

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

①テスト項目テーブルのデータ
![image](https://user-images.githubusercontent.com/101703426/158556680-1d4399e7-1639-484c-83d7-3f3025b36ea0.png)

②テストレベルテーブルのデータ
![image](https://user-images.githubusercontent.com/101703426/158556761-e50100fb-dfd6-404c-acb3-d135984e66c2.png)

③テストグレードテーブルのデータ
![image](https://user-images.githubusercontent.com/101703426/158556797-a48ebc5a-2402-4b20-9913-69d4ff02146b.png)

④並び順変更前のテストグレードテーブルのカスタム列
 　⇒この状態だと関連絞り込みは「カスタム列２：A_01：項目」しか選択できない。
![image](https://user-images.githubusercontent.com/101703426/158561123-30448077-4556-4d92-a698-275e333562eb.png)

⑤並び順変更後のテストグレードテーブルのカスタム列
　⇒この状態だと関連絞り込みは「カスタム列４：A_02：項目」しか選択できない。
![image](https://user-images.githubusercontent.com/101703426/158561361-907c6208-ba96-48ca-8eda-73c63972157c.png)

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by hirossyi73** [comment]
最新版で修正リリースしました。
