### ISSUE TITLE
インストール後にサイトファビコン(ico)の登録ができない

### ISSUE THREAD

**Issue by ShinjiOogamiKawano** [exceedone/exment#1140]
### Describe the bug / バグの説明
インストール（初期データ）後にシステム設定にあるサイトファビコン(ico)から変更したいファビコンファイルをアップロードしても「 サイトファビコン(ico)には画像ファイルを指定してください。」というエラーメッセージが表示されファビコンを変更することができない。もしくは、新規登録することができない。

### To Reproduce / 再現手順
システム設定→サイトファビコン(ico)よりファビコンファイルを選択し、「保存」ボタン押下で発生。

### Version / 発生バージョン
v4.3.4

### Screenshots / スクリーンショット
<img width="741" alt="image" src="https://user-images.githubusercontent.com/6214196/160581180-71a57612-033d-48d2-af1b-f085c69652f6.png">

### Additional context / その他  
単純に更新時のバリデーションでicoファイルが通らないだけではと思いました。
初期データインストール時は問題なくicoファイルは登録されていましたので。

**Comment by hirossyi73** [comment]
最新版で修正リリースしました。
