### ISSUE TITLE
保存後のアクションに「新規作成する」を選んだ場合、フォーム表示条件が適用されない

### ISSUE THREAD

**Issue by IRRC-Nakagawara** [exceedone/exment#1141]
### Describe the bug / バグの説明
表示条件を設定しているフォームの入力時、保存後アクションのチェックボックスを「新規作成する」にチェックした場合、データ保存後に表示条件が適用されず、規定のフォームが表示されてしまう

### To Reproduce / 再現手順
1.「フォーム優先順位」を設定したフォームでデータを入力
2.「新規作成する」にチェックを入れて「保存」ボタンをクリック

### Version / 発生バージョン
4.3.4

**Comment by hirossyi73** [comment]
@IRRC-Nakagawara 
こちらで確認している限りは、正常に動作していました。
どのような条件を設定しているかどうかをご教授いただけないでしょうか。

**Comment by IRRC-Nakagawara** [comment]
対象テーブルに「依頼種類」というカスタムフィールドを設定しています。
目的によって複数の入力フォームを用意して、この値（依頼種類）に応じた入力フォーム切り替えるよう、
フォーム優先順位の設定を行っています。

条件項目はこの依頼種類のみです（「依頼種類」はフォーム上では読み取り専用としています）。
最初の新規登録時には正常に目的のフォームが表示されますが、
そのデータの保存時に「新規作成する」のチェックを入れて保存すると、
続けて同じフォームで入力したいのに、規定のフォームが表示されてしまいます。

![新規入力時](https://user-images.githubusercontent.com/102721309/162167719-c3f5874e-3e57-4656-94a1-0d9aef6e83ed.jpg)
![保存時](https://user-images.githubusercontent.com/102721309/162167731-7d389cff-7991-4b1a-89c6-6c738f57a826.jpg)
![保存後](https://user-images.githubusercontent.com/102721309/162167739-7717d344-90c9-432a-9609-8cc50989c1d5.jpg)
![カスタムフォーム優先順位設定](https://user-images.githubusercontent.com/102721309/162168119-e70f6134-effe-41eb-b536-a6e15659e7c2.jpg)
。

**Comment by hirossyi73** [comment]
新規の場合は、「依頼種類」は未入力となる設定でしょうか？
その場合は、既定のフォームが表示されるのは仕様になります。

**Comment by IRRC-Nakagawara** [comment]
カスタム列の「初期値」で指定する、ということでしょうか？
その場合は初期値は固定ということになりますよね。
仕様ということで承知いたしました。
