### ISSUE TITLE
一覧の項目名も右寄せ・中央寄せ

### ISSUE THREAD

**Issue by a-nagai-dkg** [exceedone/exment#1145]
https://github.com/exceedone/exment/issues/1075
先日↑こちらで右寄せ・中央寄せに対応していただきましたが、
一覧の項目名の部分も、この設定に合わせて中央寄せ、右寄せされるとさらにありがたいです。
項目数が少ない場合、項目名が左、値は右でかなり距離が離れてわかりづらいことがあるので・・・

**Comment by hirossyi73** [comment]
v4.4.0にて対応しました。
※見出しの配置は、全列で統一となります。個別での設定はできません。
