### ISSUE TITLE
パラメータ変数${value_image:(列名)}を複数回使用すると反映されない。

### ISSUE THREAD

**Issue by kake359** [exceedone/exment#1147]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

公式ドキュメント（https://exment.net/docs/#/ja/plugin_quickstart_document）より
プラグイン(ドキュメント出力)にあるconfig.jsonのサンプルを使用して
Excelに画像を出力する機能を利用。

左上から1個目は適切に画像が出力されるが
2個目、3個目・・・と複数個の${value_image:(列名)}を使用すると
1個目以外は画像が出力されない。

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

下記のようにカスタムテーブルを作成し
画像A~Dの4枚を保存
ファイル形式は.jpgとなります。

![image](https://user-images.githubusercontent.com/103429968/163525281-06a09b4a-ee20-41bd-a810-cb234bfb9392.png)

config.jsonに関しては、公式ドキュメントのサンプルを活用。
Plugin_nameやUUIDなどを変更したのみ。

作成前後の処理は不要なためPlugin.phpは未使用。

document.xlsxにはパラメーター変数　${value_image:(列名)}　を利用した
下記にような簡単なdocument.xlsxを作成。

![temp](https://user-images.githubusercontent.com/103429968/163524708-33ede569-aa6a-4965-94bc-67059abb42ba.png)

上記状態でExcel出力を実行すると
左上の1個目のみ画像出力され、
残りについてはブランクのまま出力されてしまう。
![2](https://user-images.githubusercontent.com/103429968/163525570-f450eb8b-85a0-4ec7-b65b-bd46baff91e5.jpg)

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
v4.3.5

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。
出力なし

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。
仕様でしたら申し訳ございません。

**Comment by hirossyi73** [comment]
@kake359 
まだ詳細は確認できていないのですが、関連ライブラリであるPhpSpreadSheetのバージョンをご教授いただけないでしょうか？
過去のPhpSpreadSheetのバージョンによってどうもバグがあったようなので、念の為確認したいです。

https://exment.net/docs/#/ja/troubleshooting?id=excel%e3%82%92%e3%83%86%e3%83%b3%e3%83%97%e3%83%ac%e3%83%bc%e3%83%88%e3%81%a8%e3%81%97%e3%81%9f%e3%83%89%e3%82%ad%e3%83%a5%e3%83%a1%e3%83%b3%e3%83%88%e5%87%ba%e5%8a%9b%e3%81%a7%e3%80%81%e7%94%bb%e5%83%8f%e3%81%ae%e5%87%ba%e5%8a%9b%e3%81%ab%e5%a4%b1%e6%95%97%e3%81%99%e3%82%8b
