### ISSUE TITLE
カスタム列設定で、ファイルに設定した列のプレースホルダー内容がカスタムフォームに反映されない。

### ISSUE THREAD

**Issue by 5050boon** [exceedone/exment#1151]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

カスタム列設定で、ファイルに設定したプレースホルダー内容がカスタムフォームに反映されない。
プレースホルダーに表示内容を設定しても、カスタムフォームをプレビューすると”ファイルをドラッグ＆ドロップして下さい”が常に表示される。
間違いであれば申し訳ありません。（削除して下さい）

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
V4.3.5

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by hirossyi73** [comment]
・ファイルのドラッグ＆ドロップエリア
・プレースホルダー
の両方を、カスタム列設定で指定できるようにします。

**Comment by 5050boon** [comment]
ありがとうございます

**Comment by hirossyi73** [comment]
v4.4.1にて対応しました。

**Comment by 5050boon** [comment]
ありがとうございました。
