### ISSUE TITLE
特定ビューにて件数は表示されるがデータが表示されない

### ISSUE THREAD

**Issue by cob1983** [exceedone/exment#1159]
### Describe the bug / バグの説明
特定のビューにおいてデータ件数は表示されるものの、データ自体は表示されない。(以前までは表示されていたが、最近になって表示されていないことに気が付いた。)

なお別の全体ビューからフィルタにて対象データを絞り込むと同一件数でデータもきちんと表示される。

### To Reproduce / 再現手順
特になし

### Version / 発生バージョン
v4.4.1

### Error log / エラーログ
特になし

### Screenshots / スクリーンショット
![image](https://user-images.githubusercontent.com/105622194/168520718-86df0978-089d-430f-ae90-a9a8fc26b167.png)
![image](https://user-images.githubusercontent.com/105622194/168520666-1ff0626e-3e3c-4f7a-85f1-0f95f78bdfcd.png)

### Additional context / その他  
特になし

**Comment by hirossyi73** [comment]
@cob1983 
本件、現在再現しない状況です。
別の開発者で再度確認しますが、これらの情報もいただけると幸いです。

・他のビューだと正常に表示されるか
・表示条件や表示列を変えると、正しく表示されるか

**Comment by cob1983** [comment]
@hirossyi73 
◆他のビューだと正常に表示されるか
→問題なく表示されています。

◆表示条件や表示列を変えると、正しく表示されるか 
→データ表示条件(両方日付)のいずれか１つを削除すると、残りの条件で表示されます。
A日付 And B日付　データ表示されない　件数表示される
A日付　　　　　　データ表示される　　件数表示される
B日付　　　　　　データ表示される　　件数表示される

全件表示した際にフィルターで検索した際、前回はデータも件数も一致して表示されたはずですが、今日再度確認したところデータは表示されず件数のみ表示されました。

**Comment by hirossyi73** [comment]
@cob1983 
ありがとうございます。追加で、以下の情報もいただけないでしょうか？
・データベースの種類(MySQL・MariaDB・SqlServer)
・PHPバージョン

**Comment by hirossyi73** [comment]
追記：もう１名のメンバーでも、現状再現せず

**Comment by cob1983** [comment]
@hirossyi73 
データベースの種類　MariaDB
PHPバージョン　7.4.27
です。よろしくお願い致します。

**Comment by hirossyi73** [comment]
やはり再現しない状況です。
何かしらログファイルが出ていたら添付していただけないでしょうか？

**Comment by fleming35800** [comment]
脇から失礼いたします。この現象私の環境でも発生しております。
いつから出ている現象なのかは定かではないのですが・・・
私の場合「集計ビュー」にて件数は表示されるもののデータが表示されないという現象発生しております。
![image](https://user-images.githubusercontent.com/75713203/172270395-6e1c80c9-71a5-4fcb-928d-e44e6a1affb8.png)
![image](https://user-images.githubusercontent.com/75713203/172270421-27bf688f-b076-4dbc-b3a8-0dcade9b487b.png)
特にエラー等がログファイルに吐き出されているわけではなさそうです。
もし必要であればバックアップのデータなどお渡しすること可能です。
環境に関しては以下の環境になります。
Xserverにて環境構築。
exment:4.4.0
Composer version 2.1.9
PHP 7.4.13

**Comment by fleming35800** [comment]
こちらの件ですが、比較的新しくできたテーブルに関しては正しく集計およびデータの表示がされていました。
どの段階でかはわかりませんがもしかすると特定のバージョン以前で作成されたテーブルに関してデータが表示されないのかもしれません。
