### ISSUE TITLE
編集時にファイルが指定されているにもかかわらず、「ファイルを選択してください」と出て保存できない

### ISSUE THREAD

**Issue by nkgwf** [exceedone/exment#1162]
### Describe the bug / バグの説明
ファイル列が「必須」「複数選択を許可」になっている場合、編集時にファイルが指定されているにもかかわらず、「ファイルを選択してください」と出て保存できない

### To Reproduce / 再現手順
・カスタム列に列種別が「ファイル」で「必須」「複数選択を許可」を含むテーブルを作成する。
・レコードを新規作成し、ファイル列に1ファイルを選択して保存する。
・同レコードを編集して、そのまま保存ボタンを押す。
・「ファイルを選択してください」と出て保存できない。（メッセージ出ないで保存できない場合もあり。子テーブルが無い場合？）

なお、「複数選択を許可」になっていない場合は問題ない模様。

### Version / 発生バージョン
v4.3.5

**Comment by hirossyi73** [comment]
v4.4.2にてリリースしました。
