### ISSUE TITLE
親子テーブルで親テーブルが閲覧権限しかない場合、子テーブルの編集権限を持っていても編集できなくなる。

### ISSUE THREAD

**Issue by yuttta** [exceedone/exment#1166]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
親子テーブルでリレーション関係を設定し、親テーブルは閲覧権限のみ、子テーブルは編集権限を持っているアカウントで子テーブルのデータを表示すると、編集ボタンが表示されず編集できない。

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
①：親テーブルと子テーブルをリレーション設定する。
②：親テーブルの通常設定→権限設定にて「全ユーザーが閲覧可能」をYESにする。
③：子テーブルの通常設定→権限設定にて「全ユーザーが編集可能」をYESにする。
④：親テーブルにデータを登録。
⑤：子テーブルに④で作成したデータをリレーションさせてデータを登録。
⑥：⑤で登録したデータを表示させると、編集ボタンが表示されない。
⑦：試しに②で設定した親テーブルの権限設定で「全ユーザーが編集可能」をYESにする。
⑧：再度⑤で登録したデータを表示させると、編集ボタンが表示されて編集可能になる。
⑨：親テーブルのテーブル設定→拡張設定→画面からの変更不可の「編集」にチェックを入れて保存
⑩：再度⑤で登録したデータを表示させると、編集ボタンが消えて編集不可になる。

上記のことから、子テーブルで編集できる権限を持っていても親テーブルが編集不可であれば、問答無用で子テーブルも編集不可になってしまうようです。

過去に以下類似の投稿がありましたが、
アクティビティが無いままボットによってクローズされてしまっている様子だったので、
大変恐縮ですが新しく投稿させて頂きました。
[https://github.com/exceedone/exment/issues/913#issuecomment-886017804](url)

以上、お忙しい中申し訳ございませんがご確認の程よろしくお願いいたします。

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
v4.3.5

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by hirossyi-exc** [comment]
こちらは仕様になります。
