### ISSUE TITLE
iPad版 Safariでラジオボタンを押すことが困難

### ISSUE THREAD

**Issue by kake359** [exceedone/exment#1167]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

iPad版Safariにおいて、ラジオボタンを押すことが困難。
複数回押すことで稀に反応がある。

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

テストテーブルを作成し、カスタム列種類で選択肢を選択。
ラジオボタン・チェックシボックス形式をYesで模擬データを作成。

iPad純正のSafariで当該ページを閲覧し
ラジオボタンをタップするも反応しない。
複数回押すと、稀に選択できる。

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
V4.4.0
iOS15

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。
なし

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。
なし

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。
なし

**Comment by koizu-mkII** [comment]
@kake359 
こちらbotによってクローズされましたが、その後、Exmentのバージョンアップや、iOS、iPadOSのバージョンアップによって変化はありましたでしょうか？
もし、変わらず、事象が発生する場合は、スクリーンショットのご提示、iPadの型番などの情報もいただけると幸いです。
