### ISSUE TITLE
#958 子テーブルの入力フォームにおける計算式動作不良について

### ISSUE THREAD

**Issue by fleming35800** [exceedone/exment#1170]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
#958 で報告されている不具合に関してまして、当方の環境でも発生しております。
子テーブル→親テーブルのデータ参照。
親テーブル→子テーブルのデータ参照もうまく行っていないようです。
ご確認お願い致します。

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
4.4.0

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。
特にエラーログは出ておりません。

**Comment by hirossyi73** [comment]
@fleming35800 

リレーションの種類ですが、「リレーション設定」から行うものと、「カスタム列→選択肢 (他のテーブルの値一覧から選択)」の2種類あります。
https://exment.net/docs/#/ja/relation

今回、どちらの方法で2テーブルを結合しているか、ご教授いただけないでしょうか。

**Comment by fleming35800** [comment]
ご確認頂きましてありがとうございます。

「リレーション設定」より「1対多」で設定したテーブルで子テーブルより親テーブルにある小数の値を合算するものだったのですが、改めて確認した所、問題なく計算されて表示されました。
※研修報告を親テーブルで作成、親テーブルにある研修時間の合算を子テーブルで出したかったのですが、集計ビューの方がシンプルに実現できるなと思い集計ビューを使用させていただいてました。

私の勘違いでした。失礼いたしました。
クローズさせていただきます。
