### ISSUE TITLE
Azure ADでAuthenticatorアプリを使ったSAML認証ができない

### ISSUE THREAD

**Issue by ohmix1** [exceedone/exment#1175]
### Describe the bug / バグの説明

Azure ADとAuthenticator アプリを使ったSAML認証を行おうとすると、
Microsoftのサインイン画面で以下のエラーが発生します。

> 申し訳ありませんが、サインイン中に問題が発生しました。
> AADSTS75011: Authentication method 'X509, MultiFactor' 
> by which the user authenticated with the service doesn't match requested authentication method 'Password, ProtectedTransport'. Contact the Exment application owner.

### To Reproduce / 再現手順

Azure ADを利用したSAML認証設定を設定して、ログインテストを実施する。
パスワード認証だとうまくいきますが、Authenticator アプリだと上記エラーで認証できない。

Microsoftのエラー説明ページによると、
https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/error-code-aadsts75011-auth-method-mismatch
RequestedAuthnContextオプションの値を削除できるかどうかを尋ねよとのこと。
Password, ProtectedTransport 以外も受け計れるようになりませんでしょうか。

### Version / 発生バージョン
Version   v4.4.2

### Error log / エラーログ
Exmentがわでエラーは出ていないと思われます。

**Comment by hirossyi73** [comment]
@ohmix1 
申し訳ありませんが、現在その環境を持ち合わせておりませんので、プログラムの修正を実施していただき、Pull requestしていただきますよう、よろしくお願いします。

**Comment by ohmix1** [comment]
hirossyi73さん、レスポンスありがとうございます。

exment/src/Model/LoginSetting.php の 364 行当たりにrequestedAuthnContext行を足せばうまくいきました。
```
            'security' => [
                'nameIdEncrypted' => boolval($provider->getOption('saml_option_name_id_encrypted')) ??  false,
                'authnRequestsSigned' => boolval($provider->getOption('saml_option_authn_request_signed')) ??  false,
                'logoutRequestSigned' => boolval($provider->getOption('saml_option_logout_request_signed')) ??  false,
                'logoutResponseSigned' => boolval($provider->getOption('saml_option_logout_response_signed')) ??  false,
                'requestedAuthnContext' => false,
```

知識なく Pull request できませんので、ログイン設定画面含めた改善要望とさせていただきますのでご一考願います。

以上

**Comment by a0z0** [comment]
プロリクエストしてみましたのでご確認ください。
