### ISSUE TITLE
カスタム列　URL　へのエクスプローラーアドレスバーからのコピペ

### ISSUE THREAD

**Issue by 5050boon** [exceedone/exment#1179]
### Describe the feature you'd like / 希望する機能の説明を行ってください
A clear and concise description of what you want to happen. / あなたが何をしたいのかについての、明確で簡潔な説明を行ってください。

導入検討中で小規模テスト中ですが、便利に使わせて頂いております。
誠にありがとうございます。

下記に気がついた点を上げさせて頂きます。
exmentのファイルアップロード数に制限があるため、共有ファイルのフォルダーパスを、カスタム列　urlにて　file://fileserver.co.jp/・・・・と入力して使用しています。(ローカルファイルリンク有効化の拡張機能使用)
しかし、フォルダーパスをエクスプローラーからコピペしようとすると、￥　⇒　\　に変換されるためすべて　/　に上書きが必要です。

エクスプローラーのアドレスバーの　￥￥fileserver.co.jp￥・・・・　をコピペするだけで、file://fileserver.co.jp/・・・へ、または、￥￥fileserver.co.jp￥・・・を、そのまま使用できる様にならないでしょうか？
階層が深いとかなりの手間が・・・

### Additional context / その他
Add any other context or screenshots about the feature request here. / 機能リクエストに関する他のコンテキストまたはスクリーンショットをここに追加します。

**Comment by ohmix1** [comment]
ただの利用者としてのご提案です。
ニッチな機能なのでイベントプラグインで対応するのがよいかと思われます。
[https://exment.net/docs/#/ja/plugin_quickstart_event](https://exment.net/docs/#/ja/plugin_quickstart_event)
