### ISSUE TITLE
通知設定の送信先メールアドレスに複数登録するとメールが送信されない

### ISSUE THREAD

**Issue by izumi-nkc** [exceedone/exment#1184]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
通知設定で以下の設定をしたところ、メールが送信されなかった。
 - 実施トリガー : データ新規作成・更新・共有・コメント
 - 通知条件設定 : 新規
 - 実施アクション : Eメール
 - 通知対象 : 指定のメールアドレス
 - 送信先メールアドレス : (複数のメールアドレスを改行区切りで登録)

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
上記設定を参照

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
4.4.1

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。
エラーログには何も出力されていませんでした。

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。
![image](https://user-images.githubusercontent.com/75245652/178664441-14512cdc-800e-43b6-a968-797169b8a701.png)
* スクショでは不具合が発生しているので、メールアドレスを１つにしています。

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。
試しに、登録した複数のメールアドレスを１つだけに変更して試したところ、問題なくメールが送信されました。

**Comment by hirossyi73** [comment]
v5.0.0で対応完了しました。
