### ISSUE TITLE
組織の編集画面でユーザー項目が1行形式の選択項目になってしまった

### ISSUE THREAD

**Issue by ohmix1** [exceedone/exment#1187]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
組織(organization)テーブルに項目を追加したり設定変更を行っていたら、
組織の編集画面で「ユーザー」項目が1行形式の選択項目になってしまいました。
既定ではリストボックス2個形式でしたが元に戻す設定はありますでしょうか?

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
ユーザーや組織テーブルに項目追加などしていましたが、具体的な再現手順は不明です。

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
v4.4.2

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。
とくにエラーは出てないと思います。

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

**既定の形式**
![既定の形式](https://exment.net/docs/ja/img/organization/organization4.png)

**1行形式**
![1行形式](https://user-images.githubusercontent.com/13477473/178921847-06f9f346-be2f-4dd4-9000-7f782d9d6ad6.PNG)

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by hirossyi-exc** [comment]
該当データが100件を超えるとajaxによる取得形式になります。ListBox形式ではajaxに対応していないので、1行形式に切り替わります。
仕様なのでクローズします。
