### ISSUE TITLE
ワークフローに通知設定をするとエラー表示される

### ISSUE THREAD

**Issue by issg-matsuo** [exceedone/exment#1188]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

ワークフロー・汎用を作成ワークフロー
STEP01 ステータスを30定義
STEP03 アクションを２つ定義
この状態で設定を終了後
STEP03　通知設定を追加したところ
実施アクション設定は必ず1行以上入力してください。
と表示される

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
新規にワークフローを作成して
ワークフロー・汎用を作成ワークフロー
STEP01 ステータスを30定義
STEP03 アクションを２つ定義
この状態で設定を終了後
STEP03　通知設定を追加したところ
実施アクション設定は必ず1行以上入力してください。
と表示される

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。

バージョンは 

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。
v4.4.2

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。
![form](https://user-images.githubusercontent.com/109338757/179176330-2f07c103-c79f-4f74-b4db-ebfe7375f32c.jpg)
![error](https://user-images.githubusercontent.com/109338757/179176347-24b49d55-f027-4331-8f13-4df15c64542c.jpg)

**Comment by hirossyi-exc** [comment]
通知アクションを設定してください。仕様なのでクローズします。
