### ISSUE TITLE
WEBサーバのログに　404 エラーが発生する(https時)

### ISSUE THREAD

**Issue by issg-matsuo** [exceedone/exment#1190]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

httpの時はエラーが発生なし。
https時は、アクセスエラー404 が発生しているが、httpアクセス時にはエラにならない
httpdのログをみても404となったURLへのアクセスはしていないようです。

/var/log/httpd/ssl_accesslogに404のエラー
10.a.b.c - - [15/Jul/2022:20:05:44 +0900] "GET /vendor/laravel-admin/toastr/build/toastr.js.map HTTP/1.1" 404 6609
10.a.b.c - - [15/Jul/2022:20:05:47 +0900] "GET /vendor/laravel-admin/toastr/build/toastr.js.map HTTP/1.1" 404 6609
10.a.b.c - - [15/Jul/2022:20:06:00 +0900] "GET /vendor/laravel-admin/toastr/build/toastr.js.map HTTP/1.1" 404 6609
10.a.b.c - - [15/Jul/2022:20:06:00 +0900] "GET /lib/js/bignumber.js.map HTTP/1.1" 404 6609
10.a.b.c - - [15/Jul/2022:20:06:00 +0900] "GET /vendor/exment/mathjs/math.min.map HTTP/1.1" 404 6609

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

httpsアクセスを行う

ログインして
10.a.b.c - - [15/Jul/2022:20:05:43 +0900] "GET /favicon.ico HTTP/1.1" 200 -
10.a.b.c - - [15/Jul/2022:20:05:43 +0900] "GET /admin/data/mail_template?_pjax=%23pjax-container HTTP/1.1" 302 394
10.a.b.c - - [15/Jul/2022:20:05:44 +0900] "GET /admin/auth/login HTTP/1.1" 200 5226
10.a.b.c - - [15/Jul/2022:20:05:44 +0900] "GET /favicon.ico HTTP/1.1" 200 -
10.a.b.c - - [15/Jul/2022:20:05:44 +0900] "GET /admin/data/mail_template HTTP/1.1" 302 394
10.a.b.c - - [15/Jul/2022:20:05:44 +0900] "GET /admin/auth/login HTTP/1.1" 200 5226
10.a.b.c - - [15/Jul/2022:20:05:44 +0900] "GET /vendor/laravel-admin/AdminLTE/bootstrap/css/bootstrap.min.css HTTP/1.1" 200 124702
10.a.b.c - - [15/Jul/2022:20:05:44 +0900] "GET /vendor/laravel-admin/font-awesome/css/font-awesome.min.css HTTP/1.1" 200 31000
10.a.b.c - - [15/Jul/2022:20:05:44 +0900] "GET /vendor/laravel-admin/AdminLTE/dist/css/AdminLTE.min.css HTTP/1.1" 200 91082
10.a.b.c - - [15/Jul/2022:20:05:44 +0900] "GET /vendor/laravel-admin/AdminLTE/plugins/iCheck/square/blue.css HTTP/1.1" 200 1611
10.a.b.c - - [15/Jul/2022:20:05:44 +0900] "GET /vendor/laravel-admin/toastr/build/toastr.min.css HTTP/1.1" 200 6454
10.a.b.c - - [15/Jul/2022:20:05:44 +0900] "GET /vendor/exment/js/common_all.js HTTP/1.1" 200 3848
10.a.b.c - - [15/Jul/2022:20:05:44 +0900] "GET /vendor/laravel-admin/AdminLTE/plugins/iCheck/square/blue.png HTTP/1.1" 200 2185
10.a.b.c - - [15/Jul/2022:20:05:44 +0900] "GET /favicon.ico HTTP/1.1" 200 -
10.a.b.c - - [15/Jul/2022:20:05:44 +0900] "GET /vendor/laravel-admin/toastr/build/toastr.js.map HTTP/1.1" 404 6609
10.a.b.c - - [15/Jul/2022:20:05:46 +0900] "GET /admin/workflow/4/notify/create HTTP/1.1" 302 394
10.a.b.c - - [15/Jul/2022:20:05:46 +0900] "GET /admin/auth/login HTTP/1.1" 200 5226
10.a.b.c - - [15/Jul/2022:20:05:47 +0900] "GET /favicon.ico HTTP/1.1" 200 -
10.a.b.c - - [15/Jul/2022:20:05:47 +0900] "GET /vendor/laravel-admin/toastr/build/toastr.js.map HTTP/1.1" 404 6609
10.a.b.c - - [15/Jul/2022:20:05:59 +0900] "POST /admin/auth/login HTTP/1.1" 302 450

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。

exment 4.4.2.
httpd Server version: Apache/2.4.37 (Oracle Linux)  Server built:   Jun 22 2022 14:35:49

/etc/httd/conf/httpd.conf 追加

<VirtualHost *:80>
  DocumentRoot /var/www/exment/public
  <Directory /var/www/exment/public>
    Allow from all
    AllowOverride All
    Require all granted
  </Directory>
</VirtualHost>

/etc/httd/conf.d/ssl.conf  変更

<VirtualHost *:443>

# General setup for the virtual host, inherited from global configuration
#DocumentRoot "/var/www/html"
#ServerName www.example.com:443
ServerName 10.a.b.c:443

  DocumentRoot /var/www/exment/public
  <Directory /var/www/exment/public>
    Allow from all
    AllowOverride All
    Require all granted
  </Directory>

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

特になし

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

特になし
### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

httpアクセス時はログに404エラーなし

ブラウザのログ
DevTools がソースマップの読み込みに失敗しました（https://10.a.b.c/vendor/laravel-admin/toastr/build/toastr.js.map のコンテンツを読み込めませんでした（HTTP エラー: ステータス コード 404、net::ERR_HTTP_RESPONSE_CODE_FAILURE））
DevTools がソースマップの読み込みに失敗しました（https://10.a.b.c/lib/js/bignumber.js.map のコンテンツを読み込めませんでした（HTTP エラー: ステータス コード 404、net::ERR_HTTP_RESPONSE_CODE_FAILURE））
DevTools がソースマップの読み込みに失敗しました（https://10.a.b.c/vendor/exment/mathjs/math.min.map のコンテンツを読み込めませんでした（HTTP エラー: ステータス コード 404、net::ERR_HTTP_RESPONSE_CODE_FAILURE））

**Comment by hirossyi73** [comment]
環境構築のエラーは、issue対象外です。
