### ISSUE TITLE
カレンダービューに表示されているアイテムの吹き出し上部が見切れてしまう（月表示のみ）

### ISSUE THREAD

**Issue by 5050boon** [exceedone/exment#1191]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

カレンダーの月ごと表示のみ、上段のアイテム吹き出しが見切れている

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
4.4.2

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。
![キャプチャ3](https://user-images.githubusercontent.com/96157134/180112719-65e4ed00-af95-4147-9646-470fd90eb909.PNG)

![キャプチャ1](https://user-images.githubusercontent.com/96157134/180112727-ac0b0e25-ebac-4edf-a2ab-e882b4dc8986.PNG)

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。
利用させていただきありがとうございます。

**Comment by KajitoriAdmin** [comment]
v5.0.5 で修正しました。

**Comment by KajitoriAdmin** [comment]
Release Miss です。
Reopen します。

**Comment by KajitoriAdmin** [comment]
v5.0.6 でリリースしました。
ご確認ください。

**Comment by 5050boon** [comment]
V5.0.6で修正済みの確認をさせて頂きました。
ご対応ありがとうございました。
