### ISSUE TITLE
[object Object]プラグイン編集画面でファイル等が選択・編集できない

### ISSUE THREAD

**Issue by tkpontas** [exceedone/exment#1199]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

プラグイン編集画面で、以前は直接編集できていたCSSファイル等を選択すると
[object Object]と表示され、編集等が行えない。ファイルのアップロードは可能。

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
プラグイン　→　任意のプラグインを選択　→　プラグイン編集　→　プラグイン編集画面にてファイルを選択

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
Ver.5.0.0

Coreserver プラン CORE-X
PHP8.0X系／Laravel 9.X系

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。
無し

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。
省略

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。
環境依存の可能性もありますが、念のため報告

**Comment by hirossyi-exc** [comment]
PHP8.0 / Laravel9に上がった影響はありそうですね。
