### ISSUE TITLE
複数選択を許可した選択肢の項目に空白があるとフィルタで抽出されない

### ISSUE THREAD

**Issue by masayuki00001** [exceedone/exment#1200]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
複数選択を許可した選択肢の項目に空白があるとフィルタで抽出されない。

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
複数選択を許可した選択肢のカスタム列を追加し、選択肢に空白を含む項目を作成、それを含むデータを保存し検索。

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
スクリーンショットは4.4.1ですが4.4.2でも発生します。

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。
![スクリーンショット 2022-07-26 094532](https://user-images.githubusercontent.com/81345279/180899337-9bbc03ca-95e0-4740-815f-655eb9b2aa11.png)
![スクリーンショット 2022-07-26 094550](https://user-images.githubusercontent.com/81345279/180899341-c7d51f23-f931-44f5-9410-d59e81ead0e2.png)
![スクリーンショット 2022-07-26 094609](https://user-images.githubusercontent.com/81345279/180899345-3f49a6c4-c0b7-4717-a156-407762ffb0f7.png)

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by kojikoji725** [comment]
当事象ですが、このような選択肢は設定そのものがNGとなります。
空白行となる選択肢は削除をお願いいたします。

**Comment by KajitoriAdmin** [comment]
Closeとします。
