### ISSUE TITLE
ログイン権限付与していないユーザーの更新履歴があるデータを更新出来ない

### ISSUE THREAD

**Issue by Nemzo** [exceedone/exment#1212]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
ログイン権限付与していないユーザーの更新履歴があるデータを更新出来ない

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
xxxxxxx@xxxxxxxは以前使用していたユーザーで、現在はログイン権限を付与しておらず
更新履歴にxxxxxxx@xxxxxxxが更新した履歴があるデータが更新出来ない

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
Version   v5.0.2

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。
Expected response code "250/251/252" but got code "550", with message "550 5.1.1 <xxxxxxx@xxxxxxx>... User unknown".

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by kojikoji725** [comment]
下記パターンで試してみましたが、権限のないユーザーのデータも編集できるようです。
ユーザーAが作成→ユーザーBが更新→ユーザーBのログイン権限を削除→ユーザーAが更新
ユーザーAが作成→ユーザーBが更新→ユーザーAのログイン権限を削除→ユーザーBが更新

他に権限設定していませんか？
Laravel.log を頂けると幸いです。ログの場所: "storage/logs/laravel.log"

**Comment by Nemzo** [comment]
ログになります。
よろしくお願いします。

#0 /var/www/exment/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(182): Symfony\Component\Mailer\Transport\Smtp\SmtpTransport->assertResponseCode()
#1 /var/www/exment/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(240): Symfony\Component\Mailer\Transport\Smtp\SmtpTransport->executeCommand()
#2 /var/www/exment/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(201): Symfony\Component\Mailer\Transport\Smtp\SmtpTransport->doRcptToCommand()
#3 /var/www/exment/vendor/symfony/mailer/Transport/AbstractTransport.php(68): Symfony\Component\Mailer\Transport\Smtp\SmtpTransport->doSend()
#4 /var/www/exment/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(136): Symfony\Component\Mailer\Transport\AbstractTransport->send()
#5 /var/www/exment/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(521): Symfony\Component\Mailer\Transport\Smtp\SmtpTransport->send()
#6 /var/www/exment/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(285): Illuminate\Mail\Mailer->sendSymfonyMessage()
#7 /var/www/exment/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(505): Illuminate\Mail\Mailer->send()
#8 /var/www/exment/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(337): Illuminate\Mail\MailManager->__call()
#9 /var/www/exment/vendor/exceedone/exment/src/Notifications/Mail/MailChannel.php(54): Illuminate\Support\Facades\Facade::__callStatic()
#10 /var/www/exment/vendor/exceedone/exment/src/Notifications/Mail/MailChannel.php(24): Exceedone\Exment\Notifications\Mail\MailChannel->sendMail()
#11 /var/www/exment/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(148): Exceedone\Exment\Notifications\Mail\MailChannel->send()
#12 /var/www/exment/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(106): Illuminate\Notifications\NotificationSender->sendToNotifiable()
#13 /var/www/exment/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(19): Illuminate\Notifications\NotificationSender->Illuminate\Notifications\{closure}()
#14 /var/www/exment/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(109): Illuminate\Notifications\NotificationSender->withLocale()
#15 /var/www/exment/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(54): Illuminate\Notifications\NotificationSender->sendNow()
#16 /var/www/exment/vendor/laravel/framework/src/Illuminate/Notifications/SendQueuedNotifications.php(104): Illuminate\Notifications\ChannelManager->sendNow()
#17 /var/www/exment/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Notifications\SendQueuedNotifications->handle()
#18 /var/www/exment/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#19 /var/www/exment/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#20 /var/www/exment/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#21 /var/www/exment/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Container\BoundMethod::call()
#22 /var/www/exment/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container->call()
#23 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#24 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#25 /var/www/exment/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then()
#26 /var/www/exment/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(123): Illuminate\Bus\Dispatcher->dispatchNow()
#27 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}()
#28 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#29 /var/www/exment/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(125): Illuminate\Pipeline\Pipeline->then()
#30 /var/www/exment/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(69): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()
#31 /var/www/exment/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call()
#32 /var/www/exment/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(43): Illuminate\Queue\Jobs\Job->fire()
#33 /var/www/exment/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(253): Illuminate\Queue\SyncQueue->push()
#34 /var/www/exment/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(229): Illuminate\Bus\Dispatcher->pushCommandToQueue()
#35 /var/www/exment/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(77): Illuminate\Bus\Dispatcher->dispatchToQueue()
#36 /var/www/exment/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(222): Illuminate\Bus\Dispatcher->dispatch()
#37 /var/www/exment/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(76): Illuminate\Notifications\NotificationSender->queueNotification()
#38 /var/www/exment/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(39): Illuminate\Notifications\NotificationSender->send()
#39 /var/www/exment/vendor/laravel/framework/src/Illuminate/Notifications/RoutesNotifications.php(18): Illuminate\Notifications\ChannelManager->send()
#40 /var/www/exment/vendor/exceedone/exment/src/Notifications/MailSender.php(231): Exceedone\Exment\Notifications\MailSender->notify()
#41 /var/www/exment/vendor/exceedone/exment/src/Notifications/MailSender.php(202): Exceedone\Exment\Notifications\MailSender->sendMail()
#42 /var/www/exment/vendor/exceedone/exment/src/Services/NotifyService.php(479): Exceedone\Exment\Notifications\MailSender->send()
#43 /var/www/exment/vendor/exceedone/exment/src/Services/NotifyService.php(407): Exceedone\Exment\Services\NotifyService::notifyMail()
#44 /var/www/exment/vendor/exceedone/exment/src/Model/Notify.php(345): Exceedone\Exment\Services\NotifyService::executeNotifyAction()
#45 /var/www/exment/vendor/exceedone/exment/src/Model/Notify.php(246): Exceedone\Exment\Model\Notify->notifyUser()
#46 /var/www/exment/vendor/exceedone/exment/src/Model/CustomValue.php(783): Exceedone\Exment\Model\Notify->notifyCreateUpdateUser()
#47 /var/www/exment/vendor/exceedone/exment/src/Model/CustomValue.php(554): Exceedone\Exment\Model\CustomValue->notify()
#48 /var/www/exment/vendor/exceedone/exment/src/Model/CustomValue.php(447): Exceedone\Exment\Model\CustomValue->savedEvent()
#49 /var/www/exment/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(421): Exceedone\Exment\Model\CustomValue::Exceedone\Exment\Model\{closure}()
#50 /var/www/exment/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}()
#51 /var/www/exment/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php(189): Illuminate\Events\Dispatcher->dispatch()
#52 /var/www/exment/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1108): Illuminate\Database\Eloquent\Model->fireModelEvent()
#53 /var/www/exment/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1019): Illuminate\Database\Eloquent\Model->performUpdate()
#54 /var/www/exment/vendor/exceedone/laravel-admin/src/Form.php(636): Illuminate\Database\Eloquent\Model->save()
#55 /var/www/exment/vendor/exceedone/exment/src/Database/ConnectionTrait.php(86): Encore\Admin\Form->Encore\Admin\{closure}()
#56 /var/www/exment/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(462): Exceedone\Exment\Database\MariaDBConnection->transaction()
#57 /var/www/exment/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(337): Illuminate\Database\DatabaseManager->__call()
#58 /var/www/exment/vendor/exceedone/laravel-admin/src/Form.php(648): Illuminate\Support\Facades\Facade::__callStatic()
#59 /var/www/exment/vendor/exceedone/exment/src/Controllers/HasResourceTableActions.php(22): Encore\Admin\Form->update()
#60 /var/www/exment/vendor/exceedone/exment/src/Controllers/CustomValueController.php(81): Exceedone\Exment\Controllers\CustomValueController->updateTrait()
#61 /var/www/exment/vendor/exceedone/exment/src/Controllers/AdminControllerTableBase.php(54): Exceedone\Exment\Controllers\CustomValueController->update()
#62 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Exceedone\Exment\Controllers\AdminControllerTableBase->callAction()
#63 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Route.php(261): Illuminate\Routing\ControllerDispatcher->dispatch()
#64 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\Routing\Route->runController()
#65 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\Routing\Route->run()
#66 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#67 /var/www/exment/vendor/exceedone/laravel-admin/src/Middleware/Session.php(18): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#68 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Encore\Admin\Middleware\Session->handle()
#69 /var/www/exment/vendor/exceedone/laravel-admin/src/Middleware/Permission.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#70 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Encore\Admin\Middleware\Permission->handle()
#71 /var/www/exment/vendor/exceedone/laravel-admin/src/Middleware/Bootstrap.php(15): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#72 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Encore\Admin\Middleware\Bootstrap->handle()
#73 /var/www/exment/vendor/exceedone/exment/src/Middleware/LogOperation.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#74 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\Exment\Middleware\LogOperation->handle()
#75 /var/www/exment/vendor/exceedone/laravel-admin/src/Middleware/Pjax.php(24): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#76 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Encore\Admin\Middleware\Pjax->handle()
#77 /var/www/exment/vendor/exceedone/exment/src/Middleware/Bootstrap.php(22): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#78 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\Exment\Middleware\Bootstrap->handle()
#79 /var/www/exment/vendor/exceedone/exment/src/Middleware/Morph.php(20): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#80 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\Exment\Middleware\Morph->handle()
#81 /var/www/exment/vendor/exceedone/exment/src/Middleware/AuthenticatePasswordLimit.php(24): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#82 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\Exment\Middleware\AuthenticatePasswordLimit->handle()
#83 /var/www/exment/vendor/exceedone/exment/src/Middleware/Authenticate2factor.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#84 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\Exment\Middleware\Authenticate2factor->handle()
#85 /var/www/exment/vendor/exceedone/exment/src/Middleware/Authenticate.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#86 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\Exment\Middleware\Authenticate->handle()
#87 /var/www/exment/vendor/exceedone/exment/src/Middleware/Initialize.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#88 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\Exment\Middleware\Initialize->handle()
#89 /var/www/exment/vendor/exceedone/exment/src/Middleware/IpFilterBase.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#90 /var/www/exment/vendor/exceedone/exment/src/Middleware/WebIPFilter.php(15): Exceedone\Exment\Middleware\IpFilterBase->handleBase()
#91 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\Exment\Middleware\WebIPFilter->handle()
#92 /var/www/exment/vendor/exceedone/exment/src/Middleware/Browser.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#93 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\Exment\Middleware\Browser->handle()
#94 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#95 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#96 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#97 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#98 /var/www/exment/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#99 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#100 /var/www/exment/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#101 /var/www/exment/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#102 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Session\Middleware\StartSession->handle()
#103 /var/www/exment/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#104 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#105 /var/www/exment/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#106 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#107 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#108 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline->then()
#109 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\Routing\Router->runRouteWithinStack()
#110 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\Routing\Router->runRoute()
#111 /var/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\Routing\Router->dispatchToRoute()
#112 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\Routing\Router->dispatch()
#113 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#114 /var/www/exment/vendor/exceedone/exment/src/Middleware/ExmentDebug.php(15): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#115 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\Exment\Middleware\ExmentDebug->handle()
#116 /var/www/exment/vendor/exceedone/exment/src/Middleware/TrustProxies.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#117 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Exceedone\Exment\Middleware\TrustProxies->handle()
#118 /var/www/exment/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#119 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\TrustProxies->handle()
#120 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#121 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#122 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#123 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#124 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#125 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
#126 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#127 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
#128 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#129 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#130 /var/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#131 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\Pipeline\Pipeline->then()
#132 /var/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#133 /var/www/exment/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle()
#134 {main}

**Comment by Nemzo** [comment]
権限関係は設定しておらず
v4系では更新可能でしたが、v5系にアップデートしてからの現象になります。

**Comment by kojikoji725** [comment]
v5系ですね、情報、ログありがとうございます。
確認させていただきます。
