### ISSUE TITLE
テキスト検索ボックスのリセット

### ISSUE THREAD

**Issue by a0z0** [exceedone/exment#1217]
### Describe the feature you'd like / 希望する機能の説明を行ってください
A clear and concise description of what you want to happen. / あなたが何をしたいのかについての、明確で簡潔な説明を行ってください。
困っているわけではないですが...テキスト検索ボックスをリセットできると便利です。

### Additional context / その他
Add any other context or screenshots about the feature request here. / 機能リクエストに関する他のコンテキストまたはスクリーンショットをここに追加します。
![image](https://user-images.githubusercontent.com/24448524/184315457-4dd6c314-f399-4aaf-a027-c90e7d198124.png)

**Comment by fleming35800** [comment]
開発者ではありませんが・・・
私が運用している環境では連続で検索しないといけないことがあったため、検索→ページのリロード時に該当フィールドにフォーカス＆全選択するようにプラグインで実装しました。
参考になるかわかりませんが、記載内容のカバーできるのではと思い投稿させていただきました。
  ```
  $(window).off('exment:list_loaded', setEventForcus).on('exment:list_loaded', setEventForcus);
    $(window).off('exment:list_loaded', setEventSelect).on('exment:list_loaded', setEventSelect);
    function setEventForcus(ev){
        $('.form-control').focus();
    };
    function setEventSelect(ev){
        $('.form-control').select();
    };
```

**Comment by a0z0** [comment]
fleming35800さま
いただきました助言で実用十分なプラグイン作成できました。ありがとうございます。
```
$(function () {
	$(window).off('exment:list_loaded', setEvent).on('exment:list_loaded', setEvent);
	// 検索テキストボックスのフォーカス時にテキストを全選択
	function setEvent(ev){
		$("input[name='query']").off('focus', setEventFocus).on('focus', setEventFocus);
	};
	function setEventFocus(ev){
		$(this).select();
	};
});
```
