### ISSUE TITLE
マニュアルのAPI設定のページ間違えてませんでしょうか

### ISSUE THREAD

**Issue by a0z0** [exceedone/exment#1218]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

↓こちらの「独自で開発するプログラム側の実装」の章において、トークン取得要求のパラメーターをjson形式で渡すように表記していますが、パラメーター渡しではないでしょうか?
https://exment.net/docs/#/ja/api?id=%e7%8b%ac%e8%87%aa%e3%81%a7%e9%96%8b%e7%99%ba%e3%81%99%e3%82%8b%e3%83%97%e3%83%ad%e3%82%b0%e3%83%a9%e3%83%a0%e5%81%b4%e3%81%ae%e5%ae%9f%e8%a3%85-1

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by hirossyi-exc** [comment]
確認しました、誤りではありませんのでクローズします。
