### ISSUE TITLE
集計ビューでグループ列やデータ表示条件を設定するとビュー表示時に操作カラムが表示されなくなる

### ISSUE THREAD

**Issue by fleming35800** [exceedone/exment#1223]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
以下条件をどちらか満たすとき
カスタムテーブル集計ビューの設定において
・集計ビューを設定時にグループ列の対象列を2つ以上
・データ表示条件を1つ以上
設定した時に操作かカラムが表示されなくなりデータ詳細を確認できなくなってしまいます。
![image](https://user-images.githubusercontent.com/75713203/186824584-cfc4b6b0-9e8a-4bc1-b210-7b24bde40d32.png)
↓
![image](https://user-images.githubusercontent.com/75713203/186824728-17989e0e-0a92-4c6f-a881-d140576dd9f0.png)

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
v4.4.0
PHP 7.4.13
Composer version 2.1.9 2021-10-05 09:47:38

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。
特にエラーは出ていないみたいです。

**Comment by hirossyi73** [comment]
集計ビューで、グループ列や集計列で他のテーブルを使用すると、操作カラム表示しなくなる仕様となります。

**Comment by fleming35800** [comment]
確認頂きましてありがとうございます。
仰る通り別テーブルの値を表示するようにしていました。
データ連動などで別テーブルの値を連動させて改めて設定した所操作カラム表示するようになりました。
いつもありがとうございます。
