### ISSUE TITLE
カスタムテーブルの複写について

### ISSUE THREAD

**Issue by panda1118** [exceedone/exment#1226]
お世話になっております。

題名の件ですが、私の知識不足かもしれませんが、カスタムテーブルの複写
の方法がございましたらご教授願います。年度の毎に同じカスタム列の列名
を入力しております。カスタム列を毎回手で入力して設定しております。
すみませんが、宜しくお願い致します。

**Comment by a-nagai-dkg** [comment]
こちらはやはり結論として「不可能」という理解で良いのでしょうか。
私もできると非常に助かりますが・・・

**Comment by koizu-mkII** [comment]
@panda1118 
@a-nagai-dkg 
リリース日はお約束できませんが、次回のバージョンアップでリリース予定です。
今しばらくお待ちくださいませ。

**Comment by KajitoriAdmin** [comment]
v5.0.8 でリリース予定です。
8月を予定しております。

**Comment by panda1118** [comment]
v5.0.8 でリリースでリリースされておりましたでしょうか。
すみませが宜しくお願いいたします。

**Comment by a-nagai-dkg** [comment]
更新履歴を見る限り、v5.0.10の機能追加にそれっぽい「データ複製機能」とありますが、
バージョンアップしても見当たらないですね。データコピー機能は今までと変わらないようですし・・・

**Comment by KajitoriAdmin** [comment]
実装漏れのようです。
v5.0.11 以降でリリースいたします。

**Comment by a-nagai-dkg** [comment]
v5.0.11のリリース時期はおおよそいつ頃を予定されていますでしょうか。
急かせて申し訳ありませんが、大量のテーブル複製作業をやってしまうかリリースまで待つか迷っております。。

**Comment by KajitoriAdmin** [comment]
v5.0.11 でリリースしました。

**Comment by a-nagai-dkg** [comment]
ご対応ありがとうございました！
複製の対象は「通常設定、拡張設定、カスタム列」なのですね。
それでもずいぶん作業が楽になると思います。

今後、ビューやフォームなどその他の設定の複製にも期待しております。。

**Comment by KajitoriAdmin** [comment]
Close とさせていただきます。
