### ISSUE TITLE
公開ビュー機能

### ISSUE THREAD

**Issue by izumi-nkc** [exceedone/exment#1232]
### Describe the feature you'd like / 希望する機能の説明を行ってください
A clear and concise description of what you want to happen. / あなたが何をしたいのかについての、明確で簡潔な説明を行ってください。
特定のビューを一般ユーザー（ログインしていないユーザー）に公開する機能を要望します。
標準のビュー機能のフィルタ、ソート、ページングのみを許可するイメージです。

### Additional context / その他
Add any other context or screenshots about the feature request here. / 機能リクエストに関する他のコンテキストまたはスクリーンショットをここに追加します。

**Comment by a0z0** [comment]
こんにちは。一般利用者です。
私も同様の機能が欲しいと思いましが、私の場合は公式情報に準じて一覧だけ表示するページを作りました。
https://exment.net/docs/#/ja/public_site?id=%e3%83%9a%e3%83%bc%e3%82%b8%e4%bd%9c%e6%88%90

別の案としては、閲覧権限のみ持たせたguest用アカウントを作成して、
自動ログインするページを作るといけるかなと思いました。(妄想のみ)
