### ISSUE TITLE
リストアが500 SERVER ERRORで失敗する

### ISSUE THREAD

**Issue by theend12345678** [exceedone/exment#1234]
### Describe the bug / バグの説明
リストアが500 SERVER ERRORで失敗する

### To Reproduce / 再現手順

レンタルサーバ（Coreserver)にExment v5.0.2をクリーンインストールし、v4.4.2で取ったバックアップをリストアしようとすると500 SERVER ERRORで失敗する。

念のためクリーンインストールしたv5.0.2でつくったテストデータをバックアップしリストアしたが、これも500 SERVER ERRORで失敗。

どちらでもエラーログの内容は同じため、バージョンをまたいだリストアだから発生したものではないと思われる。

### Version / 発生バージョン
バックアップ元：v4.4.2
リストア先：v5.0.2
※バックアップ元とリストア先がv5.0.2でも同様のエラーが発生する

### Error log / エラーログ
[laravel.log](https://github.com/exceedone/exment/files/9593224/laravel.log)

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

### Additional context / その他  

今回のエラーとの関係性は不明だが
最新版をあてているつもりだがv5.0.3ではなくv5.0.2と表示されている。
またバックアップ元もv.4.4.3をあてているつもりだがv4.4.2と表示されている。

**Comment by fleming35800** [comment]
少し時間たってしまってますが失礼します。
（すでに解決していたら無視していただいて結構です。）

開発者ではありませんが、先日4.4.0→5.0.3へクリーンインストール後バージョンアップ行いました。
Xserverにて環境構築、運用していますが、リストア問題なく実行できました。

composerのバージョン、phpのバージョン等も情報として提示した方がよいと思います。
私は以下の環境で4.4.0→5.0.3へアップデートしています。
Composer version 2.1.9 
PHP 8.0.16 

私も5.0.3のつもりでクリーンインストールしましたが5.0.2でした。
php artisan exment:update実行した所、5.0.3になりました。

**Comment by tkpontas** [comment]
既に解決済みでしたら無視してください。

laravel.logで発生しているエラーからすると、契約しているコアサーバーのMariaDB(MySQL)に設定が必要なようです。
環境依存のエラーと思われます。

参考サイト
https://yoku0825.blogspot.com/2018/07/mysql-80load-data-local-infile-error.html

**Comment by theend12345678** [comment]
> 少し時間たってしまってますが失礼します。 （すでに解決していたら無視していただいて結構です。）
> 
> 開発者ではありませんが、先日4.4.0→5.0.3へクリーンインストール後バージョンアップ行いました。 Xserverにて環境構築、運用していますが、リストア問題なく実行できました。
> 
> composerのバージョン、phpのバージョン等も情報として提示した方がよいと思います。 私は以下の環境で4.4.0→5.0.3へアップデートしています。 Composer version 2.1.9 PHP 8.0.16
> 
> 私も5.0.3のつもりでクリーンインストールしましたが5.0.2でした。 php artisan exment:update実行した所、5.0.3になりました。

////////////////////////////////

@fleming35800 

ありがとうございます。

お返事遅くなり、申し訳ありません。

その後、5.0.2→5.0.3のバージョンアップはCoreServerのコントロールパネルからPHPの設定を変更したうえで、php artisan exment:updateを実行したところ無事にできました。

![image](https://user-images.githubusercontent.com/113819380/198938137-e74a8346-a10c-496a-b239-77200dec4324.png)

バックアップのリストアは相変わらずですが、コマンドによるリストアだとエラーは出ますが、復元はできるようなのでそれでよしとしています。

https://exment.net/docs/#/ja/backup?id=restore_command

**Comment by theend12345678** [comment]
> 既に解決済みでしたら無視してください。
> 
> laravel.logで発生しているエラーからすると、契約しているコアサーバーのMariaDB(MySQL)に設定が必要なようです。 環境依存のエラーと思われます。
> 
> 参考サイト https://yoku0825.blogspot.com/2018/07/mysql-80load-data-local-infile-error.html

/////////////////////////

@tkpontas 

ありがとうございます。

見た限り、--local-infileのオプション値は1のようでした。

ただ、CoreServerでは変更できない部分のようですので、ここら辺があきらめ時かな、と思います。

前述の通り、エラーは出ますが、コマンドであればリストアはできるので、付き合っていこうかと思います。

いったんクローズといたします。
