### ISSUE TITLE
テーブルの列種類   YES/NO指定でチェックボックス形式で表示 YESにしたときNOに変更できない

### ISSUE THREAD

**Issue by issg-matsuo** [exceedone/exment#1238]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
　　
テーブルの列種類で列を　列種類   YES/NO　の値をYESに編集された状態からNOに変更できなくなる

### To Reproduce / 再現手順

テーブルの列種類で列を
　列種類   YES/NO
　必須　YES
　検索インデックス YES
    初期値 YES
   チェックボックス形式で表示  YES
定義する

1. データ作成を行った後 列の値を YES -> NO に変更すると画面操作はできるが保存されていない

2. チェックボックス形式で表示  NOすると保存はできるようになる。

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。

Version   v5.0.3
### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

変更前
![image](https://user-images.githubusercontent.com/109338757/192408544-bb380656-6bf1-43f7-94b6-283ebd240beb.png)

画面で当該列の値を変更
![image](https://user-images.githubusercontent.com/109338757/192408609-fc64a0be-6289-460c-8ec1-03c1362dcf79.png)

![image](https://user-images.githubusercontent.com/109338757/192408635-a006d7b7-49fe-4807-8f46-6546873fdb1f.png)

値をみると変更まえのまま
![image](https://user-images.githubusercontent.com/109338757/192408668-87ea4f76-f2e9-4b17-8a3d-f00b18b5635a.png)

チェックボックス形式で表示  YES　⇒ NOに変更すると保存ができるようなる。

![image](https://user-images.githubusercontent.com/109338757/192408723-7ed15b80-63c2-4fd6-b975-ab55e65b7415.png)

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by KajitoriAdmin** [comment]
Released in v5.0.7.

**Comment by KajitoriAdmin** [comment]
Close とさせていただきます。
