### ISSUE TITLE
exmentのインストール(RedHat)へのhttpサーバの導入時の設定関して

### ISSUE THREAD

**Issue by issg-matsuo** [exceedone/exment#1239]
### Describe the feature you'd like / 希望する機能の説明を行ってください
A clear and concise description of what you want to happen. / あなたが何をしたいのかについての、明確で簡潔な説明を行ってください。

exmentのインストール(RedHat)へのhttpサーバの導入時の設定関してhttpd.confに記載内容に
WEBサーバの構成設定がありますが、
インポート等処理時間がかかる場合内部エラーが発生する可能性があるので
設定しない場合エラーが発生時画面上では、エラーが発生時内部処理エラーの表示が一瞬エラーが表示される
PHPの処理は内部で動作しているようでデータ登録がバックグラウンドで処理が継続されている

### Additional context / その他
Add any other context or screenshots about the feature request here. / 機能リクエストに関する他のコンテキストまたはスクリーンショットをここに追加します。

php.iniの処理時間の設定と同様にWEBサーバのタイムアウト時間についての設定が必要になる。
apache 2.4の場合既定のタイムアウト時が非常に短い、php.iniのmax_execution_timeの値に
応じてhttpd.confの値も修正が必要ので注釈でもよいので記載するか、php.iniの動作に
期待する設定例としてもうとありがたい。

https://httpd.apache.org/docs/2.4/mod/mod_reqtimeout.html
規定値: RequestReadTimeout handshake=0 header=20-40,MinRate=500 body=20,MinRate=500

https://httpd.apache.org/docs/2.4/ja/mod/mod_proxy.html
規定値: ProxyTimeout 300

https://httpd.apache.org/docs/2.4/ja/mod/core.html
規定値: TimeOut 60

**Comment by a0z0** [comment]
こんにちは。一利用者です。
時間のかかるPlugin実行でTimeoutになるのに悩んでおりました。
とても参考になりました。ありがとうこざいました。
