### ISSUE TITLE
入力フォームへの画像表示（データ連動設定がない）について別の方法がありましたら教えてください

### ISSUE THREAD

**Issue by 5050boon** [exceedone/exment#1241]
入力フォームへ、親テーブル内の設備情報と管理ポイント図を表示し、子テーブルへ入力の場所指定を行いたいのですが、フォーム項目 候補一覧　＞＞　その他　＞＞　画像　には、データ連動設定がありません。
何か別の方法がありましたら、情報を頂けないでしょうか？

**Comment by tkpontas** [comment]
フォーム項目その他にある拡張HTMLを使い、パラメーター変数を利用して、画像のカスタム列であればファイルのURLを表示するはずなので、親テーブルの設備情報と管理ポイント図のカスタム列をimgタグでフォーム内に読み込ませるのはどうでしょうか？

**Comment by tkpontas** [comment]
![001](https://user-images.githubusercontent.com/60683813/195769686-5d0262d0-0c2d-4965-960e-abfa85968473.png)
![002](https://user-images.githubusercontent.com/60683813/195769691-76282001-d090-4b96-ac0b-a631c0a082c7.png)

テストイメージです。この方法だと、子テーブル新規入力時には画像が表示されないのでご要望にはお応えできないかもしれません。プラグイン等の開発を検討された方がよいかもしれません。

**Comment by tkpontas** [comment]
プラグイン等できちんと実装した方がよいのかもしれませんが、フォームの拡張HTMLとパラメーター変数を利用する方法であれば、編集画面・詳細画面は表示できると思います。${parent}、${select_table}のどちらも新規画面では表示されないので一度新規作成後、編集を継続するという形であればなんとかなるかもしれません。

親テーブル
![0999](https://user-images.githubusercontent.com/60683813/195773157-c83d2055-4545-4f16-af3b-1e671e369bc7.png)

子テーブル
![1000](https://user-images.githubusercontent.com/60683813/195773207-b7b40a3a-a289-42e7-86d1-0f1f868901e8.png)

![1001](https://user-images.githubusercontent.com/60683813/195773216-f339ff1a-a032-4a15-8a53-76ec56330ecb.png)

![1002](https://user-images.githubusercontent.com/60683813/195773223-7131e3c4-d664-4a4b-b7dc-0c76cef968f5.png)

画面イメージ
![1003](https://user-images.githubusercontent.com/60683813/195773229-3db9ef96-cc37-478b-a2d1-276a2f4b4b04.png)

**Comment by 5050boon** [comment]
ご教授頂きありがとうございます。

新規入力時に、入力項目の案内図を親テーブルの登録画像から各種表示したいので、この方法でも厳しいです。
