### ISSUE TITLE
担当データ編集権限での新規レコード作成の際に自動採番がされない

### ISSUE THREAD

**Issue by shksk** [exceedone/exment#1243]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
担当データ編集権限を付与したアカウントで新規レコード作成の際に、自動採番列において採番がされない。
全データ編集権限を付与すると正しく採番される。

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
1.テーブル（例：テストテーブル）を作成
2.カスタム列で列種類を自動採番として列を新規作成、採番ルールは${id:6}
3.任意グループ（例：user_group）の役割グループの権限設定で、テストテーブルの担当データの編集と担当データの閲覧のみを有効とする。
4.user_groupに任意ユーザー（test_user）を追加
5.test_userでテストテーブルのレコードを新規作成

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
v5.0.3

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by tkpontas** [comment]
開発者ではありませんが、念のため確認させてください。
自動採番となっているカスタム列は担当データ編集権限の方が利用する入力フォームに配置されていますか？

私も以前、自動採番されないことがあり、自動採番のカスタム列を隠しフィールドでフォーム上に設置したところ改善された記憶がありましたので･･･
もし配置済みでのバグ修正要望であれば、このコメントは無視してください。

**Comment by shksk** [comment]
レコードの新規作成時には自動採番は失敗するものの、当該レコードを編集し、再保存すると番号が採番されることを確認しました。しかし、”ID-${id:6}"のような採番フォーマットだと、初回保存時に"ID-"と登録されてしまい、その後編集・保存しても採番されることはありませんでした。

**Comment by KajitoriAdmin** [comment]
Released in v5.0.7.

**Comment by KajitoriAdmin** [comment]
Close とさせていただきます。
