### ISSUE TITLE
5.0.4にアップデートするとエラーが出て役割グループの編集ができなくなる。

### ISSUE THREAD

**Issue by theend12345678** [exceedone/exment#1251]
### Describe the bug / バグの説明
5.0.3から5.0.4にアップデート後、役割グループの編集してから保存時に「SQLSTATE[42S22]: Column not found: 1054 Unknown column～」というエラーが出て設定を変更できない。

### To Reproduce / 再現手順
バージョン5.0.4に手動アップデート時（https://exment.net/docs/#/ja/update）

### Version / 発生バージョン
5.0.4
※利用サーバはCoreServerでPHPのバージョンは8.0です。

### Error log / エラーログ
[2022-12-09 19:24:57] local.ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'role_group_order' in 'field list' (SQL: update `role_groups` set `updated_user_id` = 2, `role_group_order` = 0, `role_groups`.`updated_at` = 2022-12-09 19:24:57 where `id` = 4) {"userId":2,"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'role_group_order' in 'field list' (SQL: update `role_groups` set `updated_user_id` = 2, `role_group_order` = 0, `role_groups`.`updated_at` = 2022-12-09 19:24:57 where `id` = 4) at /home/〇〇/laravel_test/exment/vendor/laravel/framework/src/Illuminate/Database/Connection.php:760)
[stacktrace]
#0 /home/〇〇/laravel_test/exment/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\\Database\\Connection->runQueryCallback()
#1 /home/〇〇/laravel_test/exment/vendor/laravel/framework/src/Illuminate/Database/Connection.php(577): Illuminate\\Database\\Connection->run()
（以下略）

### Screenshots / スクリーンショット
![image](https://user-images.githubusercontent.com/113819380/206664726-c6dfca5d-5db2-4649-8c5a-e4edcce8f2a1.png)

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by a0z0** [comment]
当方、アップデートバッチで v5.0.3 -> v5.0.4 へUpdateしましたが問題ありませんでした。
OS: Rocky Linux 8.6

ダウングレードの方法はこちらに記載ありましたので、ためしにやってみても期待通りの動作でした。
https://exment.net/docs/#/ja/update_tmp

ダウングレード
>composer require exceedone/exment=v5.0.3
>php artisan exment:update

最新アップデート
>composer require exceedone/exment
>php artisan exment:update

エラーメッセージからすると、ワークフローてーふせるの列が既にあるのに追加しようとしているように思える。
テーブル構造のバージョンとupdateのバージョンチェックが一致していないのでは?

以上

**Comment by ShinjiOogamiKawano** [comment]
私もアップデートに失敗して同様のエラーメッセージ（role_groupsの方のエラー）が出ましたが、正常にアップデートすれば権限テーブルのエラーは解決すると思います。

v5.0.3へのアップデートには
「2022_10_07_000000_role_groups_patch_221007」
というテーブル構造の修正があり
role_groupsテーブルにrole_group_order列が追加されているようです。

したがって、正常にアップデートが行えていない結果として

> exmentは使えるが役割グループの編集後、保存時に「SQLSTATE[42S22]: Column not found: 1054 Unknown column～」というエラーが出て設定を変更できない。

ということは間違いないと思いました。

直接の解決案でなく申し訳ないですが、原因はやはり[a0z0](https://github.com/a0z0)さんが指摘されているように、ワークフロー関係のテーブル構造のアップデートに失敗していることにあると思います。
どのバージョンからのアップデートであるのかご確認されたほうがいいように思いました。

**Comment by theend12345678** [comment]
> 当方、アップデートバッチで v5.0.3 -> v5.0.4 へUpdateしましたが問題ありませんでした。 OS: Rocky Linux 8.6
> 
> ダウングレードの方法はこちらに記載ありましたので、ためしにやってみても期待通りの動作でした。 https://exment.net/docs/#/ja/update_tmp
> 
> ダウングレード
> 
> > composer require exceedone/exment=v5.0.3
> > php artisan exment:update
> 
> 最新アップデート
> 
> > composer require exceedone/exment
> > php artisan exment:update
> 
> エラーメッセージからすると、ワークフローテーブルの列が既にあるのに追加しようとしているように思える。 テーブル構造のバージョンとupdateのバージョンチェックが一致していないのでは?
> 
> 以上

ありがとうございます。
根本解決にはなっていませんが、5.0.3にダウングレードすることで役割グループの編集はできるようになりました。
5.0.0にダウングレードした際もワークフローテーブルのエラーは出たので、それより前のバージョンのエラーなのか、と思いつつ4系だとPHPのバージョンを落とさなければ検証できないので、少し考えようと思います。

**Comment by theend12345678** [comment]
関連があるかと思い、アップデート時に出るシンタックスエラーも同時に記載していましたが、別問題のようですので該当の記述を切り出し、別のバグ報告にしました。

https://github.com/exceedone/exment/issues/1256

当件はテーブルに列を追加することで解決できる、という結論が出ましたのでクローズといたします。

**Comment by theend12345678** [comment]
関連があるかと思い、アップデート時に出るシンタックスエラーも同時に記載していましたが、別問題のようですので該当の記述を切り出し、別のバグ報告にしました。

https://github.com/exceedone/exment/issues/1256

当件はテーブルに列を追加することで解決できる、という結論が出ましたのでクローズといたします。
