### ISSUE TITLE
リレーションされたテーブルの値一覧表示画面（サーチ画面）でソートができない

### ISSUE THREAD

**Issue by shksk** [exceedone/exment#1253]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
リレーション設定されたカスタム列（「関連テーブル」と「選択肢 (他のテーブルの値一覧から選択)」いずれも）において、値入力時のサーチボタンからのサーチ画面で列のソートが動作しない。

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
参照元テーブル、参照先テーブルを2つ作成（設定は初期設定）
参照先テーブルは、テキスト列（インデックスを有効）を作成し、データを数個登録。ビューに、当該フィールドを追加。
参照元テーブルで、「選択肢 (他のテーブルの値一覧から選択)」のカスタム列を作成し、参照先テーブルを指定。
参照元テーブルで新規データ作成を行い、上記フィールドのサーチ画面を開き、ソートを行う。

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
v5.0.3

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。
![image](https://user-images.githubusercontent.com/49297720/207222294-93480608-ba75-4ba5-8d20-3b26b8064f3e.png)

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。
・関連テーブルでリレーションを設定した場合においても、同様の症状が発生します。
・データ並べ替え設定をした条件ビューを、対象カスタム列に登録するとソートが動作するようになりますが、上記の関連テーブルでの設定の場合、条件ビューを設定できないため、回避ができません。
・参照元テーブルの構成や設定によっては、正常にソートされる場合もあるようですが、その条件は不明です。
・デモサイトでも再現しましたのでURLを共有します。
https://demo-jp.exment.net/admin/data/sort_test1/
https://demo-jp.exment.net/admin/data/sort_test2/

**Comment by a0z0** [comment]
こんにちは。一般利用者です。
私も同様の事象で困っていますがいろいろ試してみると
選択したいテーブルに条件ビューを作って、カスタム列の絞り込み条件ビューを指定するとソートができるようになりました。
無指定の場合もデフォルトビューで動作してほしいですね。

**Comment by 5050boon** [comment]
V5.0.6を使用させて頂いております。
選択肢（他テーブルの値参照）ぐらいしか使っていないテーブル一覧でも、片側しかソートが効きません。

最初の一覧表示

![1](https://user-images.githubusercontent.com/96157134/225539902-d5433368-e614-4f4e-94ae-09177edba43f.PNG)

ソート　大　⇒　小

![2](https://user-images.githubusercontent.com/96157134/225539908-c798bb8c-7f40-4eae-bdc7-ce0b099c22a6.PNG)

ソート　小　⇒　大

![3](https://user-images.githubusercontent.com/96157134/225539915-babebb3d-792b-4448-9f8e-de991937ae1c.PNG)

小⇒大しか効かない
なぜ？
別件で立てた方がよろしいでしょうか？
