### ISSUE TITLE
計算時の切り捨てについて

### ISSUE THREAD

**Issue by panda1118** [exceedone/exment#1260]
題名の件ですが、計算式の機能で小数点第1位の四捨五入や切り捨ての
構文などがございましたらご教授願います。
また、機能追加をお願いいたします。
すみませがよろしくお願いいたします。

**Comment by KajitoriAdmin** [comment]
Released in v5.0.7.

**Comment by KajitoriAdmin** [comment]
Close とさせていただきます。
