### ISSUE TITLE
テキストエリア、ファイルパス「\\nnn\aaa」の「\n」が <br> に変換されてしまう。

### ISSUE THREAD

**Issue by lip-d** [exceedone/exment#1266]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
テキストエリアや内蔵エディタで発生する現象です。
Windowsで主に使われるパス表記「\\\\nnn\aaa\bbb」を投稿すると、
「\\
nn\aaa\bbb」
のように、ブラウザで表示されます。
（ソースコードを見ると、brタグに変換されています）

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
「バグの説明」どおりです。

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
Exment 5.0.2

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。
![image](https://user-images.githubusercontent.com/28218441/215627769-86c859b2-90d6-4f06-bade-210fe9904c92.png)

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。
このあたりが影響してそうですが、修正した場合の影響範囲が不明です・・・。
https://github.com/exceedone/exment/blob/6a4f4b9461480ac936d440cf401bf9ce8e8344df/src/Services/Helpers.php#L1231

将来のアップデートで修正は可能でしょうか。
何卒よろしくお願い申し上げます。

**Comment by KajitoriAdmin** [comment]
こちらは、仕様になります。
修正予定は、現在ありません。
よろしくお願いいたします。

**Comment by KajitoriAdmin** [comment]
Closeとさせていただきます。
