### ISSUE TITLE
複合ユニークキー設定

### ISSUE THREAD

**Issue by hayashi-m-shinozaki** [exceedone/exment#1272]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

テーブル設定　→　拡張設定　→　複合ユニークキー設定
キーが1から3の時もしくはキーが3の倍数の時は問題ないが、4つでキー設定をしたい場合や5つでキー設定したい場合にエラーになる
### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
Exment　→　v5.0.4

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by koizu-mkII** [comment]
@hayashi-m-shinozaki 
まず前提として、複合ユニークキーのカスタム列の組み合わせは、「最大３つ」となっております。
複合ユニークキー設定で、下図のように登録した場合

![image](https://user-images.githubusercontent.com/124752717/225483614-59501600-9c63-4e32-afc7-4854b9c9842d.png)

```
複合ユニークキー : 列A、列B、列C、列D、列E
```

ではなく

```
複合ユニークキー(1) : 列A、列B、列C
複合ユニークキー(2) : 列D、列E
```

となり、(1)と(2)で別々に複合ユニークキーの重複がチェックされます。

> キーが1から3の時もしくはキーが3の倍数の時は問題ないが、4つでキー設定をしたい場合や5つでキー設定したい場合にエラーになる

これは、設定時の話でしょうか？それともデータ登録時の重複チェックでの話でしょうか？

具体的な設定例や、設定したカスタム列の列種類などの情報を教えていただけますでしょうか？

**Comment by hayashi-m-shinozaki** [comment]
長い時間質問にお答えしないで申し訳ございませんでした。

複合ユニークキーの前提条件を理解していませんでした。
例題で上げて頂いた列A、列B、列C、列D、列Eで複合ユニークキー設定できると思っていました。
誠に申し訳ございませんでした。

また、「キーが1から3の時もしくはキーが3の倍数の時は問題ないが、4つでキー設定をしたい場合や5つでキー設定したい場合にエラーになる」は設定時の時に起きました。
この現象が起きた時のexmentのバージョンはV5.0.4です。
下記がその時の画面です。宜しくお願い致します。
![image](https://user-images.githubusercontent.com/100833631/235393963-dc17e522-3ad2-478a-9215-ec1823a6ffb0.png)
![image](https://user-images.githubusercontent.com/100833631/235393982-29ad8c74-bad6-4360-84d1-d01c581da26c.png)

**Comment by koizu-mkII** [comment]
@hayashi-m-shinozaki 
複合ユニークの仕様をご理解いただき、ありがとうございます。

また、上記エラーの問題も仕様となります。
「複合」ですので、１つの設定に２つ以上のカスタム列の指定を必須としております。
ですので、「列１」と「列２」に必須の＊（アスタリスク）を表示しております。

したがって、２行目の設定は、「列１」しか指定していないので、「列２」も指定してください。というエラーになります。

ご理解いただけましたでしょうか？

**Comment by hayashi-m-shinozaki** [comment]
複合キーの仕様理解出来ました。

理解不足で申し訳御座いませんでした。

今後とも宜しくご教授の程宜しくお願い致します。
