### ISSUE TITLE
カスタムデータリフレッシュコマンド　期間指定オプション追加

### ISSUE THREAD

**Issue by fleming35800** [exceedone/exment#1291]
### Describe the feature you'd like / 希望する機能の説明を行ってください
A clear and concise description of what you want to happen. / あなたが何をしたいのかについての、明確で簡潔な説明を行ってください。
現状以下のコマンドが存在しています。
オプションとしてデータの作成日時基準で期間指定したデータを削除できるような機能が欲しいです。
php artisan exment:refreshdata
php artisan exment:refreshtable (テーブル名)

Exmentシステムを2年ほど運用させていただいていますが、全体のデータがかなり増えてきており、動作も重くなってきています。過去のデータを期間指定で削除できればと感じています。

**Comment by koizu-mkII** [comment]
@fleming35800 
2年もご利用ということなので、チューニングはなさっているとは思いますが、以下の内容を見直すと速度の改善が見込めます。
- (カスタム列) 検索インデックス
- (カスタム列) フリーワード検索対象 -> むやみにたくさんのカスタム列に設定すると遅くなる原因となります。
- (カスタム列) 列種類＝選択肢(他のテーブルの値一覧から選択) -> カスタム列としての登録が多いと遅くなる原因となります。
- リレーション -> 登録が多いと遅くなる原因となります。

また、`.env`ファイルに` EXMENT_DEBUG_MODE_SQL=true`を追加し、ログにSQLの実行時間を出力して、遅い原因を特定することもお勧めいたします。

**Comment by fleming35800** [comment]
ご返信遅くなってしまい申し訳ありません。
アドバイス頂きましてありがとうございます。
頂いた内容参考ですが、チューニングできている項目もあればそうでないものもありますので、内容参考にさせて頂きまして、設定見直しをさせて頂きます。

**Comment by fleming35800** [comment]
自己解決した為closeさせて頂きます。
