### ISSUE TITLE
タブレット（surface）のタップで、ラジオボタン、チェックボックスの選択ができない。

### ISSUE THREAD

**Issue by shitakiy** [exceedone/exment#1292]
### Describe the bug / バグの説明
タブレット（surface）のタッチパネルからチェックボックス、ラジオボタンの選択ができない。

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by shitakiy** [comment]
今日テストしたら入力できました。
環境の問題だったかもしれません。

**Comment by koizu-mkII** [comment]
@shitakiy 
解決済みであればCloseをお願いいたします。

**Comment by shitakiy** [comment]
再現なしとの回答でしたが、当方でもマウス操作での動作確認はできています。
画面のタップ（指及びペン）での選択ができません。
ちなみに、ログイン画面の「ログイン状態を記憶」のチェックボックスも選択不可です。
surface go3 で、chrome,edge,firefox でも選択不可です。
WordPressのForm7で設定したラジオボタン、チェックボックスは選択可能です。

**Comment by koizu-mkII** [comment]
@shitakiy 
社内で確認、調査し、対応を検討いたします。
なお、リリース時期はお約束できませんので、その旨ご理解のほど、どうぞよろしくお願いいたします。

**Comment by shitakiy** [comment]
タブレットでの入力ができない旨の表示を行いましたので、急ぎません。
より良いものになることを期待しています。

**Comment by koizu-mkII** [comment]
@shitakiy 
ご理解の程、ありがとうございます。
また、ご期待に沿えるよう邁進してまいります。
