### ISSUE TITLE
ビューのソートアイコンによるソートが効かない

### ISSUE THREAD

**Issue by a-nagai-dkg** [exceedone/exment#1294]
### Describe the bug / バグの説明
ビューで検索インデックスを有効にしている列にソートアイコンがつくと思いますが、クリックしてもソートされません（再描画はするが順番が変わらない）。
ただし、有効なテーブルも少数派ながらあるので混乱しています。
どのバージョンからおかしくなっているかは不明です。
一回目のクリックでは出鱈目な順序に並び変わり、二回目から変わらないテーブルもあるようです。

### To Reproduce / 再現手順
ソートアイコンをクリックするだけで、ほとんどの通常ビューで再現します。
集計ビューは少ししかないのですが、どうやら再現しないようです。
検索インデックスが多すぎるなどの条件もないようで、それ以上切り分けできていません。

### Version / 発生バージョン
5.0.6

### Error log / エラーログ
特にエラーログは出力されていません。

### Screenshots / スクリーンショット
申請者IDで昇順にソートされるアイコンが表示されていますが、ソートされていない様子です。
![image](https://user-images.githubusercontent.com/77262858/230801901-e0081f60-ef46-4ebf-b3fa-804dcb2c4020.png)

### Additional context / その他  
よろしくお願いいたします。

**Comment by 5050boon** [comment]
私の場合、インデックス設定されたどの項目のソートアイコンを押しても、一度IDの昇順に並び、以降どのソートアイコンを押しても更新はしているようですが並びは変わりません。
何か解決方法がありましたらご教授ください。

**Comment by tkpontas** [comment]
いろいろ試していたら、ビューの設定でデータ表示条件を指定してあげるとデータ並び替えが正常に動作します。
逆に全件ビューの場合、データ表示条件が設定できないので並べ替えが機能しなくなりますが
全件ビューでもフリーワードにて検索して検索結果を表示している場合は並べ替えが動作します。

データ表示条件の設定有無がやはり影響していると思います。
もしお気づきでしたら、読み流してください。

**Comment by a-nagai-dkg** [comment]
確かにそうですね！
データ表示条件を設定していたり、全件ビューでもなにかしらフィルタが適用されている状態ではただしくソートされました。
情報ありがとうございます。

**Comment by KajitoriAdmin** [comment]
只今、改修中です。
6月下旬くらいにRelease予定になります。

**Comment by KajitoriAdmin** [comment]
Released in v5.0.7.

**Comment by a-nagai-dkg** [comment]
5.0.7で改修されていることを確認できました。
ご対応ありがとうございました！
