### ISSUE TITLE
APIエラー「Too Many Attempts.」の条件と設定

### ISSUE THREAD

**Issue by a-nagai-dkg** [exceedone/exment#1295]
機能要望でもないのですが、バグではないのでこちらに投稿させていただきました。

### Describe the feature you'd like / 希望する機能の説明を行ってください
APIキー形式でAPIを連続で叩く際、60回を超えると「Too Many Attempts.」エラーになるように見受けられます。
何秒以内など具体的な条件を教えていただけると助かります。
また、その条件を設定で変更することは可能でしょうか。

**Comment by a-nagai-dkg** [comment]
おそらくLaravelの問題ですね。大変失礼しました。

**Comment by koizu-mkII** [comment]
@a-nagai-dkg 
↓の記事が参考になると思います。
https://zenn.dev/naoki_oshiumi/articles/e7a1e97ba858b4
