### ISSUE TITLE
集計ビューで日付をまとめると明細が表示されない

### ISSUE THREAD

**Issue by a-nagai-dkg** [exceedone/exment#1296]
### Describe the bug / バグの説明
集計ビューでグループ列に日付タイプの項目を選び、列タイプを年月毎などなんらか指定すると、「集計データの明細を表示する」をクリックした際に明細が表示されないようです（空になる）。

### Version / 発生バージョン
v5.0.6

### Error log / エラーログ
[2023-04-17 17:23:15] local.DEBUG: 
IP : 172.16.0.11
URL : https://exment.dnkgp.jp/webapi/notifyPage
Input : 
Headers --------------------------------------
Accept:             application/json, text/javascript, */*; q=0.01
Accept-Encoding:    gzip, deflate, br
Accept-Language:    ja,en;q=0.9,en-GB;q=0.8,en-US;q=0.7
Connection:         keep-alive
Cookie:             XSRF-TOKEN=eyJpdiI6InZDaUZRa3FWQk51K2pKM0VUYzYzVGc9PSIsInZhbHVlIjoid1pGMTZjQnI0Vkh4SlpVY1dKS1Z3dUFJRDhiZk5JOUNYdERuc2ZqOHRVOWtLaHJmYzZJZW1kTzExU3IzMCs0b1NBbURYWXorZ3gwSHA0Ky9ONU1mQU5Tb2VSUDVQZjIxT3hWbzg0d25oMXhMa3RZaUl4RDdqd1VZM2RVV0RFQ1MiLCJtYWMiOiIxYTljZTk0MjE5ZDlkMThhNmM5MDdhMzYyYTFhMjM1MjZmNDFkNzkxNDZiMzc1ZmM4M2NlNmJiODNiMjY1MjkxIiwidGFnIjoiIn0%3D; laravel_session=eyJpdiI6IjFGY1lUUjQxRDNSU0d5LzFybWV5UVE9PSIsInZhbHVlIjoiRDZEREhqbWh1RG5Ud3hoZzlVMHdKSmVDNTVQNCtWMGpwYWlESTUyM2QrZXlZRW9nQURFbDlVSE5Hdk0yUlZJbkMwSHdHMk5uajFkT0dVSExYR3RPMytyU3h6TmdWd3JheWR2TjZzeVJvRWFaUnEySXdLb2loUXFRYU9wdTNET1YiLCJtYWMiOiI5ZTMzYWY2ZDVjYmE3ODVjZWQzNzQxMzBiOTNlMzNkZDg0ZDQ4YWFiYjAwZWI5YmJlOGI1MTVhZmZiZTcxMTNlIiwidGFnIjoiIn0%3D
Host:               exment.dnkgp.jp
Referer:            https://exment.dnkgp.jp/data/Account/16
Sec-Ch-Ua:          "Chromium";v="112", "Microsoft Edge";v="112", "Not:A-Brand";v="99"
Sec-Ch-Ua-Mobile:   ?0
Sec-Ch-Ua-Platform: "Windows"
Sec-Fetch-Dest:     empty
Sec-Fetch-Mode:     cors
Sec-Fetch-Site:     same-origin
User-Agent:         Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.48
X-Requested-With:   XMLHttpRequest
  
[2023-04-17 17:23:15] local.DEBUG: 
IP : 192.168.91.128
URL : https://exment.dnkgp.jp/data/SumKeihi?_pjax=%23pjax-container&group_key=%7B%22ckey_51a4ba5279b113a97dc3%22%3A%222023-04%22%7D&group_view=3ae2662f04f605ceef35&view=0d2076956b93f6f7fe62
Input : view:0d2076956b93f6f7fe62, group_view:3ae2662f04f605ceef35, group_key:{"ckey_51a4ba5279b113a97dc3":"2023-04"}, _pjax:#pjax-container
Headers --------------------------------------
Accept:             text/html, */*; q=0.01
Accept-Encoding:    gzip, deflate, br
Accept-Language:    ja,en;q=0.9,en-GB;q=0.8,en-US;q=0.7,zh-TW;q=0.6,zh;q=0.5
Connection:         keep-alive
Content-Type:       application/x-www-form-urlencoded; charset=UTF-8
Cookie:             XSRF-TOKEN=eyJpdiI6InRaVkM2UUpJdXhVMlQ3U1gvTUlpcHc9PSIsInZhbHVlIjoiMm95U2lKVm1OYnh3TW9iNkh3ZGR5ZlJuRXNQd25yaDVBV1pBbHNzTUovT2s3K0VucGZtUnZNL2o5blQ3OExvd3V0UFlZQ2UxVTJZLytoM3BpbWNWZXRFYUhmSlYxY1ZkK3lXTVRyRVNUdDBUVlJuMnVVdW0zMjJHRlMyT3hla1ciLCJtYWMiOiJiNDI1NTc0MDZiNTI2NzdiNTU2ZDdlNDI3Y2VlNzE3NjkzMTk0NGQ3NmUwODk0ZmRmMzNiZmY1Y2ViM2Q0MjFiIiwidGFnIjoiIn0%3D; laravel_session=eyJpdiI6IktpT1lKV0JKVnpGcjVOMTJvL095aUE9PSIsInZhbHVlIjoicEROdkt5MUJRaFZDMmtISW9XZTRvNmUzaUltTndUaVhiK1VxU0FSQXJYU3hlZjg0a3FkREtQWURCVlZLNHRpcDN1YUxsN2hDYm9KS2V6d3dVRWRxcENLcGVTYVQ0MGw0V05yeFNVSHBGM2dxR2hPU3dEMkUranVEYUV4SFFtY3UiLCJtYWMiOiI3OGI1ZTYzNGIwMDU0MTYyMGNmZmY0YWYwZmViMzFmMzI0NTQ0MDY1MGYzMGU4ZDA1YmIwN2JlMWQ0OWI0NmJhIiwidGFnIjoiIn0%3D
Dnt:                1
Host:               exment.dnkgp.jp
Referer:            https://exment.dnkgp.jp/data/SumKeihi?view=3ae2662f04f605ceef35
Sec-Ch-Ua:          "Chromium";v="112", "Microsoft Edge";v="112", "Not:A-Brand";v="99"
Sec-Ch-Ua-Mobile:   ?0
Sec-Ch-Ua-Platform: "Windows"
Sec-Fetch-Dest:     empty
Sec-Fetch-Mode:     cors
Sec-Fetch-Site:     same-origin
User-Agent:         Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.48
X-Pjax:             true
X-Pjax-Container:   #pjax-container
X-Requested-With:   XMLHttpRequest

### Screenshots / スクリーンショット
![image](https://user-images.githubusercontent.com/77262858/232430183-1e05d9f5-bfa3-4ca6-a1bf-c43ebb11127b.png)

**Comment by KajitoriAdmin** [comment]
修正済み、テスト中です。
