### ISSUE TITLE
フォームの見出し項目が、閲覧時と編集時でタグが異なる

### ISSUE THREAD

**Issue by a-nagai-dkg** [exceedone/exment#1299]
### Describe the bug / バグの説明
バグか仕様かわからないのですが、
フォームに見出し項目を追加した場合、生成されるHTMLタグが編集時は
`<h4 class="field-header">項目名</h4>`
ですが、閲覧時には
`<div class="box-body">項目名</div>`
となってしまいます。閲覧時も編集時と同様のタグになると助かります。

### Version / 発生バージョン
v5.0.6

**Comment by KajitoriAdmin** [comment]
こちらは、仕様になります。
詳細画面は全項目を一律同じクラスShow/Fieldで処理していて
フォーム画面は項目の種類によって、クラスを振り分けているので描画も違ってきます。

フォームにHTML項目を設定してクラスを設定すれば解決すると思います。
よろしくお願いいたします。

**Comment by a-nagai-dkg** [comment]
ご回答ありがとうございました。
なるほどそうですね、HTML項目で対応したいと思います。

**Comment by KajitoriAdmin** [comment]
ありがとうございます。
こちら、Close とさせていただきます。
引き続き、Exment をよろしくお願いいたします。
