### ISSUE TITLE
データ共有設定時に組織を指定できない(候補に出てこない)

### ISSUE THREAD

**Issue by a-nagai-dkg** [exceedone/exment#1300]
### Describe the bug / バグの説明
データ共有を設定する画面で「他のユーザー・組織に共有します」とありますが、
ユーザは指定できますが、組織を検索しても検索候補に出てきません。

### Version / 発生バージョン
5.0.6

**Comment by KajitoriAdmin** [comment]
データ共有設定で候補として選択できる組織は「すでにそのテーブルに対してなんらかの権限を持っている」ことが条件になります。
①そのテーブルになんらかの権限を持つ役割グループが設定されている（参照でも閲覧でも全データ管理者でもOK)
②上記役割グループに組織が設定されている
（①はテーブル自体の設定ですべてのユーザーが閲覧可、とかにしているのでもOK）
→ この条件を両方満たした場合に②で設定した組織が共有対象として表示されます
 
無作為に誰にでも共有できるわけではなく、閲覧権限しか持っていないユーザーや組織に編集権限を与えたり
担当データの編集権限しか持っていない相手に、自分のデータを共有したりすることが目的になります。

よろしくお願いいたします。

**Comment by a-nagai-dkg** [comment]
大変申し訳ございません、コメントし忘れておりました。
確かにご説明のとおりでございました。ありがとうございます！

**Comment by KajitoriAdmin** [comment]
Closeとさせていただきます。
