### ISSUE TITLE
このプロジェクトは継続していますか？

### ISSUE THREAD

**Issue by cold01water** [exceedone/exment#1303]
部外者が失礼なことを申し上げます。

プロジェクトが数ヶ月に渡ってcommitやissueの更新がないことが気になっています。
もし、開発停止になっているようでしたら、告知頂けると幸いです。

**Comment by KajitoriAdmin** [comment]
有償サポートのお問い合わせから優先して対応しているため、github issue 対応は順次行っております。
更新サイクルは不定期になりますので、よろしくお願いいたします。
