### ISSUE TITLE
テーブル権限設定の横スクロールバー

### ISSUE THREAD

**Issue by hayashi-m-shinozaki** [exceedone/exment#1311]
### Describe the feature you'd like / 希望する機能の説明を行ってください
A clear and concise description of what you want to happen. / あなたが何をしたいのかについての、明確で簡潔な説明を行ってください。

テーブル権限設定を設定する画面で権限を設定する画面の横スクロールバーを表の下だけではなく、上にも付けて欲しい。
理由は、テーブルの数が多くなると上の方に対象のテーブルの『全データの参照』から右側の権限設定をしたい場合、一番下までスクロール　→　横にスクロール　→　上にスクロールして対象のテーブルの権限設定をする手順を毎回繰り返すので対処方法を検討して欲しいです。

わがまま言って申し訳ございませんが、ご検討の程宜しくお願い致します。

### Additional context / その他
Add any other context or screenshots about the feature request here. / 機能リクエストに関する他のコンテキストまたはスクリーンショットをここに追加します。

**Comment by KajitoriAdmin** [comment]
Released in v5.0.7.
