### ISSUE TITLE
選択肢(テーブルから参照)で、選択した親テーブルのIDを取得したい

### ISSUE THREAD

**Issue by jnkf422** [exceedone/exment#1315]
「パラメータ変数」の「リレーション、関連データ」で、${select_table:(略)}で、参照先テーブルのIDを取得したいです。
用途としては、利用者に参照先テーブルへのリンクを表示するものです。
ユーザーが設定したカスタム列は取得できるのですが、IDは取得できませんでした。(※1)

※1 記述内容：${select_table:カスタム列名.id}　→　データが空
※2 関連データ検索は一般利用者には操作が煩雑なので使用させていません
※3 親テーブルとリレーションは未設定です(「選択肢 (他のテーブルの値一覧から選択)」のみ使用)。
　${parent:(略)}では取得できるのかもしれませんが、データ構成上の理由でこちらは使用していません。

**Comment by tkpontas** [comment]
親テーブル側に自動採番、フォーマットを${id}とするカスタム列を作成し、子テーブル側で${select_table｝を使ってそのカスタム列で取得させることで擬似的に親テーブルのIDを取得することができます。
管理が煩雑になることを考えるとあまりオススメはしませんが･･･。

そうでは無く、直接親テーブルのIDを取得したいという改善要望であれば、このコメントは見なかったことにしてください。

**Comment by jnkf422** [comment]
意図した動作にする事ができました。ありがとうございました。
（既存の親データは更新が必要ですが、まだ件数が少ないので大丈夫でした）
