### ISSUE TITLE
データインポート時の「選択肢(他テーブル)」のデータが「絞り込みビュー」から検索されてしまう

### ISSUE THREAD

**Issue by jnkf422** [exceedone/exment#1319]
データインポート時の「選択肢 (他のテーブルの値一覧から選択)」の列について、
データが見つからない旨のエラーが発生します。

参照元のデータを検索する時に、カスタム列で指定した「絞り込みビュー」(※)を見ているようです。
一時的にビュー指定を解除すると登録できました。
※データの運用上、絞り込みビューに出るデータが変動します。

カスタム列のインポート・エクスポートは空欄(ID)であり、データは全件ビューでは存在しています。

ドキュメントには挙動について特に記載されていないようですが、これは仕様ですか？
新規作成のインポートを基準とすると、この挙動は理解できます。
過去データを修正時する場合に、この挙動はユーザーには理解し難いと思いますので、対応をご検討ください。

**Comment by KajitoriAdmin** [comment]
こちらは、仕様になります。
よろしくお願いいたします。

**Comment by jnkf422** [comment]
了解しました。ありがとうございました。

**Comment by KajitoriAdmin** [comment]
Close とさせていただきます。
