### ISSUE TITLE
不具合報告（3点）

### ISSUE THREAD

**Issue by milyimi** [exceedone/exment#1320]
不具合と思われる3点について以下に記載します。

* v5.0.4→v5.0.5以降にアップデートするとカスタムテーブルのデータ一覧でソートが機能しなくなる
* インポート機能、CSV及びExcelから必須であるカラムを削除しインポートしてみたらエラーが表示されず空白挿入されていた（v3.9.2までは正常にエラー表示）
* Exmentの手動インストール、「composer require exceedone/exment」を実行してもエラーが出る（exceedone/exmentをインストールする前に「composer require psr/http-message="1.*"」を実行する必要がある）

マニュアルの「インストール手順(手動インストール)」ページで「エラーページ追加」部分についてapp/Exceptions/Handler.phpファイルを修正しなくてもLaravelのエラーが表示されずExmentエラー画面になるようです。記載不要ではと思います。

**Comment by milyimi** [comment]
もう一つ失念しておりました。
かんたんインストールの方ですが、MySQL 8.0.1以上だとExmentのインストールが不可のようです。手動インストールは問題なくインストールできています。以上、ご報告まで。

**Comment by KajitoriAdmin** [comment]
> v5.0.4→v5.0.5～ソートが機能しなくなる
A. v5.0.7 で対応しております。

> インポート機能、～（v3.9.2までは正常にエラー表示）
A. 2020年8月にAPI関連で仕様を変更しております。

> Exmentの手動インストール
A. Exment マニュアルサイトを更新いたしました。

> かんたんインストールの方ですが、MySQL 8.0.1以上だとExmentのインストールが不可
A. MySQL 5.7.8以上8.0.0未満 となっております。（MySQL 8.0以上は現在検討中です）
　https://exment.net/docs/#/ja/server?id=%e3%83%87%e3%83%bc%e3%82%bf%e3%83%99%e3%83%bc%e3%82%b9

**Comment by KajitoriAdmin** [comment]
Closeとさせていただきます。
