### ISSUE TITLE
テーブルのアーカイブ化

### ISSUE THREAD

**Issue by a-nagai-dkg** [exceedone/exment#1340]
### Describe the feature you'd like / 希望する機能の説明を行ってください
機能要望とも少し違いますが、テーブルのレコード数が肥大化し動作が重くなった場合、古いデータは年単位などで他のテーブルにアーカイブし、本番テーブルからは削除するような運用を考えています。

簡単にはできないのかなと思いますが、そのような運用をなさっている方はどのように実現されているのか、お知恵拝借できれば幸いです。

**Comment by a0z0** [comment]
利用者です。
古いデータを自動削除するプラグインを作成して運用しています。

**Comment by a-nagai-dkg** [comment]
なるほどやはりプラグインを作るのが手っ取り早そうですね、ありがとうございます。
