### ISSUE TITLE
カスタムフォームの子テーブル表示の不具合について

### ISSUE THREAD

**Issue by Med-t** [exceedone/exment#1347]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

カスタムフォームでリレーション設定されている項目数の多い子テーブルを表形式とすると新規追加や編集時に入力欄が狭く入力内容を確認できない。
詳細表示の場合は、横スクロールが可能で表示確認ができますので、同様に横スクロールができるよう変更いただきたく。
ご確認の程、よろしくお願いいたします。

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。

v5.0.7

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

【詳細表示】

![詳細](https://github.com/exceedone/exment/assets/139499058/d6c38bea-99c0-4a07-81f0-9134615e8135)

【新規追加及び編集時】

![編集](https://github.com/exceedone/exment/assets/139499058/ae1f4dff-3b5e-4c1a-9921-bbdecd377a76)

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by KajitoriAdmin** [comment]
bug というより 機能改善にありますので enhancement に変更して、検討いたします。

**Comment by Med-t** [comment]
ご確認ありがとうございます。
ご検討の程、よろしくお願いいたします。

**Comment by Med-t** [comment]
v5.0.9にて、改善されている事が確認できました。
ご対応ありがとうございました。
今後ともよろしくお願いいたします。

**Comment by Med-t** [comment]
すみません。
表示幅は改善されていましたが、横スクロールできない為、全ての列が表示されません。
ご確認の程、よろしくお願いいたします。

**Comment by Med-t** [comment]
表形式の子フォームが正常に表示されている事が確認できました。
ご対応ありがとうございました。
今後ともよろしくお願いいたします。
