### ISSUE TITLE
検索バーによる検索について

### ISSUE THREAD

**Issue by Med-t** [exceedone/exment#1353]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

全件ビュー以外のカスタムビューでデータを表示している状態で、検索バーによる検索（フリーワード検索）にて検索すると全件ビューでの検索となってしまいます。
ご確認の程、よろしくお願いいたします。

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。

v5.0.8

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by KajitoriAdmin** [comment]
こちらは、仕様になります。
よろしくお願いいたします。

**Comment by Med-t** [comment]
ご確認ありがとうございます。
フィルタボタン右横の検索バーの説明で、「この検索バーに単語を入力することで、表示しているテーブル内のデータを対象に、検索することができます。」とあり、フィルタボタンと同じように絞り込みの検索と勘違いしていました。

**Comment by Med-t** [comment]
「データ一覧画面にて、検索を行うことができます。 データ一覧画面では、検索バーによる検索と、列を指定してのフィルタ検索の2種類があります。」とあり、同じ絞り込み検索と混同してしまいますので、違いをマニュアルに記載いただけると幸いです。

**Comment by KajitoriAdmin** [comment]
Exment マニュアル更新しました。
ご確認ください。

https://exment.net/docs/#/ja/search?id=%e6%a4%9c%e7%b4%a2%e3%83%90%e3%83%bc%e3%81%ab%e3%82%88%e3%82%8b%e6%a4%9c%e7%b4%a2%ef%bc%88%e3%83%95%e3%83%aa%e3%83%bc%e3%83%af%e3%83%bc%e3%83%89%e6%a4%9c%e7%b4%a2%ef%bc%89-1

**Comment by Med-t** [comment]
早速のご対応ありがとうございました。
今後ともよろしくお願いいたします。

**Comment by Med-t** [comment]
本件、クローズとさせていただきます。
ご対応ありがとうございました。
