### ISSUE TITLE
データの複製機能

### ISSUE THREAD

**Issue by Med-t** [exceedone/exment#1374]
### Describe the feature you'd like / 希望する機能の説明を行ってください
A clear and concise description of what you want to happen. / あなたが何をしたいのかについての、明確で簡潔な説明を行ってください。

カスタムビュー設定やカスタムフォーム設定での操作アイコンで複製が可能ですが、同様に選択したデータの操作アイコンでデータを複製できるよう追加いただけないでしょうか？

①データ一覧の操作アイコン
②データ詳細の子テーブルの操作アイコン

ご検討の程、よろしくお願いいたします。

### Additional context / その他
Add any other context or screenshots about the feature request here. / 機能リクエストに関する他のコンテキストまたはスクリーンショットをここに追加します。

**Comment by KajitoriAdmin** [comment]
v5.0.10 でリリースしました。

**Comment by Med-t** [comment]
ご連絡及びご対応ありがとうございます。
複製用のアイコンが表示されていないようなのですが、何か設定等が必要でしょうか？

**Comment by KajitoriAdmin** [comment]
リリースミスしていましたので、再リリース中です。
よろしくお願いいたします。

**Comment by KajitoriAdmin** [comment]
envファイルの「EXMENT_GRIDROW_SHOW_COPY_BUTTON」の設定が必要になります。

**Comment by Med-t** [comment]
ご連絡及びご対応ありがとうございました。
.envファイルに「EXMENT_GRIDROW_SHOW_COPY_BUTTON=true」を設定し、再ログインする事で「①データ一覧の操作アイコン」に複製用アイコンが表示され、複製アイコンを選択する事でデータが複製された状態で編集画面になる事を確認できました。
今回のリリースは、「①データ一覧の操作アイコン」のみで、「②データ詳細の子テーブルの操作アイコン」については、未対応と言う事でよろしいでしょうか？

![image](https://github.com/exceedone/exment/assets/139499058/c3a214ed-0686-4d20-a796-9c31cce2d4d4)

**Comment by KajitoriAdmin** [comment]
詳細画面の方は「データコピー設定」のボタンが出る場所になるので、実装していません。
そちらは自身でカスタムなコピーを設定してください。

**Comment by Med-t** [comment]
承知しました。
ご回答ありがとうございました。
今後ともよろしくお願いいたします。
