### ISSUE TITLE
カスタムテーブル別の「データ保存後の既定リダイレクト先」

### ISSUE THREAD

**Issue by a-nagai-dkg** [exceedone/exment#1395]
### Describe the feature you'd like / 希望する機能の説明を行ってください
システム設定の詳細設定に「データ保存後の既定リダイレクト先」があり、「一覧」「表示」などを選択できます。
ただ、どれが最適かはカスタムテーブルによって異なります。
（次々登録するタイプは「一覧」、ワークフロー系は「表示」など）

カスタムテーブルにも同様の設定があり、設定すれば優先されると非常に助かります。

**Comment by KajitoriAdmin** [comment]
v5.0.11 でリリースしました。

**Comment by a-nagai-dkg** [comment]
ご対応ありがとうございました！
テーブル通常設定の「データ保存後の既定リダイレクト先」を設定することで
希望の動作することを確認いたしました。
今後とも何とぞよろしくお願いいたします。

**Comment by KajitoriAdmin** [comment]
Close とさせていただきます。
