### ISSUE TITLE
「ラジオボタン・チェックボックス形式で表示」にすると「フィールド種類 読み取り専用」にならない

### ISSUE THREAD

**Issue by a0z0** [exceedone/exment#1416]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
カスタム列を「ラジオボタン・チェックボックス形式で表示」にした場合、
フォーム設定で「フィールド種類 読み取り専用」にしていても編集できてしまう。

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
Version   v5.0.11

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。
なし。

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。
![image](https://github.com/exceedone/exment/assets/24448524/8450b1f2-5192-48bd-b19e-17a9f8eb3c6a)

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by KajitoriAdmin** [comment]
@a0z0 
v6.0.2 リリースしました、ご確認ください

**Comment by a0z0** [comment]
ありがとうございます！改善されてます。
あと。テキスト検索時のフィルター維持が地味にうれしい
