### ISSUE TITLE
アップグレード後、パスワードが変更できなくなった不具合について

### ISSUE THREAD

**Issue by milyimi** [exceedone/exment#1460]
### Describe the bug / バグの説明
Laravel10とExment6にアップグレードした後、ログイン中のパスワードが変更できなくなりました。

### To Reproduce / 再現手順
ユーザーをテンプレートエクスポートして保存された圧縮ファイルのconfig.jsonの中で「"editable_userinfo": "view"」という記述があれば問題が発生します。
問題を引き起こすと思われる個所はlaravel-admin/src/Form.phpの1053行目で「(app()->version() < '5.8.0')」というところ。

### Version / 発生バージョン
exceedone/laravel-admin v4.0.1
exceedone/exment v6.0.3

**Comment by KajitoriAdmin** [comment]
@milyimi 
バージョンアップ試してみましたが問題ありませんでした。
テンプレートが影響していると思われるので
エクスポートした ユーザーテンプレートを共有していただけますか？
よろしくお願いいたします。

**Comment by milyimi** [comment]
「"editable_userinfo": "view",」の記述がなければ、以下のように追加しインポートしていただければ確認できるかと思います。再び試していただけますか？

```json
{
    "template_name": "user",
    "version": "v6.0.3",
    "template_view_name": "ユーザーテンプレート",
    "description": null,
    "custom_tables": [
        {
            ～ 省略 ～
            "custom_columns": [
                {
                    "column_name": "user_code",
                    "column_view_name": "ユーザーコード",
                    ～ 省略 ～
                    "options": {
                        ～ 省略 ～
                        "editable_userinfo": "view",
                        ～ 省略 ～
                    }
                },
                ～ 省略 ～
            ],
            ～ 省略 ～
        }
    ],
    ～ 省略 ～
}
```

v5.0.xの時はエクスポートして「"editable_userinfo": "view",」が含まれていてインポートしても問題ありませんでしたが、アップグレード後、問題が発生するようになりました。

**Comment by milyimi** [comment]
ご対応いただきありがとうございました。
問題ないことを確認いたしました。
