### ISSUE TITLE
プラグイン作成時のエラー(公式プラグイン含む)

### ISSUE THREAD

**Issue by nishi0907** [exceedone/exment#1463]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

選択肢テーブルのみjavascriptによる自動での初期値割り当てができない。

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

公式ドキュメントの基本情報」データの編集画面で、「郵便番号1」「郵便番号2」を入力時に、郵便番号7桁から自動的に「都道府県」「住所」「住所(ビル以降)」をセットするスクリプトを作成します。

全く同じプラグインを作成しても都道府県だけ自動でセットされませんでした。

[https://exment.net/docs/#/ja/plugin_quickstart_script](url)

ConohaWing（レンタルサーバー）,ConohaVPS(Ubuntu + Nginx環境)の両方、動作せずです。

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
レンタルサーバー環境 
exment v5.0.11

VPS環境 
exment v6.0.3

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

ログファイルにはエラーなし

Chromeのデバッグ画面で
Incorrect use of <label for=FORM_ELEMENT>　の表示あり。

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。
テストの為、東京都庁の郵便番号で試した画像です。

![スクリーンショット 2024-05-31 134440](https://github.com/exceedone/exment/assets/171312455/73e2d5d0-96c1-4441-91b5-5d6b13de694c)

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by KajitoriAdmin** [comment]
@nishi0907
ConohaWingとConohaVPSは有料ホスティングサービスで試すことが出来ません。
なので、以下の環境で試しましたが、まだ再現できないです。	
・window + apache
・centos + apache
・ubuntu + nginx

依頼事項：
1) サンプルプラグインを添付するので、試してもらえますか？
2) 動作しないプラグインを共有いただけますか？

よろしくお願いいたします。
[SetAddress.zip](https://github.com/user-attachments/files/15831015/SetAddress.zip)

**Comment by nishi0907** [comment]
もらったサンプルを新しく構築したサーバーで試した見たところ動作しました。
お手数おかけしました。
複数選択にしていたことが問題だったようです。
ありがとうございました。
