### ISSUE TITLE
SSO設定後に「サイトロゴ」と「SSOログインボタンのアイコン」が表示されない

### ISSUE THREAD

**Issue by f-takahiro-watanabe** [exceedone/exment#1472]
### Describe the bug / バグの説明
ログイン設定でSSO（OAuthまたはSAML）を設定した後、「既定のログインを表示する」を「YES」にすると、
ログイン画面でサイトロゴとログインボタンのアイコンが表示されません。

### To Reproduce / 再現手順
１．「システム設定＞サイトロゴ」を設定します。
２．「システム設定＞ログイン設定＞新規」で「ログイン種別」に「OAuth」を選択します。
３．「ログインボタン設定」で任意のアイコンを選択して保存します。
３．「システム設定＞ログイン設定＞SSO設定」で「既定のログインを表示する」で「YES」を選択し保存します。
４．https://(サイト)/admin/auth/loginにアクセスします。
５．サイトロゴとログインボタンのアイコンが表示されません。

### Version / 発生バージョン
v6.0.4

### Additional context / その他  
一般ユーザーは自動ログインをさせたいため、
「システム設定＞ログイン設定＞SSO設定」で「既定のログインを表示する」を「NO」にしておきたいのですが、
システム管理を行う際のみログイン画面でユーザーIDとパスワードによるログインを行いたいです。
下記のように使い分けができるようになると幸いです。

【通常（SSOによる自動ログイン）】
https://(サイト)/admin/auth/login

【手動ログイン（SSOを使用しない）】
https://(サイト)/admin/auth/login?sso=off

**Comment by KajitoriAdmin** [comment]
@f-takahiro-watanabe 
事象確認できました、Bugなので修正中です。
その他は、enhancement Request になるので別途記載しておきます。

**Comment by f-takahiro-watanabe** [comment]
@KajitoriAdmin 
早急なご対応ありがとうございます。
バージョンアップにより、SSO設定後でも「サイトロゴ」と「SSOログインボタンのアイコン」が表示されることが確認できました。
