### ISSUE TITLE
組織階層設定（役割グループ）が5階層目までしか行き渡らない

### ISSUE THREAD

**Issue by y-kikuchi-tw** [exceedone/exment#1481]
### Describe the bug / バグの説明
システム詳細設定「組織階層設定（役割グループ）」を「親子階層のユーザーも役割の範囲に含める」で設定しています。
弊社の組織階層は最大７階層まであり、最上組織に全体用の役割グループを付与することで、全ユーザーに共通する権限を設定しています。
これにより「全データ閲覧」「個別データ編集」「インポート」「データ共有」など、役割グループ側で指定した権限は末端の第7階層組織まで行き渡っているのですが、
カスタムテーブル自体に設定された「ユーザー」「組織」カスタム列、及び『データ共有』において、**選択できるユーザーが第5階層までとなってしまいます**。
つまり第6階層・第7階層に位置する組織に所属するユーザーを『データ共有』で選択することができません。
役割グループで指定した権限は行き届いていること、少なくとも第5階層の組織までは選択可能となっていることから、何らかの不具合ではないかと思われます。
一応、第3階層の組織にも全体用の役割グループを付与することで対策は取れていますが、念のため起票致します。

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
①組織マスタで7階層分の親子関係を作成し、ユーザーを所属させる
②第1階層の組織に「個別データ編集」「データ共有」を付与
③データを登録
④「データ共有」にて、第1～5階層の組織に所属するユーザーを選択
⑤「データ共有」にて、第6・7階層の組織に所属するユーザーを選択

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
6.1.0

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。
![組織階層不具合_20240704](https://github.com/exceedone/exment/assets/152463081/cfb6c3ec-41aa-488a-8a25-4f18f0385e72)

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。
[組織階層不具合_20240704.pptx](https://github.com/user-attachments/files/16094808/_20240704.pptx)

**Comment by KajitoriAdmin** [comment]
@y-kikuchi-tw 
envのEXMENT_ORGANIZATION_DEEPSの数を増やすことで対応できると思います。
ご確認よろしくお願いいたします。

**Comment by y-kikuchi-tw** [comment]
こちらで解決致しました。
ご回答ありがとうございます。
