### ISSUE TITLE
【要望】リレーションの一括解除機能

### ISSUE THREAD

**Issue by y-kikuchi-tw** [exceedone/exment#1482]
### Describe the feature you'd like / 希望する機能の説明を行ってください
・リレーションの一括解除機能
　－具体的には「組織」に所属する「ユーザー」を一括で解除したい。
　　→大規模な組織改編が発生した際、一括で各ユーザーの所属組織を変更したい（可能なら同時に棚卸したい）が、
　　　現状だと「組織」インポートによって新しい組織を追加した上で、ユーザー個別に手動で解除する必要がある。
　　→若しくは「組織」レコードを一度全削除してインポートし直すしかないが、役割グループや他テーブルへの影響が懸念されるため。
　　→まず現行のリレーションを解除した上で、最新の所属組織をインポートする流れを理想としています。
　－リレーション設定を一度削除して設定し直しても、リレーション情報はリセットされなかった。

実装いただけますと非常に幸いです。ご検討の程よろしくお願い致します。

**Comment by KajitoriAdmin** [comment]
@y-kikuchi-tw 
ユーザーの数が多すぎるとドロップダウンになってしまうため、操作がやり難いということでしょうか？
 
大規模な組織改編などで一括作業をするならインポートでやる方がよいと思います。
①組織の一覧でインポート用のテンプレートを出力
②organization_userシートに削除したい組織IDとユーザーIDの組み合わせを列挙して
　delete_flg列に1を入れる
③ 新しく所属させたい組織IDとユーザーIDの組み合わせをその下の行に列挙する
　（別ファイルとして作って順番にインポートしてもよいと思います）
④ 組織の一覧で作成したファイルをインポートする

ご確認よろしくお願いいたします。

**Comment by y-kikuchi-tw** [comment]
こちらで解決致しました。
ご回答ありがとうございます。
