### ISSUE TITLE
列種類の選択値にもHTML上でIDが欲しい

### ISSUE THREAD

**Issue by nishi0907** [exceedone/exment#1483]
### Describe the feature you'd like / 希望する機能の説明を行ってください
A clear and concise description of what you want to happen. / あなたが何をしたいのかについての、明確で簡潔な説明を行ってください。

1行テキストにはHTML上でIDが割り当てられているため
 const nameInput = document.getElementById('test');
 nameInput.value = 'テスト';
等でjavascriptから文字を自動で割り当てができるのですが

選択値にはIDがわりあてられてないため(クロームのF12、開発者モード確認しました。)
const selectObj = document.getElementById('selecttest');
selectObj.selectedIndex = 3;
などで値を自動セットができませんでした。

なので今後のアップデート等でIDを追加して頂けると助かります。

### Additional context / その他
Javascriptなどの勉強を始めたばっかりなので他に列(選択値)の自動設定方法があるのなら教えて頂けると助かります。

F12デバックコード内容
tessssssssssssssという列(選択値)です(変換されるので画像で置き換えました。)

![image](https://github.com/user-attachments/assets/2d02adcb-51c2-4ec2-afcd-0b6b84fe9524)

**Comment by a-nagai-dkg** [comment]
ExmentではjQueryが使えます。
jQueryのセレクタではID属性だけでなく、class属性やname属性などでも要素を選択できますので、お望みのことも可能かと思います。

ExmentではIDが割り当てられていないケースが多いので、
ある文字列を含むタグの3つ上のタグ、などという複雑なセレクタもよく必要になってきます。

**Comment by nishi0907** [comment]
ありがとうございました！
jQueryで無事動作しました！
