### ISSUE TITLE
ビューの一覧の表示順の設定

### ISSUE THREAD

**Issue by a-nagai-dkg** [exceedone/exment#1484]
### Describe the bug / バグの説明
v6.0.3のリリースノートに「ビュー切替時のビューの一覧の表示順の対応」とありますが、
v6.1.0でそれに該当しそうな設定項目が見当たりません。
不具合なのか、単に設定項目を見過ごしているだけでしょうか。

**Comment by tkpontas** [comment]
開発者ではありませんが、もしかしてenvファイルで設定する以下の機能のことでしょうか？
https://exment.net/docs/#/ja/config?id=%e3%82%ab%e3%82%b9%e3%82%bf%e3%83%a0%e3%83%93%e3%83%a5%e3%83%bc%e3%81%ae%e3%82%bd%e3%83%bc%e3%83%88%e9%a0%86

**Comment by a-nagai-dkg** [comment]
おお！どうやらそれのようです。

テーブル「custom_views」の「order」列を直接書き換え、.envの「EXMENT_SORT_CUSTOM_VIEW_OPTIONS」を1か2にすれば反映することを確認できました。
助かりました、ありがとうございます！
