### ISSUE TITLE
独自ビューが削除できなくなる

### ISSUE THREAD

**Issue by nishi0907** [exceedone/exment#1493]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
独自ビューを作成し、テーブルでその独自ビューを割り当てた状態でプラグインを先に削除してしまうとテーブル側で作成した
独自ビューが削除できなくなる。

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
独自ビュー(公式かんばんプラグインを追加)
↓
お知らせでかんばんビュー作成
↓
プラグインを削除
↓
お知らせにてかんばんビューを削除
↓
削除ができず本当に削除しますかが無限ロード

テーブルごと削除すれば消えます。

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
v6.1.1

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。
![スクリーンショット 2024-07-25 073335](https://github.com/user-attachments/assets/cec03e17-374c-4383-8f47-2419aab032ad)

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by KajitoriAdmin** [comment]
@nishi0907 
マニュアルに記載がなくて申し訳ありません。
プラグイン「ビュー」を削除する場合の順番は

1. テーブルに追加した独自ビューを削除
2. プラグイン「ビュー」を削除

となります。

その状態ですと、削除したプラグインをインポートしたとしても、削除することはできません。
削除するには、DBを直接操作して、該当するビューの定義のレコードを削除するしか方法がありません。
カスタムビュー削除用SQLは以下の通りです。
```
delete FROM `custom_views` where id=[id_of_view]
```
[id_of_view]の部分は、下図のように、ビューの編集画面のURLに含まれている数字を確認して、実施してください。
![image](https://github.com/user-attachments/assets/3b9cd4c8-f5fe-42af-8d52-d4afa208f37b)

**Comment by nishi0907** [comment]
返信ありがとうございます。
ビューから削除を徹底し、消せなくなった場合はSQLから直接削除するようにします。
ありがとうございました。
