### ISSUE TITLE
テキストエディタでCtrl+Vでしか貼り付けられなくなった

### ISSUE THREAD

**Issue by a-nagai-dkg** [exceedone/exment#1501]
### Describe the bug / バグの説明
恐らくVer.6系にしてからと思われますが、テキストエディタにおいて、
右クリックを押すと「Link(Ctrl+K)」しか出てこず、ツールバーの貼付けアイコンをクリックすると
「お使いのブラウザではクリップボード機能を使うことができません」と表示され、
結果Ctrl+Vでしか貼り付けられなくなっています。
これはバグでしょうか、仕様でしょうか。

### To Reproduce / 再現手順
複数のテーブルのフォームで再現しました。
ブラウザはEdge, Chromen, Firefoxの最新版で再現しました。

### Version / 発生バージョン
v6.1.1

### Screenshots / スクリーンショット
![image](https://github.com/user-attachments/assets/241ba027-3d46-43f6-a537-05b7fc44d62b)
![image](https://github.com/user-attachments/assets/5b110ed5-3864-4f42-b4d6-b4873062b453)

**Comment by f-takahiro-watanabe** [comment]
@a-nagai-dkg 

開発者ではありませんが、エディタの開発元の公式でも非対応（仕様）です。
https://www.tiny.cloud/docs/tinymce/latest/full-featured-premium-demo/

但し、比較的新しいClipboard APIにより暫定対策は可能です。

下記サンプルコードです。
フォームのHTMLに組み込むことにより貼り付けボタンが利用できます。
最近の主要なモダンブラウザなら対応していると思いますが、
細かい動作確認はできておりませんので、参考する場合は自己責任でお願いいたします。

`
<script>
    $(function () {
        // テキストエディタのカスタマイズ（対象の列名を指定）
        let editor_contents = new customizeTextEditor('contents');
        editor_contents.customize();
    });

    /**
     * テキストエディタのカスタマイズ。
     */
    class customizeTextEditor {

        /**
         * コンストラクタ。
         * @param {string} column_name テキストエディタの列名。
         */
        constructor(column_name) {

            // テキストエディタの列名
            this._column_name = column_name;

            // インターバルID
            this._interval_id = null;

            // インターバル用カウンタ
            this._counter = 1;

            // インターバル用カウンタ最大値
            this._counter_max = 20;

            // インターバル時間（ミリ秒）
            this._delay = 100;

            // 処理済フラグ
            this._processed = false;
        }

        /**
         * カスタマイズ実行。
         */
        customize() {
            this._interval_id = setInterval(this._main.bind(this), this._delay);
        }

        /**
         * メイン処理。
         */
        _main() {

            // テキストエディタのIDを取得
            let id = $('.value_' + this._column_name).attr('id');

            // テキストエディタのボタンを取得
            let button = $('button[title="貼り付け"]');

            // 念のため処理タイミングにより2度実行されないようにフラグ確認
            if (this._processed) {
                return;
            }

            // エディタの貼り付けボタンが取得できた
            if((button.closest('.form-group').find('textarea').attr('id') == id) && (button.length >= 1)) {

                // 処理済み
                this._processed = true;
                clearInterval(this._interval_id);

                // 貼り付けボタンのクリック処理を登録
                button.off('click').on('click', function(e) {

                    // イベントの伝播を停止
                    e.stopPropagation();

                    // テキストエディタを取得
                    let editor = tinymce.get(id);

                    // クリップボードを読み込み貼り付け処理
                    navigator.clipboard.read().then((items) => {

                        for (let i = 0; i < items.length; i++) {
                            const item = items[i];

                            // 複数のタイプを持つデータの場合は１つのみ処理
                            if (item.types.includes('text/html')) {
                                // HTML（Wordファイルの内容等も対象）
                                item.getType('text/html').then((blob) => {
                                    blob.text().then((text) => {
                                        editor.execCommand('mceInsertContent', false, text);
                                    }, () => {
                                        return;
                                    });
                                }, () => {
                                    return;
                                });
                            }
                            else if (item.types.includes('text/plain')) {
                                // テキスト
                                item.getType('text/plain').then((blob) => {
                                    blob.text().then((text) => {
                                       text = '<p>' + text;
                                        text = text.replaceAll('\n', '<br>');
                                        text = text.replaceAll(' ', '&nbsp;');
                                        text = text.replaceAll('\t', '&nbsp;&nbsp;&nbsp;&nbsp;');
                                        text = text + '</p>';
                                        editor.execCommand('mceInsertContent', false, text);
                                    }, () => {
                                        return;
                                    });
                                }, () => {
                                    return;
                                });
                            }
                        }
                    }, () => {
                        return;
                    });
                });
            }

            // エディタの貼り付けボタンの検索上限に達したため処理を中断
            if (this._counter >= this._counter_max) {
                clearInterval(this._interval_id);
            }

            this._counter++;
        }
    }
</script>
`

**Comment by f-takahiro-watanabe** [comment]
右クリックで貼り付けを表示する処理は未実装です。

**Comment by a-nagai-dkg** [comment]
なるほど、そうだったのですね。。
お教えいただいたコードを試してみましたが、正常に動作いたしました。
本当にありがとうございました！
