### ISSUE TITLE
v6.1.5アップデート後、ファイル列にファイルがアップロードできなくなった

### ISSUE THREAD

**Issue by nishi0907** [exceedone/exment#1520]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
ファイル列に添付ファイルをアップロードするとエラーが発生する

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
![ss1](https://github.com/user-attachments/assets/aaee72f6-49a6-4518-b35a-b4b777f52bbb)
![ss2](https://github.com/user-attachments/assets/00a95e1a-f81b-4d13-875e-98f340a3c173)

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
v6.1.5

VPS環境およびレンタルサーバー環境で発生

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by KajitoriAdmin** [comment]
確認しました。
列種類：ファイル or 画像　で、且つ　複数選択を許可する＝YES　
の場合に、エラーが発生することが判明しております。
早急に対応いたしますが、対応完了まで今しばらくお待ちください。

**Comment by KajitoriAdmin** [comment]
v6.1.6 リリースで対応しました。
ご確認ください。

**Comment by nishi0907** [comment]
迅速な対応ありがとうございました。
ダウングレードで対応したためとても助かります。

**Comment by b169d127** [comment]
こちら公開フォームで似たようなエラーが発生しているのですが、同様の不具合の影響でしょうか。
Version / v6.1.6で発生しています。
![処理済～スクリーンショット 2024-10-21 143911](https://github.com/user-attachments/assets/aaecdacd-fccf-47a4-9896-2301c1efee89)
