### ISSUE TITLE
v6.1.6アップデート後、ファイル列がある公開フォームにファイルを添付した状態でアップロードできなくなった

### ISSUE THREAD

**Issue by b169d127** [exceedone/exment#1528]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
カスタム列がファイル列になっているテーブルの公開フォームに添付物をつけて起案するとエラーとなる。
添付物を付けない場合は、正常に登録できる。

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
ファイル列を設定しているテーブルの公開フォームに添付物をつけて登録する。
※こちらにも同様のコメントをしています。
https://github.com/exceedone/exment/issues/1520#issuecomment-2425638240

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
v6.1.6

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。
![処理済～スクリーンショット 2024-10-21 143911](https://github.com/user-attachments/assets/09576f29-2023-4e68-876f-9dd89a0a9c97)

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by KajitoriAdmin** [comment]
v6.1.7 でリリースしました。
ご確認ください。

**Comment by b169d127** [comment]
@KajitoriAdmin 
v6.1.7で解消されていることを確認しました。
迅速な対応ありがとうございます。
本件closeさせていただきます。
