### ISSUE TITLE
通知アクション設定で送信先の組織が保存されない

### ISSUE THREAD

**Issue by a-nagai-dkg** [exceedone/exment#1530]
### Describe the bug / バグの説明
通知アクション設定で実施アクションにシステム内アラートかEメールを選択し、
通知対象を「指定の組織」にして「送信先の組織」に組織を設定しても、
保存ボタンを押すと組織が消えている。

### Version / 発生バージョン
v6.1.6
滅多に該当する条件の設定は行わないため、どのバージョンから発生しているかは不明。
一年以内に問題なく保存できているバージョンがあったのは確か。

### Error log / エラーログ
エラーログは何も出ませんでした。

**Comment by KajitoriAdmin** [comment]
@a-nagai-dkg 
再現確認いたしました。

### 再現する条件
組織のレコード数が　100件（※）を超える　場合

*（※）[.env]で`EXMENT_SELECT_TABLE_LIMIT_COUNT`を設定している場合、設定値に依存します。*

### 影響箇所
- カスタムテーブルの通知設定のアクション設定の[送信先の組織]
- ワークフローの通知設定のアクション設定の[送信先の組織]

### 事象
通知設定のアクション設定を

- 実施アクション : Eメール or システム内アラート
- 通知対象 : 指定の組織

と設定し、[送信先の組織]に値を設定し保存。
次に、該当する通知設定の編集画面を表示した際、[送信先の組織]がブランクで表示される。

（なお、本事象は、表示に問題があり、設定値は正しく保存されております。）

### 今後の対応
プログラムの問題個所は特定しており、現在検証中です。
検証中のブランチ : hotfixfeature/issue_1530

検証後、新バージョンでのリリースとなりますので、今しばらくお待ちください。

**Comment by a-nagai-dkg** [comment]
早速調査いただき誠にありがとうございます。
確かに組織数は100を超えております。
ご対応何卒よろしくお願いいたします。

**Comment by KajitoriAdmin** [comment]
v6.1.7 でリリースしました。
ご確認ください。

**Comment by a-nagai-dkg** [comment]
正常に保存されることを確認いたしました。
迅速なご対応誠にありがとうございました！
