### ISSUE TITLE
フォームにおいて子テーブルにファイルが保存できない

### ISSUE THREAD

**Issue by wanpa** [exceedone/exment#292]
・フォームにおいて子テーブルにファイルが保存できない

・添付しても保存されたファイルがなにを保存されているのかが編集時に見えない。

**Comment by wanpa** [comment]
・フォーム編集中に子レコードのファイル見れるようになりました（サムネイル含め）
一方でその子レコードに新たなファイルを入れて送信出来ない且つEDITエンドポイントに遷移
https://hogehoge/admin/data/hogehoge/999/edit
した後にはサムネイル等が外れてしまいます。
レコードの表示に戻り、再度、編集にするとサムネイルが見れますが、ファイルが追加されていない。

現在のバージョン：v1.3.5

**Comment by wanpa** [comment]
ご対応ありがとうございました。

フォームの以下の緑の新規ボタンアイコンからですとまだうまくいかないです。
https://i.gyazo.com/6c6c2edb3c10da8fe7d97026cf578b64.png

**Comment by hirossyi73** [comment]
失礼しました、クローズしてしまっていました。
再度確認させてください。

**Comment by hirossyi73** [comment]
カスタム列が「ファイル」「画像」の時の、保存時にトリガーされるイベントが、子テーブルの場合に、最初の子データ1件目の時しか実行されていませんでした。
ロジックの修正を行いました。

**Comment by hirossyi73** [comment]
@wanpa 
v1.4.1にて修正しました。ご確認いただければ幸いです。

**Comment by wanpa** [comment]
ご対応ありがとうございます。
環境整い次第レビューさせて頂きます。

このツールのファンです。

**Comment by wanpa** [comment]
1.41で想定通りの動作でした。ありがとうございます！とても便利です。

少しデータの整合性という点で気になるものあるのですが、
カスタム列設定において、必須にしてあるカスタム列が
子テーブル -フォームを設定する際に、必須が除外できる点が気になります。
カスタム列設定において、必須にしてあるカスタム列は
子テーブル -フォームにおいては項目設定は外せないというのが正しいような気がします。

**Comment by hirossyi73** [comment]
お褒めいただき、ありがとうございます！非常に嬉しいです。

またご要望もありがとうございます。
上記の内容は、こちらで別にissue作成いたしました。
#318 

本issueはクローズさせていただきます。
