### ISSUE TITLE
新規インストール時のエラー

### ISSUE THREAD

**Issue by wanpa** [exceedone/exment#343]
お世話になります。
新環境で新バージョンをインストールを試したところ
以下のようなエラーが発生しましたのでご報告させて頂きます。

> 
> In Connection.php line 664:
> 
>   SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'custom_table_id' cannot be null (SQL: insert into `custom_columns` (`cust
>   om_table_id`, `column_name`, `column_view_name`, `column_type`, `description`, `system_flg`, `options`, `suuid`, `updated_at`, `created
>   _at`) values (, document_name, ドキュメント名, text, , 1, {"use_label_flg":"1","index_enabled":"1"}, 4a80ac80f28204a1cb8a, 2019-07-31 1
>   1:51:26, 2019-07-31 11:51:26))
> 
> 
> In PDOStatement.php line 119:
> 
>   SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'custom_table_id' cannot be null
> 
> 
> In PDOStatement.php line 117:
> 
>   SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'custom_table_id' cannot be null

**Comment by hirossyi73** [comment]
ご報告ありがとうございます。早急に確認させてください。

**Comment by hirossyi73** [comment]
@wanpa 
以下の環境では、正常にインストールできることを確認しました。

・OS：Windows
・Exmentバージョン：v2.0.1
・PHPバージョン：7.2.17
・MySQL種類(Mysql/MariaDB)：Mysql
・インストール方法：かんたんインストール（https://exment.net/docs/#/ja/quickstart）

環境による事象の可能性もあるので、
お手数ですがご利用の環境を教えていただけないでしょうか？

**Comment by wanpa** [comment]
ご確認ありがとうございます。

・centos7
・PHP 7.3.8
・10.4.6-MariaDB MariaDB Server
・手動インストール

再度、やってみます。

**Comment by wanpa** [comment]
お世話になります。
かんたんインストールとはzipをダウンロードするというやり方の事でよろしかったでしょうか？

**Comment by hirossyi73** [comment]
はい、おっしゃるとおりで、zipでインストールするやり方になります。

■かんたんインストール
https://exment.net/docs/#/ja/quickstart

■手動インストール
https://exment.net/docs/#/ja/quickstart_manual

**Comment by wanpa** [comment]
ありがとうございます。
かんたんインストールでLaravel Welcomeは出て
http://hogehoge.jp/exment/admin
は存在しない形になるのは
原因は何になりますでしょうか？
恐れいります。。

**Comment by hirossyi73** [comment]
今まであったケースですと、今のような場合が多かったです。

・mod_rewriteの有効確認
http://ysklog.net/mod-rewrite/related02.html
の、「mod_rewriteが使用可能か確認」の実施

・httpd.confで設定を行い場合、「Require」と「AllowOverride」が入っているかどうかを確認してください。
例：
<Directory /var/www/exment/public> 
AllowOverride All 
Require all granted 
</Directory>

**Comment by wanpa** [comment]
お世話になります。
これ通りに
改めてサーバーを立てて
https://exment.net/docs/#/ja/install_linux
・centos7
・PHP 7.3.8
・10.4.6-MariaDB MariaDB Server
やはり表題と全く同じエラーに遭遇しました。。
