### ISSUE TITLE
データの件数が大きすぎるExcelファイルでデータインポートすると、メモリオーバーが発生する

### ISSUE THREAD

**Issue by hirossyi73** [exceedone/exment#348]
・データインポート用のテンプレートファイルをダウンロードする。
・データの件数を大量に用意する。3000件もあれば十分
・データインポートを実行する。
・「Allowed memory size of XXXX bytes exhausted (tried to allocate XXXX bytes)」エラーが発生する。

※使っているライブラリは「PhpSpreadsheet」で、「PHPExcel」の後継。
Excelファイルからデータを読み込むところでエラーになっているのは間違いない。

**Comment by horihorihorihorihori** [comment]
Php.ini の　memory_limitを512mなどの大きな値にして、再起動したらなおりましたよ。

**Comment by hirossyi73** [comment]
そうですね、memory_limitを変更すれば対応可能なようです。
修正の方針として、「memory_limit不足」の場合のエラーをハンドリングし、拾ってこれるような対応を検討します。
（現在は「予期せぬエラー」か、何も表示されない状況なので）
