### ISSUE TITLE
エクスポートしたデータがインポートできない

### ISSUE THREAD

**Issue by horihorihorihorihori** [exceedone/exment#405]
選択肢 (他のテーブルの値一覧から選択)の列を含むデータをエクスポートすると、選択肢の列のデータがidのデータで、出力される。

この選択肢の列の定義について、｢インポート時のキー列｣をid以外にしていると、列の内容が異なるため、インポートできない。

**Comment by hirossyi73** [comment]
issueありがとうございます。
｢インポート時のキー列｣設定は、どちらかというと「ユーザーが新規にデータを投入する場合」を想定して、ロジックを組んでいます。
エクスポートしたデータをそのままインポートする場合、現在の仕様の場合お手数なのですが、「##setting##」シートの3行目以降を削除いただいてから、インポートしていただけますよう、お願いします。

※「データをエクスポートした時には##setting##を出さない」などの修正は、今後検討させてください。

**Comment by horihorihorihorihori** [comment]
お世話になります。
エクスポートした際に、選択肢 (他のテーブルの値一覧から選択)のデータはidでしか出力出来ないのでしょうか？別のユニークキーを出力することは出来ないでしょうか？

**Comment by hirossyi73** [comment]
@horihorihorihorihori 

ご連絡遅くなり、申し訳ありません。休暇をいただいておりました。

現在は、出力の際にはidでの出力固定になります。
今後、選択肢 (他のテーブルの値一覧から選択)の場合の出力形式を、id以外の方法で出力する方法を検討させてください。

**Comment by hirossyi73** [comment]
v3.0.21で対応したので、クローズします。
