### ISSUE TITLE
日付列を対象に月毎・日毎・曜日毎で集計するとエラー

### ISSUE THREAD

**Issue by C0ela** [exceedone/exment#429]
### 再現手順
1. 列種類「日付」のカスタム列を対象列として集計ビューを作成する。
2. 列タイプを「月毎」or「日毎」or「曜日毎」に設定する。
3. 作成したビューでデータ一覧を表示する。

### 発生するエラー
```
Exception In Carbon.php line 439 :
DateTime::__construct(): Failed to parse time string (09) at position 0 (0): Unexpected character
```

**Comment by hirossyi73** [comment]
@C0ela 
v2.1.7にて対応しましたと認識しております、ご確認いただければ幸いです。

**Comment by C0ela** [comment]
エラーが修正されたことを確認しました。ご対応ありがとうございました。
