### ISSUE TITLE
選択肢(他のテーブルの値一覧から選択)データが編集画面から消える

### ISSUE THREAD

**Issue by Nemzo** [exceedone/exment#448]
**Describe the bug / バグの説明**
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

データ編集時、選択肢(他のテーブルの値一覧から選択)の値表示が消える
ビュー画面/詳細画面では表示あり

**To Reproduce / 再現手順**
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

**Error log / エラーログ **
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

エラー出力なし

**Screenshots / スクリーンショット**
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

**Additional context / その他**
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by hirossyi73** [comment]
どういった条件で本件が発生するかどうか、発生する場合の条件などを追っていきます。

**Comment by Nemzo** [comment]
カスタム列1つでは未発生のため、この辺りが関係している気も致します。
現在の構成
カスタム列：28個必須：6個インデックス：7個

**Comment by hirossyi73** [comment]
ありがとうございます。（こちらにて失礼しまう）
列数や、親子のリレーションなどの要因が関わりありそうですね。

**Comment by hirossyi73** [comment]
@Nemzo 
他の方から同様の不具合のご報告あり、事象確認しました。
列設定の「選択肢を絞り込む 」がYESのとき、同様の症状が発生しておりました。
※こちらの不具合修正は、本日の夜にリリースいたします。

同様の設定されているか、ご確認いただけないでしょうか。

**Comment by Nemzo** [comment]
こちらでも確認出来ました。
「選択肢を絞り込む 」がYESのとき症状発生致しました。

**Comment by hirossyi73** [comment]
ありがとうございます。
v3.0.0にて、上記症状解消されていますので、ご確認ください。

**Comment by hirossyi73** [comment]
こちら、クローズさせていただきます。

**Comment by Nemzo** [comment]
現象改善している事確認出来ました。
ありがとうございました。
