### ISSUE TITLE
「通知本文」の対象データのリンクが無効 - ワークフロー

### ISSUE THREAD

**Issue by skmt8585** [exceedone/exment#457]
**Describe the bug / バグの説明**
通知に表示される「通知本文」の対象データのリンクが無効です。リンクのHTMLがそのまま表示されます。(Firefoxで確認)

**To Reproduce / 再現手順**
1.申請ユーザーで申請を開始します。
2.承認ユーザーの通知(ベルのアイコン)から該当の申請の通知を選択します。
3.「通知本文」が表示されます。「対象データ」のリンクにHTMLがそのまま表示されます。

**Error log / エラーログ**
なし

**Screenshots / スクリーンショット**
なし

**Additional context / その他**
なし

**Comment by hirossyi73** [comment]
ありがとうございます、修正を行いました。
こちらにてバージョンアップを行っていただければ幸いです。
https://exment.net/docs_dev/#/ja/quickstart_workflow_dev?id=%e3%83%86%e3%82%b9%e3%83%88%e7%92%b0%e5%a2%83%e3%82%92%e6%9b%b4%e6%96%b0%e3%81%99%e3%82%8b%e5%a0%b4%e5%90%88

**Comment by skmt8585** [comment]
デモ環境で改善していることを確認しました。
対応ありがとうございました。
