### ISSUE TITLE
申請の履歴が表示されない - ワークフロー

### ISSUE THREAD

**Issue by skmt8585** [exceedone/exment#458]
**Describe the bug / バグの説明**
申請⇒却下の順で操作すると、それ以降は詳細画面で「履歴 表示」をクリックしても、その申請の履歴が表示されなくなります。

**To Reproduce / 再現手順**
1.申請ユーザーで申請を開始します。
2.承認ユーザーで申請を却下します。
3.申請ユーザーで申請の詳細画面で「履歴 表示」をクリックしても、履歴がポップアップしない。

※「申請⇒承認」で承認した場合は、履歴は表示される。

**Error log / エラーログ**
なし

**Screenshots / スクリーンショット**
なし

**Additional context / その他**
なし

**Comment by hirossyi73** [comment]
ありがとうございます、修正を行いました。
こちらにてバージョンアップを行っていただければ幸いです。
https://exment.net/docs_dev/#/ja/quickstart_workflow_dev?id=%e3%83%86%e3%82%b9%e3%83%88%e7%92%b0%e5%a2%83%e3%82%92%e6%9b%b4%e6%96%b0%e3%81%99%e3%82%8b%e5%a0%b4%e5%90%88

**Comment by skmt8585** [comment]
デモ環境で改善していることを確認しました。
対応ありがとうございました。
