### ISSUE TITLE
テーブル詳細設定ドロップダウンメニューに不要な改行が存在する

### ISSUE THREAD

**Issue by K2N7** [exceedone/exment#459]
**Describe the bug / バグの説明**
テーブル詳細設定ドロップダウンメニューの選択項目にて、Font Awesome Iconsの直後で不要な改行が存在する。

**To Reproduce / 再現手順**

1. データ一覧画面を表示
2. テーブル詳細設定ドロップダウンメニューをクリック

[デモサイト](https://demo-jp.exment.net/admin)でも確認できます。

**Error log / エラーログ** 
なし

**Screenshots / スクリーンショット**

- 現状

![Screenshot_2019110709572318](https://user-images.githubusercontent.com/3872118/68351579-3ca56700-0147-11ea-90a7-226efa71ec4d.PNG)

- 期待値

![Screenshot_2019110710094821](https://user-images.githubusercontent.com/3872118/68351638-6494ca80-0147-11ea-861e-4870f45c2254.PNG)
Chrome DevToolにて下記コードを追加。
```css
#custom-table-menu .dropdown-menu {
  min-width: max-content;
}
```

**Additional context / その他**
カスタムjavascript/cssやはプラグイン形式ではなく管理画面よりエディタ形式で直接編集できると嬉しいです。

**Comment by hirossyi73** [comment]
- デザイン崩れについて：
Chrome側で不具合があったようで、私の端末でも確認できていました。
https://stackoverflow.com/questions/58526368/issue-with-white-space-nowrap-on-chrome-78-0-3904-70

11/6の午後のバージョンアップで、弊社開発要員2名で正常に表示されることを確認しました。
Chromeのバージョンアップを試していただけると幸いです。

- カスタムjavascript/cssについて
こちらは別のissueを作成していただけると幸いです。

**Comment by K2N7** [comment]
ご回答ありがとうございます。
Chrome 78.0.3904.97にバージョンアップし、正常に表示されることを確認しました。
カスタムjavascript/cssについては別途Issueを作成させて頂きます。
