### ISSUE TITLE
フォーム画面でのルール機能追加

### ISSUE THREAD

**Issue by K2N7** [exceedone/exment#460]
**Describe the feature you'd like / 機能する機能の説明を行ってください**

特定の列の値に(条件)応じて、特定の列の設定を動的に変更/バリデーションチェック(アクション)を設定ができるルール機能があると嬉しいです。ルールはフォームに紐づいて複数保持することができ、設定画面よりON/OFFできるようなイメージです。また、And / Or で複数の条件を1つのルールとして組み合わせ可能であることが望ましいです。

e.g)
- 列 AAA の値が NULL の場合、列 BBB を必須項目にする。
- 列 AAA の値が XXX [と等しい/以下/より大きい/を含む] 場合、列 BBB を必須項目にする。
- る。
- 列 AAA の値が XXX [と等しい/以下/より大きい/を含む] 場合、列 BBB の上限値/下限値を YYY に設定する。
- 列 AAAの値が XXX [と等しい/以下/より大きい/を含む] 、かつ列 BBB の値が YYY [と等しい/以下/より大きい/を含む] 場合、エラーとする。

**Additional context / その他**
なし

**Comment by hirossyi73** [comment]
@K2N7 
次回リリースで、バリデーションのプラグインに対応予定です。
#438

バリデーションは様々なパターンがあり、案件やプロジェクト、テーブルごとに細かい設定が予想されるので、プラグインとして追加の想定です。

**Comment by K2N7** [comment]
回答ありがとうございます。
プラグイン機能としての提供をお待ちしてます。
