### ISSUE TITLE
URLコンテキストパスの設定追加

### ISSUE THREAD

**Issue by K2N7** [exceedone/exment#461]
**Describe the feature you'd like / 機能する機能の説明を行ってください**

Exment URLコンテキストパスの設定機能を追加してほしいです。。
現状、ADMIN_ROUTE_PREFIXの設定で http://localhost/Exment のようにURLを変更可能ですが、javascript/cssファイルはhttp://localhost/vendor http://localhost/lib のファイルを参照しているため、Reverse Proxyでhttp://localhost/Exment へアクセスさせる際にはvendor、libフォルダについても個別に設定する必要があります。
ADMIN_ROUTE_PREFIXをjavascript/cssファイルを含むExment全体に効くように変更できないでしょうか。

**Additional context / その他**
なし

**Comment by hirossyi73** [comment]
こちらで回避方法を検証し、フォルダの「public」フォルダに「Exment」フォルダを作成し、シンボリックリンクを作成するなどのやり方を試してみたのですが、
「Exment」フォルダを作成したために、ページアクセスのための「http://localhost/Exment」がリンクできなくなってしまうなど、問題が大きくありそうです。

発行パスの変更も、関連ライブラリ(laravel-admin)の変更によるインパクトが大きいので、対応は少々難しそうです。

**Comment by K2N7** [comment]
回答ありがとうございます。
対応が難しそうであるとのこと理解しました。
取り急ぎはサーバー側の構成設定で回避することにします。
