### ISSUE TITLE
ダッシュボード_グラフ色変更機能

### ISSUE THREAD

**Issue by Nemzo** [exceedone/exment#465]
**Describe the feature you'd like / 機能する機能の説明を行ってください**
A clear and concise description of what you want to happen. / あなたが何をしたいのかについての、明確で簡潔な説明を行ってください。
ダッシュボードで表示されるグラフ色を変更出来る機能を追加してほしい

**Additional context / その他**
Add any other context or screenshots about the feature request here. / 機能リクエストに関する他のコンテキストまたはスクリーンショットをここに追加します。

**Comment by hirossyi73** [comment]
@Nemzo 
現在は、色の順番は固定になっています。
変更の場合、「config/exment.php」を開き、「chart_backgroundColor」で色の指定をお願いします。
