### ISSUE TITLE
APIを続けて発行すると、20件目くらいから429:TooManyRequestError発生

### ISSUE THREAD

**Issue by yukicchi** [exceedone/exment#467]
exmentAPI（カスタムテーブル更新、カスタムテーブル登録）をループ処理で続けて実行すると
20件目くらいからSTatusError：429TooManyRequestErrorが返され、登録/更新ができていない。

**Comment by hirossyi73** [comment]
@yukicchi 

app/Http/Kernel.php
の47行目前後に、
'throttle:60,1',
という記載があると思います。これは「1分間に60回のリクエストを許可する」ということのようです。
この値を変更するか、この行そのものを削除することをお願いします。
※v3.0.0以降でご確認ください。

**Comment by yukicchi** [comment]
ありがとうございました。バージョンアップで解決いたしました。
