### ISSUE TITLE
ユーザ/組織のリレーション関係でデータ連動設定ができない

### ISSUE THREAD

**Issue by K2N7** [exceedone/exment#470]
**Describe the bug / バグの説明**
フォーム設定画面にて、ユーザ/組織の項目をデータ連動設定しようとしても、エラーメッセージが表示され設定できない。
e.g)
申請者/申請者所属

**To Reproduce / 再現手順**
カスタムテーブルに列種類がユーザのカスタム列を追加
カスタムテーブルに列種類が組織のカスタム列を追加
フォーム設定画面より、ユーザに紐づく組織名を設定するためにデータ連動設定を選択

**Error log / エラーログ** 
※列の種類が「選択肢 (他のテーブルの値一覧から選択)」、「ユーザー」、「組織」となる列がテーブル内に存在しません。データ連動設定を使用する場合、これらの列を登録してください。

**Screenshots / スクリーンショット**
![Screenshot_2019111414090526](https://user-images.githubusercontent.com/3872118/68828239-5cf59880-06e8-11ea-8dda-65a3c12bca1a.PNG)

**Additional context / その他**
「選択肢 (他のテーブルの値一覧から選択)」カラムではユーザ/組織テーブルを指定できないため、手動ですることもできない。

**Comment by hirossyi73** [comment]
@K2N7 
現象確認しました。
修正完了、次回のリリース（本日夜予定）でリリースします。

**Comment by hirossyi73** [comment]
@K2N7 
バージョン3.0.1をリリースしました、こちらでご確認ください。

**Comment by K2N7** [comment]
対応ありがとうございます。
バージョン3.0.1にて修正されていることを確認できました。
