### ISSUE TITLE
ユーザ型のカスタム列の初期値設定

### ISSUE THREAD

**Issue by K2N7** [exceedone/exment#471]
**Describe the feature you'd like / 機能する機能の説明を行ってください**
ユーザ型のカスタム列の初期値設定にフォーム入力者(ログインユーザ)を設定できるようにしてほしい。現状ではサジェストも表示されないためユーザ型カラムにおける初期値設定は実用性に欠ける

**Additional context / その他**
なし

**Comment by hirossyi73** [comment]
@K2N7 
v3.0.13で対応しました！

**Comment by K2N7** [comment]
@hirossyi73 
対応ありがとうございます！
v3.0.14で動作確認できました。
