### ISSUE TITLE
実行可能ユーザ設定で組織選択時に1レコードしかサジェスト表示されない

### ISSUE THREAD

**Issue by K2N7** [exceedone/exment#472]
**Describe the bug / バグの説明**
実行可能ユーザ設定の組織選択サジェストに1レコード(ID 1のもの)しか表示されない。
組織は6レコード登録済み。

**To Reproduce / 再現手順**
ワークフロー設定 - アクション設定 - より実行可能ユーザの変更ボタンを押下
組織欄のサジェストにて表示される組織が、ID 1 のレコードのみ。

**Error log / エラーログ** 
なし

**Screenshots / スクリーンショット**
なし

**Additional context / その他**
他の欄(ユーザ/カスタム列など)は全レコードが期待値通りにサジェストされます。

**Comment by hirossyi73** [comment]
@K2N7 
ワークフローの種類は、汎用とテーブル指定のどちらでしょうか？
テーブル指定の場合、そのテーブルに対し、権限のある組織のみが一覧に表示される想定です。

汎用になっている、もしくは適切に権限設定が行われているのに表示されないなど、問題ございましたら、お手数ですがご指摘ください。

**Comment by K2N7** [comment]
回答ありがとうございます。
テーブル指定で実施しておりました。
権限設定を見直したところ、期待値していたサジェスト表示になりました。
