### ISSUE TITLE
カスタムURL、50文字を超えた部分が消える。

### ISSUE THREAD

**Issue by msyk5** [exceedone/exment#474]
**Describe the bug / バグの説明**
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
左メニューのカスタムＵＲＬ、入力したＵＲＬが50文字を超えた部分が消えてしまう。

**To Reproduce / 再現手順**
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
登録時は入力した通りに表示され、送信時にエラーにもならない。
登録後のリンク先と、再び設定画面を呼び出した際に50文字を超えた部分が消えている。

**Comment by hirossyi73** [comment]
@msyk5 
使用しているライブラリのデータベース設定で、URIの文字数が50文字までになっていました。

mysqlのデータベースに直接接続し、以下のSQLを実行いただけないでしょうか。
ALTER TABLE admin_menu MODIFY COLUMN uri varchar(2000);

(※後ほどデータベースの定義を修正する方法も、フレームワークLaravelだと用意されているのですが、どうも正常に動作しないことがあり、今回は別の方法での回避策とさせてください)

**Comment by msyk5** [comment]
SQL実行で改善されました。
ありがとうございます。

**Comment by norl-arch** [comment]
同様の問題が発生しましたが、SQLの直接実行で解決しました。

**Comment by hirossyi73** [comment]
https://exment.net/docs/#/ja/patch/menu_uri_length
こちらにて手順記載しております。
