### ISSUE TITLE
カスタムビュー設定_表示条件OR検索

### ISSUE THREAD

**Issue by Nemzo** [exceedone/exment#478]
**Describe the feature you'd like / 機能する機能の説明を行ってください**
A clear and concise description of what you want to happen. / あなたが何をしたいのかについての、明確で簡潔な説明を行ってください。

カスタムビュー設定_表示条件設定でOR検索を出来るようにしてもらいたい

条件項目-検索条件-〇〇
条件項目-検索条件-▲▲

現状＝〇〇 AND ▲▲
要望＝〇〇 OR ▲▲

**Additional context / その他**
Add any other context or screenshots about the feature request here. / 機能リクエストに関する他のコンテキストまたはスクリーンショットをここに追加します。

**Comment by hirossyi73** [comment]
v3.2.0で対応しました。
