### ISSUE TITLE
自動採番列における連番機能の追加

### ISSUE THREAD

**Issue by K2N7** [exceedone/exment#480]
**Describe the feature you'd like / 機能する機能の説明を行ってください**
フォーマットで指定した形式(年/月ごとなど)での連番機能を追加してほしい。

e.g)
${year}${month:2}-${0000} # =>  201911-0001, 201911-0002 ,201911-0003 ...
${year}-${00000} # =>  2019-00001, 2019-00002 ,2019-00003 ...           

**Additional context / その他**
なし

**Comment by A87da** [comment]
IF分での分岐（例えば会社コードが0010の場合には、ABを上2桁に付与した上で、自動採番、という連番機能も追加してほしい
