### ISSUE TITLE
カスタムフォームのリレーション時の自動計算

### ISSUE THREAD

**Issue by r-nkj** [exceedone/exment#485]
**Describe the bug / バグの説明**
1対多のリレーションを設定したテーブルで、
・親テーブルのカスタムフォームは子テーブルを[使用する]はオン
・[フォームをテーブル形式にする]はオフ
・子テーブルには自動計算カラムと、それとは別の+/-ボタンを使用するカラムがある

上記状態で、親テーブルのフォームでデータを編集（新規の場合も）する際に、子テーブルの2レコード目以降で、+/-ボタンを押下すると、1レコード目の値で自動計算される。

**To Reproduce / 再現手順**
**Error log / エラーログ **
**Screenshots / スクリーンショット**

**Additional context / その他**
v3.0.2 で試しています。
ご確認よろしくお願いします。

**Comment by r-nkj** [comment]
どうでもいいですが、
テンプレートのエラーログの見出しに、「エラーログ」と「**」の間にスペースがあるので、正しくマークアップされないようです・・・

**Comment by hirossyi73** [comment]
元々のライブラリとの関係性で問題がありそうです。調査します。

**Comment by hirossyi73** [comment]
@r-nkj 
![autocalc_test](https://user-images.githubusercontent.com/8457265/69772282-d609eb00-11d2-11ea-8993-5b53f2b97b9d.gif)

子テーブルで、n側でnumber(数値)とautocalc(number + 1の自動計算)の2列を追加したとき、現在(v3.0.4)ですと、このような挙動となっています。
列設定などの想定は、お間違い無いでしょうか？

**Comment by r-nkj** [comment]
![image](https://user-images.githubusercontent.com/37281291/69773316-db1c6980-11d5-11ea-8795-411a8d286e80.png)
autocaltにはnumber2 + 1の自動計算を設定しています。
この状態で、親テーブルか、子テーブルのnumber1と自動計算に関係のない+/-ボタンを押すと、次のようになります。
![image](https://user-images.githubusercontent.com/37281291/69773370-0737ea80-11d6-11ea-9c3e-6110575f1c7e.png)

**Comment by r-nkj** [comment]
子テーブルの2レコード目のnumber2に値を入力したときは、正しく計算されました。
その後、どこかしらの+/-ボタンで2レコード目以降の自動計算が全て1レコード目の計算結果になります。
v3.0.4へアップグレードしています。

**Comment by hirossyi73** [comment]
@r-nkj 
ありがとうございます、再現しました。調査します。

**Comment by hirossyi73** [comment]
対応しましたので、クローズいたします。
