### ISSUE TITLE
ダッシュボードで利用しているビューを削除するとレイアウトが崩れる

### ISSUE THREAD

**Issue by K2N7** [exceedone/exment#490]
**Describe the bug / バグの説明**
ダッシュボードで利用しているビューを削除すると画面レイアウトが崩れる。
Ver 3.0.4にて確認。

**To Reproduce / 再現手順**
ダッシュボードにデータ一覧 -> ビューを選択。
上記にて選択したビューを削除。
ダッシュボードにて「エラーが発生しました」のメッセージ出力。
対象ダッシュボードの編集ボタンを押下。
レイアウトが崩れる。

**Error log / エラーログ**
```
Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: Property [custom_table] does not exist on this collection instance. (View: /var/www/exment/vendor/exceedone/exment/resources/views/form/field/embeds.blade.php)
```

**Screenshots / スクリーンショット**
![exment_dashboardbox_1_edit](https://user-images.githubusercontent.com/3872118/69686127-0b92d380-1102-11ea-9021-2e03c69cf1d9.png)

**Additional context / その他**
対象ダッシュボードの削除操作は可能です。

**Comment by hirossyi73** [comment]
@K2N7 
修正完了しました、次リリースで対応いたします。

**Comment by K2N7** [comment]
対応ありがとうございます。
v3.0.5にて修正されていることを確認できました。
