### ISSUE TITLE
列種類がテキストエディタのカラムを必須項目にするとデータ登録できない

### ISSUE THREAD

**Issue by K2N7** [exceedone/exment#491]
**Describe the bug / バグの説明**
列種類がテキストエディタのカラムを必須項目にするとデータ登録できない

**To Reproduce / 再現手順**

1. 列種類がテキストエディタのカラム(必須項目)を任意のテーブルに追加
2. フォームより値を入力して送信ボタンを押下するも反応なし

**Error log / エラーログ**
なし

**Screenshots / スクリーンショット**
Chrome DevToolのConsole出力
![Screenshot_2019112718402243](https://user-images.githubusercontent.com/3872118/69712162-b4aeed80-1145-11ea-866c-67b48c9268d4.PNG)

**Additional context / その他**
v3.0.4

**Comment by hirossyi73** [comment]
@K2N7 
使用ライブラリの不具合のようなので、対応方法検討します。
https://github.com/tinymce/tinymce/issues/2584

**Comment by hirossyi73** [comment]
対応しましたので、クローズいたします。

※サーバーサイドでの必須チェックになります。
