### ISSUE TITLE
役割グループ設定の追加時にSTEP2へ移行できない

### ISSUE THREAD

**Issue by r-nkj** [exceedone/exment#492]
**Describe the bug / バグの説明**
/role_group/create だとSTEP2へ変遷できません。
/role_group/{#}/edit で開くと変遷できました。

**Additional context / その他**
v3.0.4 です

**Comment by hirossyi73** [comment]
@r-nkj 
一度、「役割グループ名(英数字)」「役割グループ表示名」といった情報を保存する必要があるので、新規作成時にSTEP2へ変遷できないのは仕様になります。
※次のステップが存在することを示すために、プログレスバーに「STEP1」「STEP2」を表示しています。

**Comment by r-nkj** [comment]
了解です。
確かに、そのまま変遷出来たらSTEP1とSTEP2に分ける必要ないですね・・・
