### ISSUE TITLE
ワークフローにて次の作業ユーザ欄が表示されない

### ISSUE THREAD

**Issue by K2N7** [exceedone/exment#498]
**Describe the bug / バグの説明**
ワークフローにて、実行可能ユーザを[アクションの実行ユーザが選択]に設定し、ワークフローを実行するも、次のユーザ欄が表示されない。

**To Reproduce / 再現手順**

1. 新規ワークフロー(テーブル専用)を新規作成
2. 作成ユーザが実行可能なアクションを追加
3. 実行可能ユーザを任意のユーザに設定したアクションを追加(特殊なアクションON)
4. 実行可能ユーザを[アクションの実行ユーザが選択]に設定したアクションを追加(特殊なアクションON)
5. 上記ワークフローを実行

上記3,4のワークフロー実行時に表示されるダイアログにて、作業ユーザ欄が空白で表示される。
3のワークフローでは、ワークフロー自体は正常に実行され、設定されたユーザにてアクションの実行は可能。
4のワークフローでは、次の作業ユーザが空白で実行され、ワークフローが止まる。(承認ユーザがどう設定されているか不明)

**Version / 発生バージョン**
V3.0.6

**Error log / エラーログ**
なし

**Screenshots / スクリーンショット**
![Screenshot_2019112914430826](https://user-images.githubusercontent.com/3872118/69846547-b1d40a00-12b7-11ea-8fdc-0be8d0366809.PNG)

**Additional context / その他**

**Comment by hirossyi73** [comment]
@K2N7 
特定のステータスに対するアクションが、「特殊なアクション」のみだった場合、ご連絡いただいた症状が発生していました。
次回リリースで対応いたします。

**Comment by hirossyi73** [comment]
@K2N7 
v3.0.8にて、該当箇所の修正を行いました。

**Comment by K2N7** [comment]
@hirossyi73 
対応ありがとうございます。
v3.0.8にて修正されていることを確認できました。
