### ISSUE TITLE
カスタムビューの表示条件で複数条件で AND,OR を使いたい

### ISSUE THREAD

**Issue by srm3852** [exceedone/exment#502]
**Describe the feature you'd like / 機能する機能の説明を行ってください**
A clear and concise description of what you want to happen. / あなたが何をしたいのかについての、明確で簡潔な説明を行ってください。

カスタムビューの表示条件についてお聞きします。
複数条件を設定するときに、AND , OR を利用した条件設定を可能にしていただきたい

**Additional context / その他**
Add any other context or screenshots about the feature request here. / 機能リクエストに関する他のコンテキストまたはスクリーンショットをここに追加します。

**Comment by hirossyi73** [comment]
#478 に集約するため、こちらはクローズします。
