### ISSUE TITLE
バックアップデータを使用して別環境にレストアできない

### ISSUE THREAD

**Issue by ganapati55** [exceedone/exment#526]
**Describe the bug / バグの説明**
新しいサーバーでExmentを新規に立ち上げ、別サーバーのExmentで保存したバックアップファイルをアップロードしてもレストアできない。
インポート⇒自動的にログアウト⇒再ログイン⇒特にインポート前と変わらず

**Version / 発生バージョン**
旧・新ともに3.0.14

代替案としてテンプレート移し替え、各テーブルごとにデータをエクスポート⇒インポートするしかないか？

**Comment by hirossyi73** [comment]
@ganapati55 
早急に確認させてください。

**Comment by hirossyi73** [comment]
@ganapati55 
ファイルをアップロードしてのリストア処理に問題がありました。
v3.0.16で対応したので、ご確認ください。

**Comment by ganapati55** [comment]
確認しました！問題ありません。ありがとうございました。
