### ISSUE TITLE
組織型のカラムにてデータ選択後にデータが消える

### ISSUE THREAD

**Issue by K2N7** [exceedone/exment#531]
**Describe the bug / バグの説明**
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
組織型のカラムにて値を選択すると、フォームがリセットされ値が消える。
一度値が消えた後は、「対象が見つかりません」と表示され、入力が不可となる。
値が消えるのはユーザ型、組織型のカラム。

**To Reproduce / 再現手順**
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

1. カスタムテーブルを作成。
2. 1行テキスト型、選択肢型、ユーザ型、組織型のカラムを追加。
3. 新規作成フォームを開く。
4. データを入力する。

**Version / 発生バージョン**
Please describe version. / ご利用のバージョンを記載してください。
v3.0.16

**Error log / エラーログ**
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。
なし

**Screenshots / スクリーンショット**
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。
![chrome-capture](https://user-images.githubusercontent.com/3872118/72857229-5f83f800-3d00-11ea-8d26-b7615376ce23.gif)

**Additional context / その他**
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by hirossyi73** [comment]
@K2N7 
v3.0.17にて対応しました。ご確認お願いします。

**Comment by K2N7** [comment]
対応ありがとうございます！
v3.0.17にて修正確認できました。
