### ISSUE TITLE
プラグインとしてStylesheetをアップしても有効にならない

### ISSUE THREAD

**Issue by ganapati55** [exceedone/exment#532]
**Describe the bug / バグの説明**
スタイルシートをアップしましたが有効になりません。
ヘッダ内を見るとアップしたCSSを読み込み後、Laravelのbootstrapのスタイルシートがいくつも読み込まれているのが原因のようです。

取り急ぎ !important を使用してしのいでいますができれば読み込み順を後にしていただければ大変助かります。

**To Reproduce / 再現手順**

**Version / 発生バージョン**
3.0.16

**Comment by hirossyi73** [comment]
@ganapati55 
ライブラリの読み込み順序に関しては、元のライブラリの修正が必要そうなので、少々検証などのお時間ください。
