### ISSUE TITLE
真偽値を表示条件にしているビューがあり、API経由でその真偽値の値をfalseからtrueに変更してもビューの表示結果に反映されない

### ISSUE THREAD

**Issue by KazuyukiSomeya** [exceedone/exment#536]
**Describe the bug / バグの説明**
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

テーブルTが検索インデックスを設定した真偽値型のカスタム列Bを持っています。
このテーブルTに対してビューVを作成し、表示条件に上記のカスタム列Bを設定しています。
つまり、カスタム列Bのtrue or falseによってビューVの表示結果を出し分けたいです。

このカスタム列Bの値をカスタムデータ情報更新API経由で変更しました。
https://exment.net/reference/ja/webapi.html#operation/put-value
このとき、
・**trueからfalseへ変更**した場合、上記ビューVの表示結果が変わります。（期待結果どおり）
・**falseからtrueへ変更**した場合、上記ビューVの表示結果が変わりません。（バグ？）
falseからtrueへ変更した場合でも表示結果が変わることが期待結果かと思います。

確認したことは以下になります。
・Postmanにて、カスタムデータ情報更新APIを使い真偽値のカスタム列Bが更新されていることを確認
・Web上から詳細画面・フォームにおいて真偽値のカスタム列Bが更新されていることを確認
・Web上のフォームから真偽値のカスタム列Bを更新（いったんfalseにして再度trueにしたあと送信）するとビューの表示結果が変わることを確認

**To Reproduce / 再現手順**
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
抽象的なので、スクショのところでお伝えします。

**Version / 発生バージョン**
Please describe version. / ご利用のバージョンを記載してください。
v3.0.17

**Error log / エラーログ**
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

**Screenshots / スクリーンショット**
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。
以下のスクショの前提として、上記説明の
・ テーブルT → equipment_management （機材運用テーブル）
・真偽値型のカスタム列B → can_useカスタム列 （利用可能カラム）
・ビューV → 機材運用テーブルの開発機材ビュー
に当たります。
また、can_useカスタム列がtrueの場合は開発機材ビューに表示される、falseの場合は表示されないのが期待結果です。
先頭の「管理名　PH-0001」のレコードのcan_useカスタム列をfalseからtrueに変更する際のスクショになります。

開発機材ビューの設定
![開発機材ビュー設定](https://user-images.githubusercontent.com/979443/73235398-b2165600-41d1-11ea-8a5b-a810138cee52.png)
開発機材ビューでは、カスタム列can_useのtrue or falseによって表示結果を出し分けたいです。

管理名　PH-0001のレコードの詳細（can_use== false）
![PH-0001_false](https://user-images.githubusercontent.com/979443/73235515-24873600-41d2-11ea-8a1e-a1f928c124eb.png)
利用可能(YES/NO)がcan_use(true/false)に相当します。

開発機材ビューでの表示
![機材運用一覧_false](https://user-images.githubusercontent.com/979443/73235356-7b404000-41d1-11ea-8578-65e9f24e1c33.png)
「管理名　PH-0001のレコード」のcan_useカスタム列がfalseなので、開発機材ビューには表示されていません。

Postmanでcan_useカスタム列をtrueに更新
![postman](https://user-images.githubusercontent.com/979443/73235684-c3ac2d80-41d2-11ea-8cd0-88c0bc3e38a7.png)

管理名　PH-0001のレコードの詳細（can_use== true）
![PH-0001_true](https://user-images.githubusercontent.com/979443/73235697-d6266700-41d2-11ea-9596-cbe2778afe81.png)
一覧やフォーム上では更新後の値が表示されています。
しかし、この状態で開発機材ビューを表示してみても「管理名　PH-0001」のレコードは表示されません。ー（★）

管理名　PH-0001のレコードの編集（can_use== true）
![PH-0001_編集](https://user-images.githubusercontent.com/979443/73235788-31585980-41d3-11ea-87f4-c49cba5d1b83.png)
表示はYESになっていますが、いったんNOにして再度YESにしたあと送信して更新します。
もしかしたら送信するだけでも良いかもしれません。

開発機材ビューでの表示
![機材運用一覧_true](https://user-images.githubusercontent.com/979443/73235836-65337f00-41d3-11ea-82f9-b7b63d177b35.png)
この段階で「管理名　PH-0001」のレコードは表示されるようになります。
本来であれば、APIで更新したあとのビュー表示（★）のタイミングで変わっていてほしいです。
上記手順でcan_useをtrueからfalseへ変更した場合は（★）のタイミングで変わっています。

**Additional context / その他**
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。
認識違いや設定方法の間違いがあれば、お手数ですがご教授ください。

**Comment by hirossyi73** [comment]
@KazuyukiSomeya 
コメント出来ておりませんでしたが、v3.0.18にて対応いたしました。
なお、今後APIから保存する値についての対応とさせてください。

**Comment by KazuyukiSomeya** [comment]
@hirossyi73 
v3.0.19にアップデートし、期待結果になっていることを確認できました。
ご対応いただきありがとうございました。
