### ISSUE TITLE
ビューごとに権限を設定できるようにしたい

### ISSUE THREAD

**Issue by oyama230** [exceedone/exment#537]
**Describe the feature you'd like / 機能する機能の説明を行ってください**
A clear and concise description of what you want to happen. / あなたが何をしたいのかについての、明確で簡潔な説明を行ってください。

#83のフォームと同様にビューにも、ビューごとの権限を設定できるようにしたい。

ひとつのテーブル内に一般グループより上位の権限者だけが入力・表示できる評価欄（カスタム列）を設けて
システムビューを一般グループ向けビューと上位の権限者向けビューに分けて一覧確認できるようにしたいが
ビューごとに権限を設定できないため、一般グループ権限者も上位の権限者用のビューをみることができる問題を解決したい。

**Additional context / その他**
Add any other context or screenshots about the feature request here. / 機能リクエストに関する他のコンテキストまたはスクリーンショットをここに追加します。

補足：EXMENT_USER_VIEW_DISABLED=trueでの運用を前提にしています。

**Comment by hirossyi73** [comment]
ユーザービュー(※ダッシュボード含む)を、他の方に共有させる、という形式で実装します。

**Comment by oyama230** [comment]
ご対応ありがとうございました。

再検討していただきたい箇所があります。

カスタムフォーム優先度設定とおなじく条件項目に「組織」「役割グループ」を
設定できるようにして欲しいのです。ご検討のほどよろしくお願いします。

**Comment by hirossyi73** [comment]
カスタムビュー＆ダッシュボード機能を追加しました。
※権限ごとの振り分けなどは、別途検討とさせてください。
