### ISSUE TITLE
プラグインに権限を設定できるようにしたい

### ISSUE THREAD

**Issue by K2N7** [exceedone/exment#538]
**Describe the feature you'd like / 機能する機能の説明を行ってください**
A clear and concise description of what you want to happen. / あなたが何をしたいのかについての、明確で簡潔な説明を行ってください。
トリガープラグインや、ドキュメントプラグインでボタン押下により動作するプラグインについて、権限設定により実行可否 or 表示非表示の制御したいです。
現状では誰でも実行できてしまうため、プラグイン内で独自制御を実装せざるを得ない状況です。

**Additional context / その他**
Add any other context or screenshots about the feature request here. / 機能リクエストに関する他のコンテキストまたはスクリーンショットをここに追加します。

**Comment by hirossyi73** [comment]
v3.2.0で対応しました。
https://exment.net/docs/#/ja/plugin
