### ISSUE TITLE
リストアできない

### ISSUE THREAD

**Issue by ganapati55** [exceedone/exment#544]
**Describe the bug / バグの説明**
Xamppで動かしているExmentに関してリストアができません。
リストア動作完了してログインしなおしても特に変化がありません。

**To Reproduce / 再現手順**
OS　Windows10 Home　
①Xamppを使用したExmentの手順通りに構築
②バックアップ実行
③カスタムテーブルを新規作成
④バックアップからリストア
⑤ログインしなおし
⑥変化なし
※別の環境下で作成したバックアップデータを読み込んでも同じでした。

**Version / 発生バージョン**
3.0.17

**Comment by ganapati55** [comment]
コマンドプロンプトで見てみましたところ
'mysql' is not  recognized as an internal or external command,operable program or batch file.
と出ます。

**Comment by hirossyi73** [comment]
こちらの手順に従い、Pathを通してください。

Windowsの場合
https://www.dbonline.jp/mysql/install/index8.html

Linuxの場合
http://www.php-mysql-linux.com/mysql/mysql_esta/mysql-pass-101002/

**Comment by ganapati55** [comment]
ありがとうございます。Xampp環境のため以下のようにPathを通したところコマンドプロンプト上でのエラー表示はなくなりました。
C:\xampp\mysql\bin

しかしながらやはりバックアップからのリストアはできないようです。Windows上ではできない設定でしょうか？

**Comment by ganapati55** [comment]
3.1.1に更新しましたらリストアできるようになりました。ありがとうございました。
