### ISSUE TITLE
マニュアルの自動採番のパラメータ変数について

### ISSUE THREAD

**Issue by akiatori** [exceedone/exment#562]
**Describe the bug / バグの説明**
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
Webマニュアルの自動採番のパラメータ変数の例の中に
${y:2}${m}${d}-${id:4} → 180809-0100
と記載されていますが、実際に実行すると、20180809-0100と年部分が4桁になってしまいます。
尚、変数一覧の「${y} or ${year}」には月のように桁数指定がありませんので、2桁対応はされていないのではないでしょうか？
出来ましたら、2桁に対応いただければ助かります。

**To Reproduce / 再現手順**
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

**Version / 発生バージョン**
Please describe version. / ご利用のバージョンを記載してください。
 v3.1.1

**Error log / エラーログ**
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

**Screenshots / スクリーンショット**
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

**Additional context / その他**
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by hirossyi73** [comment]
@akiatori 
v3.1.2にて、「now」パラメータに対応しました。
それまでマニュアルに記載していた形式と異なりますが、以下のように設定を行ってください。
${now:y}

https://exment.net/docs/#/ja/params

**Comment by akiatori** [comment]
v3.1.2にて動作確認しました。早速の対応ありがとうございました。
