### ISSUE TITLE
カスタム列の不具合

### ISSUE THREAD

**Issue by akiatori** [exceedone/exment#563]
**Describe the bug / バグの説明**
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
カスタム列に以下の列を登録した場合、実際にデータを追加しようとすると、[送信]ボタンを押してもエラーも表示されなければ、画面も変わらず、データも追加されていない。

列種類：日付と時刻
必須：YES
１度のみ入力：YES
作成時に実行日時を登録：YES

**To Reproduce / 再現手順**
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

必須：NOにすれば問題なくデータが追加されます。
「保存時に実行日時を登録」もしくは、「作成時に実行日時を登録」をYESにした際は、必須を自動的に無効にして、入力不可にした方が良さそうです。

**Version / 発生バージョン**
Please describe version. / ご利用のバージョンを記載してください。
V3.1.1

**Error log / エラーログ**
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

**Screenshots / スクリーンショット**
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

**Additional context / その他**
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by hirossyi73** [comment]
@akiatori 
v3.1.2にて対応しました。

**Comment by akiatori** [comment]
v3.1.2にて動作確認しました。早速の対応ありがとうございました。
