### ISSUE TITLE
docurainプラグイン導入時にパラメータ設定前に他端末で画面遷移するとエラーになる

### ISSUE THREAD

**Issue by phssakaigawa** [exceedone/exment#565]
**Describe the bug / バグの説明**
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

プラグインのアップロード後、パラメータ設定をせずに
画面遷移（マスター管理ー＞ユーザー）してしまうと、エラー画面が表示される
プラグイン追加作業時にメンテ予定を知らずに操作したユーザー端末でエラー画面が表示
プラグインにDocurainのキーを登録したところ、エラーメッセージが回避された

**To Reproduce / 再現手順**
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

プラグインのアップロード後、パラメータ設定をせずに
画面遷移（マスター管理ー＞ユーザー）

**Version / 発生バージョン**
Please describe version. / ご利用のバージョンを記載してください。

exment: v3.1.1
Docurain プラグイン v1.0.0

**Error log / エラーログ**
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

[laravel.log](https://github.com/exceedone/exment/files/4269751/laravel.log)
ファイルとして該当箇所だけ切り出して添付

**Screenshots / スクリーンショット**
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

取り忘れてしまいましたが、エラー内容に対してのデバッグウィンドウ表示でした

**Additional context / その他**
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

いつもありがとうございます。

画面遷移中にdocurainのボタンを描画するかなどを判定する際にdocurainプラグイン周りを読み込んで処理しているのか想像していますが、Null判定を強化いただけると間違いないのではないか、と感じましたので念の為情報連携です。

**Comment by hirossyi73** [comment]
@phssakaigawa 
v3.1.2で修正を行いました。
