### ISSUE TITLE
ワークフローの実行可能ユーザーに選択した、組織に紐づけた役割グループの設定内容が継承されない

### ISSUE THREAD

**Issue by oyama230** [exceedone/exment#569]
**Describe the bug / バグの説明**
ワークフローの実行可能ユーザーに組織を選択した場合は
組織に紐づけた役割グループの設定内容を受け継ぐことを期待していましたが
現状は継承されていないように見えます。

こちらの仕様誤認の可能性もありますが、検証をお願いします。

**To Reproduce / 再現手順**
・ユーザーに「ユーザーＡ」を追加。
・役割グループに「リーダーグループ」を追加して「ユーザーＡ」を選択。
・組織に「リーダー」を追加してユーザー選択なし
　役割グループに「リーダーグループ」を選択。
・ワークフロー「とあるアクション」の実行可能ユーザーの組織欄に「リーダー」を選択。
・ログインユーザー「ユーザーＡ」で、ワークフロー「とあるアクション」が発火する
　状況下でデータを開いても、アクションボタンは表示されない。

　なお組織「リーダー」のユーザー選択に「ユーザーＡ」を紐づけている場合は
　アクションボタンが表示される。

**Version / 発生バージョン**
 v3.1.3

**Error log / エラーログ**
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

**Screenshots / スクリーンショット**
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

**Additional context / その他**
サイト基本情報の組織設定
組織階層設定(役割グループ)　：所属組織の親子階層を含める
組織階層設定(データ)　　　　：自分の所属組織のみ
カスタムデータ共有設定　　　：ログインユーザーのみ

**Comment by hirossyi73** [comment]
@oyama230 
役割グループは、あくまでも「特定の操作する権限を設定し、その操作を実行できる組織もしくはユーザーを紐付ける」という役割であり、「役割グループに組織を紐付ければ、その役割グループに所属するユーザーも、組織に所属していることになる」という用途とは異なります。

**Comment by oyama230** [comment]
ご回答ありがとうございました。
組織と役割グループを混在させないよう
設定の再検討を行います。
