### ISSUE TITLE
組織階層に組織名が表示されなくなった

### ISSUE THREAD

**Issue by oyama230** [exceedone/exment#570]
**Describe the bug / バグの説明**
アップデートした後から
組織階層に組織名が表示されなくなった。

前のバージョンまで表示されていました。

**Version / 発生バージョン**
 v3.1.3

**Screenshots / スクリーンショット**
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。
![組織表示されない](https://user-images.githubusercontent.com/49295597/75862730-b83bca00-5e42-11ea-849a-595a1e54c931.png)

**Comment by hirossyi73** [comment]
@oyama230 
失礼しました、v3.1.4にて修正しましたのでご確認ください。

**Comment by oyama230** [comment]
ご対応ありがとうございました。
修正されていることを確認しました。
