### ISSUE TITLE
Excelインポートの時のレコード数制限？

### ISSUE THREAD

**Issue by ENEOS33** [exceedone/exment#572]
**Describe the bug / バグの説明**
テーブルデータをExcelからインポートするとき20000レコードあるが、
1830レコードでインポートが終了する。
繰り返しインポートすることで約1500レコードずつ増やすことは可能だか
1500ﾚｺｰﾄﾞに10分程度必要とする
20000レコードに1時間以上を必要とする

**To Reproduce / 再現手順**
ウインドウズ１０にXAMPPサーバーを用意しインストールした環境で発生する

**Version / 発生バージョン**
V3.1.1

**Error log / エラーログ**
エラーは出ないので仕様でしょうか？

**Additional context / その他**
もし、設定ファイルの変更で対応可能であれば教えていただきたいです

**Comment by hirossyi73** [comment]
@ENEOS33 
v3.1.7で、一度のインポートでの制限を1000件までと設定させていただきました。
画面からの実行ですと、メモリ量やタイムアウトの問題があり、限界があります。

※今後、大量データのインポートをバックグラウンドで実行する方法を検討させてください。
