### ISSUE TITLE
データ検索時に選択肢(他のテーブルの値一覧から選択)も検索出来るように改善

### ISSUE THREAD

**Issue by Nemzo** [exceedone/exment#576]
**Describe the feature you'd like / 機能する機能の説明を行ってください**
A clear and concise description of what you want to happen. / あなたが何をしたいのかについての、明確で簡潔な説明を行ってください。

データ検索時に選択肢(他のテーブルの値一覧から選択)列に
なっている箇所は検索結果として現れない
また、全件検索の場合、データ参照元テーブルの値はヒットするが、
参照先テーブルの値はヒットしないため
検索出来るように改善頂きたい。

**Additional context / その他**
Add any other context or screenshots about the feature request here. / 機能リクエストに関する他のコンテキストまたはスクリーンショットをここに追加します。

**Comment by tkpontas** [comment]
機能改善されるまでの間で代用するのであれば
隠しフィールド機能・データ連動設定を使って、選択肢（他のテーブルの値一覧から選択）が選ばれたときに、別カスタム列に内容を転記し、そのカスタム列に検索インデックスを与えておけば、検索自体は可能になるかと思います。

**Comment by tkpontas** [comment]
とりあえず、改善されるまでの代用策としては
隠しフィールド機能とデータ連動設定を活用し、選択肢(他のテーブルの値一覧から選択)が選択されたときに隠しフィールドに文字列をコピーさせた後、その隠しフィールドを検索インデックスをONにすることによって、無駄にカスタム列を消費してしまいますが、全体検索から検索自体は可能となります。もしそれをご存じで要望を出されたのであれば、素人が失礼しました。

**Comment by hirossyi73** [comment]
@Nemzo 
issueありがとうございます。

現状、データ検索時に選択肢(他のテーブルの値一覧から選択)が検索結果に引っかからない理由として、
参照元のテーブルには、参照先のidのみが保存されているためです。

例：契約→顧客テーブルと言う参照を行っていた場合、
契約テーブルには、顧客テーブルのIDのみがデータとして保存されている。そのため、顧客名などをフリーフォーマットに入れて検索しても、契約テーブル内に顧客名は存在しないため、ヒットしない

対応するのであれば、契約テーブルでの検索前に、一度顧客テーブルで検索を行ってから、ヒットしたIDをすべて抽出して取得する（もしくはなんらかのjoin）、という処理の実装が必要です。

**Comment by hirossyi73** [comment]
@Nemzo 

こちらのブランチで対応予定です。
https://github.com/exceedone/exment/tree/hotfixfeature/search_column

**Comment by hirossyi73** [comment]
@Nemzo 
v3.1.9で対応しました。

**Comment by Nemzo** [comment]
ご対応ありがとうございます。

**Comment by Nemzo** [comment]
v3.1.9にてご対応頂いた更新の確認になりますが、
契約テーブル_顧客ID(001)(他のテーブルの値一覧から選択)⇒顧客テーブル_顧客ID(001)を参照、
契約テーブル_顧客IDはリンク状態になっている状態です。
この状態で”001”と検索実施した場合に、顧客IDの値(001)が検索結果に表示される認識で間違いないでしょうか。

**Comment by hirossyi73** [comment]
@Nemzo 
再オープンしました。

現在の仕様ですと、「他のテーブルの値一覧から選択」の場合、見出しで設定されている値に合わせて、検索を行います。
例えば「顧客」テーブルの見出し列が「顧客ID」になっていれば、契約テーブルの一覧画面の検索フォームで「001」と入力することで、検索できるようになります。

画面に表示されている文言通りに検索フォームに入力することで、検索を実施できるようになる・・・という仕様になります。

**Comment by hirossyi73** [comment]
@Nemzo 
こちら再度クローズします。
