### ISSUE TITLE
ビューで表示される写真サイズの変更設定

### ISSUE THREAD

**Issue by akiatori** [exceedone/exment#582]
**Describe the feature you'd like / 機能する機能の説明を行ってください**
A clear and concise description of what you want to happen. / あなたが何をしたいのかについての、明確で簡潔な説明を行ってください。
ビューの列に写真が表示されますが、サイズの設定が出来ないため、表示される写真のサイズがバラバラであったり、サイズが大きすぎて表示できる行数が少ない場合があります。
ビューの設定時に列を写真を選択した場合、写真のサイズを設定できる項目があれば有難いです。
例えば、縦や横のピクセルサイズを指定出来たり、大・中・小と3パターン指定することができ、この場合はシステム設定であらかじめピクセルサイズを設定出来れば最高です。

同じ、フレームワーク(laravel)を使用しているIT資産管理システム(Snipe-IT)では、IT資産の写真を良い感じのサイズで表示しており、ビジュアル的に見やすくなっています。
ご検討のほどよろしくお願いします。

**Additional context / その他**
Add any other context or screenshots about the feature request here. / 機能リクエストに関する他のコンテキストまたはスクリーンショットをここに追加します。

**Comment by hirossyi73** [comment]
Snipe-ITは初めて知りました。参考にさせてください。
