### ISSUE TITLE
Web APIを使用したファイル属性列のデータをコピーできない件

### ISSUE THREAD

**Issue by oyama230** [exceedone/exment#585]
**Describe the bug / バグの説明**

権限の関係でWeb APIを使いテーブルＡをテーブルＢにデータコピーを実施する必要があり
以下の処理を作成します。

処理手順
テーブルＡからカスタムデータ検索で抽出したデータを、新規作成でテーブルＢに追加する。

ファイル属性の列は"テーブル名/exmentでリネームしたファイル名"で抽出されるため
取得情報をそのままセットして、テーブルＢを新規作成するとエラーになる。

Web APIで抽出したデータで、別テーブルを新規作成できるように、exmentで管理済の
ファイル・画像ファイルを別テーブルにリンクできるようにする必要があると感じます。
仕様の不備のバグと考え、報告させていただきます。

**Version / 発生バージョン**
Version   v3.1.5

**Comment by hirossyi73** [comment]
@oyama230 
APIのカスタムデータ取得で、パラメータに「valuetype=text」を追加しました。
https://exment.net/reference/ja/webapi.html#operation/get-values

こちらのパラメータを追加すると、ファイル・画像列で、ファイルダウンロード用のURLを取得できます。
そのURLをAPIを実行し、ファイルをダウンロードしてください。
https://exment.net/reference/ja/webapi.html#operation/get-files

**Comment by oyama230** [comment]
ご対応ありがとうございます。

v3.1.7にアップデートして確認しましたが
WebAPIで取得したURLには拡張子が抜け落ちてフルパスになっていません。


バグレポートの伝え方が整理できてなく申し訳ありません。

本来伝えたい内容は
テーブルA内のファイル属性を持つ列から
テーブルB内のファイル属性を持つ列に
WebAPIを使ってコピーしたい。

同じファイルをサーバーに複数持たせたくないので
テーブルAにあるファイル情報のリンクをテーブルBのファイル情報にセットしたい。

以上の2点でした。

ご検討のほど、よろしくおねがいいます。

**Comment by hirossyi73** [comment]
@oyama230 
本来ご要望いただいている内容としては、「添付ファイルを複数データで共有」のような機能というということは、理解しておりました。
ですが、この機能を実装するとなると、テーブル構造を大きく変更・改修などしないといけないので、実装は現状難しいです。

そのため、データを別テーブルにコピーをする場合、ファイルをダウンロード・再度登録、という流れでお願いいたします。

**Comment by oyama230** [comment]
ご連絡ありがとうございます。

本件は
WebAPIで取得したURLに拡張子を含まれることを確認してクローズとさせていただきます
引き続きのご対応をお願いします。

余談です。社内だけの環境として用意しているので、お行儀は良くないのですが
storege/app/admin以下のディレクトリにアクセスできるよう、WEBサーバーに設定を追加し
テーブルBの項目をファイル属性からURL属性に修正することでWebAPIを使って
自動的にデータをコピーできるよう対応できました。ご検討ありがとうござました。
