### ISSUE TITLE
ワークフロー（現在のステータス）をビュー表示した際に鍵アイコンがHTMLタグになってしまう

### ISSUE THREAD

**Issue by tkpontas** [exceedone/exment#586]
バグの説明**
ワークフローにおいて、現在のステータスをビューに追加した際に
設定上、データロックをかけた項目において、本来鍵アイコンが表示されるべきところ
HTMLタグがそのまま出力されてしまっている。

再現手順**
ワークフロー設定において、任意のステータスにデータロックをONにする。
フローを進行させて、データロックを行う。
ビュー設定から現在のステータスをビューに追加する。
該当ビューを表示させる。

発生バージョン**
Ver.3.1.6

エラーログ**
特になし。

**Screenshots / スクリーンショット**
![image](https://user-images.githubusercontent.com/60683813/77371444-9fba3200-6da6-11ea-8bec-a19274db3670.png)

**Additional context / その他**
ワークフローデモサイトには、きちんと鍵マークが表示されていたので
バグなのか、私の環境だけなのか原因の切り分けはできていません。

**Comment by hirossyi73** [comment]
@tkpontas 
最新バージョンで現象確認しました。近日修正します。

**Comment by hirossyi73** [comment]
@tkpontas 
アップデート前に修正が必要な場合、以下の対応をお願いしてもよろしいでしょうか。

vendor\exceedone\exment\src\ColumnItems\WorkflowItem.php
79～81行目

``` php
// before
elseif(is_string($val)){
    return $html ? esc_html($val) : $val;
}

// after
elseif(is_string($val)){
    return $val;
}
```

**Comment by tkpontas** [comment]
上記対応しましたところ、正常に鍵アイコンが表示されたことを確認しました。
早速のご対応ありがとうございます。

**Comment by hirossyi73** [comment]
v3.1.7にて対応。
