### ISSUE TITLE
隠しフィールド設定のフォーム項目における不具合について

### ISSUE THREAD

**Issue by oyama230** [exceedone/exment#588]
**Describe the bug / バグの説明**
カスタムフォーム設定ページに
表示専用にしていない、隠しフィールド設定のフォーム項目があると
編集ページを開けずにエラーページを表示するです。ご確認ください。

**Version / 発生バージョン**
v3.1.7

**Additional context / その他**
以下にエラーページに表示されてる内容を添付します。

エラーメッセージ
Method Encore\Admin\Form\Field\Hidden::displayText does not exist.

エラー詳細
<textarea name="trace" class="form-control trace" rows="5" placeholder="入力 エラー詳細" disabled="1" >#0 /opt/www/exment/vendor/exceedone/exment/src/ColumnItems/CustomItem.php(267): Encore\Admin\Form\Field-&gt;__call(&#039;displayText&#039;, Array)
#1 /opt/www/exment/vendor/exceedone/exment/src/ColumnItems/CustomItem.php(252): Exceedone\Exment\ColumnItems\CustomItem-&gt;getCustomField(&#039;Encore\\Admin\\Fo...&#039;, Array, NULL)
#2 /opt/www/exment/vendor/exceedone/exment/src/Controllers/CustomValueForm.php(267): Exceedone\Exment\ColumnItems\CustomItem-&gt;getAdminField(Object(Exceedone\Exment\Model\CustomFormColumn))
#3 /opt/www/exment/vendor/exceedone/exment/src/Controllers/CustomValueForm.php(105): Exceedone\Exment\Controllers\CustomValueController-&gt;getCustomFormColumns(Object(Encore\Admin\Form), Object(Exceedone\Exment\Model\CustomFormBlock), Object(Exceedone\Exment\Model\Class_935ef6fbc561a283ce9b))
#4 /opt/www/exment/vendor/exceedone/exment/src/Controllers/CustomValueController.php(191): Exceedone\Exment\Controllers\CustomValueController-&gt;form(&#039;3&#039;)
#5 [internal function]: Exceedone\Exment\Controllers\CustomValueController-&gt;edit(Object(Illuminate\Http\Request), Object(Encore\Admin\Layout\Content), &#039;kpn&#039;, &#039;3&#039;)
#6 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#7 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller-&gt;callAction(&#039;edit&#039;, Array)
#8 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\Routing\ControllerDispatcher-&gt;dispatch(Object(Illuminate\Routing\Route), Object(Exceedone\Exment\Controllers\CustomValueController), &#039;edit&#039;)
#9 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\Routing\Route-&gt;runController()
#10 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(665): Illuminate\Routing\Route-&gt;run()
#11 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /opt/www/exment/vendor/exceedone/laravel-admin/src/Middleware/Session.php(21): Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Encore\Admin\Middleware\Session-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#14 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 /opt/www/exment/vendor/exceedone/laravel-admin/src/Middleware/Permission.php(42): Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#16 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Encore\Admin\Middleware\Permission-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#17 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 /opt/www/exment/vendor/exceedone/laravel-admin/src/Middleware/Bootstrap.php(15): Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Encore\Admin\Middleware\Bootstrap-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 /opt/www/exment/vendor/exceedone/exment/src/Middleware/LogOperation.php(39): Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\Exment\Middleware\LogOperation-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 /opt/www/exment/vendor/exceedone/laravel-admin/src/Middleware/Pjax.php(24): Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Encore\Admin\Middleware\Pjax-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /opt/www/exment/vendor/renatomarinho/laravel-page-speed/src/Middleware/PageSpeed.php(28): Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#28 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): RenatoMarinho\LaravelPageSpeed\Middleware\PageSpeed-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /opt/www/exment/vendor/renatomarinho/laravel-page-speed/src/Middleware/PageSpeed.php(28): Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): RenatoMarinho\LaravelPageSpeed\Middleware\PageSpeed-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /opt/www/exment/vendor/renatomarinho/laravel-page-speed/src/Middleware/PageSpeed.php(28): Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): RenatoMarinho\LaravelPageSpeed\Middleware\PageSpeed-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /opt/www/exment/vendor/exceedone/exment/src/Middleware/Bootstrap.php(21): Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#37 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\Exment\Middleware\Bootstrap-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /opt/www/exment/vendor/exceedone/exment/src/Middleware/Morph.php(20): Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#40 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\Exment\Middleware\Morph-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /opt/www/exment/vendor/exceedone/exment/src/Middleware/AuthenticatePasswordLimit.php(23): Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#43 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\Exment\Middleware\AuthenticatePasswordLimit-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /opt/www/exment/vendor/exceedone/exment/src/Middleware/Authenticate2factor.php(23): Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#46 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\Exment\Middleware\Authenticate2factor-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 /opt/www/exment/vendor/exceedone/exment/src/Middleware/Authenticate.php(39): Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#49 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\Exment\Middleware\Authenticate-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 /opt/www/exment/vendor/exceedone/exment/src/Middleware/Initialize.php(56): Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#52 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\Exment\Middleware\Initialize-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 /opt/www/exment/vendor/exceedone/exment/src/Middleware/IpFilterBase.php(27): Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#55 /opt/www/exment/vendor/exceedone/exment/src/Middleware/WebIPFilter.php(15): Exceedone\Exment\Middleware\IpFilterBase-&gt;handleBase(Object(Illuminate\Http\Request), Object(Closure), &#039;web_ip_filters&#039;)
#56 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\Exment\Middleware\WebIPFilter-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#57 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 /opt/www/exment/vendor/exceedone/exment/src/Middleware/Browser.php(21): Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#59 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Exceedone\Exment\Middleware\Browser-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#60 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#62 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Routing\Middleware\SubstituteBindings-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#63 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#64 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(68): Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#65 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#66 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#67 /opt/www/exment/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#68 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\View\Middleware\ShareErrorsFromSession-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#69 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#70 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#71 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Session\Middleware\StartSession-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#72 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#73 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#74 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#75 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#76 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#77 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Cookie\Middleware\EncryptCookies-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#78 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#79 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#80 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\Pipeline\Pipeline-&gt;then(Object(Closure))
#81 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(642): Illuminate\Routing\Router-&gt;runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#82 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(608): Illuminate\Routing\Router-&gt;runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#83 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Router.php(597): Illuminate\Routing\Router-&gt;dispatchToRoute(Object(Illuminate\Http\Request))
#84 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router-&gt;dispatch(Object(Illuminate\Http\Request))
#85 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel-&gt;Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#86 /opt/www/exment/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#87 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\Proxy\TrustProxies-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#88 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#89 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#90 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#91 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#92 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#93 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#94 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#95 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#96 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\ValidatePostSize-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#97 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#98 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#99 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#100 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#101 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#102 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline-&gt;then(Object(Closure))
#103 /opt/www/exment/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel-&gt;sendRequestThroughRouter(Object(Illuminate\Http\Request))
#104 /opt/www/exment/public/index.php(55): Illuminate\Foundation\Http\Kernel-&gt;handle(Object(Illuminate\Http\Request))
#105 {main}</textarea>

**Comment by oyama230** [comment]
設定のしかたに気を付ければ良いだけの問題ですが
念のため報告しました。

**Comment by hirossyi73** [comment]
@oyama230 
ありがとうございます。v3.1.8にて修正しました。

**Comment by oyama230** [comment]
v3.1.8にてエラーの出ないことを確認しました。
ご対応ありがとうございました。
