### ISSUE TITLE
docker-compose対応

### ISSUE THREAD

**Issue by dev-hayash** [exceedone/exment#589]
**Describe the feature you'd like / 機能する機能の説明を行ってください**
A clear and concise description of what you want to happen. / あなたが何をしたいのかについての、明確で簡潔な説明を行ってください。

個人でymlを作成・公開されている方もいらっしゃいますが、できれば```公式```に対応して頂けたらと思います。

**Comment by hirossyi73** [comment]
https://exment.net/docs/#/ja/install_docker
対応しました。
