### ISSUE TITLE
カスタムフォーム優先度設定ページにおいて組織を条件にした場合に選択肢を正しく表示できない

### ISSUE THREAD

**Issue by oyama230** [exceedone/exment#593]
**Describe the bug / バグの説明**
カスタムフォーム優先度設定ページの条件項目に「組織」を選択した場合
選択肢に組織を表示しないで「対象が見つかりません」と表示される。

送信して編集アイコンで開きなおすと、選択肢に組織を表示するようになる。

**Comment by oyama230** [comment]
v3.1.9にアップデートしましたが
選択肢に組織は表示されませんでした。

v3.1.10以降の対応になるのでしょうか？

**Comment by hirossyi73** [comment]
@oyama230 
こちらに表示されている組織は、そのテーブルにアクセスできる権限をもつ組織が表示されます。
v3.1.8以前では、画面読み込み時はその制御が出来ておらず、「+新規」ボタンをクリックした時に表示される組織リストでは、正常に制御しておりました。
v.3.1.9にて、画面読み込み時にも、そのテーブルにアクセスできる権限をもつ組織のみ表示するようになっております。

該当の組織が、対象のカスタムテーブルにアクセスする権限があるか、ご確認いただけないでしょうか。

**Comment by oyama230** [comment]
組織・ユーザー・役割グループのコンセプトを
なんとなく理解できたと思います。

確認時点の設定は
ユーザーに役割グループを紐づけしているので
組織にはあえてユーザーだけを紐づけるように設定してありました。

ユーザー単体ではアクセスする権限はあるけれどユーザーの属する組織から見ると
権限はないという考えかたですね。

組織の選択肢を確認できましたので、本件をcloseします。
ご対応ありがとうございました。
