### ISSUE TITLE
V3.1.9 アップデート適用後、ログインページにアクセスできずエラーページを表示する

### ISSUE THREAD

**Issue by oyama230** [exceedone/exment#602]
**Describe the bug / バグの説明**
V3.1.9のアップデートした後
EXMENT設定値のEXMENT_USE_CACHEを有効の状態で
ログインページにアクセスするとexceptionが発生する。

EXMENT_USE_CACHEを無効に変更して
サービスの再起動後、正常にログインページを表示できる。

**Version / 発生バージョン**
V3.1.9 

**Error log / エラーログ**
ErrorException (E_WARNING)
file_put_contents(/hoge/www/exment/storage/framework/cache/data/c7/b7/c7b76b68942fd04f1af560ac11a34850a9db1cd9): failed to open stream: Permission denied

※excepton メッセージを添付します。

**Comment by hirossyi73** [comment]
V3.1.9にアップデートした後で、はじめてEXMENT_USE_CACHEを有効にしたということでしょうか？
もしくは、以前よりEXMENT_USE_CACHEを使用していて、V3.1.9ではじめて発生ということでしょうか。

エラーログを見る限りですと、Laravelフレームワークとして、cacheにアクセス出来ていなさそうです。
Webサーバー(Apacheとします)の実行ユーザーとして、以下のフォルダにが追加されているかどうか、ご確認いただけないでしょうか。
/hoge/www/exment/storage/framework/cache

※参考
https://qol-kk.com/wp2/blog/2019/03/13/post-1149/

**Comment by oyama230** [comment]
ご依頼の件、確認結果をお知らせします。

EXMENT_USE_CACHEの有効化はV3.1.8の時点で実施し
V3.1.9にアップデートするまでは問題なく動作していました。

/hoge/www/exment/storage/framework/cacheは
Apacheの実行ユーザーでパーミッションは777です。

ただしcache配下のdataフォルダは
Apacheの実行ユーザーでパーミッション744です。

**Comment by hirossyi73** [comment]
@oyama230 
ありがとうございます。
今回の件は、使用しているフレームワークの問題ということもあり、的確な解決方法をお出しすることが難しく、何回かお試し頂く必要があるかもしれません。
その点ご了承いただければ幸いです。

以下のコマンドで、キャッシュを削除いただき、再度ページ表示をお願いしてもよろしいでしょうか。
https://qiita.com/Ping/items/10ada8d069e13d729701

**Comment by oyama230** [comment]
.envのキャッシュ設定を無効⇒有効に修正して
キャッシュクリアのコマンド（php artisan cache:clear）を実行。

キャッシュファイルの削除を確認後、サービスを再起動すると
ログインページにアクセスできました。

V3.1.10へのアップデートはキャッシュ設定を無効で実施したので
問題の発生環境とは違う状況の可能性もあり
解決できているか判断はできないと考えます。

このままキャッシュ有効の環境でテスト運用して
次回のバージョンアップで再検証します。

**Comment by hirossyi73** [comment]
@oyama230 
ありがとうございます、非常に助かります。
こちらも、キャッシュを有効にした上でアップデートなど、複数の検証環境で試してみることで、再現するか確認を取っていきます。

**Comment by oyama230** [comment]
v3.1.11適用後も変わらず
キャッシュ有効でログインページにアクセスするとexceptionが発生し
無効にするとログインページを表示できました。

過去のキャッシュが悪さをしているようなので
キャッシュ無効の設定で運用を検討します。


Version / 発生バージョン
v3.1.11


Error log / エラーログ
ErrorException (E_WARNING)
file_put_contents(/hoge/www/exment/storage/framework/cache/data/c7/b7/c7b76b68942fd04f1af560ac11a34850a9db1cd9): failed to open stream: Permission denied

**Comment by hirossyi73** [comment]
ありがとうございます。お手数おかけします。
・どんな環境でも、キャッシュ有効時に、アップデート後にエラーが発生するか
・エラーが発生する場合、アップデート実施後にキャッシュを削除する処理を追加した場合に回避できるのか

これらについて調査させてください。

**Comment by oyama230** [comment]
v3.1.12アップデート適用後、問題なくexmentにログインできるようになりました。

確認手順
.envファイルをキャッシュ有効に変更し
exmentをしばらく利用しキャッシュのタイムスタンプの
更新を確認後、v3.1.12へのアップデートを実施。
exmentに問題なくログインできるようになりました。

ご対応ありがとうございました。

**Comment by hirossyi73** [comment]
@oyama230 
ありがとうございます。記載抜けておりましたが、3.1.12より、アップデート時にキャッシュ有効設定になっていたら、すべてのキャッシュを削除する処理を自動実行するようにしています。
