### ISSUE TITLE
ダッシュボードにグループダッシュボードの追加

### ISSUE THREAD

**Issue by y-hayama** [exceedone/exment#603]
現在ダッシュボードにシステムダッシュボードとユーザダッシュボードがありますが、ここにグループで共有できるダッシュボードの追加をお願いしたいです

**Comment by hirossyi73** [comment]
[ダッシュボードの共有](https://exment.net/docs/#/ja/dashboard?id=%e3%83%80%e3%83%83%e3%82%b7%e3%83%a5%e3%83%9c%e3%83%bc%e3%83%89%e3%81%ae%e5%85%b1%e6%9c%89)機能をv3.3.0より追加しましたので、こちらで代用をお願いいたします。
