### ISSUE TITLE
カスタム列の「選択肢 (他のテーブルの値一覧から選択)」について

### ISSUE THREAD

**Issue by akiatori** [exceedone/exment#613]
**Describe the feature you'd like / 機能する機能の説明を行ってください**
A clear and concise description of what you want to happen. / あなたが何をしたいのかについての、明確で簡潔な説明を行ってください。
私の理解不足でしたら申し訳ありません。
カスタムテーブルの設定で「選択し(他のテーブルの値一覧から選択)」を指定した場合、他のテーブルを参照した時に表示されるのは、参照先のテーブルの2項目めの値のみでしょうか？

一般的なデータベースだと、例えば売上入力システムであれば、明細項目に商品コードを入力すれば、商品マスターからデータ参照を行い、自動的に商品名、単価などが表示されると思います。

マニュアルを見たり、色々試したりもしていますが、Exmentでは現時点でこのような事で出来そうにありません。同様にコードを入力し、そのコードで検索する場合、プルダウンで表示される項目(上記の例の場合、商品コード＋商品名)を指定できれば有難いです。

また、ビューを指定する際に、入力した項目で検索条件を絞り込みたいです。
例えば、都道府県の項目に「東京」と入力すると、区市町村に「港区、新宿区・・・」といった感じでその都道府県の住所が検索条件に追加されるイメージです。

お願いばかりで申し訳ありませんが、これらの機能が無いと、Webデータベースとしては正直本番利用は厳しいです。

**Additional context / その他**
Add any other context or screenshots about the feature request here. / 機能リクエストに関する他のコンテキストまたはスクリーンショットをここに追加します。

**Comment by hirossyi73** [comment]
見出し列設定
https://exment.net/docs/#/ja/table?id=見出し表示列設定

データ連動設定
https://exment.net/docs/#/ja/form?id=データ連動設定
