### ISSUE TITLE
他のテーブルの値一覧から選択の不具合について

### ISSUE THREAD

**Issue by akiatori** [exceedone/exment#614]
**Describe the bug / バグの説明**
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
教えて頂いたマニュアルを見て、色々試してみましたが、結論的に上手く動作しません。
以下のようなテーブルを作成したところ、以下の不具合が見られました。
・生産設備マスターの「制御機器名」が「対象が見つかりません」と表示される。
但し、「設備メーカー名」を選択して値をセットすると、そのメーカーの制御機器名が表示される。
「メーカーマスター」では色々な種類のメーカーを登録しているため、設備メーカーが
検索条件になってしまい、期待した制御機器メーカーが抽出されていない。

■生産設備マスター
	・設備名
	・設備メーカー名	選択肢 [他のテーブルの値一覧から選択:メーカーマスター]
	・制御機器名	選択肢 [他のテーブルの値一覧から選択:制御機器マスター]

■制御機器マスター
	・制御機器名
	・制御機器メーカー名	選択肢 [他のテーブルの値一覧から選択:メーカーマスター,ビュー(制御機器メーカー)]
	拡張設定の見出し表示列設定 [制御機器メーカー名,制御機器名]

■メーカーマスター
	・メーカー名
	・メーカー区分 [設備メーカー,商社,制御機器メーカー]
	ビュー(設備メーカー):表示条件[メーカー区分 検索を含む 設備メーカー]
	ビュー(商社):表示条件[メーカー区分 検索を含む 商社]
	ビュー(制御機器メーカー):表示条件[メーカー区分 検索を含む 制御機器メーカー]

そもそも、条件ビューで設定した値だけデータが抽出されるという訳では無く、何かの要因でデータの抽出条件が追加されるという事でしょうか？
マニュアルを見たり、このような現象になる規則性を探しましたが良くわかりませんでした。

**To Reproduce / 再現手順**
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

**Version / 発生バージョン**
Please describe version. / ご利用のバージョンを記載してください。
最新

**Error log / エラーログ**
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

**Screenshots / スクリーンショット**
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

**Additional context / その他**
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by akiatori** [comment]
追加です。
あれから色々と試しましたが、そもそもカスタムビューが正常に機能していない場合がある事がわかりました。
例えば表示条件が「条件項目：装置(選択肢:値・見出で、機械,電気)」「検索条件：検索値を含む」「条件値：機械」の場合、
データはあるにも関わらず、何も表示されません。
しかし、カスタムビューを参照している別の項目で「メーカー」を入力すると、上記の「機械,電気」は無視されて、そのメーカーの
装置がすべて表示されてしまいます。
一般的にデータベースアプリケーションを開発するときは、テーブル名や項目名をソースにコンスタントで指定することが多いと
思いますが、こういったWebデータベースになると内部的にIDなどで管理すると推測されますので、何かの条件で内部的なIDが
ずれてしまっていて、違うテーブルか項目でSQLが作成されているような気がします。
もちろん、正常に動作するパターンもあるようなので、全てという言う訳ではありませんが・・・。

**Comment by hirossyi73** [comment]
@akiatori 
SELECT_RELATION_LINKAGE_DISABLED=true
という設定値を入れて、ご確認いただいてもよろしいでしょうか？

背景として、親子関係のあるテーブルの選択が同じフォームにあった場合、親を選択したら、自動的に子データを絞り込むようになっています。
（例：「顧客」と「担当者」が親子関係になっていた場合、顧客を選んだら、その顧客の担当者が自動的に絞り込まれる）

この機能が現在、すべての親子関係で有効になっているため、すべてのフォームでこの機能を無効にするための設定です。
※本来であれば、「親子関係の絞り込みを行う」という設定を、画面で個別に行うべきなのですが、少々お時間頂いています。この設定を追加していただけると幸いです。

**Comment by hirossyi73** [comment]
v3.1.1の機能にによるものとして、以下の内容を行ってください。
https://exment.net/docs/#/ja/form?id=%e9%96%a2%e9%80%a3%e7%b5%9e%e3%82%8a%e8%be%bc%e3%81%bf%e8%a8%ad%e5%ae%9a

こちらはクローズさせていただきます。
