### ISSUE TITLE
publishes メソッドの一部失敗

### ISSUE THREAD

**Issue by C0ela** [exceedone/exment#622]
**Describe the bug / バグの説明**
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

Developer 向け設定の途中、 artisan コマンドの publishes メソッドの一部が失敗する。

**To Reproduce / 再現手順**
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

[Develop.md](https://github.com/exceedone/exment/blob/master/Develop.md)中の次の手順

```sh
composer update
php artisan vendor:publish --provider="Exceedone\Exment\ExmentServiceProvider"
```

**Version / 発生バージョン**
Please describe version. / ご利用のバージョンを記載してください。

v3.2.0

**Screenshots / スクリーンショット**
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

![2020-05-07 145150](https://user-images.githubusercontent.com/32484688/81262506-f048ce80-9078-11ea-9e27-1dceb5ed49b3.jpg)

**Additional context / その他**
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

Windows 10 pro, WSL 1, Ubuntu 18.04.4

**Comment by hirossyi73** [comment]
ありがとうございます。v3.2.1にて対応しました。
