### ISSUE TITLE
通知をシステム内アラートにした場合において、通知内容の対象データ表示がおかしい

### ISSUE THREAD

**Issue by tkpontas** [exceedone/exment#629]
**Describe the bug / バグの説明**
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

通知をシステム内アラートにした場合において、通知内容の対象データ表示がおかしい
（PHP・データベースの中身が表示されているような印象）

**To Reproduce / 再現手順**
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
テーブルに対して、コメントや更新の通知設定を以下のように設定。

![コメント 2020-05-07 201811](https://user-images.githubusercontent.com/60683813/81288639-fb632500-909f-11ea-8038-c3382ae11a1a.png)

ほかのユーザーでコメントを実施後、テーブルデータを作成したユーザーでログインし直すと
正常にコメント通知は出るが通知を開くと以下のように表示される。

![コメント 2020-05-07 201314](https://user-images.githubusercontent.com/60683813/81290363-e63bc580-90a2-11ea-8940-68bc97b55a7f.png)

以前は対象データはリンクが表示されていたような印象を受けるのですが
どこか設定を変えれば良いのでしょうか？

**Version / 発生バージョン**
Please describe version. / ご利用のバージョンを記載してください。

Ver.3.2.0

**Error log / エラーログ**
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

今回の件についてはエラーログは残っていませんでした。

**Screenshots / スクリーンショット**
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

上記に貼り付け済。

**Additional context / その他**
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

メールでこのような現象が起きるかどうかは未確認です。

**Comment by hirossyi73** [comment]
@tkpontas 
本リリースまでに少々お時間いただきそうなので、お手数ですが、以下の記述を直接変更いただけないでしょうか。

 src/Controllers/NotifyNavbarController.php  112行目
``` php
                    //return $custom_value->getValue(true);
                    return $custom_value->getLabel();
```

**Comment by tkpontas** [comment]
早速のご対応ありがとうございます。直接記述変更したところ、問題なく表示されました。リリースもお待ちしております。

**Comment by hirossyi73** [comment]
v3.2.2にてリリースしました。
