### ISSUE TITLE
スマホで見ている時にスマホのカメラをバーコードリーダーとしてフォームに入力する機能

### ISSUE THREAD

**Issue by garyohosu** [exceedone/exment#632]
**Describe the feature you'd like / 機能する機能の説明を行ってください**
A clear and concise description of what you want to happen. / あなたが何をしたいのかについての、明確で簡潔な説明を行ってください。
Exmentをスマホから開いた時に思ったのですが、フォームの入力時にスマホのカメラをバーコードリーダー使えないでしょうか。出荷時の製品のバーコードの読み取りなどに使えるのではと思います。
以下の記事で「HTML/CSSとJavaScriptを使ってWebサイトにQRコードリーダーを実装する方法」が紹介されていますが、こちらを取り込むことはできないでしょうか？
https://www.webprofessional.jp/create-qr-code-reader-mobile-website/

**Additional context / その他**
Add any other context or screenshots about the feature request here. / 機能リクエストに関する他のコンテキストまたはスクリーンショットをここに追加します。

**Comment by hirossyi73** [comment]
現在開発中の、「独自の列追加」機能で対応できると考えています。
https://exment.net/archives/1410

また、スマホとの連動については、近々アナウンスできることがあるかもしれないので、少々お待ちください。
