### ISSUE TITLE
通常ビューの表示条件を「いずれかの条件に一致」した場合の動作がおかしい

### ISSUE THREAD

**Issue by shu-sp** [exceedone/exment#634]
・通常ビューの表示条件を「いずれかの条件に一致」した場合の動作がおかしい。

　　　現在のステータス　検索値と一致する　状態A
　　　現在のステータス　検索値と一致する　状態B

　　とした場合、どちらの状態も表示されない。

**Comment by hirossyi73** [comment]
ありがとうございます。v3.2.5で修正しました。
