### ISSUE TITLE
列種類が選択肢で複数選択:許可の時のインポートエラー

### ISSUE THREAD

**Issue by yjmtmtk** [exceedone/exment#636]
**Describe the bug / バグの説明**
カスタム列の列種類が「選択肢」で「複数選択」を「許可」している時
実際に値をいれて（複数でも単体でも）インポート(csv,xls)を行うとエラーになる。

ColumnItems/CustomColumns/ImportValueTrait.php
20行目の

` if (!array_has($options, strval($value))) {`

$valueに配列が入るためstrvalによるエラーになります。

**Version / 発生バージョン**
Version   v3.2.4

**Comment by hirossyi73** [comment]
ありがとうございます。v3.2.5で修正しました。
