### ISSUE TITLE
カスタム数値列の最小値最大値が桁数チェックになる

### ISSUE THREAD

**Issue by yisaka117** [exceedone/exment#64]
カスタム列（ColumnTypeがIntegerやDecimal）に最小値、最大値を設定した場合に最小桁数と最大桁数として扱われる。
Laravelのmin/max validateでruleにintegerやdecimalが設定されていないと、文字列扱いのチェックになるため。（exmentではIntegerやDecimalのチェックをオリジナルクラスで行っている。）

**Comment by hirossyi73** [comment]
v1.1.0にて対応を行いました。
