### ISSUE TITLE
カスタムテーブルのデータのexport時にエラーが出る

### ISSUE THREAD

**Issue by y-hayama** [exceedone/exment#640]
**Describe the bug / バグの説明**
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

カスタムテーブルのデータのexport時にPHPExcelにて「Maximum 31 characters allowed in sheet title」の例外がthrowされます。
カスタムテーブル単体では30文字の文字数制限がかかっているかと思いますが、リレーションを貼っているカスタムテーブルをエクスポートすると「親テーブル名_小テーブル名」で名前が生成され、最大60文字の文字数になることが原因かと思われます。

**To Reproduce / 再現手順**
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

1. カスタムテーブルAを作る（テーブル名は20文字前後）
2. カスタムテーブルBを作る（テーブル名は20文字前後）
3. カスタムテーブルAを親テーブルにしてカスタムテーブルBと1対Nのリレーションを貼る
4. カスタムテーブルAにデータを作成する
5. カスタムテーブルBにデータを作成する。この際にカスタムテーブルAのデータと紐付ける
6. カスタムテーブルAのデータをエクスポートする

**Version / 発生バージョン**
Please describe version. / ご利用のバージョンを記載してください。

v3.2.4

**Error log / エラーログ**
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

**Screenshots / スクリーンショット**
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

**Additional context / その他**
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by hirossyi73** [comment]
v3.2.8で対応しました。
