### ISSUE TITLE
役割グループ設定がエラーで表示されない[Version v3.2.6]

### ISSUE THREAD

**Issue by yjmtmtk** [exceedone/exment#641]
**Describe the bug / バグの説明**
Version v3.2.4 から Version   v3.2.6にアップデートしたところ
役割グループ設定が表示されなくなりました。

RoleGroupController.php
47行目の$countsにNULLが入ってしまってエラーとなります。

```
$grid->column('role_group_users', exmtrans('role_group.users_count'))->displayEscape(function ($counts) {
            return count($counts); //$counts ←NULL
        });
```

**Version / 発生バージョン**
Version   v3.2.6

If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

![スクリーンショット 2020-05-30 10 16 29](https://user-images.githubusercontent.com/65989382/83316055-b6757d00-a25e-11ea-9eec-99d5712846dc.png)

**Comment by yjmtmtk** [comment]
```
$grid->column('role_group_users', exmtrans('role_group.users_count'))->displayEscape(function ($counts) {
           return is_null($counts) ? 0 : count($counts);	
        });
```
として一時的に利用しています。

**Comment by hirossyi73** [comment]
ご報告ありがとうございます。お手数おかけします。
役割グループは今回、直接的には修正していない箇所なので、原因調査し、早急に対応します。

**Comment by hirossyi73** [comment]
v3.2.7で修正しました。
