### ISSUE TITLE
データImportの仕様と機能制限について

### ISSUE THREAD

**Issue by tmmuras** [exceedone/exment#644]
いつもお世話になります。
1.A,B複数ユーザによるImport操作について。
　時間差でダウンロードしたExcel/CSVデータをそれぞれが編集→Aがimportする前にBがダウンロードし、それぞれが後から主キー指定でupdateした場合、後勝ちになると想定されますが、認識は相違ないでしょうか。
2.上記によるオペレーションミスを防ぐ対策の一つとして、グループ単位/テーブル単位でimport/exportの権限設定は可能でしょうか。

**Comment by hirossyi73** [comment]
@tmmuras 
すみません、ご返信遅くなりました。

1. 現状ですと、後勝ちになります。
画面では楽観的排他制御を行っているので、[設定値](https://exment.net/docs/#/ja/config)で、「インポート時に排他制御を行う」という内容を追加することは可能です。

2. 役割グループの設定で、インポート・エクスポートの権限を以前検討したのですが、現在は編集・閲覧権限に集約しています。そのため、現在はグループ/テーブル単位でのインポート・エクスポートの権限設定は未実装です。
