### ISSUE TITLE
全件ビューの利用不可設定が欲しい

### ISSUE THREAD

**Issue by bird-white** [exceedone/exment#645]
**Describe the feature you'd like / 機能する機能の説明を行ってください**
A clear and concise description of what you want to happen. / あなたが何をしたいのかについての、明確で簡潔な説明を行ってください。

テーブル毎で、システムビューの”全件ビュー”を利用出来ないようにする設定が欲しい。

一般ユーザーには全てのデータは見せたくないが、ユーザー以外が作成した一部のデータを閲覧させたい。
※カスタムデータ自動共有設定では、組織に縛られるので設定では
　求めている事が実現出来ませんでした

対象データを全て共有する事が大変なので実装の検討をお願いします。

**Comment by hirossyi73** [comment]
全件ビューは、「どんなユーザーでも使用される、ならびにヘッダーでのデータ検索時などで使用される、汎用的なビュー」という立ち位置です。
利用制限を追加すると、場合によっては「テーブルで使用できるビューが一つも存在しない」という事になりかねないです。

そのため、申し訳ありませんが全件ビューの利用制限の実装予定はございません。
