### ISSUE TITLE
CSVインポート時、３行目（ヘッダの次の行）が取り込まれない

### ISSUE THREAD

**Issue by bird-white** [exceedone/exment#646]
**Describe the bug / バグの説明**
カスタムテーブルにCSVでインポート時、ヘッダの次の行が取り込まれない。
なお、無視される行のエラーチェックも実施されていない。

**To Reproduce / 再現手順**
適当なカスタムテーブルのCSVテンプレートをダウンロードして、数行入力した後にアップロードする。

**Version / 発生バージョン**
 v3.2.7

**Comment by hirossyi73** [comment]
弊社環境ですと再現しない状況です。動作環境をご教授いただけないでしょうか。

**Comment by bird-white** [comment]
こちらの環境は下記となります。
MySQLを個別インストールした事以外は、御社サイトのインストール手順にてサーバ設定を行いました。
exmentインストールパスも”C:\xampp\local\exment”となります。

Windows10 Pro ver.1909
XAMPP Version: 7.3.18（Apache、PHP、phpMyAdminのみインストール）
PHP 7.3.18
MySQL 5.7（mysql-installer-community-5.7.30.0.msiでインストール）
