### ISSUE TITLE
ビューの表示条件項目にある条件の結合が正しく動作していない

### ISSUE THREAD

**Issue by bird-white** [exceedone/exment#647]
**Describe the bug / バグの説明**
ビューの表示条件で、条件の結合を「いずれかの条件に一致 」に設定しても
AND条件となっているのか正しい結果が表示されない。

**To Reproduce / 再現手順**
カスタムテーブルに、ユーザーコード項目を２つ作成し、それぞれ別のユーザーコードを登録。
ビューの表示条件に、それぞれの項目を追加し、「ログインユーザーに合致する」を選択。
条件の結合で「いずれかの条件に一致」を選択してビューを作成する。

登録されているユーザーでログインしてもデータが表示されない。
（権限は全データの閲覧・編集可能としている）

**Version / 発生バージョン**
v3.2.7

**Screenshots / スクリーンショット**
![image](https://user-images.githubusercontent.com/66356875/83731879-3009d280-a686-11ea-813e-c9b86f5616c3.png)

**Comment by hirossyi73** [comment]
2行目の「現在の作業ユーザー」が、ワークフローの設定項目の可能性があります。（同名の列を作成されていましたらごめんなさい）

**Comment by bird-white** [comment]
eご確認ありがとうございます。
ご指摘通り、ワークフローの設定項目です。
「現在の作業ユーザー」を条件から外す事で正しく表示されました。
ワークフロー項目は使用しない方向で検討致します。
