### ISSUE TITLE
Excelテンプレートインポート時に表示順が反映されない

### ISSUE THREAD

**Issue by mdb-project-git** [exceedone/exment#648]
**Describe the bug / バグの説明**
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
・テンプレートのExcelアップロード機能でカスタム列の表示順がテーブルに反映されず、すべて0として登録されてしまう。
・貴社HPのサンプルを編集せずにそのままアップロードしても反映されないことを確認済み。
(https://exment.net/downloads/sample/template/exment_template_sample.xlsx)

**To Reproduce / 再現手順**
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
①　テンプレートファイルをDL（https://exment.net/downloads/template/exment_template.xlsx）
②　「custom_tables」に任意のテーブル情報を記載
③　「custom_columns」にカスタム列情報を記載、この時Excel上N列（options.order）に半角数字で表示順を記載
④　Exment>テンプレートで作成したExcelファイルをアップロード
⑤　UPされたテーブルのカスタム列情報を確認すると表示順がすべて０になっている（その他列種類、名称、選択肢等は問題なく反映）

**Version / 発生バージョン**
Please describe version. / ご利用のバージョンを記載してください。
Version   v3.2.7

**Error log / エラーログ**
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

**Screenshots / スクリーンショット**
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

**Additional context / その他**
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by hirossyi73** [comment]
テンプレートファイル、サンプルファイル、ともに差し替えました。ご確認をお願いいたします。

**Comment by mdb-project-git** [comment]
ご対応ありがとうございます
更新いただいた内容で再UPし不具合解消していることを確認しました、
こちらで課題クローズですが、
以下Excelドキュメント修正点あるようですのでご確認をお願いいたします
・サンプルファイルの並べ替え(order)列の25～28行目が空欄の為、そのままUPするとエラーになってしまうようです
・サンプルファイル同様テンプレートファイルのフォーマット修正もお願いいたします
