### ISSUE TITLE
リポジトリにルーティング情報が含まれていないのでは？

### ISSUE THREAD

**Issue by kakisoft** [exceedone/exment#649]
試しに使ってみようとしたのですが、routes ディレクトリと、その配下のルーティング情報（api.php や web.php）がありませんでした。

composer create-project "laravel/laravel=5.6.*" exment コマンドにてプロジェクトを作成した場合は、
Laravel デフォルトの内容が作成されました。

このままでは試しに動かしてみる事が出来ないので、対応頂けると嬉しいです。

**Comment by hirossyi73** [comment]
https://github.com/exceedone/exment/blob/master/src/Providers/RouteServiceProvider.php
