### ISSUE TITLE
DB暗号化

### ISSUE THREAD

**Issue by tkud** [exceedone/exment#651]
**Additional context / その他**
さくらレンタルサーバに構築しました。MySQL5.7で利用します。
社内アカウントなどの情報管理に利用する予定ですが、登録したデータが
暗号化されていないことを確認しました。
アプリ側での暗号処理を要望しますが、計画などはございますか。

**Comment by hirossyi73** [comment]
計画はございません。
各自で、以下のような実装をご検討ください。
https://qiita.com/hmatsu47/items/476d446887244de17ae4

**Comment by tkud** [comment]
回答ありがとうございました。案内いただいたサイト他を確認済みです。
自力対応で解決します。
