### ISSUE TITLE
複数選択を許可した「選択肢（他のテーブルの値一覧から選択）」が関連検索されない

### ISSUE THREAD

**Issue by shimaday8** [exceedone/exment#655]
**Describe the bug / バグの説明**
複数選択を許可した「選択肢（他のテーブルの値一覧から選択）」が関連検索されません。

**To Reproduce / 再現手順**
1. 複数選択を許可した「選択肢（他のテーブルの値一覧から選択）」に値を設定します。
2. 設定した値に対応する親データで関連検索を行います。
3. 関連データ検索画面の子テーブルの欄に「検索結果がありませんでした」と表示されます。

**Version / 発生バージョン**
 v3.2.8

**Comment by hirossyi73** [comment]
v3.3.1で対応しました。
