### ISSUE TITLE
「選択肢（他のテーブルの値一覧から選択）」列でのソートがおかしい

### ISSUE THREAD

**Issue by shimaday8** [exceedone/exment#656]
**Describe the bug / バグの説明**
「選択肢（他のテーブルの値一覧から選択）」列でソートしても、画面に表示されている文字列（親テーブルの「見出し表示列」）の順に並びません。

**To Reproduce / 再現手順**
1. 親テーブルに「見出し表示列」を設定します。
2. 子テーブルに「選択肢（他のテーブルの値一覧から選択）」列を追加して親テーブルに関連付けます。
3. 子テーブルに複数のデータを登録します。
4. 子テーブルの一覧画面で「選択肢（他のテーブルの値一覧から選択）」列をクリックします。
5. 見た目とは異なる順番でソートされます。

**Version / 発生バージョン**
 v3.2.8

**Screenshots / スクリーンショット**
![sort_asc](https://user-images.githubusercontent.com/66708775/84372218-c2295200-ac15-11ea-8908-b05cc650181a.PNG)
![sort_desc](https://user-images.githubusercontent.com/66708775/84372230-c5bcd900-ac15-11ea-8d60-3754dfe8186b.PNG)

**Comment by hirossyi73** [comment]
・データの見出しに該当する列は他のテーブルにあるため、見出しの内容で並び替えることは現状できません。(ライブラリの仕様もあり、order時のみのテーブル結合も少々難しそうです。)
・IDでの並べ替えを実施しています。こちらは、v3.3.1で整数としての並べ替えを実施するようにしました。
・複数選択を許可している場合、並べ替えを出来なくしました。
