### ISSUE TITLE
親子関係にある「選択肢（他テーブルの値一覧から選択）」の子テーブルの選択肢が表示されないことがある

### ISSUE THREAD

**Issue by shimaday8** [exceedone/exment#659]
**前提**

カスタムテーブルに「選択肢（他テーブルの値一覧から選択）」を2つ追加し、それらの参照先テーブルの間に「選択肢（他テーブルの値一覧から選択）」による親子関係があるとき、親テーブル側の選択肢を入力すると、それに連動して子テーブル側の選択肢が絞り込まれます。

この動作について、Exmentのドキュメントに記載は見つけられませんでしたが、Exmentの仕様だろうと想定しています。以降、この仕様を前提として話を進めます。

* 親テーブル（大分類）に紐づく子テーブル（中分類）が選択肢に表示されている。
![01-02-cut](https://user-images.githubusercontent.com/66708775/84467815-2d2b6500-acb8-11ea-8a11-ce9c137062b1.PNG)

* 親テーブルの入力値を変更すると、子テーブルの選択肢が変化する。
![01-03-cut](https://user-images.githubusercontent.com/66708775/84467829-33214600-acb8-11ea-9a5c-52d828297ecd.PNG)

**Describe the bug / バグの説明**

複数選択を許可した「選択肢（他テーブルの値一覧から選択）」項目を2つ追加します。それぞれの項目の参照先テーブルの間には「選択肢（他テーブルの値一覧から選択）」による親子関係があります。
そのようなカスタムテーブルで、親テーブルの値を入力しても、子テーブルの選択肢になにも表示されません。親テーブルの値を入力して保存したあと、編集画面を開きなおすと、子テーブルの選択肢が表示されるようになります。

**Version / 発生バージョン**
v3.2.8

**Screenshots / スクリーンショット**

* 親テーブル（大分類）の値を入力した直後。
![01-04-cut](https://user-images.githubusercontent.com/66708775/84468810-ac219d00-acba-11ea-9b1d-073e15612f4c.PNG)

* 親テーブルの値を入力して保存してから、編集画面を開きなおした。
![01-05-cut](https://user-images.githubusercontent.com/66708775/84468827-b2177e00-acba-11ea-8bc9-127c644d876a.PNG)

**Comment by hirossyi73** [comment]
v3.1.1で修正しました。
