### ISSUE TITLE
「選択肢（他テーブルの値一覧から選択）」の絞り込み方法を指定できるようにしてほしい

### ISSUE THREAD

**Issue by shimaday8** [exceedone/exment#664]
**Describe the feature you'd like / 機能する機能の説明を行ってください**

「選択肢（他テーブルの値一覧から選択）」項目が複数あり、それらの参照先テーブルの間に親子関係があると、親テーブル側の入力に応じて、子テーブル側の選択肢が自動的に絞り込まれます。この仕組みはとても重宝しており、ほとんどのケースで思った通りの動きになります。

ただし、常に有用というわけではなく、選択肢が絞り込まれすぎたり、選択肢がなにも表示されなくなったり、意図しない絞り込みをされてしまうことがあります。

そこで、お願いがあります。
「選択肢（他テーブルの値一覧から選択）」の絞り込みを柔軟に指定する仕組みを実現していただけないでしょうか。

絞り込むという仕組みは残してほしいです。どのテーブルにより絞り込みを行うのか（もしくは行わないのか）など、絞り込みの方法を柔軟に指定できるオプション機能がほしいです。

**Additional context / その他**

次のようなケースが考えられます。

![tables](https://user-images.githubusercontent.com/66708775/84735030-6ed04e80-afdd-11ea-9ca0-cc592adda21a.png)
テーブル親は、テーブル子の親です。
テーブル共通は、テーブル親の親でもあり、テーブル子の親でもあります。

テーブル親にデータを登録します。
![parent](https://user-images.githubusercontent.com/66708775/84735351-45fc8900-afde-11ea-97e1-23a4184ec7d4.png)

テーブル子の新規登録画面です。テーブル共通の入力内容に連動して、テーブル親の選択肢が絞り込まれます。
![child](https://user-images.githubusercontent.com/66708775/84735737-2fa2fd00-afdf-11ea-8f47-04d7f266b8f4.png)

問題となるのは、テーブル共通によらずテーブル親からデータを選択したいケースです。そのようなケースでは、テーブル共通の選択内容に連動して「意図せず」テーブル親の選択肢が絞り込まれてしまい、本当に選択したいテーブル親が「選択肢に現れない」という状態になります。

**Comment by hirossyi73** [comment]
ちょうど現在開発中です、2～3週間ほどお待ちください。

**Comment by shimaday8** [comment]
承知しました。よろしくお願いします。

**Comment by hirossyi73** [comment]
v3.1.1で対応しました。詳細はこちらをご確認ください。
https://exment.net/docs/#/ja/form?id=%e9%96%a2%e9%80%a3%e7%b5%9e%e3%82%8a%e8%be%bc%e3%81%bf%e8%a8%ad%e5%ae%9a

**Comment by shimaday8** [comment]
早速のご対応、大変ありがとうございました。
思った通りの動きをするようになり、とても重宝しております。
