### ISSUE TITLE
親テーブルの削除で確認画面が表示され続ける

### ISSUE THREAD

**Issue by shimaday8** [exceedone/exment#668]
**Describe the bug / バグの説明**
「選択肢（他テーブルの値一覧から選択）」による親子関係が設定された親テーブルの削除で、確認画面が表示され続けます。1分ほど待ちましたが表示が消えることはありませんでした。親テーブルは削除されずに残っています。

**Version / 発生バージョン**
v3.3.0

**Screenshots / スクリーンショット**
![delete_me2](https://user-images.githubusercontent.com/66708775/84855169-6be96280-b09e-11ea-93e2-56cf026dab8a.png)

**Comment by hirossyi73** [comment]
v3.3.1で対応しました。
