### ISSUE TITLE
ユーザーコードにピリオドを含む事は許容されないでしょうか

### ISSUE THREAD

**Issue by dev-hayash** [exceedone/exment#671]
**Describe the feature you'd like / 機能する機能の説明を行ってください**
A clear and concise description of what you want to happen. / あなたが何をしたいのかについての、明確で簡潔な説明を行ってください。

V3.3.0でLDAP認証を追加して頂いたので試したところ、ログインテストで以下表示され、認証に失敗しました。

-----
実行失敗しました。
正しい形式のuser codeを指定してください。 : dev.hayash
-----

マッピング設定のユーザーコードにSamAccountNameを指定しています。
（返却値が "dev.hayash"です）

原因を考えていましたが新規ユーザー登録でも、user codeにはハイフンかアンダーバーしか許容されていない事を思い出し、これが原因かなと想像しています。

新規ユーザーでLDAP認証する際、ユーザーコードにマッピングした項目にピリオドが含まれていると認証（ユーザー登録）できない現象は、元を辿るとユーザーコードにピリオドが許容されていない事に行きつきます。

ＡＤサーバーの運用方法次第とは思いますが、SamAccountNameやuserPrincipalNameには苗字．名前の形式を採用している場合、ユーザー登録が不可能です。

Exmentの設計思想としてユーザーコードにピリオドを含ませない事について、事情を解さないで要望する形で恐縮ですが、ご検討をお願いします。

**Comment by hirossyi73** [comment]
バージョン3.3.0より、カスタム列種類「1行テキスト」の「使用可能文字」に、「ドット」を追加しました。
v3.3.0未満からv3.3.0以上にアップデートした場合は、ドットが未許可状態になっているので、カスタム列設定より設定変更し、再度ご確認をお願いします。

**Comment by dev-hayash** [comment]
御回答ありがとうございます。

> バージョン3.3.0より、カスタム列種類「1行テキスト」の「使用可能文字」に、「ドット」を追加しました。

すみません。こちら、気づきませんでした。

本件、closeさせて頂きます。
