### ISSUE TITLE
カスタム列（別テーブルを参照する選択肢）の項目について、選択肢にない場合その場で別テーブルにデータを追加する機能

### ISSUE THREAD

**Issue by tmmuras** [exceedone/exment#672]
**Describe the feature you'd like / データ登録画面でのマスタ登録実装要望**
A clear and concise description of what you want to happen. / カスタム列で別テーブル（**マスタ等）とリレーションを張った選択肢の入力項目を選択するときに、選択肢に存在しない場合にその場でマスタにデータ追加できる機能の実装をお願いできませんでしょうか。
もし現在の機能で対応可能な場合その方法をご教示ください。

**Additional context / その他**
Add any other context or screenshots about the feature request here. / 
https://exment.net/docs/#/ja/column?id=%e8%a8%98%e5%85%a5%e9%a0%85%e7%9b%ae%e3%81%ae%e8%a9%b3%e7%b4%b0%e8%aa%ac%e6%98%8e%e5%88%97%e7%a8%ae%e9%a1%9e%e5%88%a5

**Comment by hirossyi73** [comment]
現在の機能では対応不可なので、将来的なアップデートでの検討とさせてください。
※他にも、ダイアログで詳細なデータ検索を行える機能の要望もあります。

**Comment by tmmuras** [comment]
かしこまりました！いつもご対応ありがとうございます。ご検討のほどよろしくお願いいたします。
