### ISSUE TITLE
ワークフローを削除できるようにしてほしい

### ISSUE THREAD

**Issue by shimaday8** [exceedone/exment#673]
**Describe the feature you'd like / 機能する機能の説明を行ってください**
ワークフローは設定が完了すると削除できなくなります。これはExmentの仕様だと認識しています。
仕様をくつがえすお願いなので大変恐縮ですが、利便性を向上させるため、「ワークフローを削除する」機能のご検討をお願いします。

以前、誤って定義したワークフローを削除できなかったことがあり、検証環境上でしたので被害は大きくありませんでしたが、できれば実現していただきたく思います。

**Comment by shimaday8** [comment]
対応を希望します。

**Comment by fleming35800** [comment]
Exmentの開発関係者ではありませんが、ワークフローの削除はmySQLの管理画面から実施することが可能です。
（#720 で話が出ていますが、私が把握している限り、setting_completed_flgを変えるだけでは削除できない場合もありましたので、ワークフローの削除は、自己責任にて、関連しているデータ等に対する細心の注意を払ったうえで実施となります。）

ワークフロー設定完了後の削除が不可としている真意は不明ですが、
削除を実現したことにより想定されるリスクが大きい、削除する為に検討しなければならない事が多いからなのではないかと考えています。
（間違えて使用されているワークフローが削除されてしまう事。
　ワークフローに関連して生成されるデータが多いことから、設定完了後のワークフロー削除を実施しようとする時にその全ての要素を完全に遡り、どこからどこまで削除対象とするのか等。）

**Comment by shimaday8** [comment]
情報提供ありがとうございます。

データベースを直接操作することはExmentが動作保証していないと考えております。そのため、Exmentの機能として実現されることを希望しております。
