### ISSUE TITLE
「見出し」項目の詳細画面表示がおかしい（再報告）

### ISSUE THREAD

**Issue by shimaday8** [exceedone/exment#681]
**Describe the bug / バグの説明**
#654 が修正されていないようです。現象は変わりません。

詳細画面の「見出し」項目が、編集画面と同じ表示になることを希望します。（同じHTML要素が出力されると想像しています）
よろしくお願いします。

**Version / 発生バージョン**
v3.3.1

**Comment by shimaday8** [comment]
是非対応してほしいのでお願いします。

**Comment by hirossyi73** [comment]
v4.1.0で、フォーム構造を修正したこともあり、対応予定です。

**Comment by hirossyi73** [comment]
2021/04/19 v4.1.0リリース完了
