### ISSUE TITLE
「お知らせ」テーブルが権限なしでも閲覧できる

### ISSUE THREAD

**Issue by shimaday8** [exceedone/exment#682]
**Describe the bug / バグの説明**
「お知らせ」テーブルが権限なしでも閲覧できます。

**To Reproduce / 再現手順**
1. 「お知らせ」テーブルの権限がない権限グループを作成します。（スクリーンショットのとおり）
2. 作成した権限グループにユーザを所属させます。
3. そのユーザで「お知らせ」テーブルを閲覧します。

**Version / 発生バージョン**
v3.3.1

**Screenshots / スクリーンショット**
![おしらせ](https://user-images.githubusercontent.com/66708775/85516331-0b779980-b639-11ea-912c-de1939c8e641.png)

**Comment by hirossyi73** [comment]
https://exment.net/docs/#/ja/table?id=%e5%85%a8%e3%83%a6%e3%83%bc%e3%82%b6%e3%83%bc%e3%81%8c%e9%96%b2%e8%a6%a7%e5%8f%af%e8%83%bd

**Comment by shimaday8** [comment]
カスタムテーブルの設定を変更することで、閲覧できなくなりました。
お教えいただき、ありがとうございました。
