### ISSUE TITLE
ダッシュボードのチャートの配色の数を増やして欲しい

### ISSUE THREAD

**Issue by y-hayama** [exceedone/exment#695]
**Describe the feature you'd like / 機能する機能の説明を行ってください**
A clear and concise description of what you want to happen. / あなたが何をしたいのかについての、明確で簡潔な説明を行ってください。

チャートの集計項目が複数ある場合に配色が同色になる場合があるので、色の数を増やして欲しいです

**Additional context / その他**
Add any other context or screenshots about the feature request here. / 機能リクエストに関する他のコンテキストまたはスクリーンショットをここに追加します。

![スクリーンショット 2020-06-26 16 03 27](https://user-images.githubusercontent.com/13801922/85830002-d00ad580-b7c6-11ea-9ec6-0fc7bfa1dbb0.png)

**Comment by hirossyi73** [comment]
https://exment.net/docs/#/ja/config?id=%e3%83%80%e3%83%83%e3%82%b7%e3%83%a5%e3%83%9c%e3%83%bc%e3%83%89%e3%81%ae%e3%82%b0%e3%83%a9%e3%83%95%e8%a1%a8%e7%a4%ba%e3%81%ae%e8%89%b2%e3%82%92%e5%a4%89%e6%9b%b4
こちらにて対応しました。
