### ISSUE TITLE
ビュー形式でデータインポートできるようにして欲しい

### ISSUE THREAD

**Issue by y-hayama** [exceedone/exment#697]
**Describe the feature you'd like / 機能する機能の説明を行ってください**
A clear and concise description of what you want to happen. / あなたが何をしたいのかについての、明確で簡潔な説明を行ってください。

現在はエクスポートのみビュー形式でエクスポートできますが、このままデータを更新して取り込みたいニーズがあり、ビュー形式でのインポートに対応して欲しいです。

**Additional context / その他**
Add any other context or screenshots about the feature request here. / 機能リクエストに関する他のコンテキストまたはスクリーンショットをここに追加します。

**Comment by hirossyi73** [comment]
ビューの仕様上、インポートは難しいです。
