### ISSUE TITLE
ビューの新規作成ができない

### ISSUE THREAD

**Issue by ganapati55** [exceedone/exment#699]
**Describe the bug / バグの説明**
急にビューの作成そのものができなくなりました。
項目を設定後送信するとエラーが発生します。
項目を変えていろいろ試してみましたが駄目です。
verは3.3.2です。

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'suuid' in 'field list' (SQL: insert into `custom_view_columns` (`custom_view_id`, `view_column_table_id`, `view_column_type`, `view_column_target_id`, `options`, `order`, `suuid`, `created_user_id`, `updated_user_id`, `updated_at`, `created_at`) values (39, 14, 0, 95, [], 10, 6413d3ee463a0b7d7a19, 1, 1, 2020-06-29 13:55:36, 2020-06-29 13:55:36))

**Comment by hirossyi73** [comment]
@ganapati55 
こちらですべてのビューで新規作成試してみましたが、特に問題なさそうでした。

念の為、以下のコマンドを実施してみてほしいです。
php artisan migrate

**Comment by ganapati55** [comment]
返信いただきましてありがとうございます。上記実行してみましたが　Nothing to migrate　でした。
