### ISSUE TITLE
ワークフロー対応

### ISSUE THREAD

**Issue by hirossyi73** [exceedone/exment#70]
ワークフローにサポートし、データの承認や、上長への報告などに対応できるようにする

**Comment by skmt8585** [comment]
・通知に表示される「通知本文」の対象データのリンクが無効です。リンクのHTMLがそのまま表示されます。(Firefoxで確認)

・申請⇒却下の順で操作すると、それ以降は詳細画面で「履歴 表示」をクリックしても、その申請の履歴が表示されなくなります。
