### ISSUE TITLE
選択肢(他のテーブルの値一覧から選択)で選択した値をキーにデータ検索が出来なくなる

### ISSUE THREAD

**Issue by phssakaigawa** [exceedone/exment#706]
いつもありがとうございます。
発生バージョンが明確でないため、心苦しいのですが起票いたします。

**Describe the bug / バグの説明**
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

商品マスタ、商品在庫テーブルという関係でテーブルを作成し、
商品マスタにある商品コードをキーに、選択肢(他のテーブルの値一覧から選択)の項目で
商品在庫テーブルにレコードを登録しています。
以前のバージョンでは商品コードをキーに画面上部のデータ検索フィールドから検索すると、
商品マスタ、商品在庫テーブルの双方にあるデータが抽出できましたが、
3.x以降のバージョンアップからか（正確には判明していません）、商品マスタのみで商品在庫テーブルにある在庫情報が抽出できなくなりました。

**Comment by phssakaigawa** [comment]
現在の最新版3.4へ本日アップデートしましたが、この状態でも状況変わらずです

**Comment by hirossyi73** [comment]
以下の内容をご確認いただけないでしょうか？

・テーブル「商品在庫」の設定で、「検索可能」が「YES」になっていること。
・テーブル「商品在庫」の列「商品コード」のカスタム列設定で、「検索インデックス」と「フリーワード検索対象列」が「YES」になっていること。
　※v3.4.0で、「フリーワード検索対象列」が追加されました。本来ですとアップデート時に、検索インデックスがYESであれば自動的にYESになりますが、念の為ご確認ください。

![image](https://user-images.githubusercontent.com/8457265/86547119-d5a8ae00-bf72-11ea-98e0-8ca717676372.png)

**Comment by phssakaigawa** [comment]
内容確認しました。

・テーブル「商品在庫」の設定で、「検索可能」は「YES」になっています。
・テーブル「商品在庫」の列「商品コード」のカスタム列設定で、「検索インデックス」と「フリーワード検索対象列」は「YES」になっています。

3.4､3.3.xのタイミングで探せなくなり、バージョンダウン検証をするか検討しています。
7/1 0:21 にバージョンアップを最新版にしたので、そのタイミングのバージョンになります

**Comment by hirossyi73** [comment]
状況の確認ですが、以下でよろしいでしょうか。

■商品マスターがある。
![image](https://user-images.githubusercontent.com/8457265/86560909-516a2100-bf9a-11ea-8c0b-c9b5cf6a8802.png)

■商品在庫状況がある。「商品マスター」列は、「商品マスター」テーブルへの参照となる、「選択肢(他のテーブルの値一覧から選択)」の列。検索可能YES、フリーワード検索対象列YES。
![image](https://user-images.githubusercontent.com/8457265/86560934-5dee7980-bf9a-11ea-9e17-050aaa812f75.png)

■ヘッダーに商品マスターのコード「A001」を入れた時、
![image](https://user-images.githubusercontent.com/8457265/86561025-9726e980-bf9a-11ea-9517-df140047f8c7.png)

■「A001」を商品マスターとする商品在庫状況が表示されない。（キャプチャーの最後の部分。）
![image](https://user-images.githubusercontent.com/8457265/86561037-a27a1500-bf9a-11ea-9b88-a901033b50d6.png)

**Comment by phssakaigawa** [comment]
はい。ご認識のとおりです

**Comment by hirossyi73** [comment]
最後の部分で「■「A001」を商品マスターとする商品在庫状況が表示されない。（キャプチャーの最後の部分。）」と記載したのですが、
・「商品在庫情報」のブロックそのものが表示されない
・「ID：1」のような、検索結果に該当するはずの行が表示されない
のどちらになりますでしょうか。

また、今回の現象はシステム管理者でも発生しますでしょうか？

**Comment by phssakaigawa** [comment]
・「ID：1」のような、検索結果に該当するはずの行が表示されない
になります。
システム管理者・一般ユーザーどちらの権限でも確認しています。

**Comment by hirossyi73** [comment]
ありがとうございます。こちらも追記いたしました、ご確認をお願いいたします。

(3)「商品在庫状況」の「商品マスター」列で表示されている見出しは、「商品マスター」の「商品コード」に該当する文字列になっておりますでしょうか。それとも、他の列との組み合わせになっておりますでしょうか。

**Comment by hirossyi73** [comment]
ありがとうございます。以下の内容をご確認いただけないでしょうか。

(1)カスタムテーブル設定の「見出し表示列設定」に遷移する。
https://exment.net/docs/#/ja/table?id=%e8%a6%8b%e5%87%ba%e3%81%97%e8%a1%a8%e7%a4%ba%e5%88%97%e8%a8%ad%e5%ae%9a
の「見出し表示列設定」

(2)こちらの設定で「商品コード」が設定されていることを確認する。

**Comment by phssakaigawa** [comment]
ありがとうございます。

商品在庫テーブルの見出し表示列設定へ、商品コードを設定し、確認を行ないましたが、
変化がありません

**Comment by hirossyi73** [comment]
商品マスターの見出し表示列に、商品コードを追加した場合はどうでしょうか？

**Comment by phssakaigawa** [comment]
ありがとうございます。無事表示ができるようになりました

**Comment by hirossyi73** [comment]
ありがとうございます。

こちらは以前、参照先のテーブルの「見出し列」の設定内容に沿って、画面に表示される文言を検索バーに入力すれば、見出しの内容で検索できるよう機能追加しました。

![image](https://user-images.githubusercontent.com/8457265/86569021-c6dcee00-bfa8-11ea-8adc-b69bdf7ff693.png)

ですが、「見出し列」が1件も存在しない場合の考慮ができておりませんでした。
次回リリースで、「見出し列」が1件も存在しない場合、画面に合わせて、カスタム列の1件目でヒットするように修正します。

**Comment by hirossyi73** [comment]
ｖ3.4.1にて、見出し列が0件でも、ヒットするように修正しました。
※検索時の仕様のマニュアルも追記しています。
https://exment.net/docs/#/ja/search
