### ISSUE TITLE
ブラウザの横幅が狭い場合に検索窓が消える

### ISSUE THREAD

**Issue by saku09** [exceedone/exment#708]
**Describe the bug / バグの説明**
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
ブラウザの横幅が狭い場合に検索窓が消える

**To Reproduce / 再現手順**
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
ブラウザの横幅を狭める

**Version / 発生バージョン**
Please describe version. / ご利用のバージョンを記載してください。
v3.3.2

**Error log / エラーログ**
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。
N/A

**Screenshots / スクリーンショット**
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。
<img width="1271" alt="スクリーンショット 2020-07-08 15 09 59" src="https://user-images.githubusercontent.com/803254/86883689-57443b80-c12d-11ea-9999-38ba843e338e.png">

**Additional context / その他**
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。
N/A

**Comment by hirossyi73** [comment]
v3.4.1にて、幅の指定を修正しました。
