### ISSUE TITLE
Excelインポートでユーザー登録しパスワード変更を行うと、ログインできない場合がある

### ISSUE THREAD

**Issue by tmmuras** [exceedone/exment#709]
**Describe the bug / バグの説明**
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
ユーザー->Excelインポートで新規作成　当該ユーザについて、ログインユーザー設定->Excelインポートでパスワード設定
の操作を行うとき、英数記号8文字以下のパスワードで登録すると、当該ユーザはログインできない。

**To Reproduce / 再現手順**
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
画像添付します。
<img width="434" alt="issue" src="https://user-images.githubusercontent.com/66045161/86982848-33cccf80-c1c5-11ea-8fbd-ce5a02b9e1e7.png">

**Version / 発生バージョン**
Please describe version. / ご利用のバージョンを記載してください。
ver3.3.2

**Error log / エラーログ**
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。
[laravel.log](https://github.com/exceedone/exment/files/4893816/laravel.log)

**Screenshots / スクリーンショット**
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。
再現手順のファイルに画像もあり

**Additional context / その他**
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。
[コードを追ったわけではないですがおそらく、ログインのロジックにパスワード制限のvalidationが含まれているためだと思います。ただしログイン時のValidationから外すのは適切ではないと思われますので、Excelインポート時のロジックに加えていただくことになるかと想定します。

**Comment by hirossyi73** [comment]
ありがとうございます、v3.4.2にて修正しました。

**Comment by hirossyi73** [comment]
> Excelインポート時のロジックに加えていただくことになるかと想定します。
こちらを追加いたしました。

**Comment by tmmuras** [comment]
ご対応ありがとうございました。添付の内容で、こちらの方でも確認とれました。
いつもありがとうございます。
<img width="651" alt="1" src="https://user-images.githubusercontent.com/66045161/87619780-fa153f00-c757-11ea-821c-7dfe116a06aa.png">
