### ISSUE TITLE
列種類ユーザーの表示専用項目の設定値を削除できる

### ISSUE THREAD

**Issue by oyama230** [exceedone/exment#716]
**Describe the bug / バグの説明**
フォーム画面において
列種類ユーザーかつ表示専用の属性を持つ欄の下に「サーチ」ボタンがあり
クリックするとポップアップ表示されるページの選択欄にいるユーザーアイコンの
×をクリックするとユーザーを削除できる、さらに「設定」ボタンをクリックすると
フォームからユーザーが削除される。

表示専用属性を持つ欄に「サーチ」ボタンの表示は不要と考えます。

**Version / 発生バージョン**
V3.4.1

**Comment by hirossyi73** [comment]
ありがとうございます、仰る通りです。
v3.4.2にて修正しました。

**Comment by oyama230** [comment]
機能の修正を確認しました。
ご対応ありがとうござました。
