### ISSUE TITLE
ユーザー情報の変更時にパスワード文字列のチェックが行われない

### ISSUE THREAD

**Issue by oyama230** [exceedone/exment#718]
**Describe the bug / バグの説明**
ユーザーのパスワードを変更する際のパスワードを4文字の英文字を入力すると保存できるがログインできない。

項目下にあるガイド表記「英数記号で8文字以上記入してください。」かつ
ログイン時のパスワード文字列に認められない場合は、エラーを表示してください。

**Comment by hirossyi73** [comment]
ありがとうございます、v3.4.2にて修正しました。

**Comment by oyama230** [comment]
機能の修正を確認しました。
ご対応ありがとうござました。
