### ISSUE TITLE
ログイン方式_openLDAP対応

### ISSUE THREAD

**Issue by Nemzo** [exceedone/exment#725]
**Describe the feature you'd like / 機能する機能の説明を行ってください**
A clear and concise description of what you want to happen. / あなたが何をしたいのかについての、明確で簡潔な説明を行ってください。
ログイン方式にopenLDAPも対応してもらいたい

**Additional context / その他**
Add any other context or screenshots about the feature request here. / 機能リクエストに関する他のコンテキストまたはスクリーンショットをここに追加します。

**Comment by hatsu1119** [comment]
あまり美しくないですが、Exceedone\Exment\Services\Login\Ldap\LdapService.phpをカスタマイズして自社のOpenLDAPで認証できてます。

LDAPスキーマ選択と検索フィルタのパラメータ化がポイントです。

[LdapService.php.zip](https://github.com/exceedone/exment/files/4937535/LdapService.php.zip)

**Comment by hirossyi73** [comment]
@hatsu1119 
あまり知見がなく恐縮なのですが、LDAPスキーマ選択と検索フィルタ項目は、LDAPにおいて汎用的な内容でしょうか？
プルリクエストいただければ、エンジンへの取込も可能です。

**Comment by hatsu1119** [comment]
スキーマ選択は、単にadldapでAD以外にもクラスが用意されているので選択式にしたに過ぎず，汎用的かどうかまでは確認していません。(気持ち的に名前を合わせたかった)
なのでOpenIPAでは認証の検証すら取ってません。
また、Exceedone\Exment\Services\Login\Ldap::syncLdapUser()の$provider->search()->users()では，その実体クラスである\Adldap\Query\Factory::users()においてldapクエリの検索フィルタがセットされ、これのデフォルト値がOpenLDAPクラスだと(&(objectClass=user)(objectClass=person))になっていて、当方の組織で運用しているOpenLDAPのスキーマ定義に噛み合いませんでした。それで検索フィルタを設定項目に追加した次第です。
組織内の特定の属性をもったユーザに絞るなど、検索フィルタはどのLDAPに対しても汎用だと思います。

**Comment by Nemzo** [comment]
頂いたphpにてLdapService.php修正した所、ldapログインクリック後(画面遷移後)に下記エラーが発生致しました。
またこちらの運用環境としてldap上にはメールアドレス項目が無く、マッピング設定ではuidなど適当な項目をマッピングしております。下記エラーと関係はございますでしょうか。

＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
local.ERROR: Call to undefined method Adldap\Models\Entry::getAuthIdentifier() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method Adldap\\Models\\Entry::getAuthIdentifier() at /var/www/exment/vendor/exceedone/exment/src/Services/Login/Ldap/LdapUser.php:29)
[stacktrace]
[laravel.log](https://github.com/exceedone/exment/files/5025433/laravel.log)

**Comment by tmmuras** [comment]
同じく実装を希望します
こちら自社でもハードコーディングにはなりますが、OpenLdap向け処理を実装し運用しているものの
ver.UP都度ソースに取り込むことは現実的ではないため、実装を希望しております。
何卒よろしくお願いいたします

**Comment by hirossyi73** [comment]
こちらですが、openLDAP形式のLDAP環境をこちらで整えることが少々難しい都合上、修正の上プルリクエスト頂ければ、対応可能です。

**Comment by m-hagane** [comment]
「LDAPスキーマ選択と検索フィルタのパラメータ化」使わせていただきました。
V5.0.3 だと、patchコマンドでエラーが出てしまったので、ソース見ながら修正しました。
差分をアップさせていただきます。
[LdapService_patch.zip](https://github.com/exceedone/exment/files/9571523/LdapService_patch.zip)

**Comment by KajitoriAdmin** [comment]
@m-hagane 
LdapService_patch ありがとうございます。
社内テストしましてOKだったので、masterにマージさせていただければと思います。
よろしいでしょうか？

**Comment by m-hagane** [comment]
はい、よろしくお願いします
