### ISSUE TITLE
ユーザー間のメッセージ機能

### ISSUE THREAD

**Issue by Yuusuke9228** [exceedone/exment#727]
**Describe the feature you'd like / 機能する機能の説明を行ってください**
ユーザー間での、個別メッセージをやり取りできる機能があると良い。（社内メール機能）

小規模企業では、複数人で共有で１台のPCを使用しているケースが多く、個人のメールアドレスを用意していないケースがあるので、アプリケーション内でログインした際に、個別ユーザーがメッセージ機能を使用できると良いと思います。

欲を言えば、リアルタイムチャット機能・グループチャット機能なども良いと思うが、最低限メッセージ機能がある事で、使い勝手が格段に向上すると思います。

**Comment by oyama230** [comment]
v3.4.0 (2020/07/03)に追加された
テーブル毎のデータ自動共有設定追加。データ保存時、値として設定されている組織またはユーザーに、自動的にデータを共有することができます。詳細は[こちら](https://exment.net/docs/#/ja/table?id=%E3%83%87%E3%83%BC%E3%82%BF%E8%87%AA%E5%8B%95%E5%85%B1%E6%9C%89%E8%A8%AD%E5%AE%9A)を利用すれば簡易的なメール機能は実現できると思います。
