### ISSUE TITLE
V3.4.0からV3.5.4にアップグレード後、入力フォームが開かなくなりました。

### ISSUE THREAD

**Issue by tetsukami** [exceedone/exment#741]
**Describe the bug / バグの説明**
V3.4.0からV3.5.4にアップグレード後、編集ボタンを押した際や新規ボタンを押した際に
入力フォームが開かなくなってしまいました。

**To Reproduce / 再現手順**
一覧から「新規」をクリックするとエラーとなります。
また、一覧から既存データをクリックし、詳細を表示後、「編集」をクリックしても同様です。

**Version / 発生バージョン**
V3.5.4

**Error log / エラーログ**
[laravel.log](https://github.com/exceedone/exment/files/5039984/laravel.log)

**Screenshots / スクリーンショット**
![error](https://user-images.githubusercontent.com/69305303/89622127-80432200-d8cd-11ea-8c45-11269576356d.PNG)

**Additional context / その他**
アップグレード時、下記のメッセージが表示されましたが、関係ございますでしょうか。
![upgrade](https://user-images.githubusercontent.com/69305303/89622174-951fb580-d8cd-11ea-820d-f27e0fc21d01.png)

この後のExmentのアップグレード自体は問題なく終了したものと思います。
お手数ではございますが、ご確認いただけます様よろしくお願いいたします。

**Comment by hirossyi73** [comment]
以下のコマンドを実行した時に、どのような表示になりますでしょうか。
composer require exceedone/laravel-admin

**Comment by tetsukami** [comment]
ありがとうございます。
実行結果を添付いたします。
![result1](https://user-images.githubusercontent.com/69305303/89624487-4542ed80-d8d1-11ea-9441-deb713329b84.png)
![result2](https://user-images.githubusercontent.com/69305303/89624325-06149c80-d8d1-11ea-8d31-3388497cf89c.png)

当方の作業にてちゃんとアップグレードがなされていなかったものと思われます。
上記後、新規、編集ともに入力画面が表示されることを確認いたしました。

お騒がせして申し訳ございませんでした。
