### ISSUE TITLE
インポートが実行出来ません（インポートファイルが見つからない？）

### ISSUE THREAD

**Issue by tetsukami** [exceedone/exment#750]
**Describe the bug / バグの説明**
データのインポートが行えません。画面上は何も起きておらず、ログにエラーが出力されます。

**To Reproduce / 再現手順**
カスタムテーブルAを作成。カスタム列に1行テキストを追加。
インポートのテンプレート出力にてExcelテンプレートを出力
出力したテンプレートのカスタム列に1文字入力。保存。
インポートより該当ファイルを指定してインポート
画面では何も起きず。
データはインポートされておらず、ログにはエラーが出力されており、
[2020-08-19 10:48:40] local.ERROR: File "" does not exist.
ファイルが無いといった内容。

**Version / 発生バージョン**
V3.5.4

**Error log / エラーログ**
[2020-08-19 10:48:40] local.ERROR: File "" does not exist. {"userId":1,"email":"XXXXX_XXXXX@XXXXXX","exception":"[object] (InvalidArgumentException(code: 0): File \"\" does not exist. at C:\\exment\\vendor\\phpoffice\\phpspreadsheet\\src\\PhpSpreadsheet\\Shared\\File.php:135)
[stacktrace]
#0 C:\\exment\\vendor\\phpoffice\\phpspreadsheet\\src\\PhpSpreadsheet\\Reader\\Xlsx.php(320): PhpOffice\\PhpSpreadsheet\\Shared\\File::assertFile(false)
#1 C:\\exment\\vendor\\exceedone\\exment\\src\\Services\\DataImportExport\\Formats\\Xlsx.php(55): PhpOffice\\PhpSpreadsheet\\Reader\\Xlsx->load(false)
#2 C:\\exment\\vendor\\exceedone\\exment\\src\\Services\\DataImportExport\\DataImportExportService.php(204): Exceedone\\Exment\\Services\\DataImportExport\\Formats\\Xlsx->getDataTable(Object(Illuminate\\Http\\Request))
#3 C:\\exment\\vendor\\exceedone\\exment\\src\\DataItems\\Grid\\DefaultGrid.php(472): Exceedone\\Exment\\Services\\DataImportExport\\DataImportExportService->import(Object(Illuminate\\Http\\Request))
#4 C:\\exment\\vendor\\exceedone\\exment\\src\\Controllers\\CustomValueController.php(371): Exceedone\\Exment\\DataItems\\Grid\\DefaultGrid->import(Object(Illuminate\\Http\\Request))
#5 [internal function]: Exceedone\\Exment\\Controllers\\CustomValueController->import(Object(Illuminate\\Http\\Request), 'SampleImport')
#6 C:\\exment\\vendor\\exceedone\\exment\\src\\Controllers\\AdminControllerTableBase.php(54): call_user_func_array(Array, Array)
#7 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(45): Exceedone\\Exment\\Controllers\\AdminControllerTableBase->callAction('import', Array)
#8 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Exceedone\\Exment\\Controllers\\CustomValueController), 'import')
#9 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(169): Illuminate\\Routing\\Route->runController()
#10 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(665): Illuminate\\Routing\\Route->run()
#11 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#12 C:\\exment\\vendor\\exceedone\\laravel-admin\\src\\Middleware\\Session.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#13 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(151): Encore\\Admin\\Middleware\\Session->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#14 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 C:\\exment\\vendor\\exceedone\\laravel-admin\\src\\Middleware\\Permission.php(42): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#16 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(151): Encore\\Admin\\Middleware\\Permission->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 C:\\exment\\vendor\\exceedone\\laravel-admin\\src\\Middleware\\Bootstrap.php(15): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(151): Encore\\Admin\\Middleware\\Bootstrap->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 C:\\exment\\vendor\\exceedone\\exment\\src\\Middleware\\LogOperation.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(151): Exceedone\\Exment\\Middleware\\LogOperation->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 C:\\exment\\vendor\\exceedone\\laravel-admin\\src\\Middleware\\Pjax.php(24): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#25 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(151): Encore\\Admin\\Middleware\\Pjax->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 C:\\exment\\vendor\
enatomarinho\\laravel-page-speed\\src\\Middleware\\PageSpeed.php(28): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#28 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(151): RenatoMarinho\\LaravelPageSpeed\\Middleware\\PageSpeed->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 C:\\exment\\vendor\
enatomarinho\\laravel-page-speed\\src\\Middleware\\PageSpeed.php(28): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(151): RenatoMarinho\\LaravelPageSpeed\\Middleware\\PageSpeed->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 C:\\exment\\vendor\
enatomarinho\\laravel-page-speed\\src\\Middleware\\PageSpeed.php(28): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(151): RenatoMarinho\\LaravelPageSpeed\\Middleware\\PageSpeed->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 C:\\exment\\vendor\\exceedone\\exment\\src\\Middleware\\Bootstrap.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#37 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(151): Exceedone\\Exment\\Middleware\\Bootstrap->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 C:\\exment\\vendor\\exceedone\\exment\\src\\Middleware\\Morph.php(20): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#40 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(151): Exceedone\\Exment\\Middleware\\Morph->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 C:\\exment\\vendor\\exceedone\\exment\\src\\Middleware\\AuthenticatePasswordLimit.php(24): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#43 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(151): Exceedone\\Exment\\Middleware\\AuthenticatePasswordLimit->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 C:\\exment\\vendor\\exceedone\\exment\\src\\Middleware\\Authenticate2factor.php(23): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#46 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(151): Exceedone\\Exment\\Middleware\\Authenticate2factor->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 C:\\exment\\vendor\\exceedone\\exment\\src\\Middleware\\Authenticate.php(39): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#49 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(151): Exceedone\\Exment\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 C:\\exment\\vendor\\exceedone\\exment\\src\\Middleware\\Initialize.php(67): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#52 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(151): Exceedone\\Exment\\Middleware\\Initialize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 C:\\exment\\vendor\\exceedone\\exment\\src\\Middleware\\IpFilterBase.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#55 C:\\exment\\vendor\\exceedone\\exment\\src\\Middleware\\WebIPFilter.php(15): Exceedone\\Exment\\Middleware\\IpFilterBase->handleBase(Object(Illuminate\\Http\\Request), Object(Closure), 'web_ip_filters')
#56 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(151): Exceedone\\Exment\\Middleware\\WebIPFilter->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 C:\\exment\\vendor\\exceedone\\exment\\src\\Middleware\\Browser.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#59 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(151): Exceedone\\Exment\\Middleware\\Browser->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#62 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(151): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#63 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#64 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php(68): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#65 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#66 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#67 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#68 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(151): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#69 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#70 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#71 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(151): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#72 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#73 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#74 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(151): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#75 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#76 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#77 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(151): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#78 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#79 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#80 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(667): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#81 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(642): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#82 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(608): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#83 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(597): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#84 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#85 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#86 C:\\exment\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#87 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#88 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#89 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#90 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#91 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#92 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#93 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#94 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#95 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#96 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#97 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#98 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#99 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#100 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#101 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#102 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#103 C:\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#104 C:\\exment\\public\\index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#105 {main}
"} 

**Screenshots / スクリーンショット**
![キャプチャ](https://user-images.githubusercontent.com/69305303/90583497-41856400-e20b-11ea-8a94-632b4d608cd5.PNG)
[テスト用インポート20200819104743.xlsx](https://github.com/exceedone/exment/files/5093651/20200819104743.xlsx)

**Additional context / その他**
テスト用に使ったインポート用のExcelも添付させていただきます。

お忙しいところ申し訳ございませんが、ご確認よろしくお願いいたします。

**Comment by tetsukami** [comment]
その後も調査を続けていますが、カスタム列にファイルを設定し、保存しようとしたところ、エラーとなる事がわかりました。
![キャプチャ2](https://user-images.githubusercontent.com/69305303/91155687-241a3380-e6fe-11ea-828c-ae219982fe6e.PNG)

サーバの設定問題でファイルがアップロード出来ていない様に感じ、
php,iniの確認などを実施しましたが、原因がつかめていません。
環境としてはWindows Serverによる環境構築を実施し、立ち上げ時は下記でした。

Windows Server 2016　Datacenter
PHP　7.3.20
MySQL 5.7.29
Exment V3.4.0
その後、V3.5.4 → V3.6.0までバージョンアップを実施した環境となります。

**Comment by dev-hayash** [comment]
横からすいません。

再現手順で「カスタム列に1行テキストを追加。」とあるのですが、
「カスタム列にファイルを設定し、保存しようとしたところ、エラーとなる事がわかりました。」という追記があります。

カスタム列は『ファイル』なのですか？『1行テキスト』なのですか？

**Comment by tetsukami** [comment]
dev-hayash様
ありがとうございます。混乱を招く書き方で申し訳ありません。
補足させていただきますと、当初、インポートを実行しようとしていて、「1行テキスト」1つのテーブルを作成しました。
インポートをテストしたところ、ファイルが見つからないというエラーでしたので、
通常のファイルの登録はどうなのだろうと思い、
「1行テキスト」のみのテーブルに、「ファイル」列を追加し、フォームからファイルアップロードをしたところ、
フォーム上ではアップロードしたファイルが表示されているのですが、「保存」ボタンを押したところエラーとなった次第です。

**Comment by 48ne89** [comment]
おそらくファイルインポートに関わらず全てのアップロードが失敗している状態ではないでしょうか。
プラグインのアップロードやテンプレートのアップロード等も失敗すると思います。
以前、Windows ServerでIISを使用していたところ同様の事象が発生していました。
原因は不明なのですが、IISではなくApacheで動作させたところ正常に動作しました。

**Comment by tetsukami** [comment]
48ne89様
ありがとうございます。おっしゃる通り、全てのファイルアップロードが失敗している状態と思われます。
Windows Server、IIS使用で同様の事象が発生していて、Apacheに変更されたところ正常に動作されたとのこと、承知しました。確かにXAMPPで構築した開発環境では問題なくファイル登録が行えています。
ですが社の都合で、出来ればIISで動かしたいところです。。。

**Comment by tetsukami** [comment]
Windows Server IIS使用の場合、PHP側に追加設定が必要との事でした。
PHP.ini内のupload_tmp_dirに任意の作業用フォルダパスの設定とIIS_IUSRSの書き込み権限が必要。

例）
C:\tempというフォルダを作成。
PHP.iniを開き、下記を設定。
upload_tmp_dir = "C:\temp"
また、PHP.ini内に「exstension=php_fileinfo.dll」という記載がある場合はコメントアウトを解除しておく。
弊社環境では「extension=fileinfo」という記載でした。
その後、作成したtempフォルダにてIIS_IUSRSに書き込み権限を付与する。

IIS再起動後、弊社環境ではファイルアップロードが出来る様になりました。
