### ISSUE TITLE
CSVインポート時に列種類「1行テキスト」に半角数字が入らない

### ISSUE THREAD

**Issue by yjmtmtk** [exceedone/exment#754]
**Describe the bug / バグの説明**
csvでインポートを行う際に、
列種類が「1行テキスト」のフィールドに
半角数字だけを記入していると、
「XXX(yyyy)には文字列を指定してください。」
とエラーになってしまう。

1←はいならい
01←頭にゼロの付いている半角数字ならはいる

**Version / 発生バージョン**
Version   v3.5.4

**Comment by hirossyi73** [comment]
v3.6.2にて修正しました。
