### ISSUE TITLE
役割グループに「親組織」を設定すると、子組織のユーザーに権限が割り当てられてしまう。

### ISSUE THREAD

**Issue by KenjiMorimoto** [exceedone/exment#756]
**Describe the bug / バグの説明**
**To Reproduce / 再現手順**
組織A（最上位）
　組織B
　　組織C
のような３段階の組織構成で、組織Aには管理権限、組織Bには編集権限、組織Cには閲覧権限を設定したい場合、
役割りグループの設定で管理権限を組織A、編集権限を組織B、閲覧権限を組織Cに割り当てると、組織Cに所属しているユーザーに管理権限が割り当てられてしまう。

**Version / 発生バージョン**
3.6.1

**Error log / エラーログ**
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

**Screenshots / スクリーンショット**
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

**Additional context / その他**
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。
本来、最下部の組織に割り当てられた権限は当然のごとく上位の組織に引き継ぐべきだと思うが、上位の組織に割り当てられた権限が、その組織の下位となる組織に引き継いでしまうのはおかしいのではないかと思う。

現状の考え方だと、組織管理において、親組織という概念を取り外し、役割グループで組織の階層イメージを作らなければならないように思える。

**Comment by hirossyi73** [comment]
こちらをどうぞ
https://exment.net/docs/#/ja/organization

**Comment by KenjiMorimoto** [comment]
> こちらをどうぞ
> https://exment.net/docs/#/ja/organization

マニュアルを最後までちゃんと確認せず、大変致しました。
ありがとうございました。
思い通りの動作になってくれました。
