### ISSUE TITLE
「テンプレート」にメニューの表示ビューが反映されない

### ISSUE THREAD

**Issue by shimaday8** [exceedone/exment#760]
**Describe the bug / バグの説明**
「テンプレート」にメニューの表示ビューが反映されません。

**To Reproduce / 再現手順**
1. メニューをテンプレートにエクスポートします。
2. エクスポートしたテンプレートを別環境にインポートします。
3. インポート先でメニューの設定を確認します。
4. テーブルデータの表示ビューが未設定になっています。エクスポート元では設定されています。

**Version / 発生バージョン**
v3.6.2

**Screenshots / スクリーンショット**

* エクスポート元
![@menu1](https://user-images.githubusercontent.com/66708775/92350824-16f53f80-f115-11ea-88fe-221445f51db8.png)

* インポート先
![@menu2](https://user-images.githubusercontent.com/66708775/92350830-1bb9f380-f115-11ea-895b-1fb50012d3d7.png)

**Comment by hirossyi73** [comment]
v3.6.3にて対応しました。
※v.3.6.3以降でエクスポートしたテンプレートのみ、正常に動作しますので、ご了承ください。
