### ISSUE TITLE
「テンプレート」にフォームの見出しが最後の1つしか反映されない

### ISSUE THREAD

**Issue by shimaday8** [exceedone/exment#761]
**Describe the bug / バグの説明**
「テンプレート」にフォームの見出しが最後の1つしか反映されません。

**To Reproduce / 再現手順**
1. カスタムテーブルをテンプレートにエクスポートします。
2. エクスポートしたテンプレートを別環境にインポートします。
3. インポート先でカスタムテーブルのフォームの設定を確認します。
4. フォームの見出しが最後の1つしか設定されていません。エクスポート元では複数設定しています。

**Version / 発生バージョン**
v3.6.2

**Screenshots / スクリーンショット**

* エクスポート元
![@form1](https://user-images.githubusercontent.com/66708775/92351256-20cb7280-f116-11ea-9fc2-800592bc082b.png)

* インポート先
![@form2](https://user-images.githubusercontent.com/66708775/92351070-af8bbf80-f115-11ea-9f20-1b4cf457a7ee.png)

**Comment by hirossyi73** [comment]
@shimaday8 
現在のテンプレート出力の仕様上、修正に少々お時間かかるかもしれません。
申し訳ありませんが、よろしくお願いします。

**Comment by shimaday8** [comment]
承知しました。
インポート先で見出しを追加することにより正常に稼働しておりますので、致命的ではなく、緊急度は低いです。

**Comment by shimaday8** [comment]
修正を希望します。

**Comment by hirossyi73** [comment]
v4.1.0で、フォーム構造を修正したこともあり、対応予定です。

**Comment by hirossyi73** [comment]
2021/04/19 v4.1.0リリース完了
