### ISSUE TITLE
ユーザが所属している組織を取得したいです。

### ISSUE THREAD

**Issue by tetsukami** [exceedone/exment#762]
ユーザ/組織のリレーション関係でデータ連動設定ができない
https://github.com/exceedone/exment/issues/470#issue-522632899

過去のIssuesにてユーザとそのユーザに紐づく組織の取得がデータ連動設定で実現出来ると見かけました。
こちらは、現在でも実現可能なのでしょうか。

カスタム列にてユーザ列と組織列を追加し、フォーム設定からデータ連動設定を実施してみたところ、
ユーザの列を選択しすると、リンク列にはユーザテーブルの情報のみが表示されているようです。

![datarendo](https://user-images.githubusercontent.com/69305303/92453949-e38ce080-f1fa-11ea-987f-63f43d628d67.PNG)

どなたか情報をお持ちではないでしょうか。

**Comment by fleming35800** [comment]
投稿が古いのですでに解決されているかもしれませんが。
私も同じことで引っかかっていろいろ試しましたが、確認する限り、
現在もデータ連動では組織のデータは取得できないようです。

データ詳細設定の更新列設定でログインユーザーの所属組織は引っ張れるようですが。

![image](https://user-images.githubusercontent.com/75713203/104884275-73147e00-59a9-11eb-9e73-e033c94114b0.png)

**Comment by hirossyi73** [comment]
申し訳ございませんが、現在は、データ連動設定で、ユーザーが所属する組織を取得する機能はありません。

**Comment by fleming35800** [comment]
ご返信と情報いただきありがとうございます。
私自身気になっていた部分でもありましたので。参考にさせて頂きます。

**Comment by tetsukami** [comment]
ありがとうございます。
クローズさせていただきます。
