### ISSUE TITLE
カスタム列設定の計算式で、子テーブルの合計が1行目の数値しか反映されない

### ISSUE THREAD

**Issue by ghost987** [exceedone/exment#769]
**Describe the bug / バグの説明**
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
カスタム列設定の計算式で、リレーションをはった子テーブルの金額の合計を設定した。
フォームビューで子テーブルに金額を追加したところ、1行目の金額は正常に反映されたが、2行目以降は入力しても反映されない。
2行目以降があるときは1行目を変更しても反応しないが、2行目以降を削除して1行だけにすると、1行目の変更は反映される。

**To Reproduce / 再現手順**
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
通貨フィールドのあるテーブルを2個用意し、1対多リレーションを設定
親テーブルのフォーム設定で子テーブルを使用・フォームをテーブル形式にするを選択し、通貨フィールドを設置して保存
データ一覧から新規ボタンで作成画面に遷移し、子テーブルに金額を入力する

**Version / 発生バージョン**
Please describe version. / ご利用のバージョンを記載してください。
3.6.4

**Comment by takahiroro-dev** [comment]
@ghost987 
私も同様の事象が発生いたしましたが、取り急ぎの回避策としては子テーブルの金額欄の設定でカンマ区切り表示をオフにすると正しく計算されました。同様に、カンマ区切り不要な3桁以内の金額だと、2レコード目も正しく集計されるのではないかと思います
(カンマ付の文字列で四則演算しようとしてエラーになっているのかと)

@hirossyi-exc 
本件関連で、子テーブルの削除時に計算ロジックが動いていないようなので、ご確認いただければと思います。
