### ISSUE TITLE
検索条件「選択肢（他のテーブルの値一覧から選択）」に選択肢があらわれない

### ISSUE THREAD

**Issue by shimaday8** [exceedone/exment#772]
**Describe the bug / バグの説明**
データ一覧のフィルタで、検索項目「選択肢（他のテーブルの値一覧から選択）」に選択肢があらわれません。「少なくとも1文字を入力してください」と表示されます。文字を入力すると該当するデータがあるのに「結果が読み込まれませんでした」と表示されます。

データ新規追加や編集では正常に選択肢があらわれます。

過去のバージョンではこのような問題は発生していなかったと思います。

**Version / 発生バージョン**
v3.6.4

**Screenshots / スクリーンショット**
* フィルターの検索条件に選択肢があらわれません
![1](https://user-images.githubusercontent.com/66708775/93157446-3576be80-f745-11ea-9d76-f97197a4441c.png)

* 文字を入力しても同じです
![2](https://user-images.githubusercontent.com/66708775/93157461-3c9dcc80-f745-11ea-8387-12ecb1c00bf0.png)

* データの新規追加や編集では選択肢があらわれます
![3](https://user-images.githubusercontent.com/66708775/93157465-40315380-f745-11ea-9749-ddbc81b5faa3.png)

**Comment by hirossyi73** [comment]
@shimaday8 
こちら確認出来ました、なるべく早い段階で修正リリースいたします。

**Comment by hirossyi73** [comment]
サーバーにログインし、以下のコマンドを実行してください。
composer require exceedone/laravel-admin

※こちらの修正内容は、今後のExment本体のプログラムアップデートに含まれます。

**Comment by shimaday8** [comment]
早速のご対応ありがとうございます。
修正されていることを確認しました。

**Comment by hirossyi73** [comment]
v3.6.5を正式リリースしたので、クローズします。
