### ISSUE TITLE
関連データ検索でページネーションが機能しない

### ISSUE THREAD

**Issue by shimaday8** [exceedone/exment#774]
**Describe the bug / バグの説明**
関連データ検索の結果、複数ページに分かれて出力されているカスタムテーブルについて、ページネーションが機能しません。1,2,..という数字をクリックしても何も反応がありません。「<」や「>」も同様です。

過去のバージョンではこのような問題は発生していなかったと思います。

**Version / 発生バージョン**
v3.6.4

**Comment by hirossyi73** [comment]
@shimaday8 
すみません、こちらも開発メンバー2人で検証して再現しなかったので、詳細情報いただけると幸いです。

**Comment by shimaday8** [comment]
いくつか操作を試したところ、現象が発生する場合としない場合がありましたので、ご報告いたします。

カスタムテーブルや親子関係を一から作成しなおしてデータを登録した直後は、現象が再現しませんでした。その後、ログインしなおして関連データ検索を行ったところ、現象が再現しました。その状態で関連データ検索画面をリロードする（F5キーを押す）と、現象が再現しなくなりました。
関連データ検索画面をリロードするまでは現象が再現され続けます。また、リロードした後にログインしなおすと現象が再発します。

親子関係が「リレーション」でも「選択肢（他のテーブルの値一覧から選択）」でも発生します。

複数のブラウザで確認しましたが、現象は同じです。
Google Chrome　85.0.4183.102（Official Build） （64 ビット）
Microsoft Edge　85.0.564.51 (公式ビルド) (64 ビット)
Mozilla Firefox　80.0.1 (64 ビット)

ブラウザを起動したOSはWindows10 Pro 1909です。

情報の不足がございましたらお教えください。できる限りご提供させていただきます。

**Comment by hirossyi73** [comment]
@shimaday8 
詳細情報ありがとうございます。原因判明しました。
ダッシュボードの表示時に実施しているスクリプトで、関連データ検索のイベントを、不用意に打ち消ししてしまっていました。

不具合修正しましたので、近日修正リリース致します。

**Comment by hirossyi73** [comment]
v3.6.5にてリリースしましたので、ご確認ください。

**Comment by shimaday8** [comment]
修正されていることを確認しました。
大変ありがとうございました。
