### ISSUE TITLE
子テーブルのデータを更新するフォームでデータの更新に失敗することがある。

### ISSUE THREAD

**Issue by Yuusuke9228** [exceedone/exment#778]
**Describe the bug / バグの説明**
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
全てのデータでは無いので、原因は分かりませんが、子テーブルも同時に登録・更新できるフォームで、データを更新する際にエラーになることがある。
テキストエディターを使用している場合に発生している気がする。

**To Reproduce / 再現手順**
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
はっきりわからない。

**Version / 発生バージョン**
Please describe version. / ご利用のバージョンを記載してください。
3.6.4

**Error log / エラーログ**
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。
[2020-09-19 10:30:03] local.ERROR: Invalid argument supplied for foreach() {"userId":1,"email":"admin@example.com","exception":"[object] (ErrorException(code: 0): Invalid argument supplied for foreach() at {domain}/exment/vendor/exceedone/laravel-admin/src/Form/EmbeddedForm.php:147)

**Additional context / その他**
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

問題があるデータと、通常通りアップデートできるデータの違いがわからない。

**Comment by Yuusuke9228** [comment]
追記です
上記エラーが発生するテーブルで、新規データを作成しようとすると、下記エラーが発生して登録できません。

local.ERROR: Call to a member function setValueFilters() on null {"userId":5,"email":"admin@example.com","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function setValueFilters() on null at {domain}/exment/vendor/exceedone/exment/src/Model/Notify.php:319)

暫定的に下記の様に対象箇所をコメントアウトすると登録できる様になります。

public function isNotifyTarget($custom_value, $notify_trigger)
    {
        if (array_get($this, 'notify_trigger') != $notify_trigger) {
            return false;
        }
        $custom_view_id = array_get($this, 'custom_view_id');
        if (isset($custom_view_id)) {
            // ここから
            // $custom_view = CustomView::getEloquent($custom_view_id);
            // $query = $custom_value->custom_table->getValueModel()->query();
            // return $custom_view->setValueFilters($query)->where('id', $custom_value->id)->exists();
           // ここまで
        }
        return true;


**この現象が発生する前に、下記の様な作業を行っています。
・「on/off列」（必須項目でViewなどの条件に指定していた。）
を削除した。
※併せて条件で使用していたViewなども削除してあります。**

原因、対処法などがある様でしたら、お願いいたします。

**Comment by hirossyi73** [comment]
@Yuusuke9228 
通知設定で、削除したビューを「絞り込み条件ビュー」に設定した通知がありませんでしょうか？
もしありましたら、通知の削除などをお願いします。

※本来、通知設定などで使用されているビューを削除しようとすると、エラーになってくれることが必要なのですが、現状出来ておりませんでした。
そのため、お手数ですが、上記の削除を手動でお願いします。

**Comment by Yuusuke9228** [comment]
@hirossyi73 
ありがとうございます。
通知の条件は絞り込みViewを使用しない設定に変更してから削除していたのですが、上記のエラーが出ていました。

その通知自体を削除し、再度通知設定を行うことで問題が解消いたしました。
ありがとうございました。

**Comment by hirossyi73** [comment]
ご確認ありがとうございます。
削除前のバリデーションなど、対応べき内容を修正予定ですので、issueは再オープンさせて下さい。

**Comment by hirossyi73** [comment]
v3.6.6にて対応しました。
