### ISSUE TITLE
データ新規作成・編集時にテキストエディタやプルダウンが機能していない

### ISSUE THREAD

**Issue by daisuke-1132** [exceedone/exment#783]
**Describe the bug / バグの説明**
データ新規作成・編集時にテキストエディタやプルダウンが機能していない

**To Reproduce / 再現手順**
新規作成、編集を画面を開く、リレーションが組んであるデータのみ機能していない様子

**Version / 発生バージョン**
3.6.5

**Screenshots / スクリーンショット**
![image](https://user-images.githubusercontent.com/67406057/94160949-27047180-fec0-11ea-8990-d6ecf511e38d.png)

**Comment by hirossyi73** [comment]
v3.6.6で再現するかどうか、ご確認ください。
#785 に関連する不具合だった可能性があり、その場合はv3.6.6で解消しています。

**Comment by hirossyi73** [comment]
#785 による問題とし、こちらはクローズします。
