### ISSUE TITLE
自動採番されないことがある

### ISSUE THREAD

**Issue by oyama230** [exceedone/exment#784]
**Describe the bug / バグの説明**
自動採番にしている項目で値がセットされず欠落することが時々ある。

設定値は以下のとおり
　検索インデックス　：　YES
　1度のみ入力　　　：　YES
　採番種類　　　　　：　フォーマット
　採番フォーマット　：　${id}
　※未記載の項目はNoまたは空欄

**To Reproduce / 再現手順**

頻度は感覚値で10件の入力に対し1件程度、欠落が発生する。
発生タイミングの法則性はみられず再現方法も不明。

**Version / 発生バージョン**
Please describe version. / ご利用のバージョンを記載してください。

v3.6.5

**Error log / エラーログ**
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

**Screenshots / スクリーンショット**
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

**Additional context / その他**
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by oyama230** [comment]
採番のタイミングに問題ありませんか。
新規にデータを追加したタイミングでは、${id}採番ができていないレコードがあります。
未採番のレコードを開くタイミングで採番されることがあります。

カスタム列の保存内容を確定してからIDの採番を行っているような動きに見えます。

**Comment by hirossyi73** [comment]
自動採番は、データの作成後（IDの値が決まった後）に実施されます。

**Comment by oyama230** [comment]
保存ボタンの押下時の処理順は、フォーマット処理⇒IDの採番⇒DB書き込みと推測しています。
                                                                                        ^^^^^^
そのため新規登録のみ実施したレコードは、IDの値が決定しない状態でフォーマット処理が行われるため
自動採番${id}が空欄となる現象が発生していると考えます。

確かにデータの作成後IDの発番されている、自動採番欄が空欄のレコードをフォーム画面で開いて保存すれば
採番される事象について認識しています。

本来あるべき処理順は
IDの採番⇒フォーマット処理⇒DB書き込みとなっていると思われるのですが確認していただけませんか。
^^^^^^

**Comment by oyama230** [comment]
データを作成し保存処理の前に、ID値の採番は保証されるということでしょうか？

**Comment by oyama230** [comment]
[自動採番されないことがある.pdf](https://github.com/exceedone/exment/files/5315504/default.pdf)

採番されないデータのスクリーンショット＋まとめを添付させていただきました。
