### ISSUE TITLE
テキストエディタタイプのカスタム列を1つのフォーム内で複数使用すると、登録・編集時にJavaScriptのエラーが発生します。

### ISSUE THREAD

**Issue by sayoko-iwahashi** [exceedone/exment#785]
**Describe the bug / バグの説明**
テキストエディタタイプのカスタム列を1つのフォーム内で複数使用すると、編集時にJavaScriptのエラーが発生していて
テキストエディタが無効になってしまいます。
同様に日付等、JavaScriptを利用しているカスタム列も手打ちしかできなくなります。

**To Reproduce / 再現手順**

**Version / 発生バージョン**
Version   v3.6.5

**Error log / エラーログ**

**Screenshots / スクリーンショット**

**Additional context / その他**

**Comment by hirossyi73** [comment]
@sayoko-iwahashi 
一時的に、こちらのファイルを、vendor\exceedone\exment\src\Form\Fieldに差し替えでいかがでしょうか？
[Tinymce.php](https://github.com/exceedone/exment/blob/hotfix/src/Form/Field/Tinymce.php)

**Comment by sayoko-iwahashi** [comment]
ファイルの置き換えでうまくいきました。
ご対応ありがとうございました。
