### ISSUE TITLE
アップロードしたファイルのダウンロードができない

### ISSUE THREAD

**Issue by kazt117** [exceedone/exment#788]
ファイルをアップロードし、アップロードしたファイルをダウンロードをしようとすると下記のエラーメッセージが表示される。
エラーメッセージ：
Class 'finfo' not found
エラー詳細：
　長いため、添付にしました。

インストール環境：
　windows10　64ビット
　IIS
　mysql　5.7.31
　php　7.3.22
　Exment　3.6.5

[エラー詳細.txt](https://github.com/exceedone/exment/files/5285885/default.txt)

**Comment by hirossyi73** [comment]
環境依存のためクローズ
