### ISSUE TITLE
ログインできない

### ISSUE THREAD

**Issue by eliaya** [exceedone/exment#789]
**Describe the bug / バグの説明**
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
詳しくは説明でないませんが簡単に言うとある時間の後ログアウトされてしましましたが（SESSIONタイムアウトとなる）
ユーザーとパスワード入力間違えないはずなんですがログインできません

**To Reproduce / 再現手順**
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
. Docker Compose stack 立てし起動
. EXmentをインストール初期画面にセトアップして
. 最初はadmin ユーザーはログインできで
. あることしたりやってたりとか
. 何もせず何時間か後ログアウトされてしましました後でもう一度ログインできません

**Version / 発生バージョン**
Please describe version. / ご利用のバージョンを記載してください。
ログインできませんですからv3.6.5 (2020/09/22)を利用させていただくと思います

**Error log / エラーログ**
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。
ありません

**Screenshots / スクリーンショット**
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。
https://imgur.com/a/YSQd2Ml

**Additional context / その他**
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by kohki-shikata** [comment]
I have two questions.

1. Can you describe "あることしたりやってたりとか" in more detail?
2. Can you paste here your docker-compose.yml?

**Comment by eliaya** [comment]
thank for reply,sorry for the late response.
after push a latest version(v3.6.6 (2020/09/28)) from repository it was works fine now thanks.
I guess the problem was when i remove the email setting in Custom Form Setting?then i cant login(tried install and reinstall extment many times for this case)

Also i tried Nginx-Proxy with Exment on docker and get this problem,but localhost (macOS Catalina) without any issue.

返信してくれてサンクス〜リプレイ遅くてすみません
新しv3.6.6 (2020/09/28)をダンロートして何日か試して見たら無事で働いてます😀
システムに「Custom Form Setting」でメールアドレスを表示されないと設定するとログインできないって関係があるかと思います

とはいえDockerでNginx-Proxy とExment2つを組み立てるとの影響を受けているのかと考えています
