### ISSUE TITLE
インポートプラグインにおいても取り込み異常をクライアントに返却したい

### ISSUE THREAD

**Issue by dev-hayash** [exceedone/exment#794]
**Describe the feature you'd like / 機能する機能の説明を行ってください**
A clear and concise description of what you want to happen. / あなたが何をしたいのかについての、明確で簡潔な説明を行ってください。
インポートプラグインのexecute()が返すのはbooleanだけですが、デフォルトのインポートのように取り込んだデータの行番号などをクライアントに返却したい。

PR送ります。

**Additional context / その他**
Add any other context or screenshots about the feature request here. / 機能リクエストに関する他のコンテキストまたはスクリーンショットをここに追加します。

**Comment by hirossyi73** [comment]
PRありがとうございます！
masterブランチに取り込み、v3.6.7にてリリースしましたので、ご確認ください。

**Comment by dev-hayash** [comment]
ありがとうございます。
