### ISSUE TITLE
N:Nのリレーションの紐付けがインポートで登録できない

### ISSUE THREAD

**Issue by y-hayama** [exceedone/exment#799]
**Describe the bug / バグの説明**
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

N:Nのリレーションを貼っている複数のテーブルがある場合、紐付けがインポートで登録できないテーブルがあります

**To Reproduce / 再現手順**
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

1. テーブルA,B,Cを作成して、それぞれ数件データを登録する
2. A-B, A-C 間でテーブルAを親にしてN:Nのリレーションを貼る
3. xlsx形式のファイルでA-B, A-C 間のリレーションをそれぞれ数件登録し、インポートする
4. A-B 間のデータはリレーションが貼られるが、A-C 間のデータはリレーションが貼られない

**Version / 発生バージョン**
Please describe version. / ご利用のバージョンを記載してください。

v3.6.6

**Comment by hirossyi73** [comment]
v5.6.8にて修正しましたので、ご確認ください。

**Comment by y-hayama** [comment]
修正されていることを確認しました。ありがとうございます！
