### ISSUE TITLE
ドットが連続するメールアドレスを登録できない

### ISSUE THREAD

**Issue by yjmtmtk** [exceedone/exment#800]
**Describe the bug / バグの説明**

列種類　メールアドレス 
にて

昔のドコモなどで利用できた
aaa..bbbb.cc@docomo.ne.jp
xxx.yyy.@docomo.ne.jp
などのドットが連続したり＠の前にドットがあるメールが弾かれて登録できない。

メーラーやメール送信システム（Sendgrid等）では
"aaa..bbbb.cc"@docomo.ne.jp
"xxx.yyy."@docomo.ne.jp
などダブルクォートで囲むと送信できます。

昔のガラケーを利用している顧客のメールアドレスを登録できなくなる可能性があるので、
修正をお願いしたいです。

**Version / 発生バージョン**
Version   v3.6.6

**Comment by yjmtmtk** [comment]
インポートでは
"aaa..bbbb.cc"@docomo.ne.jp
ダブルクォートで囲んでの登録ができるのを確認しました。

**Comment by hirossyi73** [comment]
Laravel5.6では、RFC822準拠でメールアドレスのバリデーションを行っています。これは、ドットの連続のようなメールアドレスは違反とみまします。
Exmentの標準としては、メールアドレスはドットの連続はバリデーションエラーと考えています。
