### ISSUE TITLE
集計ビューの昇順／降順ソートが機能していない

### ISSUE THREAD

**Issue by dev-hayash** [exceedone/exment#807]
**Describe the bug / バグの説明**
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

仕様なのか判断がつかないのですがレポートします。
集計ビューを作成し、グループ列を１つ指定しました。
グループ列の並び替えを昇順にしても降順にしても、一覧表示の結果が変わりませんでした。

**To Reproduce / 再現手順**
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

2020/10/13 16:45時点のデモサイトに集計ビューを作成しました。
https://demo-jp.exment.net/admin/data/project?view=6e44387507c14bf86873

【降順の場合】
●設定内容
![image](https://user-images.githubusercontent.com/19341340/95832090-d07aac80-0d74-11eb-8f54-081332fabdf5.png)

●表示結果
![image](https://user-images.githubusercontent.com/19341340/95832140-e25c4f80-0d74-11eb-83bf-ec655ce96fa3.png)

【昇順の場合】
●設定内容
![image](https://user-images.githubusercontent.com/19341340/95832255-0455d200-0d75-11eb-9f33-ccfab280385f.png)

●表示結果
![image](https://user-images.githubusercontent.com/19341340/95832286-0d46a380-0d75-11eb-93bb-80518455b8a6.png)
降順と変わっていません。

**Version / 発生バージョン**
Please describe version. / ご利用のバージョンを記載してください。
v3.6.8

**Comment by hirossyi73** [comment]
昇順・降順の設定は、並べ替え設定の隣の「並び順」があった上での設定となるので、そちらの設定をお願いします。

**Comment by dev-hayash** [comment]
ありがとうございます。
確認できました。

お手数をおかけいたしました。
closeさせて頂きます。
