### ISSUE TITLE
フリーワード検索対象にしてもカスタム列表示画面でチェックがつかない

### ISSUE THREAD

**Issue by masayoshist** [exceedone/exment#813]
**Describe the bug / バグの説明**
フリーワード検索対象にしてもカスタム列表示画面でチェックがつきません。
ですが実際にはフリーワード検索は可能です。

**To Reproduce / 再現手順**
カスタム列設定より、ある行のフリーワード検索対象を有効にする
カスタム列一覧のフリーワード検索対象列の表示にチェックがつかない

**Version / 発生バージョン**
Version   v3.7.0

**Error log / エラーログ**
ログ出力はありませんでした。

**Screenshots / スクリーンショット**
![91](https://user-images.githubusercontent.com/57345418/96349278-7a499880-10e9-11eb-9a6e-487be7230bbb.PNG)
![92](https://user-images.githubusercontent.com/57345418/96349279-7b7ac580-10e9-11eb-9012-e93dbdce9a83.PNG)

**Additional context / その他**
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by hirossyi73** [comment]
ありがとうございます。v3.7.1にて修正ました。
