### ISSUE TITLE
インポートで同じ主キーのレコードができてしまう

### ISSUE THREAD

**Issue by dev-hayash** [exceedone/exment#817]
**Describe the bug / バグの説明**
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

テーブルの主キーを他テーブルの値から選択にした場合、インポートで同じ主キーのレコードができてしまいます。

**To Reproduce / 再現手順**
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

準備：テーブルAとBを作成します。

＜テーブルA＞
カラム１： 必須 、 検索インデックス 、ユニーク(一意)を指定

＜テーブルB＞
カラム１： 必須 、 検索インデックス 、ユニーク(一意)を指定し、テーブルAのカラム１から選択するようにします。
　　　　　インポート時のキー列、エクスポート時のキー列にカラム１を指定します。

手順１．テーブルAにレコードを登録します。
手順２．テーブルBにレコードを登録（手順１のレコードを選択）します。
手順３．テーブルBをエクスポートします。
手順４．テーブルBをそのままインポートします。インポート時の主キーはカラム１を選択します。

結果、テーブルBに手順２で登録したレコードがもう一つ追加されます。
テーブルBのカラム１はユニークであってほしいですが、同一の値が登録されます。

有ってほしい動作は、インポートしたレコードのキーが既に存在する場合は、上書きの動作であってほしいです。

**Version / 発生バージョン**
Please describe version. / ご利用のバージョンを記載してください。
v3.6.6

**Error log / エラーログ**
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

ログへの出力はありませんでした。

**Screenshots / スクリーンショット**
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

以下は、テーブルBのインポート直後で、PCS-201408-001の文字列がテーブルAの選択値です。
![image](https://user-images.githubusercontent.com/19341340/96559352-e39ef680-12f7-11eb-9506-ee55ae6b8244.png)

**Additional context / その他**
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

最新環境(v3.7.1)のデモサイトで再現確認を行ってみました。
https://demo-jp.exment.net/admin/data/table_a
https://demo-jp.exment.net/admin/data/table_b

上記はそれぞれ、テーブルAとテーブルBです。
テーブルBでエクスポートし、そのままのファイルをインポート（送信ボタンをクリック）すると、ボタンのcaptionが loading... に変わり、その後「送信」に戻るので、恐らくインポート処理でエラーが起きているように思います。

**Comment by hirossyi73** [comment]
インポート時のキー制御は、v3.7.0にて修正しておりますので、まずはそちらにアップデートいただけないでしょうか。
v3.7.1デモ環境でのメッセージ表示は、一度確認します。

**Comment by dev-hayash** [comment]
早急な御回答ありがとうございます。
アップデートについて、了解しました。

デモ環境に再現のデータを追加してしまい申し訳ありません。
close時に削除いたします。

**Comment by dev-hayash** [comment]
遅くなって申し訳ありません。
v3.7.2で実行してみました。

親と子のテーブルデータは以下の通りです。
![image](https://user-images.githubusercontent.com/19341340/97659552-97e80c00-1ab2-11eb-8c05-701eb1d71ba5.png)

子テーブルの１レコードをエクスポートして、そのまま子テーブルにインポートしました。
インポート時には子テーブルのユニークキーを指定します。

![image](https://user-images.githubusercontent.com/19341340/97659440-5fe0c900-1ab2-11eb-9352-47e5c74c5905.png)

実行時のLaravel.logを添付します。
[laravel.log](https://github.com/exceedone/exment/files/5462979/laravel.log)

インポートに使用したExcelはこちらです。
[テスト子テーブル20201030131424.xlsx](https://github.com/exceedone/exment/files/5462984/20201030131424.xlsx)


本件の状況を整理しますと、
起票時（v3.6.6）は同じ主キーのレコードが作成されてしまう現象でしたが、現在（v3.7.2）はインポート時にエラーが起きています。

仮に改修によりエラーが起きなくなった時の期待する振る舞いとしては、主キーが同じであれば上書きしてくれる事です。
