### ISSUE TITLE
ExmentAPIのカスタムデータ情報更新で失敗する（500エラー）

### ISSUE THREAD

**Issue by Akatsuki-0725** [exceedone/exment#820]
**Describe the bug / バグの説明**
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
既存データの簡単な更新を行う為にAPIを使用して更新を行いたく、
APIの動作確認を行っていましたが、カスタムデータ情報更新で失敗します（取得や新規作成は成功します）。
　
以下のエラーメッセージが返ってきます。

array_filter() expects parameter 1 to be array, object given in file D:\xampp\local\exment\vendor\exceedone\exment\src\Validator\SelectRule.php on line 41

リクエストの方法などが間違っていたらご教示お願いします。

**To Reproduce / 再現手順**
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

検証の為、ChromeのAdvanced REST Clinetを使用しています。
　
リクエストは以下の通りです。
【Method】PUT
【URL】http://localhost:8001/admin/api/data/{更新対象テーブル名を指定}/{IDを指定}
【Headers】
　content-type：application/json
　authorization：{取得したトークン}
【Body】
　{"value":{"note":"test"}}

**Version / 発生バージョン**
Please describe version. / ご利用のバージョンを記載してください。
　v3.7.1

**Error log / エラーログ**
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

[2020-10-23 10:23:01] local.ERROR: array_filter() expects parameter 1 to be array, object given {"exception":"[object] (ErrorException(code: 0): array_filter() expects parameter 1 to be array, object given at D:\\xampp\\local\\exment\\vendor\\exceedone\\exment\\src\\Validator\\SelectRule.php:41)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'array_filter() ...', 'D:\\\\xampp\\\\local\\\\...', 41, Array)
#1 D:\\xampp\\local\\exment\\vendor\\exceedone\\exment\\src\\Validator\\SelectRule.php(41): array_filter(Object(Illuminate\\Support\\Collection))
#2 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Validation\\Validator.php(539): Exceedone\\Exment\\Validator\\SelectRule->passes('value.correspon...', Object(Illuminate\\Support\\Collection))
#3 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Validation\\Validator.php(359): Illuminate\\Validation\\Validator->validateUsingCustomRule('value.correspon...', Object(Illuminate\\Support\\Collection), Object(Exceedone\\Exment\\Validator\\SelectRule))
#4 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Validation\\Validator.php(268): Illuminate\\Validation\\Validator->validateAttribute('value.correspon...', Object(Exceedone\\Exment\\Validator\\SelectRule))
#5 D:\\xampp\\local\\exment\\vendor\\exceedone\\exment\\src\\Validator\\ExmentCustomValidator.php(21): Illuminate\\Validation\\Validator->passes()
#6 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Validation\\Validator.php(293): Exceedone\\Exment\\Validator\\ExmentCustomValidator->passes()
#7 D:\\xampp\\local\\exment\\vendor\\exceedone\\exment\\src\\Validator\\ExmentCustomValidator.php(26): Illuminate\\Validation\\Validator->fails()
#8 D:\\xampp\\local\\exment\\vendor\\exceedone\\exment\\src\\Controllers\\ApiDataController.php(796): Exceedone\\Exment\\Validator\\ExmentCustomValidator->fails()
#9 D:\\xampp\\local\\exment\\vendor\\exceedone\\exment\\src\\Controllers\\ApiDataController.php(390): Exceedone\\Exment\\Controllers\\ApiDataController->saveData(Object(Illuminate\\Http\\Request), Object(Exceedone\\Exment\\Model\\Class_3aa74cbf1240feee8620))
#10 [internal function]: Exceedone\\Exment\\Controllers\\ApiDataController->dataUpdate(Object(Illuminate\\Http\\Request), '...', '395')
#11 D:\\xampp\\local\\exment\\vendor\\exceedone\\exment\\src\\Controllers\\ApiDataController.php(47): call_user_func_array(Array, Array)
#12 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(45): Exceedone\\Exment\\Controllers\\ApiDataController->callAction('dataUpdate', Array)
#13 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Exceedone\\Exment\\Controllers\\ApiDataController), 'dataUpdate')
#14 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(169): Illuminate\\Routing\\Route->runController()
#15 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(665): Illuminate\\Routing\\Route->run()
#16 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#17 D:\\xampp\\local\\exment\\vendor\\exceedone\\exment\\src\\Middleware\\CheckForAnyScope.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#18 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(151): Exceedone\\Exment\\Middleware\\CheckForAnyScope->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'value_write')
#19 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 D:\\xampp\\local\\exment\\vendor\\exceedone\\exment\\src\\Middleware\\LogOperation.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#21 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(151): Exceedone\\Exment\\Middleware\\LogOperation->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 D:\\xampp\\local\\exment\\vendor\\exceedone\\exment\\src\\Middleware\\Morph.php(20): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#24 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(151): Exceedone\\Exment\\Middleware\\Morph->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 D:\\xampp\\local\\exment\\vendor\\exceedone\\exment\\src\\Middleware\\AuthenticateApi.php(25): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#27 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(151): Exceedone\\Exment\\Middleware\\AuthenticateApi->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 D:\\xampp\\local\\exment\\vendor\\exceedone\\exment\\src\\Middleware\\IpFilterBase.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#30 D:\\xampp\\local\\exment\\vendor\\exceedone\\exment\\src\\Middleware\\ApiIPFilter.php(16): Exceedone\\Exment\\Middleware\\IpFilterBase->handleBase(Object(Illuminate\\Http\\Request), Object(Closure), 'api_ip_filters')
#31 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(151): Exceedone\\Exment\\Middleware\\ApiIPFilter->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(151): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\ThrottleRequests.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#37 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(151): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure), 60, '1')
#38 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#40 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(667): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#41 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(642): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#42 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(608): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#43 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(597): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#44 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#45 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#46 D:\\xampp\\local\\exment\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#47 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#50 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#53 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#56 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#59 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#62 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#63 D:\\xampp\\local\\exment\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#64 D:\\xampp\\local\\exment\\public\\index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#65 {main}

**Screenshots / スクリーンショット**
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

**Additional context / その他**
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by hirossyi73** [comment]
列「note」の、カスタム列設定をご記載いただけないでしょうか。

**Comment by Akatsuki-0725** [comment]
お返事ありがとうございます。
note列は「複数行テキスト」になります。
　
一覧でも大丈夫でしょうか。
他に「YES/NO」や「1行テキスト」などでも試してみましたが、同様の状態になりました。
よろしくお願いします。
　
![image](https://user-images.githubusercontent.com/50621320/96951924-948bd800-1528-11eb-9fe8-f612b58e4b0e.png)

**Comment by hirossyi73** [comment]
ありがとうございます。
今回問題となっているSelectRuleというクラスが、列種類「選択肢」の内容になってますので、こちらの詳細画面もお見せいただけると幸いです。
※機密情報などありましたら、「テストテスト」といった別の文字列に置き換えていただけると助かります

**Comment by Akatsuki-0725** [comment]
ご確認ありがとうございます。
選択肢の内容が問題とのことでしたので、複数設定しているカスタム列の列種類「選択肢」の項目を1件ずつ削除して確認いたしましたところ、
以下の詳細設定画面で登録されている項目を削除した状態でAPIよりデータの更新に成功いたしました。
　
ただし、データリストア後、カスタム列設定詳細の「選択肢」の内容を変更しても同様のエラーが表示されました。
　
他の設定項目、または既存のデータ等に問題があるのでしょうか。

詳細画面のキャプチャを張り付けさせていただきます。
※カスタムテーブル名等は業務件名を含む為、消去させていただいております。

どうぞよろしくお願い致します。

![image](https://user-images.githubusercontent.com/50621320/97130280-4f63e200-1784-11eb-8aaa-a531d98804ed.png)
![image](https://user-images.githubusercontent.com/50621320/97130285-52f76900-1784-11eb-815a-d3a4d6c518e0.png)

**Comment by hirossyi73** [comment]
ありがとうございます。内容確認しました。
・APIのデータ更新時
・列設定で「複数選択を許可する」にチェックしていた場合
この条件で、現象発生するようでした。こちら、遅くとも今週中に修正し、リリースします。

**Comment by Akatsuki-0725** [comment]
ご確認ありがとうございます。

リリースの件、承知いたしました。
よろしくお願い致します。

**Comment by hirossyi73** [comment]
v3.7.2にて修正しました。

**Comment by Akatsuki-0725** [comment]
v3.7.2で更新できることを確認しました。

対応ありがとうございました。
