### ISSUE TITLE
カスタムビューの表示条件「指定日以降」で指定日が検索されない

### ISSUE THREAD

**Issue by shimaday8** [exceedone/exment#821]
**Describe the bug / バグの説明**
データ表示条件「指定日以降」を設定したカスタムビューでデータを表示たところ、指定日と同じ日付のデータが検索されません。指定日の翌日およびそれ以降のデータが表示されています。
データ一覧のフィルタで「指定日以降」の検索をしたときは指定日のデータも検索されます。これが期待する動きです。

**Version / 発生バージョン**
v3.7.1

**Comment by hirossyi73** [comment]
v3.7.2にて修正しました。

**Comment by shimaday8** [comment]
v3.7.2でも問題が再現しました。

次のようなデータが登録されている場合に、
![1](https://user-images.githubusercontent.com/66708775/97389305-56722800-191d-11eb-92a9-4f81849090c5.png)

カスタムビューの条件「開始日が2020-10-26以降」で、開始日2020-10-26が表示されません。
![2](https://user-images.githubusercontent.com/66708775/97389323-5d993600-191d-11eb-8d88-fa2b3c3ada16.png)
![3](https://user-images.githubusercontent.com/66708775/97389326-5ffb9000-191d-11eb-8014-4a82195b0c79.png)
