### ISSUE TITLE
複数行テキストの初期値に複数行入力したい

### ISSUE THREAD

**Issue by shimaday8** [exceedone/exment#822]
**Describe the feature you'd like / 希望する機能の説明を行ってください**
複数行テキストの初期値に複数行入力したいです。現状、1行テキストしか入力できないようです。

**Comment by hirossyi73** [comment]
v4.1.0で、各カスタム列ごとの初期値設定に対応予定です。

**Comment by hirossyi73** [comment]
2021/04/19 v4.1.0リリース完了
