### ISSUE TITLE
Please additional release notes

### ISSUE THREAD

**Issue by cw-hrtech** [exceedone/exment#825]
**Describe the feature you'd like / 希望する機能の説明を行ってください**
A clear and concise description of what you want to happen. / あなたが何をしたいのかについての、明確で簡潔な説明を行ってください。

Please additional release notes like this.
Ex: https://github.com/ElemeFE/element/releases/tag/v2.6.0

**Comment by hirossyi73** [comment]
Sorry, now I added this page for Japanese.
https://exment.net/docs/#/ja/release_note

 You wanna add release note on github for English, right?

**Comment by cw-hrtech** [comment]
Thank you for the addition release note.
If there is an English version it's also better for people who don't know Japanese like me

Currently, I can use google translate also.

Thank you very much

**Comment by hirossyi73** [comment]
Thanks. 
90% of the users who use Exment are Japanese.
We will create release note and manual English version.
