### ISSUE TITLE
PDF等添付ファイルのブラウザ表示

### ISSUE THREAD

**Issue by ganapati55** [exceedone/exment#826]
以前セキュリティ上の問題を解決するためにブラウザ上での表示をやめダウンロードが必須となりましたが、出来ればブラウザ上での表示を設定で選択できるとありがたいです。（あくまで自己責任で）
仕事の効率がだいぶ下がりました。

**Comment by hirossyi73** [comment]
https://exment.net/docs/#/ja/config
v3.7.3にて、こちらの「添付ファイルをクリックした時に、ブラウザ上で表示する拡張子の変更」を追加しましたので、ご確認ください。

**Comment by ganapati55** [comment]
ご対応いただき大変ありがとうございました。
ちなみに値は何とすればよいのでしょうか？
trueでやってみたのですが動作しませんでした。

**Comment by hirossyi73** [comment]
マニュアルに手順記載してますので、ご確認下さい。

**Comment by ganapati55** [comment]
大変失礼しました。動作確認しました。ありがとうございました！
