### ISSUE TITLE
APIでカスタム列のデータを取り出したら、日本語部分がUNICODEになっている

### ISSUE THREAD

**Issue by ShinjiHirano** [exceedone/exment#828]
**Describe the feature you'd like / 希望する機能の説明を行ってください**
APIでカスタムテーブルのデータをJSON形式で取り出していますが、日本語部分がUNICODEになっています。
例："keywords":"RFID \u696d\u52d9\u6539\u5584"
UTF-8で返すことはできないでしょうか？

**Additional context / その他**
Add any other context or screenshots about the feature request here. / 機能リクエストに関する他のコンテキストまたはスクリーンショットをここに追加します。
　　 let command = '/admin/api/data/xxxx';
        let url = exment_server + command;
        let options = {
            url: url,
            method: 'GET',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': 'Bearer ' + token
            }
        };
    
        response = await request(options, function(err, resp, result) {
            return result;
        });

**Comment by dev-hayash** [comment]
@ShinjiHirano 

間違っていたらすみません。

requestのoptionの中で、明示的に encoding: null を指定しないと、requestのモジュール内で勝手にbody.toString() が行われていた気がします。

encodingを追加した場合はどうでしょうか。

```
let options = {
  url: url,
  method: 'GET',
  headers: {
    'Content-Type': 'application/json',
    'Authorization': 'Bearer ' + token
  },
  encoding: null
}
```

また、日本語文字列がエンコードされているというのは、データを表示する方法によって異なると思いますので
どのように確認したか記載すると回答の精度が上がると思います。

**Comment by ShinjiHirano** [comment]
ありがとうございます。

戻り値の確認としては、
console.log(result);
で表示しています。

encoding:null　を追加してみました。結果は、こんな感じです。
<Buffer 7b 22 63 75 72 72 65 6e 74 5f 70 61 67 65 22 3a 31 2c 22 64 61 74 61 22 3a 5b 7b 22 69 64 22 3a 31 2c 22 73 75 75 69 64 22 3a 22 66 31 31 30 61 39 38 ... 17303 more bytes>

その後、いろいろ見直していて、次のように設定したら、うまく行きました。

        let options = {
            url: url,
            method: method,
            json:true,　　＜＝＝これを追加
            headers: {
                'Content-Type': 'application/json',
                'Authorization': 'Bearer ' + token
            }
        };

結果表示で
    console.log(JSON.stringify(result));

「json:true」最初はつけていたのですが、いろいろやっているうちに削除していました。
落ち着いてみれば、普通の指定ですね。

お騒がせして申し訳ありませんでした。

**Comment by dev-hayash** [comment]
@ShinjiHirano 

解決したようで何よりです。closeですか？

**Comment by ShinjiHirano** [comment]
はい、クローズしていただいて問題ありません。
ありがとうございました。

**Comment by dev-hayash** [comment]
issue起票者かプロダクトオーナーでないとcloseできないので、問題が解決した場合は積極的にcloseしてください:smile:
