### ISSUE TITLE
通知の設定でボタン・Eメールを選択した際、添付ファイルが利用できなくなっている

### ISSUE THREAD

**Issue by yome2020** [exceedone/exment#832]
**Describe the bug / バグの説明**
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

通知の設定で「ボタン」、「Eメール」を設定した場合、以前は利用できていた添付ファイルの欄が無くなっている。
設定値のEXMENT_ARCHIVE_MAIL_ATTACHMENTはTrueにしてあります。

**To Reproduce / 再現手順**
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

**Version / 発生バージョン**
Please describe version. / ご利用のバージョンを記載してください。
Ver.3.7.2

**Error log / エラーログ**
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。
無し

**Screenshots / スクリーンショット**
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。
![スクリーンショット 2020-11-06 110736](https://user-images.githubusercontent.com/68719898/98317681-50b4ca80-2020-11eb-9f74-11e778dbe0f0.png)

**Additional context / その他**
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。
もし仕様でしたらごめんなさい。以前のバージョンでは添付ファイル及びパスワード付き圧縮ができていたはずなので・・・。

**Comment by yome2020** [comment]
追記情報として
メール送信履歴に記録が残るメールとそうでないメールの差は何でしょうか？

**Comment by hirossyi73** [comment]
#3.7.4で対応したので、ご確認をお願いします。
※添付ファイルは、通知先にEメールが設定されている時に表示されます。
v3.7.0で、通知の内部処理を修正した時に、ロジックに不備がありました。

※v3.7.4で、通知に関して、自動テストコードを厚めに追加させていただきました。

**Comment by yome2020** [comment]
対応ありがとうございます。
当該チケット（issue）について修正されていることを確認しました。
