### ISSUE TITLE
データの作成時等の自動通知が2件送られる

### ISSUE THREAD

**Issue by Yuusuke9228** [exceedone/exment#833]
**Describe the bug / バグの説明**
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

はっきりとバグなのか、設定が間違えているのか分からないので、申し訳ないのですが、メールの自動通知が2件送られます。
また、役割・組織が原因かも分からない（エラーでは無いのでログが無い）ので、対応方法があれば、ご教示願います。

**To Reproduce / 再現手順**
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
役割グループを作り、役割を設定
↓
組織を作り、組織に属するユーザーと、役割グループを設定
↓
通知設定「データ作成時、権限のあるユーザーへEMAILを自動送信」の状態にする
↓
自動通知対象テーブルで、データを作成
↓
同じ内容のメールが権限のあるユーザーへ2件届く

**Version / 発生バージョン**
Please describe version. / ご利用のバージョンを記載してください。
3.7.2(最新)

**Error log / エラーログ**
無し

**Screenshots / スクリーンショット**
無し

**Additional context / その他**
一応、マニュアルは確認したのですが、特別設定は間違えていないようなので、対応出来る方法があれば、お願いいたします。

**Comment by Yuusuke9228** [comment]
再現する方法と、対応が分かりました。
**＜発生条件＞**

1. 組織・役割管理を行うように設定
2.組織にユーザーを所属させる
3.役割グループに組織を割り当てる

ユーザー単位で役割グループに所属させると、メール通知は１件しか送られない。
ユーザーを参加させた組織を役割グループに割り当てると、２件同じメール通知が送られる

**＜暫定対処＞**
面倒だが、役割グループにユーザー一人一人を割り当てることにして対処した。

役割グループにユーザが参加する組織を割り当てるだけで、通知が１件しか行かない様にはできないでしょうか？
ユーザーが増えると、役割グループの中が煩雑です。

**Comment by hirossyi73** [comment]
#3.7.4で対応したので、ご確認をお願いします。
