### ISSUE TITLE
インポート時に起きるエラー

### ISSUE THREAD

**Issue by dev-hayash** [exceedone/exment#835]
**Describe the bug / バグの説明**
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

特定条件の時に複数レコードをインポートするとエラーになる。
但し、１レコードだけだとインポートできる。

条件：ユニーク属性のカラムを定義する

**To Reproduce / 再現手順**
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

以下のカラムを持つテーブルがあります。
https://demo-jp.exment.net/admin/data/asset_table
![image](https://user-images.githubusercontent.com/19341340/98523803-afe13c00-22b9-11eb-8418-4c9bb0b014b0.png)

インポートテンプレートをダウンロードして、以下の内容まで列を削除しました。

![image](https://user-images.githubusercontent.com/19341340/98523913-da32f980-22b9-11eb-8476-0d0beceb2e20.png)

インポートすると以下のメッセージを表示するエラーとなります。

![image](https://user-images.githubusercontent.com/19341340/98524024-0189c680-22ba-11eb-856e-2d9d9716e39e.png)

同じファイルを１レコードだけに変更します。

![image](https://user-images.githubusercontent.com/19341340/98524171-3bf36380-22ba-11eb-9894-d0abdef6f3c7.png)

インポートすると成功します。（ID：4がインポートした１レコード）

![image](https://user-images.githubusercontent.com/19341340/98524251-56c5d800-22ba-11eb-9736-b8096df550af.png)

**Version / 発生バージョン**
Please describe version. / ご利用のバージョンを記載してください。
v3.7.2

**Error log / エラーログ**
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

複数行の取込み時に"インポートに失敗しました"のメッセージが表示されているのですが、ログには一切の出力がありませんでした。

**Additional context / その他**
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

インポートに使用したExcelを添付します。
[資産台帳20201109182427.xlsx](https://github.com/exceedone/exment/files/5509461/20201109182427.xlsx)

**Comment by hirossyi73** [comment]
v3.9.3にて対応しました。

**Comment by hirossyi73** [comment]
v3.9.3にてリリースしました。

**Comment by dev-hayash** [comment]
返信が遅くなり申し訳ありません。

busyで確認が遅れそうです。
一旦、closeさせて頂き問題がありましたら、別途起票させて頂きます。
