### ISSUE TITLE
フィルタ機能で多対多のリレーションを貼っているテーブルをフィルタできない

### ISSUE THREAD

**Issue by y-hayama** [exceedone/exment#838]
**Describe the bug / バグの説明**
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

カスタムテーブルのデータのフィルタ機能について、多対多のリレーションを複数貼っている際、親テーブルのフィルタができないようです。

**To Reproduce / 再現手順**
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

1. カスタムテーブルA,B,Cを作成する
2. A-Cで多対多のリレーションを貼る
3. B-Cで多対多のリレーションを貼る
4. カスタムテーブルCでフィルタをかける

**Version / 発生バージョン**
Please describe version. / ご利用のバージョンを記載してください。

v3.6.8

**Error log / エラーログ**
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

**Screenshots / スクリーンショット**
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

**Additional context / その他**
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by dev-hayash** [comment]
横からすみません。
#805 #806 とは別な現象でしょうか？

異なる場合は相違のレポートがあると良いです。
同じ内容のチケット起票は開発者の負担になるので、同一内容でしたらcloseする事をお勧めします。

**Comment by y-hayama** [comment]
チケット見てみましたが #806 は同じ現象のようなのでこちらはクローズしたいと思います。
#805 は別事象でしたが、最新バージョンだと  実装いただいているように見えるのでこのチケットもクローズしたいと思います。
ご指摘ありがとうございます。
