### ISSUE TITLE
パラメータ

### ISSUE THREAD

**Issue by ookini** [exceedone/exment#839]
通知のメールテンプレートで、
メール件名[${system:site_name}]ワークフロー${workflow:workflow_view_name}が実行されました
と設定した場合、
${workflow:workflow_view_name}
が、表示されませんでした。
https://github.com/exceedone/exment/blob/master/resources/lang/ja/exment.php
を見たのですが、どこが間違っているのでしょうか？
---
Exment v3.7.3

**Comment by hirossyi73** [comment]
https://exment.net/docs/#/ja/params
こちらに記載してませんので、仕様です。
