### ISSUE TITLE
「参照」権限で、全ユーザーの作成レコードが表示されてしまう

### ISSUE THREAD

**Issue by scsaht** [exceedone/exment#847]
**Describe the bug / バグの説明**
ユーザーに「参照」権限がついていると
カスタムテーブルの一覧画面で全てのユーザーの作成レコードが表示されてしまいます

**To Reproduce / 再現手順**
以下のパターンで全ユーザーの作成レコードがカスタムテーブルの一覧画面で表示されます

「カスタムテーブル設定」 > 「権限設定」 > 「全ユーザーが参照可能」　Yes
「役割グループ設定」 > 「全データの参照」　チェック
「役割グループ設定」 > 「担当データの編集」　チェック

「カスタムテーブル設定」 > 「権限設定」 > 「全ユーザーが参照可能」　No
「役割グループ設定」 > 「全データの参照」　チェック
「役割グループ設定」 > 「担当データの編集」　チェック

「カスタムテーブル設定」 > 「権限設定」 > 「全ユーザーが参照可能」　Yes
「役割グループ設定」 > 「全データの参照」　空
「役割グループ設定」 > 「担当データの編集」　チェック

**Version / 発生バージョン**
v3.7.4

**Additional context / その他**
たしか以前のバージョンでは「参照」権限では他ユーザーの作成レコードは表示されなかったような気がします

**Comment by scsaht** [comment]
バージョン v3.9.0 で改めて
この３種類の設定の組み合わせ６通りを試したところ
データ一覧画面で自分の作成レコードのみが表示される結果になるパターンは

「カスタムテーブル設定」 > 「権限設定」 > 「全ユーザーが参照可能」　No
「役割グループ設定」 > 「全データの参照」　空
「役割グループ設定」 > 「担当データの編集」　チェック

の場合でした
ただし、この場合当然ながら、関連データ検索などの検索結果に他ユーザーのレコードが反映されなくなります。

このため現状では、例えば
経費テーブルでは自分の入力データのみ表示されるが、案件テーブルでは他ユーザーの入力した経費も合わせて集計して表示したい
などの用途で使えなくなってしまっております。

この状態も再現されませんでしょうか。

**Comment by scsaht** [comment]
組み合わせは９通りでした

**Comment by hirossyi73** [comment]
前提として、全データ参照権限の用途としては、
・データとしては、表示させたい
・ただ、わざわざデータ一覧画面の表示などは行わせたくない
というテーブルに対し、「全データ参照」の権限のみ、設定する用途でいました。
（例：税率マスターなど。他のテーブルで全員に使用させたいが、各ユーザーは一覧画面を表示・編集させたくない、といった用途）

そのため、「全データの参照」と「担当データの編集・閲覧など」といった内容と組み合わせることは、想定外という状況です。

今後のアップデートで、「全データの参照」と「担当データの編集・閲覧など」を組み合わせて、役割グループが保存できないよう、アップデートを行う予定です。

**Comment by scsaht** [comment]
承知いたしました。
素早い対応ありがとうございました。
