### ISSUE TITLE
【情報募集中】composer2によるアップデート失敗

### ISSUE THREAD

**Issue by C0ela** [exceedone/exment#849]
**Describe the bug / バグの説明**
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

コマンドでのアップデート時にエラーが発生する。
エラー発生後、Exmentへアクセスできなくなる（真っ白な画面）。

**To Reproduce / 再現手順**
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

WSL2
Ubuntu 18.04.5 LTS
Composer version 2.0.6

Windows Terminalから`ExmentUpdateLinux.sh`を実行。

**Version / 発生バージョン**
Please describe version. / ご利用のバージョンを記載してください。

3.7.2

**Error log / エラーログ**
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

```
$ ./ExmentUpdateLinux.sh
---------Start Exment Update---------
Execute Backup
Update exceedone/laravel-admin
Using version ^1.7 for exceedone/laravel-admin
./composer.json has been updated
Running composer update exceedone/laravel-admin
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
  - Upgrading exceedone/laravel-admin (v1.7.41 => v1.7.42)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Downloading exceedone/laravel-admin (v1.7.42)
  - Upgrading exceedone/laravel-admin (v1.7.41 => v1.7.42): Extracting archive
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
Carbon 1 is deprecated, see how to migrate to Carbon 2.
https://carbon.nesbot.com/docs/#api-carbon-2
    You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In PackageManifest.php line 122:

  Undefined index: name


Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
Update exceedone/exment
Using version ^3.7 for exceedone/exment
./composer.json has been updated
Running composer update exceedone/exment
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
  - Upgrading exceedone/exment (v3.7.2 => v3.7.4)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 2 updates, 0 removals
  - Downloading exceedone/laravel-admin (v1.7.41)
  - Downloading exceedone/exment (v3.7.4)
  - Downgrading exceedone/laravel-admin (v1.7.42 => v1.7.41): Extracting archive
  - Upgrading exceedone/exment (v3.7.2 => v3.7.4): Extracting archive
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
Carbon 1 is deprecated, see how to migrate to Carbon 2.
https://carbon.nesbot.com/docs/#api-carbon-2
    You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In PackageManifest.php line 122:

  Undefined index: name


Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
Execute Update

In PackageManifest.php line 122:

  Undefined index: name


Finish Update!
```

**Screenshots / スクリーンショット**
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

**Additional context / その他**
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

Composerを1.x系に戻したところ正常にアップデートできました。

**Comment by hirossyi73** [comment]
https://qiita.com/fagai/items/15232a3f1a5a640d84a7
こちらを試していただけないでしょうか？

**Comment by hirossyi73** [comment]
> Composerを1.x系に戻したところ正常にアップデートできました。
こちら見逃していました。

参考までに教えていただきたいのですが、今のコマンドで、Laravelのバージョンをご教授いただけ無いでしょうか。
php artisan --version

**Comment by C0ela** [comment]
> 参考までに教えていただきたいのですが、今のコマンドで、Laravelのバージョンをご教授いただけ無いでしょうか。
> php artisan --version

Laravel Framework 5.6.39 でした。

**Comment by hirossyi73** [comment]
ありがとうございます。
現在、こちらで動いている環境(composer2.0.6、Laravel 5.6.39、XServer)では正常に動作しているので、他の原因を調査してみます。
取り急ぎ、公式サイトの推奨文は取り下げました。ご報告ありがとうございます。

**Comment by hirossyi73** [comment]
タイトル変更させていただきました。

現在、私ならびに開発者で調査を行っているのですが、過去バージョンのExment、ならびに古いバージョンのcomposer2で、現象が再現できていません。
もし、同様の症状が発生する方がいらっしゃいましたら、情報をいただけると非常に助かります。

composer2は非常に高速に動作するので、できればそちらを推奨したいのですが、エラーが発生するという情報をいただいている以上、推奨が難しいので、なるだけ解決したいと思っています。

**Comment by hirossyi73** [comment]
検証を進め、laravel/frameworkのバージョンが5.6.39以下の場合、この現象が発生することが分かりました。
以下の手順で、laravel/frameworkのバージョンを上げてから、composerのバージョンを2にしていただきますよう、お願いします。
https://exment.net/docs/#/ja/update_composer

**Comment by C0ela** [comment]
ご案内のとおり laravel/framework のバージョンを 5.6.40 に上げると当該現象が発生せずアップデートできました。（親記事でWSL内で別にインストールしていたExmentで確認）
検証ありがとうございました。

**Comment by y-hayama** [comment]
ご報告ですが、[ご案内](https://exment.net/docs/#/ja/update_composer)に従ってlaravel/frameworkのバージョンアップとcomposerのバージョンアップをしたところ問題なくバージョンアップできました。

**Comment by hirossyi73** [comment]
@C0ela  @y-hayama 
ご報告いただき、ありがとうございました。

一度、こちらのスレッドはクローズします。
万が一、ご案内させていただいた手順でアップデートが上手く行かない場合、クローズしていますが、こちらにコメントいただけると幸いです。

**Comment by dev-hayash** [comment]
typo報告です。
https://exment.net/docs/#/ja/update_composer

> # 以下のいずれかを実施してください
> composer self-update -–2
> composer selfupdate -–2

そのままコピペするとエラーになります。
2文字目のハイフンが全角とも違う不思議なハイフンでした。
