### ISSUE TITLE
Wordによるドキュメント出力に対応する

### ISSUE THREAD

**Issue by hirossyi73** [exceedone/exment#85]
PHPWordというものがあるので、これでWordによるドキュメント出力に対応する
（Word形式、PDF形式）
https://github.com/PHPOffice/PHPWord

**Comment by yisaka117** [comment]
Word=>PDF変換について
・MPDFはPHPWordのクラスを使った場合フォント設定ができない。（強制的に設定しても、一部のフォントにしか対応していない。日本語が使えるかは不明）
・TCPDFで出力した場合も色、インデント、改ページ、左寄せ右寄せ、などは反映されない。また、一部の文字が消えてしまう。（条件不明）

**Comment by hirossyi73** [comment]
了解です、ありがとうございます。
品質の担保が難しいので、Wordのテンプレートは止めておきます。
