### ISSUE TITLE
ビューで子テーブルのID列に親テーブルのIDが表示されてしまう

### ISSUE THREAD

**Issue by baclam** [exceedone/exment#851]
**Describe the bug / バグの説明**
別テーブルのレコードを選択肢とするカスタムカラムを二つ持つテーブルがある。（テーブルA、テーブルBとする）
このテーブルに通常のビューを定義し、表示列として「テーブルA：ID」「テーブルB：ID」を定義した場合に、この二つのカラムには元のテーブルのID値が表示されてしまう。IDでは無く内部IDとしても同様。
DBには正しくデータは格納されているため、ビューのバグでは無いかと推測しています。
また、別名表示を指定しても同様。

**To Reproduce / 再現手順**
上記の通り。

**Version / 発生バージョン**
Please describe version. / ご利用のバージョンを記載してください。
3.5.4
（まだバージョンアップしてませんが、issueを見た所、指摘・解消されている形跡は見られなかったため報告）
<img width="1667" alt="exmentビュー不具合" src="https://user-images.githubusercontent.com/10202918/100047994-21db8880-2e57-11eb-952f-9591aeaf245e.png">

**Comment by hirossyi73** [comment]
v3.7.7.にてリリースしました。

**Comment by hirossyi73** [comment]
こちらですが、実施した修正方法だと他の箇所に影響が出てしまったので、大変恐縮ですが、一度差し戻しました。
別の方法での修正を行いますので、もう少々お待ち下さい。

**Comment by hirossyi73** [comment]
v3.9.0にて、対応方法を変えて再度リリースしました。
お手数ですが、再度ご確認ください。
