### ISSUE TITLE
APIで"Replicating claims as headers is deprecated and will removed from v4.0."が発生した場合

### ISSUE THREAD

**Issue by hirossyi73** [exceedone/exment#855]
APIの認証や実行時に、稀に以下のエラーが発生するご報告を受けております。

```
Replicating claims as headers is deprecated and will removed from v4.0. Please manually set the header if you need it replicated. 
```

こちらは、関連ライブラリ”lcobucci/jwt”が、11/25にてv3.4.0へのアップデートが行われ、そのライブラリで不具合が発生している模様です。
https://github.com/lcobucci/jwt/issues/550

早い段階でマイナーバージョンアップが入るとは思いますが、万が一このエラーが発生する場合、Exmentのルートフォルダで、以下のコマンドを実行してください。

```
composer require lcobucci/jwt=3.3.*
```

**Comment by lcobucci** [comment]
Hello @hirossyi73, I'm sorry you're receiving error reports based on deprecation messages. 

Laravel Passport has been patched to solve the incompatibilities. However, https://github.com/laravel/framework/pull/35381 should help Laravel users not to be disrupted by them.

I'll be more than happy to help you folks too :+1:

**Comment by hirossyi73** [comment]
v4.0.0より、lcobucci/jwt=3.3.をrequireするようにしたので、クローズします。
