### ISSUE TITLE
フリーワード検索が機能しません

### ISSUE THREAD

**Issue by scsaht** [exceedone/exment#856]
**Describe the bug / バグの説明**
フリーワード検索を実行すると、検索中の表示のまま変化しなくなるか、真っ白なページに遷移してしまいます

**To Reproduce / 再現手順**
「検索インデックス」Yes
「フリーワード検索対象」Yes
としたカラムのレコードに含まれている語句でフリーワード検索をする

**Version / 発生バージョン**
v3.7.4

**Error log / エラーログ**
この現象では、./strage/logs/laravel.logファイルにエラーログは記載されません

**Screenshots / スクリーンショット**
検索バーによる検索の場合
![kensaku_1](https://user-images.githubusercontent.com/51815867/100326564-77f22c80-300d-11eb-9753-7a5d7f901d0c.gif)

データ一覧画面の検索の場合
![kensaku_2](https://user-images.githubusercontent.com/51815867/100326585-7c1e4a00-300d-11eb-81af-0846f4f798fb.gif)

**Additional context / その他**

**Comment by scsaht** [comment]
実行環境は以下の通りです
Ubuntu 18.04.5 LTS
PHP 7.2.34-8+ubuntu18.04.1+deb.sury.org+1 (cli) 
Laravel Framework 5.6.40
10.4.17-MariaDB-1:10.4.17+maria~bionic mariadb.org binary distribution

**Comment by hirossyi73** [comment]
エラーログは出力されないということですが、可能であれば、Chromeのコンソールに、エラーが出ているかどうかの確認をいただけないでしょうか。
見方としては
・Chrome上で、「F12」をクリックする。
・Consoleタブをクリックする。
・なにかエラーが発生していれば、このような表示が行われますので、この内容をご確認いただきたいです。

![image](https://user-images.githubusercontent.com/8457265/100405425-eafbb180-30a6-11eb-97ef-7cf712f82d72.png)

**Comment by scsaht** [comment]
ブラウザのコンソールは以下の通りです。
いずれも
 500 (Internal Server Error) , jQuery-2.1.4.min.js:4
となっております。

検索バーの場合
![console_1](https://user-images.githubusercontent.com/51815867/100427062-388f1300-30d5-11eb-9e2c-84aee2ec7536.gif)

データ一覧画面の場合
![console_2](https://user-images.githubusercontent.com/51815867/100427082-404eb780-30d5-11eb-9cba-355395f48629.gif)

**Comment by scsaht** [comment]
エラー内容を展開した画像も投稿いたします。
![console_3](https://user-images.githubusercontent.com/51815867/100428039-bc95ca80-30d6-11eb-8f1c-b3f0db1c215b.gif)

**Comment by hirossyi73** [comment]
ありがとうございます。何かしらのエラーが出ていますね。

今度は、以下の手順で、エラーの内容をご確認いただけないでしょうか。

・Chrome上で、「F12」をクリックする。
・Networkタブをクリックする。
・この状態で検索バーに文字を入れると、Name列に赤色の行が表示されると思います。そちらがエラーが発生しているリクエストですので、その行をクリックし、Responseの内容を教えてください。

![image](https://user-images.githubusercontent.com/8457265/100437543-3f715200-30e4-11eb-82c2-d0ff940fa42b.png)

**Comment by scsaht** [comment]
返信が遅れて申し訳ありません。

検索バーでの検索時のResponseは
「This request has no response data available」

データ一覧画面においては、白いページに遷移してから
`<div class="block_custom_value_grid custom_value_project row"><div class="col-sm-12">`
と出ます。

**Comment by hirossyi73** [comment]
別の開発者とも連携し、調査を行ったのですが、現状、再現しない状況です。
別途、再現する条件などご存知の方いらっしゃいましたら、情報いただけますと幸いです。
