### ISSUE TITLE
ヘッダー右上のユーザー情報のMember since adminを消去または置換する機能

### ISSUE THREAD

**Issue by yome2020** [exceedone/exment#858]
**Describe the feature you'd like / 希望する機能の説明を行ってください**
A clear and concise description of what you want to happen. / あなたが何をしたいのかについての、明確で簡潔な説明を行ってください。

ヘッダー右上のユーザー情報で、Member since adminのところを消去または他の項目に置き換える設定項目を追加してほしい

![スクリーンショット 2020-11-30 115319](https://user-images.githubusercontent.com/68719898/100563805-acfac980-3302-11eb-971a-5523fe738d71.jpg)

**Additional context / その他**
Add any other context or screenshots about the feature request here. / 機能リクエストに関する他のコンテキストまたはスクリーンショットをここに追加します。

/laravel/exment/vendor/exceedone/laravel-admin/resources/views/partials/header.blade.php内の
Member since admin {{ Admin::user()->created_at }}を編集すれば良いのは分かるのですが
アップデートを実施する度に元に戻ってしまうので、もし機能として実装してもらえたらありがたいです。

**Comment by hirossyi73** [comment]
どんな内容を表示したい、というご希望はありますか？

**Comment by yome2020** [comment]
こちらで想像しうる内容としては

・　ログインユーザーの所属する組織名（複数ある場合は最下層？）
・　ユーザーコード名（既に左側のメニューに実装済みですが・・・）
・　肩書き、チーム名など任意の文字列（ユーザーテーブルに専用のカスタム列）
・　会員ランクや操作権限名のようなもの（例：ブロンズ会員、シルバー会員・・・　一般ユーザー、主任、副店長・・・）
・　外出中や離席中などの情報（他のユーザーから見えるようにするとなると大変か・・・）
・　前回のログイン日時

想像力に乏しく、要望を出したものの、具体的な案を提示できなくて申し訳ありません。

現状としましては Member Since adminという英語表記を例えば、ユーザー登録日のような日本語にしたり
非表示にできる設定項目（YES/NO）を設置したりできればありがたいです。

**Comment by hirossyi73** [comment]
アイデア、ありがとうございます。
大変恐縮ですが、現在現行の機能の強化やリファクタリング・テストの強化を中心に行っている都合もあり、PRいただくか、お待ちいただきますよう、よろしくお願いします。

**Comment by hirossyi73** [comment]
最新バージョンで一部対応しましたので、一度クローズします。
