### ISSUE TITLE
一覧表示で作成日時・更新日時でソートしようとするとエラーが発生する

### ISSUE THREAD

**Issue by y-sugaizumi** [exceedone/exment#863]
**Describe the bug / バグの説明**
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

一覧表示で作成日時・更新日時のヘッダー部分の△を押下するとエラーが発生する

**To Reproduce / 再現手順**
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

一覧画面でソートをする

**Version / 発生バージョン**
Please describe version. / ご利用のバージョンを記載してください。

v3.7.7

**Error log / エラーログ**
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。
```
 QueryException In Connection.php line 664 :
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'exm__850e73f0008454e642bb-updated_at' in 'order clause' (SQL: select * from `exm__850e73f0008454e642bb` where `exm__850e73f0008454e642bb`.`deleted_at` is null order by `exm__850e73f0008454e642bb-updated_at` desc limit 20 offset 0)
```
**Screenshots / スクリーンショット**
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

![2020-12-08_23h56_54](https://user-images.githubusercontent.com/56142495/101500117-6451a900-39b1-11eb-8986-7fa3c8d72059.gif)

**Additional context / その他**
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。
クエリパラメータが`exm__c84a1ae1040f4653fbd3-created_at`となっており`exm__c84a1ae1040f4653fbd3-created_at`というカラムが無いと言われる。`exm__c84a1ae1040f4653fbd3.created_at`になれば良い？？

**Comment by hirossyi73** [comment]
@y-sugaizumi 
https://github.com/exceedone/exment/commit/49463cec514e181a19ef27ad7748973c23eef526
こちらの修正で悪影響が出ていました。一度、差し戻しリリースを行います。

**Comment by hirossyi73** [comment]
v3.8.0でリリースを行いましたので、クローズします。
