### ISSUE TITLE
コメント欄の表示に関する要望

### ISSUE THREAD

**Issue by ganapati55** [exceedone/exment#866]
**Describe the feature you'd like / 希望する機能の説明を行ってください**

現在、コメント欄が見にくいです。
長文になるとカラム内から文字が飛び出します。
結果としてほとんど活用できていません。
そこで以下のようにしていただけると助かります。

・コメント部分に独自のCSSを充てられるようにHTMLを出力して欲しい
・添付ファイルや更新履歴のカラムと表示順序を調整できればありがたい
・WYSIWYGで入力できると最高です。なかなか難しいでしょうが・・・。

**Comment by hirossyi73** [comment]
>長文になるとカラム内から文字が飛び出します。
こちらについては、v3.9.0にて対応しました。

**Comment by ganapati55** [comment]
確認しました。ありがとうございます。
