### ISSUE TITLE
テーブル詳細設定でインポート時のキー列を設定しても「選択肢に含まれない値が選択されています。」のエラーが出る

### ISSUE THREAD

**Issue by A87da** [exceedone/exment#870]
**Describe the bug / バグの説明**
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

最新バージョンにアップデート後
カスタムテーブル新規に作成
テーブル詳細設定からカスタム列の設定
選択肢 (他のテーブルの値一覧から選択)
 他のテーブルを設定
インポートやエクスポート時のキー列を（候補としては他のテーブルの項目名が正しく表示される）候補から選択
「選択肢に含まれない値が選択されています。」のエラーが表示され設定できない。

**To Reproduce / 再現手順**
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
同上

**Version / 発生バージョン**
Please describe version. / ご利用のバージョンを記載してください。
v3.9.1

**Error log / エラーログ**
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

**Screenshots / スクリーンショット**
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。
![image](https://user-images.githubusercontent.com/75293775/102731019-042c1100-437a-11eb-8283-38b69d12fa39.png)

**Additional context / その他**
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by hirossyi73** [comment]
@A87da 
ご報告ありがとうございます、v3.9.2をリリースし対応しました。
