### ISSUE TITLE
メニューにテーブルデータが追加出来なくなりました。

### ISSUE THREAD

**Issue by burukaniro** [exceedone/exment#872]
**Describe the bug / バグの説明**
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
メニュー追加画面から、メニュー種類「テーブルデータ」を追加しようとすると
既存のテーブルデータを指定しても
 **選択肢に含まれない値が選択されています。**
と表示されて設定出来ません。

**To Reproduce / 再現手順**
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
少なくとも、以前に設定したメニューには追加出来ていましたので
v.3.9.1以前は問題なかったと思います。v.3.9.1以降で発生し、3.9.2でも改善されておらず、テーブルデータを初期化して
再登録してもダメでした。

**Version / 発生バージョン**
Please describe version. / ご利用のバージョンを記載してください。
V3.9.1と3.9.2

**Error log / エラーログ**
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。
ログはありません。

**Screenshots / スクリーンショット**
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

![image](https://user-images.githubusercontent.com/76467166/102857741-4fbee780-446c-11eb-821b-16d979b33621.png)

**Additional context / その他**
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by hirossyi73** [comment]
確認しました。
次回リリースにて修正しますが、優先して対応する場合、下記のファイルを、
https://github.com/exceedone/exment/blob/hotfix/src/Controllers/MenuController.php
下記のURLの手順で入れ替えをお願いします。
https://exment.net/docs/#/ja/update_tmp

**Comment by hirossyi73** [comment]
v3.9.3にて対応しました。
