### ISSUE TITLE
IF文等での条件分岐による自動採番の実装

### ISSUE THREAD

**Issue by A87da** [exceedone/exment#874]
**Describe the feature you'd like / 希望する機能の説明を行ってください**
A clear and concise description of what you want to happen. / あなたが何をしたいのかについての、明確で簡潔な説明を行ってください。
所属部門や、所属会社等で、社員番号の頭2桁を文字列→例）　株式会社ABC→　Aを上1桁につけて、あとは連番での自動採番をする。株式会社B所属の場合→Bnnnnnでの自動採番にするような仕様の実装

**Additional context / その他**
Add any other context or screenshots about the feature request here. / 機能リクエストに関する他のコンテキストまたはスクリーンショットをここに追加します。

**Comment by hirossyi73** [comment]
@A87da 
パラメータの書き方(構文)について悩んでいるのですが、なにか他のシステムなどで、参考になりそうなものはありませんでしょうか？

**Comment by A87da** [comment]
hirossyiさん、いつも早々にありがとうございます。
構文ですか。

IF CompanyName = 〇〇株式会社
ID（ここがパラメーター変数？） =A-$ {y} -${id:5}
ENDIF
IF CompanyName = ▲株式会社
ID（ここがパラメーター変数？） =B-$ {y} -${id:5}
ENDIF　
とかでしょうか。DB構文詳しくなくすみません~
