### ISSUE TITLE
カスタム列種類「画像」でjpg形式がアップできない

### ISSUE THREAD

**Issue by ashtail** [exceedone/exment#882]
**Describe the bug / バグの説明**
カスタム列種類「画像」でjpg形式がアップできない。png、gifは大丈夫でした。

編集画面ではアップロードできサムネイルで確認できますが、保存をすると「画像ファイルを指定してください。」とエラーがでます。

**Additional context / その他**
その他要望ですが、ビュー等で画像を表示する際、ダウンロードでなくライトボックスのような形で画像を表示できるとよいです。

**Comment by hirossyi73** [comment]
> カスタム列種類「画像」でjpg形式がアップできない。png、gifは大丈夫でした。
次回リリースでmasterに反映致します。[Laravelのソースに、jpgが含まれていないことが原因のようでした](https://github.com/laravel/framework/blob/v5.6.40/src/Illuminate/Validation/Concerns/ValidatesAttributes.php)
お急ぎの場合、[こちら](https://exment.net/docs/#/ja/update_tmp)の手順で、[こちらのファイル](https://github.com/exceedone/exment/blob/hotfix/src/Validator/ImageRule.php)の差し替えをお願いします。

> その他要望ですが、ビュー等で画像を表示する際、ダウンロードでなくライトボックスのような形で画像を表示できるとよいです。
ダウンロードではなくブラウザで表示する場合は、[こちら](https://exment.net/docs/#/ja/config?id=%e6%b7%bb%e4%bb%98%e3%83%95%e3%82%a1%e3%82%a4%e3%83%ab%e3%82%92%e3%82%af%e3%83%aa%e3%83%83%e3%82%af%e3%81%97%e3%81%9f%e6%99%82%e3%81%ab%e3%80%81%e3%83%96%e3%83%a9%e3%82%a6%e3%82%b6%e4%b8%8a%e3%81%a7%e8%a1%a8%e7%a4%ba%e3%81%99%e3%82%8b%e6%8b%a1%e5%bc%b5%e5%ad%90%e3%81%ae%e5%a4%89%e6%9b%b4)をご確認ください。

**Comment by ashtail** [comment]
> 次回リリースでmasterに反映致します。Laravelのソースに、jpgが含まれていないことが原因のようでした
> お急ぎの場合、こちらの手順で、こちらのファイルの差し替えをお願いします。

ありがとうございます。

> ダウンロードではなくブラウザで表示する場合は、こちらをご確認ください。

マニュアル見逃しておりました、ブラウザ表示ありがとうございます。助かります。
脆弱性の件とのことで難しいとは思いますが、ライトボックス的な表示も期待しております。

**Comment by hirossyi73** [comment]
なるほど、ライトボックスは単純に、画像をブラウザで表示するものとは別物ということですね。勘違いしていました。

**Comment by ashtail** [comment]
そうですね、オーバーレイ的な表示ができるとサクサクと画像を確認できますので。
ただ、単純なブラウザ表示だけでもかなり運営しやすくなりました。ありがとうございます。
