### ISSUE TITLE
特定テーブルの編集権限を付けた役割をアカウントに付与したが反映されていない

### ISSUE THREAD

**Issue by toshihiro86** [exceedone/exment#883]
**Describe the bug / バグの説明**
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

役割グループCにテーブルAの全データ編集権限をつけて、特定のアカウントにその役割を紐づけました。
そのアカウントでログインしてみたところ、テーブルAの閲覧権限しかついていませんでした。
テーブルAで参照しているテーブルBの編集権限を役割グループCにつけたところ、役割を割りあてたアカウントでテーブルAの
編集が可能になりました。ちなみにテーブルBの参照以下の権限をつけた状態では、テーブルAの編集は割り当てアカウントではできませんでした。（編集のボタンが表示されませんでした）

**To Reproduce / 再現手順**
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
バグの説明の通りです

**Version / 発生バージョン**
Please describe version. / ご利用のバージョンを記載してください。

(v3.9.4)

**Error log / エラーログ**
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。
特になし

**Screenshots / スクリーンショット**
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

**Additional context / その他**
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by hirossyi73** [comment]
確認しましたが、正常に動作しているようでした。
![image](https://user-images.githubusercontent.com/8457265/103722546-93d8ed00-5013-11eb-8519-1cbafe3304ae.png)

![image](https://user-images.githubusercontent.com/8457265/103722642-c551b880-5013-11eb-92c5-9ccb62fcb2f2.png)

![image](https://user-images.githubusercontent.com/8457265/103722658-cbe03000-5013-11eb-8a3b-4d1f1bd8c6f0.png)

**Comment by toshihiro86** [comment]
ありがとうございます。

確認したところ
テーブルBは子供、テーブルAが親のリレーション関係がありました。
この場合は、親の編集権限がないと子供は編集できないというのは仕様でしょうか？

**Comment by toshihiro86** [comment]
上記いかがでしょうか？マニュアル参照しましたが、該当項目が見つかりません

**Comment by hirossyi73** [comment]
親子関係のリレーションがある場合、現在は、そのような仕様となっています。
※設定により、子だけ編集できるような仕様は検討します。

**Comment by toshihiro86** [comment]
承知しました。ありがとうございました。
