### ISSUE TITLE
列を追加後ダウンロード時にデータが出力されない

### ISSUE THREAD

**Issue by NorimasaArima** [exceedone/exment#884]
Exment Version   v3.9.4 
データをインポート後に列を追加してエクスポートで全てを実行するがCSV、エクセルともにデータ出力しない。
追加した列を削除するとデータの出力が行われる。

**Comment by hirossyi73** [comment]
再現しませんでした。
対応が必要な場合、issue作成時の「Bug report / 不具合報告」テンプレートを使用し、詳細情報をご報告ください。
