### ISSUE TITLE
メニューからテーブルデータ削除後再度追加できない

### ISSUE THREAD

**Issue by fujifuji427** [exceedone/exment#888]
**Describe the bug / バグの説明**
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

新規カスタムテーブル作成（メニュー追加オプションでYES選択）後、メニュー編集画面から新規作成した
テーブルデータのメニューを削除後、そのテーブルデータを対象に新規で追加しようとすると
「選択肢に含まれない値が選択されています。」と表示され追加できない。
・カスタムテーブル自体は削除していません
・メニュー名（英数字）は再追加時念のため変更しています。

仕様なのかどうかも含めてご確認いただけると助かります。

**Version / 発生バージョン**
Please describe version. / ご利用のバージョンを記載してください。
3.9.2

**Screenshots / スクリーンショット**
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。
![image](https://user-images.githubusercontent.com/77132765/103966378-193ed780-51a3-11eb-9121-ee9463a7f4e5.png)

**Comment by hirossyi73** [comment]
最新版にアップデートを行ってください。

**Comment by fujifuji427** [comment]
3.9.3のリリースノート見逃しておりました。
3.9.4にアップデートして修正を確認いたしました。
お手数おかけしました。
