### ISSUE TITLE
カスタム列設定の設定変更ができない

### ISSUE THREAD

**Issue by y-hayama** [exceedone/exment#894]
**Describe the bug / バグの説明**
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
カスタム列設定の列設定で設定変更を保存しようとするとエラーになります

**To Reproduce / 再現手順**
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
1. カスタム列設定で入力必須設定をYESにした列を作成する
2. 作成した列の必須設定をNOにする

**Version / 発生バージョン**
Please describe version. / ご利用のバージョンを記載してください。
v3.9.4

**Error log / エラーログ**
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。
[log.txt](https://github.com/exceedone/exment/files/5786496/log.txt)

**Screenshots / スクリーンショット**
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。
<img width="497" alt="スクリーンショット 2021-01-08 19 00 07" src="https://user-images.githubusercontent.com/13801922/104002213-16180b80-51e4-11eb-8cd4-8a899993a518.png">

**Additional context / その他**
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by y-hayama** [comment]
EXMENT_DEBUG_MODE_REQUESTを有効にしていると発生するようです

**Comment by hirossyi73** [comment]
ありがとうございます。別の不具合と合わせ、早急にリリースします。

**Comment by hirossyi73** [comment]
v3.9.5にて対応しました。
