### ISSUE TITLE
カスタム列設定　列種類－選択肢　のフリー入力

### ISSUE THREAD

**Issue by fleming35800** [exceedone/exment#896]
**Describe the feature you'd like / 希望する機能の説明を行ってください**
A clear and concise description of what you want to happen. / あなたが何をしたいのかについての、明確で簡潔な説明を行ってください。
カスタム列設定の列種類において、「選択肢」を選択した時の動作で、データ作成者が選択肢に選択したい項目が無い場合にフリー入力できるようにしてほしい。

**Additional context / その他**
Add any other context or screenshots about the feature request here. / 機能リクエストに関する他のコンテキストまたはスクリーンショットをここに追加します。

**Comment by hirossyi73** [comment]
2021/04/19 v4.1.0リリース完了
