### ISSUE TITLE
データコピー設定時カスタムテーブルを削除することができない

### ISSUE THREAD

**Issue by fleming35800** [exceedone/exment#897]
**Describe the bug / バグの説明**
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
カスタムテーブルでコピーデータ設定時カスタムテーブルをコピーすることができません。
コピーデータ設定されているカスタムテーブルも削除できません。

**To Reproduce / 再現手順**
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
１．任意のカスタムテーブルでコピーデータ設定をする。
２．１．で設定したカスタムテーブルを削除する。
３．削除失敗。

回避方法
　データコピー設定を削除するとカスタムテーブル削除可能になります。

**Version / 発生バージョン**
Please describe version. / ご利用のバージョンを記載してください。
v3.9.5

**Error log / エラーログ**
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。
[2021-01-13 14:47:11] local.ERROR: PDOException: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`exment_database`.`custom_copies`, CONSTRAINT `custom_copies_from_custom_table_id_foreign` FOREIGN KEY (`from_custom_table_id`) REFERENCES `custom_tables` (`id`)) in C:\xampp\local\exment\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php:129
Stack trace:

**Screenshots / スクリーンショット**
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。
![image](https://user-images.githubusercontent.com/75713203/104413207-43343780-55b1-11eb-8d3e-e21077bd2e30.png)
![image](https://user-images.githubusercontent.com/75713203/104413216-4af3dc00-55b1-11eb-8225-0b94d698eff8.png)

**Additional context / その他**
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by hirossyi73** [comment]
v4.0.1で、修正しました。

**Comment by fleming35800** [comment]
こちらに関しても改修されていることを確認できました。
ご対応いただきましてありがとうございます。
