### ISSUE TITLE
ビューの表示列に子テーブルの値を追加してほしい

### ISSUE THREAD

**Issue by a-kaneda0630** [exceedone/exment#898]
ビューの表示列に子テーブルの値を追加できるようにできないでしょうか。
一覧で表示させたいと考えております。

**Comment by dev-hayash** [comment]
親テーブルの一覧表示に子テーブルを表示する場合、1対1のレコード関係が保証されないと予期せぬ子レコードの値が表示されてしまうので、難しくないでしょうか

**Comment by hirossyi73** [comment]
@dev-hayash さんのご記載いただいている理由で、ビューの表示列は、子データを表示することはできません。
似たような方法としては、子テーブル側で、親テーブルのデータを表示することが出来ますので、そちらをご利用ください。

**Comment by a-kaneda0630** [comment]
早速のご回答ありがとうございました。
