### ISSUE TITLE
列種類ユーザーで必須の項目をもつテーブルは、ユーザー列に自分以外が入力されているとデータ更新できない

### ISSUE THREAD

**Issue by oyama230** [exceedone/exment#899]
**Describe the bug / バグの説明**

列種類ユーザーの必須の項目をもつテーブルは、
ユーザー列に自分以外の入力があるとデータ更新できない。

なおユーザー列が自分の場合は、正しくデータは更新される。

**To Reproduce / 再現手順**

【テーブルＡ】
カスタム列①：担当者　列種類：ユーザー　必須有効　1度のみ入力　初回値ログインユーザーをセット
カスタム列②：コメント　列種類：1行テキスト
テーブルＡに付与する権限は。全データの編集／全データの閲覧

テーブルＡに登録されているデータ
　担当者　|　コメント
　いろは　|　null
　ほへと　|　null

ログインユーザー「いろは」

1行目のデータにコメント「hogehoge」を入力して保存
⇒　正しく更新され一覧に戻る。
　担当者　|　コメント
　いろは　|　hogehoge
　ほへと　|　null

2行目のデータにコメント「hogehoge」を入力して保存
⇒　更新されない、入力フォームのまま。

**Version / 発生バージョン**
v3.9.5

**Error log / エラーログ**
データが更新されないケースにおいて
更新ボタンを押下後、入力フォームにエラー表記はなく、
ログにエラー情報の表記もない。

**Additional context / その他**
テーブルＡのカスタム列①の必須を無効にしても
状況は改善されませんでした。

**Comment by oyama230** [comment]
追記
カスタム列①：担当者　列種類：ユーザー　必須有効　1度のみ入力　初回値ログインユーザーをセット
から、1度のみ入力と初回値ログインユーザーをセットもの設定をそれぞれ初期値に戻したところ更新処理が行われた。

テーブルＡには、WEBAPIで追加されるデータと手入力のデータが混在している
本件で問題となったデータは、WEBAPIで追加されたものだった。

障害事由が「更新できない」のため、新規追加時に発火するイベントと設定と思われる
1度のみ入力　初回値ログインユーザーをセットの設定値は気にしていなかったが
登録済のデータに対して、前述項目の影響により更新処理に進めない状態のように見えます。

**Comment by hirossyi73** [comment]
情報ありがとうございます。
すみません、来週頭にLaravel6.X対応を控えており、その後確認とさせてください。

**Comment by hirossyi73** [comment]
v4.0.1で、修正しました。

**Comment by oyama230** [comment]
前述の設定値においてデータの保存が、できることを確認しました。
ご対応ありがとうございました。

本件クローズさせて頂きます。
