### ISSUE TITLE
テキストエディタで画像の挿入ができない

### ISSUE THREAD

**Issue by ashtail** [exceedone/exment#901]
**Describe the bug / バグの説明**
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

カスタム列テキストエディタで画像の挿入ができません。

**To Reproduce / 再現手順**
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

テキストエディタの画像挿入で画像を選択しても「Error: fileには画像ファイルを指定してください。」とでます。
jpg,png,gifすべて不可です。

**Version / 発生バージョン**
Please describe version. / ご利用のバージョンを記載してください。

Version   v3.9.5

**Comment by hirossyi73** [comment]
jpgは確認できましたので、対応しました。(#882 と関連)
残りは、こちらの環境だとアップロード出来、再現しませんでした。

**Comment by ashtail** [comment]
いろいろアップしてみたところ、こちらの環境だと10Mを超えると上記のエラーがでるようです。
アップロード上限を20Mに設定してありますが、テキストエディタは摘要範囲外という仕様でしょうか。

**Comment by ashtail** [comment]
申し訳ありません。再度試したところ10M以上も大丈夫でした。失礼致しました。

**Comment by hirossyi73** [comment]
ありがとうございます。
v4.0.0にてリリースしましたので、一旦クローズします。
