### ISSUE TITLE
php.ini の設定の読出し方の変更

### ISSUE THREAD

**Issue by ibikd** [exceedone/exment#905]
**Describe the feature you'd like / 希望する機能の説明を行ってください**
A clear and concise description of what you want to happen. / あなたが何をしたいのかについての、明確で簡潔な説明を行ってください。

はじめまして。

おそらく php.ini ファイルの内容を読み込んでexmentの動作に反映させる設計なのではないかと思うのですが、
php.ini ファイルではなく、
php -i 等のphpの出力をexmentの動作へ反映させるように変更するのはいかがでしょうか。

といいますのは、php の build時に、--with-config-file-scan-dir のオプションを付与した場合に、
php は php.ini の内容に加えオプションで指示されたディレクトリ内の設定を読み込みます。

--with-config-file-scan-dir で指定したディレクトリに、GD 等の extension module の設定（extension=gd.so等）を記載したファイルを配置している場合、
php の実行時には所望のmoduleが読み込まれているのに、exment上では読み込まれていない判定になります。

という事で、php.ini ファイルの設定だけではでは判断出来ない場合があるため、そのような変更はいかがでしょうか。
あるいは、php -i で --with-config-file-scan-dir を検出し、php.ini と 繋げて？判定する、といった方法でも対応出来るのだろうなと思っております。

**Additional context / その他**
Add any other context or screenshots about the feature request here. / 機能リクエストに関する他のコンテキストまたはスクリーンショットをここに追加します。

**Comment by hirossyi73** [comment]
ご提案ありがとうございます。
今回ご提案いただいた内容をExmentに反映させる場合、Laravel（ならびにPHP）を、どのように修正すれば実現できますでしょうか？
