### ISSUE TITLE
子テーブルを持つ親テーブルのフォームで正しく関連絞り込みされない場合がある

### ISSUE THREAD

**Issue by C0ela** [exceedone/exment#909]
**Describe the bug / バグの説明**
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

子テーブルを持つ親テーブルのフォームで正しく関連絞り込みされない場合があります。

**To Reproduce / 再現手順**
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

登場するテーブルは次の3つです。

- 親テーブル
- 子テーブル（参照先テーブルを参照する列を持つ）
- 参照先テーブル（カテゴリーA、Bが登録されている）

親テーブルのカスタムフォーム内で子テーブルを編集するとき、参照先テーブルを参照して関連絞り込みを設定します。

この時、親テーブルで

親
┣子a（カテゴリーA）
┗子b（カテゴリーB）

という内容のデータを登録すると、親テーブルのカスタムフォーム内で子テーブル編集時に、
子aの関連絞り込み結果　→　カテゴリーBでの絞り込み結果
または
子bの関連絞り込み結果　→　カテゴリーAでの絞り込み結果
になります。

なお、子が全て同じカテゴリーを使用していれば症状は発生しません。
また、同様に関連絞り込みを設定している子テーブル側のカスタムフォームを使用した場合も正しく絞り込みされます。

**Version / 発生バージョン**
Please describe version. / ご利用のバージョンを記載してください。

Exment v3.9.5

**Comment by hirossyi73** [comment]
@C0ela 
【テーブル】
・製品カテゴリ
・製品（製品カテゴリを親に持つ？）

■データ構成
カテゴリ　製品
A　製品a1
A　製品a2
A　製品a3
B　製品b1
B　製品b2
 
・契約
・契約明細（製品カテゴリ列、製品列を参照列で持つ）

 
【データ登録時】
契約
明細１　製品カテゴリA選択→製品b1とb2になる
明細２　製品カテゴリB選択→製品a1とa2とa3になる

このような状況で合っていますでしょうか。
