### ISSUE TITLE
v4.0へのバージョンアップに失敗します

### ISSUE THREAD

**Issue by sayoko-iwahashi** [exceedone/exment#922]
**Describe the bug / バグの説明**
v3.9からｖ4.0へのバージョンアップでcomposer updateが失敗します。

**To Reproduce / 再現手順**
https://exment.net/docs/#/ja/update/v4_0　の記載通り
１．composerのバージョンアップ（1->2)
２．composer require lcobucci/jwt=3.3.*　の実行
３．composer.json修正　
４．composer update の実行

**Version / 発生バージョン**
Please describe version. / ご利用のバージョンを記載してください。
V3.9

**Error log / エラーログ**
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

**Screenshots / スクリーンショット**
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install exment-oauth/microsoft-graph v1.0.1 (conflict analysis result)
    - Root composer.json requires exceedone/exment ^4.0 -> satisfiable by exceedone/exment[v4.0.0].
    - Conclusion: don't install laravel/framework v6.20.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.4 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.5 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.6 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.7 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.8 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.9 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.10 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.11 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.12 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.13 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.14 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.15 (conflict analysis result)
    - exment-oauth/microsoft-graph v1.0.0 requires laravel/socialite ~3.2.0 -> satisfiable by laravel/socialite[v3.2.0].
    - Root composer.json requires exment-oauth/microsoft-graph ^1.0 -> satisfiable by exment-oauth/microsoft-graph[v1.0.0, v1.0.1].
    - laravel/socialite v3.2.0 requires illuminate/support ~5.4 -> satisfiable by illuminate/support[v5.4.0, ..., 5.8.x-dev].
    - Only one of these can be installed: illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev], laravel/framework[v6.0.0, ..., 6.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
    - exceedone/exment v4.0.0 requires laravel/framework ~6.20 -> satisfiable by laravel/framework[v6.20.0, ..., 6.x-dev].
    - Conclusion: don't install laravel/framework v6.20.0 (conflict analysis result)

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**Additional context / その他**
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by hirossyi73** [comment]
情報の集約のため、こちらに記載をお願いします。
https://github.com/exceedone/exment/issues/885

**Comment by hirossyi73** [comment]
対応しましたので、再度マニュアルをご確認ください。
https://exment.net/docs/#/ja/update/v4_0

composer.jsonの、  "exment-oauth/microsoft-graph": "~2.0",の値を修正し、update実施します。

**Comment by sayoko-iwahashi** [comment]
ご対応ありがとうございました！
無事、バージョンアップできました。
