### ISSUE TITLE
UIデザイン改善について

### ISSUE THREAD

**Issue by a0z0** [exceedone/exment#929]
**Describe the feature you'd like / 希望する機能の説明を行ってください**
A clear and concise description of what you want to happen. / あなたが何をしたいのかについての、明確で簡潔な説明を行ってください。

パソコンで試行させていただいてますが、操作上のストレス何点かございます。

- 一覧画面の"操作"アイコンが小さすぎます。マウス操作がシビアです。
> 提案: 大きくする、余白を設ける、Mouse Overのフォーカスをわかりやすくする。

- 表示/編集フォームでスクリーンに収まる項目が少なすぎます。5項目くらいしか表示されない。
- また、2列表示では、直感的な項目並び順にならない
> 提案: IDなどのヘッダーを控えめにする。
> 提案: 1行に複数の項目を表示できるようにする。狭い幅の項目、チェック項目などを1行で配置位置したい
> 提案: プルダウンの[サーチ]ボタンを項目の後ろに配置する。

**Additional context / その他**
Add any other context or screenshots about the feature request here. / 機能リクエストに関する他のコンテキストまたはスクリーンショットをここに追加します。

**Comment by fleming35800** [comment]
開発者ではありませんが、その辺りの調整はスタイルのプラグインを作成する事である程度可能な項目になります。
ホームページに操作マニュアル等ございますので、ご自身で確認してご対応可能かと存じ上げます。
https://exment.net/docs/#/ja/plugin

**Comment by a0z0** [comment]
ご回答ありがとうございます。
プラグインでCSSを設定すればレイアウト調整可能ということですね。
個別対応としては有効な手段ですが、それでも標準機能のさらなる改善は必要と考えます。

**Comment by hirossyi73** [comment]
> 一覧画面の"操作"アイコンが小さすぎます。マウス操作がシビアです。

こちらは、確かにそうですね。対応検討します。
