### ISSUE TITLE
検索インデックスYES の数28個以上に対応

### ISSUE THREAD

**Issue by ma2mura01** [exceedone/exment#93]
エラー時のコード
`QueryException In C:\xampp\htdocs\Etest\vendor\laravel\framework\src\Illuminate\Database\Connection.php line 664 :
SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs (SQL: ALTER TABLE exm__4969d5a5db9ea80ad7e2 ADD column_d5320d8c29b311d168f6 nvarchar(768) GENERATED ALWAYS AS (json_unquote(json_extract(`value`,'$.select2ndChoice'))) VIRTUAL;)
`

**Comment by hirossyi73** [comment]
検索インデックスは、1テーブルにつき10個までとします。
それ以上のインデックスを登録しようとしたらエラーを表示してください。
