### ISSUE TITLE
画面入力による一括更新機能

### ISSUE THREAD

**Issue by a0z0** [exceedone/exment#930]
**Describe the feature you'd like / 希望する機能の説明を行ってください**
A clear and concise description of what you want to happen. / あなたが何をしたいのかについての、明確で簡潔な説明を行ってください。

一覧画面から一括更新できるようになってますが、
更新する値を画面から入力または選択できるようになりませんでしょうか。

**Additional context / その他**
Add any other context or screenshots about the feature request here. / 機能リクエストに関する他のコンテキストまたはスクリーンショットをここに追加します。

**Comment by hirossyi73** [comment]
v4.2.2にて実装しました。
