### ISSUE TITLE
カスタム列ごとのアクセス権限

### ISSUE THREAD

**Issue by a0z0** [exceedone/exment#931]
**Describe the feature you'd like / 希望する機能の説明を行ってください**
A clear and concise description of what you want to happen. / あなたが何をしたいのかについての、明確で簡潔な説明を行ってください。

カスタム列ごとにアクセス権限を設定することはできませんでしょうか。
例えば、ユーザーテーブルの生年月日の列は管理者しか参照できないように。

**Additional context / その他**
Add any other context or screenshots about the feature request here. / 機能リクエストに関する他のコンテキストまたはスクリーンショットをここに追加します。

**Comment by fleming35800** [comment]
#929 と同様こちらに関しても設定で対応可能な項目になります。
https://exment.net/docs/#/ja/permission
このあたりを参考にされるとよいかと存じます。

**Comment by a0z0** [comment]
ご回答ありがとうございます。
ご呈示いただいたマニュアルで権限に関する事項を再確認いたしましたが、
カスタム列の権限について記載はございませんでした。
いまのところ、
- カスタムフォームまたはプラグインで権限ごとに表示項目を切り替える
- テーブル(またはデータ)を権限ごとに分割する
などを思案しましたが、いまいちです。

**Comment by fleming35800** [comment]
役割グループを利用することにより、テーブル毎表示非表示もしくはテーブル内のデータの閲覧、編集、等切替可能です。

**Comment by a0z0** [comment]
ご回答ありがとうございます。
ここの設定では全データ(=テーブル)とデータ(=レコード)のアクセス権限を設定できると思いますが、
カスタム列(=項目)ごとの権限設定はできないのでは?
私の認識違でしたら申し訳ございません。

**Comment by fleming35800** [comment]
列ごとの権限設定をしたいのですね。
確かに権限設定はできない認識です。
カスタムテーブルと勘違いしていました。
失礼いたしました。
