### ISSUE TITLE
【知見いただきたいです】Vue.jsのキャッシュを削除する方法

### ISSUE THREAD

**Issue by hirossyi73** [exceedone/exment#937]
少々困っています、知見ある方助けていただけると嬉しいです。

マニュアルページが、[docsify](https://docsify.js.org/#/)というVueベースのライブラリを使用しているのですが、mdファイルを更新しリリースしても、キャッシュが残ってしまい、
最新のマニュアルを更新するためには、Ctrl+F5を実行するなどの手間が発生しています。
https://exment.net/docs/#/ja/
そのため、ユーザーによってはキャッシュが残り続け、古いマニュアルのままになってしまうという症状が発生しています。

htmlファイルにキャッシュを保持しないなどの処理は記載したのですが、有効にならず困っています。
どなたか詳しい方いらっしゃいましたら、Vueのキャッシュを有効にせず、都度最新のファイルを読み込む方法をご提供いただけると嬉しいです。

**Comment by dev-hayash** [comment]
お世話になっております。
docsifyは使用したことはなく、ドキュメントを見た内容だけで回答しております。

https://docsify.js.org/#/configuration?id=requestheaders
こちらにキャッシュ制御の記述があります。

```
window.$docsify = {
  requestHeaders: {
    'cache-control': 'max-age=600',
  },
};
```
また、docsifyのissueにキャッシュが効かないけど自己解決した内容がありました。

https://github.com/docsifyjs/docsify/issues/1119#issuecomment-613479794
'cache-control': 'max-age=0'で解決しているようです。

https://developer.mozilla.org/ja/docs/Web/HTTP/Headers/Cache-Control
こちらを見ると、max-ageの代わりに　'no-store'　でも良さそうに見えます。（max-age=0を包括している）

**Comment by hirossyi73** [comment]
@dev-hayash 
ありがとうございます！コメント嬉しいです。
ただ、ソース見てみたのですが、以前調べてみた時に、こちらを追加済みでした。

```
      requestHeaders: {
        'cache-control': 'no-store',
      },
```

他に何らかの理由があると思うので、もう少しdocsify.jsを検証してみます。

**Comment by dev-hayash** [comment]
流石に対策していますよね😅

ちなみにキャッシュされた場合のlast-modifiedは、実際の更新日が格納されているのでしょうか。
![image](https://user-images.githubusercontent.com/19341340/107917183-d8f52500-6faa-11eb-8a80-e74b7e747ddf.png)

**Comment by hirossyi73** [comment]
確認してみました。
last-modified、サーバーの実際の更新日時ではなく、キャッシュされた日時になっていました。

いただいたお話を元にもう少し調べてみた所、こちらをrequestHeadersに入れることで、解消された気がします。
XMLHttpRequestのキャッシュ削除文を強化しました。
http://sookibizviz.blog81.fc2.com/blog-entry-1625.html

```
      requestHeaders: {
        'cache-control': 'no-cache',
        'Pragma': 'no-cache',
        'If-Modified-Since': 'Thu, 01 Jun 1970 00:00:00 GMT',
      },
```

ありがとうございます！
