### ISSUE TITLE
【仕様確認】バックアップ時の処理

### ISSUE THREAD

**Issue by fleming35800** [exceedone/exment#938]
お世話になっております。

当方の環境にて毎日自動バックアップを回しており、バックアップデータのサイズが毎日増えていくのですが、
40MBを超える位のサイズになった次の日のバックアップで、データサイズがかなり小さくなります。
（おおよそ1/4くらい）
特に登録しているデータが前日に比べいきなり減ったといった事は無いハズなのですが、何回かこのようなことが確認されています。
一定以上データが大きくなった場合に、データを圧縮するような処理を噛ませるようなことをしているのでしょうか？
![image](https://user-images.githubusercontent.com/75713203/108008777-7e100c00-7044-11eb-8dfd-f649e6752a83.png)

**Comment by hirossyi73** [comment]
2重バックアップなどは特に実施していないです。
環境依存によるものなのか、どの環境でも発生するものなのか、一度確認させてください。

**Comment by fleming35800** [comment]
ご回答ありがとうございます。承知いたしました。

何回かデータが小さくなった時にリストアを試して、問題なさそうなのは確認しており、
運用上特に不都合があるわけでもありませんが、追加で何かわかりましたら情報頂けましたら幸いです。
