### ISSUE TITLE
システム管理者にユーザーを追加しようとすると「選択肢に含まれない値が選択されています」と赤字でエラーがでて更新反映されません。

### ISSUE THREAD

**Issue by toshihiro86** [exceedone/exment#940]
**Describe the bug / バグの説明**
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
システム管理者にユーザーを追加すると失敗します。
「選択肢に含まれない値が選択されています」とエラー表示されます

**To Reproduce / 再現手順**
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
システム設定のページに移動する
https://dev-exment.uzabase.com/system

システム管理者の追加用の入力個所に追加したいユーザー名を入れる

サジェストされるのものを選ぶ

青色背景で入力追加されていることを確認する

保存ボタンを押す

添付画像のエラーが発生する
※別ユーザーでも同様

**Version / 発生バージョン**
Please describe version. / ご利用のバージョンを記載してください。
v4.0.1  

**Error log / エラーログ**
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

**Screenshots / スクリーンショット**
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。
![image](https://user-images.githubusercontent.com/77033639/108137031-6eed9480-70fe-11eb-89fe-d336d0022d50.png)

**Additional context / その他**
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by hirossyi73** [comment]
ユーザーが100人以上の時に発生する事がわかりました。すぐに対応します。

**Comment by hirossyi73** [comment]
@toshihiro86 
先ほどv4.0.3にて対応しましたので、ご確認ください。
