### ISSUE TITLE
カスタム列で自動採番を選択肢→フォーマット→変数に$ {y}-${id:8}をセットしても上手く採番してくれない

### ISSUE THREAD

**Issue by A87da** [exceedone/exment#942]
カスタム列で自動採番を選択肢→フォーマット→変数に$ {y} -${id:8}をセットしても上手く採番してくれません。
新規データを入力した場合、
文字列として$ {y}-${id:8}のまま出力されてしまう

**Comment by A87da** [comment]
$ {year}だといけました~

**Comment by A87da** [comment]
自動採番の場合、テストデータを入れた後にテストデータを削除後、正規データを入れて番号を00001からまたスタートさせたい場合はアーカイブされた（過去使用済、削除された）番号をリセットする方法はありますでしょうか。

**Comment by hirossyi73** [comment]
「$」と「{y}」の間にスペースが入っている気がするのですが、それはGitHubに記入の都合でしょうか？
また、データのリセットは、1からリセットする場合のみ対応しています。
https://exment.net/docs/#/ja/refresh_data

**Comment by A87da** [comment]
Hirossyiさん、ありがとうございます。
空白は除いてました。

データリセットの件もありがとうございます！！！

2021年2月18日(木) 15:02 hirossyi73 <notifications@github.com>:

**Comment by A87da** [comment]
Hirossyiさん

いつもお世話になっております。
いろいろといつもありがとうございます

検索で見つけられなかったのですが、ワークフロー機能を使いたい場合には、デフォルトぽい組織マスタの
organaizationマスタへデータを投入するといいのでしょうか。

手順箇所あればお手すきで教えていただけたら大変嬉しいです。

花田

2021年2月18日(木) 15:04 Akiko Hanada <akiko.hanada@uzabase.com>:
