### ISSUE TITLE
バージョン4.X.0 リリース機能

### ISSUE THREAD

**Issue by hirossyi73** [exceedone/exment#952]
[現在開発中のv4.1.0](https://github.com/exceedone/exment/issues/906)の後、v4.2.0の開発に着手していきたいのですが、
その際、どの機能を優先して実装するかどうかで、現在検討中です。

ここはOSSらしく、Voteで皆様のご意見を募ることにしました。
実際に様々な業務で使っていただいている皆様のご意見を、可能な限り取り入れて行きたいと考えています。

優先して実装してほしい内容に対し、下記に記載するissueレスへのリンクに、+1（:thumbsup:）していただけると幸いです。

投票数の上限は明確には決めませんが、できれば1～2件ぐらいまでの方が信憑性が上がるので嬉しいです。

※私が個人的に実装したい内容を、下記issueレスに入れていますが、「これを候補に入れたい」というのがあれば、別途レスいただいて構いません。
※機能要望は、ここで初出にはせず、個別のissueを立て、そのリンクを記入いただけると助かります。（埋もれてしまうことの防止）

※期限は票数を見つつ、3/14頃までで検討しています。

**Comment by hirossyi73** [comment]
#951 Excelファイル内のテーブルを元に、Exmentのテーブル・列・フォーム・ビュー・データを一括で作成する

**Comment by hirossyi73** [comment]
#950 プラグイン種類に、CRUDページを追加する
→プラグイン種類にCRUD + Listを追加する。
他のデータベースエンジンや、WordPress、SharePointリスト、他社Webデータベース、会計システムなどを、Exmentにデータを取り込むことなく、Exmentの画面で容易に管理可能にする。

**Comment by hirossyi73** [comment]
#802 レコードコメントでメンション（宛先）を指定して、利用ユーザーに通知したい
→「@」などで特定のユーザーへのレスポンスを可能にし、そのユーザーには通知を送信する。

**Comment by hirossyi73** [comment]
#808 レコードの複製に関する要望
→1:nのリレーションのある親テーブル側で、子テーブルのレコードも含めた複製ができるようになる機能。
もしくは、1:nでの親子テーブルの「レコードのテンプレート」のようなものを登録し呼び出せるような機能。

**Comment by hirossyi73** [comment]
#669 多言語対応
・ユーザー毎に言語を変更でき、その言語で画面表示するようにする。
・テーブル表示名や列表示名など、一部の項目を、他言語で設定可能にする。
・中国語に対応。（Google翻訳になってしまうと思いますが）

**Comment by fleming35800** [comment]
#945 複数データの一括申請操作
　振込依頼等、申請を複数まとめて作成して、申請する機会がある為、一括で申請操作をできるようにしていただければと考えております。
・複数申請作成後、「一括削除」操作と同じようなイメージで「一括申請」可能にする。

**Comment by ookini** [comment]
ワークフローの削除を可能にして欲しい

**Comment by tkpontas** [comment]
#966 カレンダービューの拡充
色分け条件にカスタム列のユーザーまたは組織の列を利用できるようにする。

**Comment by hirossyi73** [comment]
投票ありがとうございました！
以下の2つが非常に票数が多かったので、次期対応とさせてください。

---


#951 Excelファイル内のテーブルを元に、Exmentのテーブル・列・フォーム・ビュー・データを一括で作成する
→業務などで使用しているExcelファイルをアップロードし、Exmentのテーブル・列・フォーム・ビュー・データを一括で作成する機能

#950 プラグイン種類に、CRUDページを追加する
→プラグイン種類にCRUD + Listを追加する。
他のデータベースエンジンや、WordPress、SharePointリスト、他社Webデータベース、会計システムなどを、Exmentにデータを取り込むことなく、Exmentの画面で容易に管理可能にする。

---

次点：
#808 レコードの複製に関する要望
#662 「データ複製」機能
→1:nのリレーションのある親テーブル側で、子テーブルのレコードも含めた複製ができるようになる機能。
もしくは、1:nでの親子テーブルの「レコードのテンプレート」のようなものを登録し呼び出せるような機能。
→通知設定の「複製」と同じような機能で、カスタムテーブルのデータを「複製」する機能。

**Comment by hirossyi73** [comment]
当初、v4.2.0の機能として検討していましたが、他の機能のご要望が多数あり、申し訳ありませんが将来的な対応とさせてください。
