### ISSUE TITLE
【仕様確認】ワークフロー履歴の取得

### ISSUE THREAD

**Issue by fleming35800** [exceedone/exment#955]
ワークフロー実施時に申請データ選択して履歴を表示すると出てくる以下の「実行ユーザー」に関して、
プラグインードキュメント出力などで利用できる形でデータを取得することは現状難しいのでしょうか？
![image](https://user-images.githubusercontent.com/75713203/109766806-06440300-7c3a-11eb-999a-9ee909ffa4c7.png)

**Comment by hirossyi73** [comment]
$custom_value->getWorkflowHistories($appendsStatus = false)
で、履歴は取ってこれます。
※引数をtrueにすると、ステータス名も取ってこれます

**Comment by fleming35800** [comment]
お世話になっております。
ご返信いただきありがとうございます。
いつも大変助かっております。ご確認させていただきます。

**Comment by fleming35800** [comment]
確認させていただきまして、履歴の取得できました。
ご教授いただきましてありがとうございます。
