### ISSUE TITLE
【仕様確認】カスタム列-列種類「ファイル」の添付可能ファイル数について

### ISSUE THREAD

**Issue by fleming35800** [exceedone/exment#959]
いつもお世話になっております。

カスタムデータの添付ファイルのファイル数は設定のEXMENT_DOCUMENT_UPLOAD_MAX_COUNTにて調整可能という認識ですが、
カスタム列ー列種類「ファイル」にて入力するフォームの添付ファイル数は基本ファイル入力フォームひとつにつき１ファイルなのでしょうか？
現状、ひとつのファイル入力フォームに対して複数ファイル添付する方法はございますでしょうか？

カスタムデータの添付ファイルで、1度にアップロードできるファイル数
設定キー : EXMENT_DOCUMENT_UPLOAD_MAX_COUNT
既定値 : 5
役割 : カスタムデータの添付ファイルのフォームで、1度にアップロードできる件数です。

![image](https://user-images.githubusercontent.com/75713203/110263562-7667d580-7ffa-11eb-895e-84e54c16daf7.png)

お忙しい中恐縮ですが、ご確認いただけましたら幸いです。

**Comment by hirossyi73** [comment]
現状は1つですが、4.1.0にて複数ファイルに対応予定です。

**Comment by fleming35800** [comment]
お世話になっております。
承知いたしました。情報ありがとうございます。
