### ISSUE TITLE
Composerエラー

### ISSUE THREAD

**Issue by patipati3** [exceedone/exment#965]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
さくらインターネットでExmentを構築したところ、Composerをインストールしたにもかかわらず、composerのインストールを確認できませんでした。Exmentのアップデートが正常に完了しない場合があります。というエラーが発生する。

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
Exment公式サイトにある手順通りにComposerをインストールした。
Composer保存場所
/home/ドメイン名/usr/local/bin/composer

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
Exment Ver v4.0.6
Composer version 2.0.11

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。
composerのインストールを確認できませんでした。Exmentのアップデートが正常に完了しない場合があります。※権限設定やパスの設定により、composerが設定されているにも関わらず、この警告が表示される場合があります。

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。
Exment公式サイトの説明通りに進めて行っていたのですが、このようなエラーが出たため、可能であれば解決後、今後導入される方に向けて、情報の更新をしていただければ幸いです。

**Comment by hirossyi73** [comment]
こちら確認してください。
https://exment.net/docs/#/ja/server?id=composer%e3%82%a4%e3%83%b3%e3%82%b9%e3%83%88%e3%83%bc%e3%83%ab

**Comment by patipati3** [comment]
ご返信ありがとうございます。

こちらのURLも質問をする前に確認させていただいたのですが

これは、Webサーバーを動作させるユーザーからcomposerのパスが通っていない、権限が足りないなどの理由があります。
composerが正常にインストールされており、実際にアップデートを実施するユーザーが実行可能な場合は、この警告は無視してください。

この説明内の文面で言えば、パスなどの設定はさくらインターネットの場合はなかったため、実際にアップデートを行うユーザーがSSL通信でComposerを実行できることを確認できたならば、無視していただいて構わないということでよろしいでしょうか。
