### ISSUE TITLE
ヘッダー右上のユーザー名に、別のユーザー名が表示される

### ISSUE THREAD

**Issue by oyama230** [exceedone/exment#971]
### Describe the bug / バグの説明

フリーアドレス的なイメージでパソコンをシャッフルして利用する
環境で使わせていただいております。

頻度はわずかですが、掲題の事象に困っています。

発症事例も少なく、利用者もユーザー名が違うと
びっくりして直ぐログアウトする傾向があり検証しにくく
問題を再現できるところまで調査できていません。

現在つかめている状況は以下のとおり
- ログインしなおすと正しいユーザー名で表示される。
- 別のユーザー名で表示されている状態で
　入力した内容はログインユーザーのデータとして登録されてる。
- 表示される別のユーザー名は、直前の利用者ではなく、
　数日前に利用したユーザー名。ブラウザーのキャッシュ以外の影響も。

補記
設定一覧のキャッシュ設定は「無効」としています。

以上です
ご確認のほど、よろしくお願いいたします。

### Version / 発生バージョン
v3.9.5

**Comment by hirossyi73** [comment]
初めて聞くケースですので、いくつかご質問させてください。

「別のユーザー名が表示される」直前に、ログインはしておりますでしょうか？以下のいずれかを確認したいです。
　・最初はログアウトだったので、ログインしたにも関わらず、画面は前操作者の名前になっている
　・操作者のログイン状態が残っていたので、最初からログイン状態だった時に発生
　・それ以外

**Comment by oyama230** [comment]
ご回答させていただきます。

>「別のユーザー名が表示される」直前に、ログインはしておりますでしょうか？以下のいずれかを確認したいです。
>　・最初はログアウトだったので、ログインしたにも関わらず、画面は前操作者の名前になっている
⇒　このケースですが、直前の操作者ではなく、数日前の操作者名だった。
　　前操作者が表示されている状態に気づかず、登録したデータは操作者本人のものだった。
　　（※データ登録後に操作者名の違いに気づいた。）

>　・操作者のログイン状態が残っていたので、最初からログイン状態だった時に発生
⇒　設定値「EXMENT_SESSION_EXPIRE_ON_CLOSE」をtrueにて運用しているため
　　本ケースは検討から外していいと考えます。

気づいたこと
- 発生頻度は1ヶ月に1度あるかないか。
- 社内ではChromeまたはFirefoxを使用していますが、本トラブルはChromeで発生している気がしています。
- PCは毎日、朝立ち上げて、帰るときにはシャットダウンしています。

以上です、ご確認のほどよろしくお願いいたします。
