### ISSUE TITLE
アップデートがExmentでされない

### ISSUE THREAD

**Issue by patipati3** [exceedone/exment#972]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
お世話になっております。
先日、以下の件で問い合わせをさせていただいた者です。
https://github.com/exceedone/exment/issues/965

アップデートの通知がきており、アップデート手順通りにアップデートを行ったのですが、ログアウトをしてからログインをし直しても、バージョンが更新されないという状況になっております。

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
https://exment.net/docs/#/ja/update
さくらインターネットなので、上記URLの通りにアップデートを行いました。

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
Exment Ver 4.0.8
PHP 7.4.15
composer version 2.0.11 2021-02-24 14:57:23

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。
---------Start Exment Update---------
Execute Backup
Could not open input file: artisan
Update exceedone/laravel-admin
Using version ^2.0 for exceedone/laravel-admin
./composer.json has been updated
Running composer update exceedone/laravel-admin
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.
Generating autoload files
54 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Update exceedone/exment
Using version ^4.0 for exceedone/exment
./composer.json has been updated
Running composer update exceedone/exment
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.
Generating autoload files
54 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Execute Update
Could not open input file: artisan
Finish Update!

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by hirossyi73** [comment]
環境依存のお問い合わせは、こちらより、有償サポートをご検討ください。
https://exment.net/inquiry
