### ISSUE TITLE
ワークフローで現在の作業ユーザーをフィルタリング対象にするとエラー

### ISSUE THREAD

**Issue by burukaniro** [exceedone/exment#974]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

ワークフローを作成してから、「現在の作業ユーザー」をフィルタリング対象にすると
ビュー設定でも一覧からのフィルタリングでもエラー表示になります。

( エラーコード )
QueryException In Connection.php line 669 :

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。

4.0.9

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

 QueryException In Connection.php line 669 :
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'test_db.view_workflow_value_unions' doesn't exist (SQL: select count(*) as aggregate from `exm__9703f818966a34f17303` left join ((select distinct `exm__9703f818966a34f17303`.`id` as `morph_id` from `exm__9703f818966a34f17303` inner join `view_workflow_start` on `view_workflow_start`.`workflow_table_id` = 36 where not exists (select 1 from `workflow_values` where `workflow_values`.`morph_id` = `exm__9703f818966a34f17303`.`id` and `workflow_values`.`morph_type` = A-1-1 and `workflow_values`.`latest_flg` = 1) and ((`authority_related_id` = 1 and `authority_related_type` = user) or (`authority_related_id` in (1) and `authority_related_type` = organization) or (`authority_related_id` = 150 and `authority_related_type` = column and `exm__9703f818966a34f17303`.`column_21575e8ce71a4b41fd93` = 1) or (`authority_related_id` = 0 and `authority_related_type` = system and `exm__9703f818966a34f17303`.`created_user_id` = 1))) union (select distinct `exm__9703f818966a34f17303`.`id` as `morph_id` from `exm__9703f818966a34f17303` inner join `view_workflow_value_unions` on `view_workflow_value_unions`.`custom_value_id` = `exm__9703f818966a34f17303`.`id` and `view_workflow_value_unions`.`custom_value_type` = A-1-1 and `view_workflow_value_unions`.`workflow_table_id` = 36 where ((`authority_related_id` = 1 and `authority_related_type` = user) or (`authority_related_id` in (1) and `authority_related_type` = organization) or (`authority_related_id` = 150 and `authority_related_type` = column and `exm__9703f818966a34f17303`.`column_21575e8ce71a4b41fd93` = 1) or (`authority_related_id` = 0 and `authority_related_type` = system and `exm__9703f818966a34f17303`.`created_user_id` = 1)))) as `workflow_values_wf` on `exm__9703f818966a34f17303`.`id` = `workflow_values_wf`.`morph_id` where (`workflow_values_wf`.`morph_id` is not null) and `exm__9703f818966a34f17303`.`deleted_at` is null)

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

![image](https://user-images.githubusercontent.com/76467166/113110114-aee98080-9241-11eb-83c8-0cc0add8d2dd.png)

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

キャッシュの削除やクリーン環境にリストアしましたが同様の現象が発生します。

**Comment by jyodai** [comment]
view_workflow_value_unionsテーブルが存在しない事が原因だと推測します。

私の環境で以下のコードを実行し、バグの説明通りの動作を行うと再現しました。

```
mysql> Rename tables view_workflow_value_unions to view_workflow_value_unions_back;
Query OK, 0 rows affected (0.01 sec)
```

お手数ですが、対象DBのテーブルにview_workflow_value_unionsテーブルが存在しているかご確認をお願い致します。

**Comment by burukaniro** [comment]
遅くなりましたがアドバイス有難うございます。確認しましたところ、view_workflow_value_unionsテーブルについては存在しておりました。
ただ、その他幾つか検証しましたところ、どうもExmentの自動バックアップではSQLから取得出来ていない箇所があるようです。
手動でバックアップを実行するとdumpのフェーズで
mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces
とエラーが出ており、所々抜けがあるようです。(MySQL5.73以降の仕様変更のようです。)

Exment付属のバックアップ機能ではなくmysqldumpでエクスポートしたものをリストアしたところ
今のところは該当のエラーは解消されているようです。
