### ISSUE TITLE
画面プラグインを複数登録していると、各プラグインのpublicを参照するHTMLが生成される

### ISSUE THREAD

**Issue by dev-hayash** [exceedone/exment#977]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

仕様かもしれないのですが、不都合が起きそうな動作の為、起票しました。

UUIDが異なる画面プラグインを３つ登録しています。
![image](https://user-images.githubusercontent.com/19341340/113985908-9d2e5b80-9887-11eb-8303-12c4eed8bb4b.png)

プラグインをそれぞれメニューに登録し、そのうちの１つを表示させたところ、３つのプラグインに含まれるpublicフォルダ内のファイルをすべてscriptタグで参照するHTMLが生成されています。

実際に、それらのファイルはGETメソッドで取得されていました。
<br><br>
### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
（古くて恐縮ですが）v3.7.2
<br><br>
### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

HTML内ソース
![image](https://user-images.githubusercontent.com/19341340/113994306-3a8d8d80-9890-11eb-93b1-29a21b168bb0.png)
<br><br>

**Comment by hirossyi73** [comment]
結論から申し上げると、仕様になります。

Exment（のベースとなっているlaravel-admin）は、pjaxと呼ばれるフレームワークを採用しています。
pjaxでは、cssとjsについて、画面読み込み時に、共通パーツとして、すべてのcssとjsを読み込む仕様になっています。個別に読み込んでトリガー実施することは基本的にできません。
そのため、プラグインでも、最初に関連するすべてのプラグインのjsなどを読み込む仕様になっています。

これ、どこかに書いたほうが良いですね。

**Comment by dev-hayash** [comment]
ご回答ありがとうございます。
使用しているフレームワークの仕様ですね。

この振る舞いはプラグイン作成者に広い視野を求めることになりますね。（他プラグインの内容も把握する必要があります）
`$(document).ready(function(){・・・}`
登録したプラグインのjsに上記の記述があると、どの画面でも実行されるので記述する内容に注意が必要ですね。

仕様を理解しましたので解決とさせていただきます。
