### ISSUE TITLE
非メジャーな形式のファイルをアップロードする際

### ISSUE THREAD

**Issue by NoPlan123** [exceedone/exment#980]
### Describe the bug / バグの説明
office系以外のファイル形式(CADのDXF形式など)をカスタム列のファイルにてアップロードしようとする際
ページにファイルが載った際（保存前)に、データの中身がテキストで無理矢理表示された状態になります。
サイズが大きなファイルだと、テキスト化する処理が終わるまで該当のタブが固まります。

### To Reproduce / 再現手順
カスタム列でファイル用意し、あまりメジャーではない形式のファイルを追加します。

### Version / 発生バージョン
v4.0.10  

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。
![ss](https://user-images.githubusercontent.com/14049053/114858084-fec06e00-9e23-11eb-8ae0-6544cf41de17.jpg)

### Additional context / その他  
文章管理システムとしても使おうと考えています。対応しない形式のファイルは代替アイコンを表示するなど対応希望です。

**Comment by hirossyi73** [comment]
v4.1.0で対応

**Comment by hirossyi73** [comment]
v4.1.0で修正完了
