### ISSUE TITLE
ワークフロー設定完了後に案内される「設定完了する」ウィンドウについて

### ISSUE THREAD

**Issue by kometchtech** [exceedone/exment#984]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。

ワークフロー作成後、設定完了をしたいが「設定完了する」をどのように対応すれば良いか分からない。
キーワードは必須入力扱いになっているが、何を入力しても「キーワードを正しく入力してください」と通知される。

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。

ワークフロー設定完了後、以下の入力を問われる。マニュアルにはこの手順が案内されていない。
また、この問題はv4.0.10までは無かったように記憶している。
https://exment.net/docs/#/ja/workflow_setting?id=%e8%a8%ad%e5%ae%9a%e5%ae%8c%e4%ba%86%e3%81%99%e3%82%8b#/ja/workflow_setting?id=%e8%a8%ad%e5%ae%9a%e5%ae%8c%e4%ba%86%e3%81%99%e3%82%8b#/ja/workflow_setting?id=%e8%a8%ad%e5%ae%9a%e5%ae%8c%e4%ba%86%e3%81%99%e3%82%8b

* キーワード
* 通知に追加する

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。

v4.1.0

### Error log / エラーログ
If possible, paste error log. Log's path is "storage/logs/laravel.log". / 可能であれば、ログを貼り付けてください。ログのパスは"storage/logs/laravel.log"です。

特にこのウィンドウが表示されるタイミングでは何も出力されていないが、ログファイル自体は添付します。
[laravel.log](https://github.com/exceedone/exment/files/6334786/laravel.log)

### Screenshots / スクリーンショット
If possible, paste the screenshot. / 可能であれば、スクリーンショットを貼り付けてください。

![screenshot-2021 04 19-18_08_03](https://user-images.githubusercontent.com/5137077/115211542-a0083680-a13a-11eb-84c7-32eef2e5b00d.png)

### Additional context / その他  
Add any other context about the problem here. / その他に記載すべき内容がありましたら、ご記載ください。

**Comment by hirossyi73** [comment]
こちら、弊社2名で確認し、特に問題なく表示されていました。
「テキストそのものが存在しない」のか、「スタイルで表示になっている」のかをご教授いただけないでしょうか。

また、他のダイアログでも同様の表示か、ご教授ください。
例：ワークフローのアクションユーザー設定

**Comment by kometchtech** [comment]
> こちら、弊社2名で確認し、特に問題なく表示されていました。
> 「テキストそのものが存在しない」のか、「スタイルで表示になっている」のかをご教授いただけないでしょうか。
> 
> また、他のダイアログでも同様の表示か、ご教授ください。
> 例：ワークフローのアクションユーザー設定

すみません、このissueのあとv4.0.9環境があったので確認したところ、"yes"と入力するだけで良かったんですね。
ただ、ヘルプが一切表示されていなくなったことで混乱しておりました（これは別問題？）

![exment komeho info-1619144698202202](https://user-images.githubusercontent.com/5137077/115809360-e99c9e00-a426-11eb-9e59-f9d261b60d91.jpg)

大変お騒がせするとともにお時間ちょうだいしたこと申し訳ありません。

**Comment by hirossyi73** [comment]
そうですね、本文が一切出てこないことが気になっていました。
おそらく最初のキャプチャの状況でも、「yes」と入力すれば動くとは思うのですが、そもそもなぜ説明文が出てきていないのか、気になっています。

**Comment by kometchtech** [comment]
> おそらく最初のキャプチャの状況でも、「yes」と入力すれば動くとは思うのですが、そもそもなぜ説明文が出てきていないのか、気になっています。

ありがとうございます。こちら仰るとおり`yes`と入力することで問題なく設定を進めることが出来ました。
少なくとも本issueについては解決しました。

> そうですね、本文が一切出てこないことが気になっていました。

こちらについては別のissueを作成するなど必要でしょうか？　念のためご指示いただけると助かります。

**Comment by hirossyi73** [comment]
>こちらについては別のissueを作成するなど必要でしょうか？　念のためご指示いただけると助かります。
そうですね、こちらお願いいたします。
現状、弊社開発者数人で確認できていない状況なので、すぐの対応は難しいのですが、確認でき次第対応いたします。

**Comment by kometchtech** [comment]
> > こちらについては別のissueを作成するなど必要でしょうか？　念のためご指示いただけると助かります。
> 
> そうですね、こちらお願いいたします。
> 現状、弊社開発者数人で確認できていない状況なので、すぐの対応は難しいのですが、確認でき次第対応いたします。

#993 にてヘルプの文章が表示されない件についてチケットを作成しました。
本件は解決したためクローズします。お手数おかけしました。
