### ISSUE TITLE
V4.1.0でLDAP認証ができない

### ISSUE THREAD

**Issue by chibbba** [exceedone/exment#986]
### Describe the bug / バグの説明

V4.1.0でLDAP認証ができなくなった。
問題なくLDAP認証出来ていたV4.0.10からV4.1.0にアップデートした環境のほか、
V4.1.0新規インストール直後にLDAP認証設定のみを行った場合でも再現。

### To Reproduce / 再現手順

・ログイン設定画面でLDAP認証を設定して保存
・ログイン設定画面のログインテストでは認証成功
・ログイン画面では「IDまたはパスワードが違います。」と表示されてログインできない
・ちなみに、ローカルユーザーのID/PWの場合、通常のログインボタンだけではなく、LADP認証のログインボタンでもログインできてしまう（V4.0.10では試していない）

### Version / 発生バージョン

V4.1.0

**Comment by hirossyi73** [comment]
V4.１.1にて修正しました。
