### ISSUE TITLE
#901 デグレ　テキストエディタ貼り付けイメージが表示されない　

### ISSUE THREAD

**Issue by fleming35800** [exceedone/exment#989]
### Describe the bug / バグの説明
A clear and concise description of what the bug is. / バグの内容のかんたんな説明を記載してください。
お世話になっております。
過去#901にて対応していただいた不具合が再発生しております。

### To Reproduce / 再現手順
Please describe the reproduction procedure in as much detail as possible. / 再現手順を、可能な限り詳細に記載してください。
#901 と同様

### Version / 発生バージョン
Please describe version. / ご利用のバージョンを記載してください。
4.1.0→4.1.2にて再発生。

お忙しい中恐縮です。
対応コードでも構いませんのでご対応いただければ幸いです。

**Comment by hirossyi73** [comment]
![image](https://user-images.githubusercontent.com/8457265/115992805-84a19d80-a60a-11eb-9dec-d28ef248b2e9.png)
![image](https://user-images.githubusercontent.com/8457265/115992821-9125f600-a60a-11eb-8791-585ed2035fd1.png)
![image](https://user-images.githubusercontent.com/8457265/115992828-97b46d80-a60a-11eb-8fdf-1283f60dc899.png)

最新版で確認した所、特に問題なく動いてそうです。

**Comment by hirossyi73** [comment]
(※一度、貼り付けないように誤りがありました。削除しました、失礼しました)

vendor\exceedone\exment\src\Auth\Permission.php
の229行目前後を、以下のように修正してください。

```
            case "tmpfiles":
            // 追加
            case "tmpimages":
                return true;
            ///// only system permission
            case "system":
```

画像のエンドポイントを変更したことによるデグレでした。

**Comment by hirossyi73** [comment]
v4.1.3にてリリースしました。細切れのリリースになってしまい恐縮です。

**Comment by fleming35800** [comment]
お世話になっております。
いつも早急な対応ありがとうございます。
確認させていただきます。

**Comment by fleming35800** [comment]
お世話になっております。対応確認させていただきました。
ご対応いただきましてありがとうございます。
