### ISSUE TITLE
かんばんとして表示するビューの作成方法について

### ISSUE THREAD

**Issue by patipati3** [exceedone/exment#999]
### Describe the feature you'd like / 希望する機能の説明を行ってください
A clear and concise description of what you want to happen. / あなたが何をしたいのかについての、明確で簡潔な説明を行ってください。
お世話になっております。
https://exment.net/archives/1684

現在、タスク管理を行っていく中で、上記URLにある、Ver4.1～から導入される、かんばんビューを使用したいと考えているのですが、プラグインを作成とあるのですが、こちら作り方などはどちらかに記載があるのでしょうか。

また、可能であれば、こちらのプラグインの作り方などご教示いただけますと幸いです。

**Comment by fleming35800** [comment]
Exment利用者で、開発者ではありませんがプラグインに関しての記載は以下に有ります。

・プラグインとは
https://exment.net/docs/#/ja/plugin?id=%e3%83%97%e3%83%a9%e3%82%b0%e3%82%a4%e3%83%b3%e3%81%a8%e3%81%af
・プラグイン作成方法
https://exment.net/docs/#/ja/plugin_quickstart?id=%e3%83%97%e3%83%a9%e3%82%b0%e3%82%a4%e3%83%b3%e4%bd%9c%e6%88%90%e6%96%b9%e6%b3%95

かんばんビューのプラグイン作成に関する説明は以下にあります。
https://exment.net/docs/#/ja/plugin_quickstart_view
